### ISSUE TITLE
Hi! Quicklook can really bring everything together when bundled with microsoft powerun

### ISSUE THREAD

**Issue by infusionproximity** [QL-Win/QuickLook#1001]
Hi! i would like to just leave a suggestion to add quick look functionality for people who use microsoft powertoys [https://docs.microsoft.com/en-us/windows/powertoys/](url) (link) to really make it perfect for windows!

**Comment by rabelux** [comment]
https://github.com/QL-Win/QuickLook/issues?q=is%3Aissue+powertoys
