### ISSUE TITLE
strange behaviour in some cases

### ISSUE THREAD

**Issue by rmadner** [QL-Win/QuickLook#1003]
We want to use Quicklook at office, made a few tests, and still are not convinced: We run Citrix on Windows2016Server, need Quicklook as substitute für builtin Windows-Viewer, so it has to work from WindowsExplorer, Outlook (attachments) and varying platforms via browser (Firefox and Chrome).

It seems easy to get it running in Windows, but there ist strange behaviour in the browsers: some pictures cannot be opened, you only get the message "Quicklook is running now in the background". I even have one example, that does not work, but when i load it down and up again, there is no problem anymore.

Before I look for the needle in a haystack: Are there any restrictions with Citrix, WindowsServer, picture-size, picture-properties?

Datatypes tested:
BMP, JPG, TIFF, PNG - work well
JPEG, HEIC, GIF - sometimes strange (not opening, opening in other browser, offering download)

used Versions:
Windows Server 2016 Standard Version 1607 64bit
MS Office Professional Plus 2013 MSO 15.0.5381.1000 32bit
Google Chrome Version 93.0.4577.82 64bit
Mozilla Firefox 91.1.0esr 32bit
SBOX 10.5.0 von ownCloud-Community www.owncloud.com (on premise)
OTRS Business Solution 5 (on premise)

There is no way to make these platforms available for reproduction. Since they are on premise, we don't want to make them open to the internet (sensitive data).

Any suggestion, what else do you need to solve this problem?

**Comment by emako** [comment]
While we are constantly adding new features, it is difficult to maintain a system that is too old.
