### ISSUE TITLE
Fluent design icons for buttons to match Windows 11

### ISSUE THREAD

**Issue by nitin2953** [QL-Win/QuickLook#1006]
Thin line icons, some of them look crisp while other looks blurry  

Replace them with New Fluent design icons  

theme switcher & img info button can be moved to title-bar

**Comment by xupefei** [comment]
Sure, would you like to contribute?

**Comment by emako** [comment]
The icon has been updated, but buttons such as the theme switcher are not planned to be moved to the title-bar.
