### ISSUE TITLE
Win11: Quicklook not working in Save as/Open explorer dialogs

### ISSUE THREAD

**Issue by xzayn** [QL-Win/QuickLook#1007]
Using Windows 11 Dev build and latest Quicklook v3.7, also use qttabbar but thats not the issue
![image](https://user-images.githubusercontent.com/74079803/135335347-3fc3e9cc-d5f3-4b4a-a490-094c850dc928.png)

**Comment by rabelux** [comment]
You should have mentioned you're using the msi version. Can anyone confirm?

**Comment by moxwel** [comment]
This issue also ocurrs to me. In Windows 10, with QuickLook `msi` version.

**Comment by xupefei** [comment]
I tried on my machine and it seems this issue does exist but happens randomly. After boot, QL is not able to preview in file dialogues of a 64-bit app, but after I quit & restart QL the preview works again. I tend to believe it's just another Windows 11 bug.

**Comment by xzayn** [comment]
btw its also not working in Everything 1.5a latest build... for me

**Comment by volcbs** [comment]
Can confirm that v3.7.0 is not working in Save as/Open explorer dialogs, reverting it back to v3.6.11 fixes the problem.

**Comment by xupefei** [comment]
@volcbs Could you test more? For me v3.7.0 works occasionally in Windows 11. The last change for `QuickLook.Native` is Aug 2020 so the only possible reason is because the C++ compiler.

**Comment by volcbs** [comment]
@xupefei I did the same as @moxwel (fully uninstall with deleting pooi.moe folder), and it still doesn't work.
It's very possible that it's either related to changing image detection mechanism (https://github.com/QL-Win/QuickLook/commit/3ef980bb1706a7ffa4f67ab7e96e5f3ef74a4d14) or using "hold space to quick view" mechanism (https://github.com/QL-Win/QuickLook/commit/c10773249f43dee79b23be64da6eb74fcf66eab9)
