### ISSUE TITLE
MS Smartscreen: QuickLook-3.7.0.msi was blocked because it could harm your device.

### ISSUE THREAD

**Issue by MithrilFlame** [QL-Win/QuickLook#1009]
Hi all, love this project!

**Describe the bug**
Upon downloading the latest QuickLook update in Microsoft Edge Version 94.0.992.31 (Official build) (64-bit), the download window informed me:
MS Smartscreen: QuickLook-3.7.0.msi was blocked because it could harm your device.

**To Reproduce**
1. Go to https://github.com/QL-Win/QuickLook/releases/tag/3.7.0
2. Click on https://github.com/QL-Win/QuickLook/releases/download/3.7.0/QuickLook-3.7.0.msi
3. File is downloaded...
4. See error: "QuickLook-3.7.0.msi was blocked because it could harm your device."

**Expected behavior**
Expected no error, and to be able to update my favourite QuickLook :)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Version 20H2 (OS Build 19042. 1237)
 - QuickLook download file Version: 3.7.0 from github, currently running v3.6.11 without issue.

**Comment by rabelux** [comment]
See #663

**Comment by rabelux** [comment]
Have a look at https://github.com/microsoft/winget-pkgs/pull/1241.
Apparently every release has to be submitted and cleared manually so this issue will continue to pop up :disappointed:
