### ISSUE TITLE
QuickLook v 3.7 最新版本 预览ai格式文件显示错误，同时对max格式文件不能预览。

### ISSUE THREAD

**Issue by xujieone** [QL-Win/QuickLook#1020]
QuickLook v 3.7 最新版本 预览ai格式文件显示错误（全是代码），同时对max格式文件不能预览。
The latest version of quicklook V 3.7 preview AI format file displays an error, and the max (autoudesk) format file cannot be previewed.

> 

 - OS Version: [e.g. Windows 11]

**Comment by emako** [comment]
#1516
