### ISSUE TITLE
Support Acrylic in Windows 11

### ISSUE THREAD

**Issue by Shomnipotence** [QL-Win/QuickLook#1033]
Acrylic is the stander in temporary control

Windows Start Menu，context menu，search suggestions list，Jump list ，Acrylic is used for all temporary control backgrounds. Obviously, Quick Look should also be the same. 

Now that Windows 11 has been released, it is time to bring back acrylic.

**Comment by Michael82548** [comment]
Should be an optional setting for users that like Metro or Windows 10 matching UI.

**Comment by xupefei** [comment]
Fixed.

**Comment by Shomnipotence** [comment]
> Fixed.

Will? it would been fixed?

**Comment by rabelux** [comment]
Try the latest nightly.

**Comment by Shomnipotence** [comment]
> Try the latest nightly.

Yeah I have downloaded it and installed but not Acrylic

**Comment by xupefei** [comment]
Try https://ci.appveyor.com/project/xupefei/quicklook/builds/42564414/artifacts

**Comment by Shomnipotence** [comment]
> Try https://ci.appveyor.com/project/xupefei/quicklook/builds/42564414/artifacts

Amazing！I downloaded it（msi），but not Acrylic Brush Not work
![image](https://user-images.githubusercontent.com/6630660/153841342-866c33a5-6637-4a0e-b636-01aff1533b1f.png)

It seems used fallback brush

**Comment by xupefei** [comment]
What graphics card do you have?

**Comment by Shomnipotence** [comment]
> What graphics card do you have?

2070 Super.

However, acrylic brush from Windows Apps (eg. Mail(Background Acrylic), Settings(Mica),context menu(Acrylic), Microsoft Store (in-app Acrylic) ) works well

**Comment by xupefei** [comment]
Do you have manually disabled transparency: https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-window-transparency-since-v3611-23?

**Comment by Shomnipotence** [comment]
> Do you have manually disabled transparency: https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-window-transparency-since-v3611-23?

No，but after I receiving your relay，I forced enable the transparency.
<UseTransparency>True</UseTransparency>

But not work.

All the operation has reboot the Windows

**Comment by Shomnipotence** [comment]
> Do you have manually disabled transparency: https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-window-transparency-since-v3611-23?

Is it a bug?

**Comment by Shomnipotence** [comment]
![image](https://user-images.githubusercontent.com/6630660/154193074-790dc735-e6d9-41eb-aeb1-0120b3036653.png)

Sometimes what it looks like this screenshot shows
