### ISSUE TITLE
Question: Activate "Run at Startup" with a script 

### ISSUE THREAD

**Issue by grafst** [QL-Win/QuickLook#1039]
How do I activate the Option "Run at Startup" with a script? Is there a registry-Key or config file? I can't find it.
A switch for the .msi would also be great.

**Comment by grafst** [comment]
Hi, Thanks for your response. Sorry for the late reply. 
I was able to create the shortcut with a script, but the checkmark does still not show...
![grafik](https://user-images.githubusercontent.com/8471055/144265542-4e886c2c-d143-4d2c-8221-87077ecf14f5.png)
However this is a minor detail...

**Comment by xupefei** [comment]
You may have an LNK file with an incorrect name: https://github.com/QL-Win/QuickLook/blob/master/QuickLook/Helpers/AutoStartupHelper.cs#L77
QL expects `QuickLook.lnk`.
