### ISSUE TITLE
QuickLook as plugin for Microsoft PowerToys

### ISSUE THREAD

**Issue by michael-motornyi** [QL-Win/QuickLook#1041]
It will be great if QuickLook can be installed or integrated with PowerToys app from Microsoft. Is it possible?

**Comment by rabelux** [comment]
Did you know GitHub as a feature where you can find out whether a topic has already been discussed?
![grafik](https://user-images.githubusercontent.com/16120882/142387024-7a70a0dc-1280-4a56-b049-e2041d842b94.png)
Please use it.
