### ISSUE TITLE
Windows 11 - can't install plugin

### ISSUE THREAD

**Issue by Sidnikos** [QL-Win/QuickLook#1042]
Hello there,

I would like to inform you that I can't install plugins for QuickLook.

I downloaded the QuickLook.Plugin.OfficeViewer.qlplugin but doubleclicking it doesn't seem to do anything, as it asks me to find an application to open this type of file. And I can't even find QuickLook trying to search it in my application folders.

Thank you.

**Comment by rabelux** [comment]
https://github.com/QL-Win/QuickLook/wiki/Available-Plugins#how-to-install-or-upgrade-a-plugin

**Comment by Sidnikos** [comment]
Thank you very much. I hadn't understand the guide.
