### ISSUE TITLE
No video thumbnails when quick look is set as the default video player

### ISSUE THREAD

**Issue by TyraVex** [QL-Win/QuickLook#1043]
**Describe the bug**
Said in title

**To Reproduce**
Click on video file
Open with → Quick look (this sets the app as the default video player in windows settings)
Video thumbnails are gone

**Expected behavior**
Get video thumbnails
![image](https://user-images.githubusercontent.com/34800546/142778628-43d7d1a9-a9c6-413d-a9cb-8cdeba0943f6.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 21H2 19044.1348
 - QuickLook Version:  3.7.1 from Windows Store

**Comment by rabelux** [comment]
I don't know whether the dev knows a fix for this but in case he doesn't:
Yes, you can use a knife as a screwdriver in some cases but don't complain if you break it.

Same with QuickLook. You aren't using it in the intended way.

**Comment by TyraVex** [comment]
I was asking since image thumbnails was supported.
So why not videos ¯\_(ツ)_/¯

**Comment by xupefei** [comment]
> image thumbnails was supported
That's done by Microsoft, not QuickLook.
