### ISSUE TITLE
新版3.7.1打开就自动退出，运行不了，想退回3.7.0 找不到可下载的地方！唉！！！！

### ISSUE THREAD

**Issue by iD2073** [QL-Win/QuickLook#1044]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by iD2073** [comment]
能不能先给老版本留个下载的链接，

**Comment by rabelux** [comment]
https://github.com/QL-Win/QuickLook/releases
