### ISSUE TITLE
Can QuickLook provides file preview on what I called "file select window"?

### ISSUE THREAD

**Issue by LovelyQuantum** [QL-Win/QuickLook#1047]
**Description**
I use Google Image search for an example. When you enter that web, click on choose file, a window will pop up, and select an image to upload from that window. This window is highly like File Explorer. So can QuickLook provides a preview on that kind of window?
This function will be very beneficial because now you can't preview files on that kind of window. Your double click will submit your selection rather than open it.

PS. Maybe this is just a bug on Windows 11 Build 22000.348? I'm not sure about the behavior on other windows versions. All the tests run on win11.

![1](https://user-images.githubusercontent.com/44353226/143799520-13a06dc1-e5d3-4146-b0dd-e1fb1fefb119.png)
![Picture1](https://user-images.githubusercontent.com/44353226/143799644-2e73fc26-7769-472b-8ff7-aa205ca5919f.png)
**Env**
Windows 11(22000.348)
Google Chrome

**Comment by rabelux** [comment]
Explained [here](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions)
