### ISSUE TITLE
White SVG items

### ISSUE THREAD

**Issue by JesseN02** [QL-Win/QuickLook#1048]
**Describe the bug**
When I want to preview a white SVG image, I can't see it because the background is white too

**To Reproduce**
Preview a white svg item

**Expected behavior**
The background should be a little bit grey, so that you can preview white svg files. In Seer this is working fine

**Desktop (please complete the following information):**
Windows 11
Newest Quicklook version

![image](https://user-images.githubusercontent.com/95239658/143907954-1e7e7243-4358-4d6a-a445-720c1d45825b.png)

**Comment by rabelux** [comment]
The background is actually black-grey in a chess style pattern. You can switch to a white-ish background with the button in the top right corner.

**Comment by rabelux** [comment]
I don't get what your issue is. QuickLook diesplays your image just fine. Only thing I can think of is that maybe the zoom is not 100%.
![grafik](https://user-images.githubusercontent.com/16120882/144092990-07b61c21-cbdb-4078-9d79-975ee3ec8e7d.png)
