### ISSUE TITLE
Support for new “ExplorerTabs”?

### ISSUE THREAD

**Issue by Inversil** [QL-Win/QuickLook#1049]
**Is your feature request related to a problem? Please describe. A clear and concise description of what the problem is.**
I want to use quick look while using explorertabs but quicklook doesn’t recognize it as a file explorer yet so hitting space does nothing.

Recently a cleaner looking alternative for QTTabbar’s tabs showed up; https://explorertabs.com/

It’s a remake of eji.me’s clover, which is a similar tab explorer that used to be good until the devs started bundling adware 5 years ago.

As for explorertabs, quicklook does not work with it currently but I’m still quite fond of it.

It seems like it wraps around the original explorer without fully replacing it. Closing the program in the tray makes the file manager revert to normal. 

I get the feeling that adding support for this should be pretty easy, as most of it is exactly the same as vanilla windows. I found some docs about plugins. I’ll try doing it myself and see how hard it gets :-)

**Comment by rabelux** [comment]
I just reworked the wiki pages for [file managers](https://github.com/QL-Win/QuickLook/wiki/File-Managers) and [how to integrate file managers](https://github.com/QL-Win/QuickLook/wiki/Develop%2C-build-and-integrate#integrating-with-file-managers). I hope that helps.

File managers that don't work with QuickLook are usually those who capture the spacebar. Therefore the file manager has to be configured to invoke QuickLook and not QuickLook to work the file manager.
