### ISSUE TITLE
Use File.Exists() to detect the pipe of QuickLook will break the named pipe

### ISSUE THREAD

**Issue by zhuxb711** [QL-Win/QuickLook#1052]
**Describe the bug**
Use File.Exists() to detect the pipe of QuickLook will break the named pipe.

**To Reproduce**
```csharp
        public static bool CheckQuicklookIsAvaliable()
        {
            try
            {
                // Powershell: get-childitem \\.\pipe\ | out-string -stream | Select-String -Pattern "QuickLook"
                // ------          1/1/1601   8:00 AM              1 QuickLook.App.Pipe.S-1-5-21-329068152-1454471165-1417001333-8399333
                if (File.Exists($@"\\.\pipe\QuickLook.App.Pipe.{WindowsIdentity.GetCurrent().User?.Value}"))
                {
                    // Powershell: get-childitem \\.\pipe\ | out-string -stream | Select-String -Pattern "QuickLook"
                    // <Empty>
                    using (NamedPipeClientStream Client = new NamedPipeClientStream(".", PipeName, PipeDirection.Out))
                    {
                        Client.Connect(500);

                        using (StreamWriter Writer = new StreamWriter(Client, leaveOpen: true))
                        {
                            Writer.WriteLine($"{SwitchCommand}|");
                            Writer.Flush();
                        }
                    }

                    return true;
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex, "Could not connect to the Quicklook");
            }

            return false;
        }
```

**Expected behavior**
Use File.Exists() to detect if a named pipe exists and that should not crash the pipe

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2/21H1 &  Windows 11
 - QuickLook Version: Tested in 3.6.11/3.7.1 (Msi & Store) and might affect more versions

**Screenshots and Exception Log**
Could not found the exception log file in the data location

**Comment by zhuxb711** [comment]
The same behavior if I use CreateFIle to detect the pipe. Pipe broken without reason.

```csharp
Kernel32.CreateFile($@"\\.\pipe\{PipeName}", Kernel32.FileAccess.GENERIC_WRITE | Kernel32.FileAccess.FILE_WRITE_ATTRIBUTES, FileShare.ReadWrite, null, FileMode.Open, FileFlagsAndAttributes.FILE_ATTRIBUTE_NORMAL)
```

**Comment by xupefei** [comment]
This piece of code is not from QuickLook. Are you reporting an issue in some file explorers?

**Comment by zhuxb711** [comment]
> This piece of code is not from QuickLook. Are you reporting an issue in some file explorers?

This issue is related to the communication between 3rd party file explorer and QuickLook. The code is provided to  show how to make QuickLook failed to response.

**Comment by zhuxb711** [comment]
Create a new console project. Run the code above. You will found that Quicklook loss response and can not be exited from system tray. Only Task Manager can terminate it.

**Comment by rabelux** [comment]
So you're trying to integrate QuickLook into your file explorer? Have you seen [this section](https://github.com/QL-Win/QuickLook/wiki/Develop%2C-build-and-integrate#integrating-with-file-managers) in the wiki?

**Comment by xupefei** [comment]
Yeah please try Bridge.zip on the above wiki page. If it works then something wrong with your code.

**Comment by zhuxb711** [comment]
> So you're trying to integrate QuickLook into your file explorer? Have you seen [this section](https://github.com/QL-Win/QuickLook/wiki/Develop%2C-build-and-integrate#integrating-with-file-managers) in the wiki?

I integrated QuickLook for a long time. I use NamedPipeClientStream to connect and catch 'TimeoutException' to determine if QuickLook is running before. But I don't like that so I tried 'File.Exists()' and found that 'File.Exists('<QuickLook's pipe name>')' will cause QuickLook freeze.

That's why I created this issue. And please pay attention to the comment in my code. Not the issue from my side totally.
If File.Exists() removed from the code. Everything works perfect. 

In my opinion. Named pipe should always work as expected and should not freeze the QuickLook because it's normal to use File.Exists() or Kerneal32.CreateFile to determine if a named pipe is exists.

Nevermind, I use 'Kerneal32.WaitNamedPipe()' instead to avoid exception.

**Comment by xupefei** [comment]
I don't understand why it's problem. If you use `File.Exists` (which tries to open and read from file) on a named pipe then at least one side will interrupt and wait, which is expected.

You should not use `File.Exists` to check a pipe. Use something that will not read from the target file.

**Comment by lindexi** [comment]
@zhuxb711 [Using File.Exists to check the pipe created will make the NamedPipeClientStream connect fail · Issue #69604 · dotnet/runtime](https://github.com/dotnet/runtime/issues/69604 )
