### ISSUE TITLE
Question: Install Plugins programatically?

### ISSUE THREAD

**Issue by grafst** [QL-Win/QuickLook#1053]
Is there a way to install Plugins with a script?

**Comment by rabelux** [comment]
*.qlplugin files are just renamed zip files. You should be able to unzip them into the `QuickLook.Plugin` directory inside your [install directory](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by grafst** [comment]
ah great, thanks!
I updated the wiki, hope thats ok...
