### ISSUE TITLE
White SVG Item

### ISSUE THREAD

**Issue by JesseN02** [QL-Win/QuickLook#1055]
Describe the bug
When I want to preview a white SVG image, I can't see it because the background is white too. The option to change the color to black or white doesnt work. Added screenshot of seer too

To Reproduce
Preview a white svg item or use the file i added.

Expected behavior
The background should be a little bit grey, so that you can preview white svg files. In Seer this is working fine

Desktop (please complete the following information):
Windows 11
Newest Quicklook version

Below a screenshot of how seer displays it
![image](https://user-images.githubusercontent.com/95239658/144448394-2488ec90-7736-454e-886f-5502bce5885d.png)

Here a screenshot on how QuickLook displays it:
![image](https://user-images.githubusercontent.com/95239658/144448531-06ffec4f-b548-4b58-9842-2d3b425559ac.png)

Download the svg item: https://we.tl/t-zZupixzXi4

**Comment by xupefei** [comment]
I would say the way Seer displays it is wrong. Chrome also displays the image as a white rectangle, the same as QuickLook.

Looking at your SVG file, it explicitly said that the background color is white:
```
<style type="text/css">
	.st0{fill:#FFFFFF;}
</style>
```

If you remove these three lines then the image could be displayed correctly in both Chrome and QuickLook.

**Comment by xupefei** [comment]
Have you tried this: https://howchoo.com/illustrator/background-transparent-illustrator?

**Comment by xupefei** [comment]
Okay, I know why. ImageMagick will assign a white background when converting SVG into other files.
Should be an easy fix.

**Comment by xupefei** [comment]
Could you try https://ci.appveyor.com/project/xupefei/quicklook/builds/41749238/artifacts?

**Comment by JesseN02** [comment]
Unfortunately this did not fix it

**Comment by xupefei** [comment]
Really? The new build fixes the issue on my machine. Could you post a new screenshot?

**Comment by JesseN02** [comment]
Nevermind its working perfect now! Thanks for your effort!
