### ISSUE TITLE
How to install QuickLook for all users' accounts? (C:\Program Files instead of C:\Users\%username%\AppData\Local\Programs

### ISSUE THREAD

**Issue by carloscadux** [QL-Win/QuickLook#1056]
Hi,
I'd appreciate your help.
I intend to deploy QuickLook and each computer have some different users' accounts.
By running the .msi installer the installation folder is user based: "C:\Users\%username%\AppData\Local\Programs\QuickLook\"
Is there any to make the .msi to install in C:\Program Files\QuickLook directly?
By having QuickLook set for all users I'm expecting that update it later will also be easier, instead of having to update it user by user several times in same computer.

Thank you!

**Comment by xupefei** [comment]
https://stackoverflow.com/questions/8839978/install-msi-with-msiexec-into-specific-directory.
Run commands in the above thread as admin.

**Comment by carloscadux** [comment]
Hi @xupefei. Many thanks for the information!

I could accomplish the installation, but the QuickLook shortcut entry was created only in the Start Menu of the current user, from where the installation command was run. 
The shortcut entry is missing from the other users in the same computer's Start Menu.

=> By chance, do you know how to create the QuickLook shortcut entry in Start Menu for all users?

------------------

Below I'm documenting the command for custom installation of QuickLook, since after testing many commands from that Stackoverflow thread, the only command that worked with QuickLook was:

`msiexec /i "msi path" INSTALLFOLDER="C:\MyFolder path" /qb `

Just replace within quotation marks with the desired paths. 
The quotation marks are part of the command.
Run the command as admin. 

NOTE: It was commented in the Stackoverflow thread that the choice of commands INSTALLFOLDER or TARGETDIR (the latter didn't work with QuickLook) will depend on what tool was used to build the MSI file. For instance, an MSI built using WiX should work with INSTALLFOLDER, while TARGETDIR may be used by other tools.

**Comment by carloscadux** [comment]
Just found out how to  create the QuickLook shortcut entry in Start Menu for all users as well.
It's necessary to append to the syntax the command `ALLUSERS=1`
So the syntax that (1) installs an MSI into custom folder and (2) create shortcuts for all users is:

`msiexec /i "msi path" INSTALLFOLDER="C:\MyFolder path" ALLUSERS=1 /qb `

Cheers!

**Comment by carloscadux** [comment]
Hi.
Just a suggestion for adding the information of how to deploy QuickLook somewhere in the documentation/wiki.
It was so useful for me and may be to others.
Many thanks for this incredible application!

**Comment by rabelux** [comment]
@grafst just wanted to notify you about this topic as it sounds like you're also deploying QL.

**Comment by rabelux** [comment]
I added a wiki page regarding this.

@xupefei: There is one ToDo in https://github.com/QL-Win/QuickLook/wiki/Deployment-Topics#run-at-startup that I can't answer. Does QuickLook check both paths or just the current user's one?

**Comment by xupefei** [comment]
@rabelux Thanks for working on the Wiki!

QL will only check the current user's StartUp folder, which means that if an LNK is being added to all users' StartUp, one **must not** check the "Run at StartUp" option in the context menu, or he/she will get a message box saying "QuickLook is already running".
