### ISSUE TITLE
QuickLook instakilled

### ISSUE THREAD

**Issue by JoeBarouneD** [QL-Win/QuickLook#1057]
Hello, all worked perfect until i updated to 3.7.1.

The program launches and is instant killed.

I'm using "7+ Taskbar Tweaker" and "StartAllBack", which can be the problem, but with 3.7.0, all is fine.

So, i'm obliged to stay on 3.7.0...

I'm on W11.

**Comment by rabelux** [comment]
Hard to provide support without logs, screenshots or a video.

**Comment by JoeBarouneD** [comment]
Nevermind, i'm unable to reproduce it though i had the bug since the 3.7.1 update.

Maybe one of the 3d party apps i mentionned who has been updated.

So it's now working !

Thank you.
