### ISSUE TITLE
Hide Pop-up window after loading OS.

### ISSUE THREAD

**Issue by x-tropic** [QL-Win/QuickLook#1063]
How to hide pop-up window after loading OS?

Windows 10 Pro 21H2
QuickLook 3.7.1.msi
![25 12 - 22-03_Ek](https://user-images.githubusercontent.com/46036927/147391915-52ab5c2c-a54c-41c6-a706-c97459bb56f1.jpg)

**Comment by rabelux** [comment]
There shouldn't be any popup window on startup. What does the popup say?
If it says that QuickLook is already running you're trying to start two instances of QL.

**Comment by x-tropic** [comment]
> There shouldn't be any popup window on startup. What does the popup say? If it says that QuickLook is already running you're trying to start two instances of QL.

it's say: QuickLook already run, etc...
Ok, i check this, thanks.

**Comment by x-tropic** [comment]
@rabelux 
you're right, thanks)
