### ISSUE TITLE
Filename too long bug

### ISSUE THREAD

**Issue by zoharli** [QL-Win/QuickLook#1065]
If the filename is too long, quickLook won't launch when pressing 'space'. Can you fix it? Thank you.

**Comment by xupefei** [comment]
QuickLook supports the long file path since 3.6.10. Could you try if that helps?
How to turn it on in Group Policy: https://www.tenforums.com/tutorials/51704-enable-disable-win32-long-paths-windows-10-a.html

**Comment by zoharli** [comment]
Thanks, this resolved my problems.
