### ISSUE TITLE
Replace x86

### ISSUE THREAD

**Issue by MaxG-Enpal** [QL-Win/QuickLook#1066]
Hey,

please replace the x86 architecture with x64 and arm64 for futureproofing the app.
I would like to get rid of Programms (x86) folder at all.

Thanks

**Comment by rabelux** [comment]
Duplicate of #551.
There is currently a PR open suggesting some changes regarding architectures (#1064).
Also note that QL usually installs in your *AppData* and not your *Program Files (x86)* folder.
