### ISSUE TITLE
Directory structure chaos and Chinese garbled problems occur when viewing zip files

### ISSUE THREAD

**Issue by AdoShan** [QL-Win/QuickLook#1071]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*
No
**Describe the bug**
Directory structure chaos and Chinese garbled problems occur when viewing zip files
**To Reproduce**
1. Open source file
[Maven课件.zip](https://github.com/QL-Win/QuickLook/files/7869170/Maven.zip)
2. Use Quicklook Preview Files

3. See error

**Expected behavior**
As shown in the screenshot.

**Desktop (please complete the following information):**
 - OS Version: Windows 11 21H2
 - QuickLook Version: 3.7.1 from Windows Store

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/44154107/149487862-e8c65e2c-5f63-4971-acda-b11bfc691869.png)
[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/7869147/QuickLook.Exception.log)

**Comment by rabelux** [comment]
Related to #1035

**Comment by xupefei** [comment]
Duplicate.
