### ISSUE TITLE
How do I install extra plugins? And where please? 

### ISSUE THREAD

**Issue by Scaramanga89** [QL-Win/QuickLook#1074]
How do I install extra plugins I have downloaded (like viewing Office docs)? And where please?

**Comment by rabelux** [comment]
1. Go to the wiki page for plugins
2. Scroll down
3. Profit

**Comment by Scaramanga89** [comment]
My apologies, I was on that page. I’m an idiot. Thanks for taking the time.

Regards,

Stephen Forbes
Email: ***@***.******@***.***>
Phone: +447970524139/+48726190872
Web: www.steadycomps.com<http://www.steadycomps.com/>






DISCLAIMER: This e-mail contains proprietary information some of which may be legally privileged. It is for the intended recipient only. If an addressing or transmission error has misdirected this e-mail, please notify the author by replying to it. If you are not the intended recipient you may not use, disclose, distribute, copy, print or rely on this e-mail.

Steady Comps is a trading name of Steady Comps Ltd., registered in N Ireland, England and Wales.

Company registration number NI625792. VAT number 193259678
