### ISSUE TITLE
Can't Install on Windows 11

### ISSUE THREAD

**Issue by umarmughal** [QL-Win/QuickLook#1081]
It was working fine on Win 10 but after i formatted my system and fresh install Win 11, it's not installing from Microsoft Store, is it only me?

**Comment by rabelux** [comment]
You're the first to report this issue and we're having quite a few users of win 11. As a workaround you could use the msi version.

**Comment by umarmughal** [comment]
I tried to reinstall the app next day and it works fine, thanks for your support ...
