### ISSUE TITLE
Previous/Next buttons

### ISSUE THREAD

**Issue by barn852** [QL-Win/QuickLook#1082]
I really miss some previous/next buttons!

I know how it works and such buttons might be confusing as the program operation is not restricted for the similar file types. (like for picture viewers it supposed to be used for images, and for example for irfanview it can be a bit annoying when it starts showing all the supported file types)

However please think about it if it can be implemented some way, eg. for all files or for the same/similar file types or just for certain file types (pictures) or making it optional (like plugin form?).

Thanks in advance

**Comment by emako** [comment]
Same as https://github.com/QL-Win/QuickLook/issues/1422

There are currently no plans, maybe in the future...

or accept someone's PR
