### ISSUE TITLE
是不是可以把ViewerWindow里的tootips文本也添加进翻译配置文件

### ISSUE THREAD

**Issue by pr0arr0w** [QL-Win/QuickLook#1084]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by pr0arr0w** [comment]
看了一下源码，ViewerWindow里的tootips文本是在代码里直接写死了，是不是也可以添加到翻译配置文件里，这样翻译配置文件就可以作为全局语言配置使用了吧

**Comment by rabelux** [comment]
Duplicate of #868.
