### ISSUE TITLE
Stll not Previewing on open dialogs. "The old one"

### ISSUE THREAD

**Issue by EAZY5D** [QL-Win/QuickLook#1085]
**It does not preview on this type of dialog**

![rundll32_lCdCBQ6wsT](https://user-images.githubusercontent.com/55167211/153320256-96819dd9-9591-44d3-b0e0-46eeb1ebf91f.png)

**To Reproduce**
Just open A WIndows old dialog ❤️

**Comment by rabelux** [comment]
Duplicate of #1028?
There is a template for creating issues. Use it.
