### ISSUE TITLE
Any chance to support viewing xapk info?

### ISSUE THREAD

**Issue by fjj739964256** [QL-Win/QuickLook#1086]
Currently, the plugin only supports viewing apk information. Is there any plugin that supports viewing xapk?

![Snipaste_2022-02-12_09-31-23](https://user-images.githubusercontent.com/33320479/153690961-16669cc9-a343-41a5-a998-841b7ac39553.jpg)

![Snipaste_2022-02-12_09-30-57](https://user-images.githubusercontent.com/33320479/153690957-6d1695fe-7aae-4581-816e-f3c5ae38ab04.jpg)

**Comment by rabelux** [comment]
There isn't as far as I know. You could ask the dev of the ApkViewer-Plugin to enhance his plugin.
