### ISSUE TITLE
3.7.1-1-7 gfc14b58 Acrylic not work , shows white color

### ISSUE THREAD

**Issue by Shomnipotence** [QL-Win/QuickLook#1088]
**Describe the bug**
Acrylic not work. It shows whtie sometimes
(https://github.com/QL-Win/QuickLook/issues/1033)

**To Reproduce**
when press space bar
It shows like the screenshot

**Expected behavior**
Acrylic Brush works well

force enable transparency
![image](https://user-images.githubusercontent.com/6630660/154194870-df28b41e-d47a-4a41-9e81-1c731f421091.png)

**Desktop (please complete the following information):**
 - OS Version: [Windows 11 Build 22543.rs_prerelease.220122-2315]
 - QuickLook Version: [3.7.1-1-7 gfc14b58  msi  nightly build]
 (2070Super)
 (in other apps and Windows 11，in-App Acrylic, Backgroun Acrylic, Mica works well)

in-app acrylic
![image](https://user-images.githubusercontent.com/6630660/154194607-963e4ffc-9d5e-4fab-99e7-cf4491be249c.png)

background acrylic
![image](https://user-images.githubusercontent.com/6630660/154194719-bc1a0aa4-9448-4144-be28-4500d22d62a3.png)

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/6630660/154194264-4ed38d17-b1b3-4251-b02d-01ff96f63a18.png)

**Comment by xupefei** [comment]
Thanks for the detailed report. I'll check on my own machine.

**Comment by Shomnipotence** [comment]
It exists in 22557.ni_release.220210-1445

**Comment by Shomnipotence** [comment]
> Thanks for the detailed report. I'll check on my own machine.

It exists in 22557.ni_release.220210-1445

**Comment by xupefei** [comment]
![image](https://user-images.githubusercontent.com/1687847/154852074-25ad6e92-b451-4570-95ca-b31eaadb29c4.png)

Works for me.

**Comment by xupefei** [comment]
Have you tried to use Windows 11 release version?

**Comment by Shomnipotence** [comment]
> Have you tried to use Windows 11 release version?

No，obviously，I have only dev version. It may be better to use Acrylic instead of Aero, it may work well perhaps.

**Comment by xupefei** [comment]
Then I think you should try to report this issue to Microsoft -- it's very likely that something is broken (again) in the dev build.

**Comment by Shomnipotence** [comment]
> Then I think you should try to report this issue to Microsoft -- it's very likely that something is broken (again) in the dev build.

Do you have more info of technology？I will try to share with MS, even though I think it is useless.

**Comment by xupefei** [comment]
I don't think it's useless. The same thing happens before and got fixed in the first Windows 11 release: https://github.com/QL-Win/QuickLook/issues/955#issuecomment-886008684.

**Comment by Shomnipotence** [comment]
> I don't think it's useless. The same thing happens before and got fixed in the first Windows 11 release: [#955 (comment)](https://github.com/QL-Win/QuickLook/issues/955#issuecomment-886008684).

Where should I post the Feedback? Windows Feedback Hub or ...?

However I suggest that move to Acrylic like https://github.com/JasonStein/Notepads

**Comment by xupefei** [comment]
Windows Feedback Hub is the place.

**Comment by Shomnipotence** [comment]
> Windows Feedback Hub is the place.

Well, it seems will be a api with no supportion in the future. Will you like to choose another technology way?

**Comment by xupefei** [comment]
I simply can't, unless MS fixed the issue when using the new Acrylic with borderless windows.

**Comment by Shomnipotence** [comment]
> I simply can't, unless MS fixed the issue when using the new Acrylic with borderless windows.

Is it possible to use background acrylic brushes?（with border）

**Comment by emako** [comment]
It should be an outdated issue. If you have any questions, continue to follow.
