### ISSUE TITLE
After sleep, quicklook and other uwp applications will exit

### ISSUE THREAD

**Issue by borninfreedom** [QL-Win/QuickLook#1089]
** Issue **
After sleep, quicklook and other uwp applications will exit. 

** OS **
win11 21H2

** quicklook version **
v3.7.1 from Microsoft store

**Comment by xupefei** [comment]
> and other uwp applications will exit

Since this happens for all UWP applications, I think you should report to Microsoft instead :)

**Comment by denghailong123** [comment]
Since this happens for all UWP applications, I think you should report to Microsoft instead :)
