### ISSUE TITLE
the first versions had the magnifying glass in the form of a Q but it does not match with other icons, I decided to make the magnifier with a realistic shape like the Snip & Sketch scissors and the white part form a Q.

### ISSUE THREAD

**Issue by Ph-Rab** [QL-Win/QuickLook#1092]
the first versions had the magnifying glass in the form of a Q but it does not match with other icons, I decided to make the magnifier with a realistic shape like the Snip & Sketch scissors and the white part form a Q.
**QuickLook Icon V3 | Snip & Sketch Icon**
![Quicklook](https://user-images.githubusercontent.com/25881789/78299686-54212a00-7504-11ea-8985-6b80f37d9ed3.png)![snip](https://user-images.githubusercontent.com/25881789/78300107-f8a36c00-7504-11ea-9cec-d9f081324f63.png)

_Originally posted by @QubitsDev in https://github.com/QL-Win/QuickLook/issues/627#issuecomment-608091628_

**Comment by rabelux** [comment]
Please stop messing around here.

**Comment by xupefei** [comment]
Reported.
