### ISSUE TITLE
After installing PostScriptViewer v1 expansion pack, the software cannot preview the. eps file.

### ISSUE THREAD

**Issue by tthigher** [QL-Win/QuickLook#1096]
<img width="447" alt="image" src="https://user-images.githubusercontent.com/95599158/156685171-8dd707c0-be1c-4359-9578-5a67fc838997.png">

**Comment by rabelux** [comment]
Wrong repo.

**Comment by Nickyg001** [comment]
is the display of EPS fixable?
Many Eps I get this error or another type of error.
