### ISSUE TITLE
You don't support MSG-files longer than 256 characters together with characters of the path

### ISSUE THREAD

**Issue by Blueearthmoon** [QL-Win/QuickLook#1100]
Hi,
I tested your plugin via potable-install:
(+) = PLUS = layout and and german umlauts (so "ä", "ü" etc) are correctly rendered in the preview;
(-) = MINUS (till now) = does NOT support (unlike BrandsICT-Msg) MSG-files longer than 256 characters together with characters of the path (both DOPUS and BrandsICT-Msg support this).
It would be nice if your plugin could do this, too ;-)
Thx. & Cheers

**Comment by emako** [comment]
No fix plan for it
