### ISSUE TITLE
Maybe we should have a separate "discussions" section

### ISSUE THREAD

**Issue by ezxpro** [QL-Win/QuickLook#1103]
I always thought the "issues" page from most GitHub projects seems to be a lot less about issues than it is about discussions in general. 

Explorer Patcher is a project where the devs explicitly ask people to only post issues in that page, and everything else (including feature suggestions or requests, but also general discussions relating the project) goes into a separate discussion page. I think that'd be nice to have here, see this:

https://github.com/valinet/ExplorerPatcher/issues/56

**Comment by xupefei** [comment]
👍
