### ISSUE TITLE
Integration with Files V2 (AKA Files.Community) file explorer.

### ISSUE THREAD

**Issue by ezxpro** [QL-Win/QuickLook#1104]
[Files V2](https://github.com/files-community/Files) is a new file explorer that uses fluent design and is way better than Windows' own file manager. 

You can set it as default and except for some minute features that aren't there yet, it's good enough to replace File Explorer completely, especially if you don't have any extraordinary workflow.

Quicklook doesn't work on it, though.

Is it a possibility that it can work there at some point?

**Comment by rabelux** [comment]
QuickLook is already supported by Files V2. Have a look at the issues in their repo, that should help. https://github.com/files-community/Files/issues?q=is%3Aissue+quicklook

**Comment by ezxpro** [comment]
@rabelux Thanks, I didn't find info about that.

**Comment by ezxpro** [comment]
> QuickLook is already supported by Files V2. Have a look at the issues in their repo, that should help. https://github.com/files-community/Files/issues?q=is%3Aissue+quicklook

Well, it's not working here. According to what I found there, it should work with files right out of the box, though.

**Comment by rabelux** [comment]
That's right and one guy wrote he resetted his files app then it worked again. There is nothing QuickLook can do.

**Comment by ezxpro** [comment]
Reinstalling quicklook worked, thanks.

Em sáb., 12 de mar. de 2022 às 18:59, Alexander Raab <
***@***.***> escreveu:
