### ISSUE TITLE
Please add an Outlook MSG preview handler API in order for QuickLook to be used for file manager preview panes

### ISSUE THREAD

**Issue by DavidGP** [QL-Win/QuickLook#1107]
It would be awesome if QuickLook's excellent Outlook preview:
![image](https://user-images.githubusercontent.com/1527716/158159849-ac994cf4-70b2-4c00-b7d8-70507513e6fa.png)
...could also be used by third party programs, particularly by file managers.

The problem with previewing Outlook MSG files in file managers is that (apart from QuickLook) there is no viable way to preview them other than Outlook's own preview handler.  However, Outlook's preview handler has the major issue that it first connects to the Outlook server when you try to preview any MSG file, and therefore it is almost unusably slow in most cases.

See the discussion about this [at the Dopus Resource center](https://resource.dopus.com/t/alternative-msg-viewer-for-outlook-etc-by-brands-ict/34037/3?u=davidp).

There, it was suggested to ask you to add a preview API to QuickLook's Outlook preview, so that QuickLook could be used as a preview handler in Dopus (or in other file managers).

The only alternative to Outlook's own preview is a MSG preview handler called [Brands ICT](https://www.brandsict.nl/msgpreviewer_en.php), which is also mentioned in that discussion. The Brands ICT preview handler is, however, very rudimentary:
![image](https://user-images.githubusercontent.com/1527716/158159650-d7a87d8c-f8af-4703-afcb-72c68dc1114e.png)

Thanks @Paddy for considering this feature request!

**Comment by paddy** [comment]
Wrong paddy. I don't maintain, use or follow this repository. Thanks.

**Comment by DavidGP** [comment]
Sorry. But my feature request is correct here, is it?

**Comment by xupefei** [comment]
Thumbnail providers have a different architecture, I'm quite sure that it's not possible for QL to do it without rewriting most codes.

I'll mark this issue as `won't do` but meanwhile, DOpus does support QuickLook -- just press `Spacebar` in DOpus.

**Comment by DavidGP** [comment]
Sorry, I saw only now that this has been rejected and/or closed. 

I was going to add that this is not about a Thumbnail Previewer, but about a Windows Explorer Preview Pane Plugin. 

So maybe this issue can be reopened, if it should be possible to implement it.
