### ISSUE TITLE
Failed to preview the picture with quicklook

### ISSUE THREAD

**Issue by laozhaixiaodi** [QL-Win/QuickLook#1108]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
Using quicklook to preview the pictures on  the desktop is okay , but when previewing the pictures in other paths under the file explorer , pressing the spacebar does not respond

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 21H1 
 - QuickLook Version:  v3.7.1 from Windows Store

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by rabelux** [comment]
Are you using default windows explorer or some 3rd party software? 3rd party software might not be supported. It's explained in the wiki.
If you're using windows file explorer pls provide screenshots.
