### ISSUE TITLE
Display connection resets (display turns on and turns back on) when clicking the "X" to close a preview window.

### ISSUE THREAD

**Issue by Carl2X** [QL-Win/QuickLook#1111]
*Plese search within existing issues before the submission. Has this issue already been reported?*
No

**Describe the bug**
Display connection resets (the display turns on and turns back on) when clicking the "X" to close a preview window. This behavior only occurs when clicking the "X" to close the window; using spacebar or ESC to close it does not incur the issue.

**To Reproduce**
1. preview any file with Quicklook using spacebar.
2. click the X in the top right.

**Expected behavior**
The window should close without turning the display off.

**Desktop (please complete the following information):**
 - OS Version: Windows 11 Version 21H2 (OS Build 22000.556)
 - QuickLook Version: 3.7.1 from msi

**Screenshots and Exception Log**
Not applicable

**Comment by Carl2X** [comment]
Update:
This issue fixed itself after the restart but reappeared after leaving the computer on for a while. This issue also seems to be in sync with a video playback issue I experienced while playing Netflix on Microsoft Edge. After leaving the computer on for a while, trying to play any Netflix video would cause Windows to freeze for a dozen seconds.

**Comment by rabelux** [comment]
Sounds like another bug from Microsoft and not like something QuickLook can fix.
