### ISSUE TITLE
Failed to preview MS/WPS Office files such as docx (Consider reporting this incident to author.)

### ISSUE THREAD

**Issue by oxu118o** [QL-Win/QuickLook#1113]
Hi there,

Quicklook is useful, but I got an issue, hope you can help me.

I can preview pictures via quicklook and I installed plugin, but I could not preview MS/WPS Office such as docx.
My Windows update is disabled so that I can share my printer in the internet with my colleague.

**Expected behavior**
To preview office files directly.

**Desktop (please complete the following information):**
 - OS Version:[Windows 10 Pro]
 - QuickLook Version: [3.6.11 from Windows Store] (3.7.1 could not be opened.) 

**Screenshots and Exception Log**
![Failed to preview MSWPS Office files](https://user-images.githubusercontent.com/102003395/159224237-1caf7d2c-f536-4585-bfb6-3581db35e521.png)

![open Windows updates](https://user-images.githubusercontent.com/102003395/159224726-da22403d-8b17-4701-a016-484cd3abfeb6.png)

Thank you so much!
Ming Xu

**Comment by syehoonkim** [comment]
I think writing down the content of C:\Users\(username)\AppData\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log or attatching the file will be very helpful.

**Comment by oxu118o** [comment]
> I think writing down the content of C:\Users(username)\AppData\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log or attatching the file will be very helpful.

Thank you Kim! Is this file?

![C file](https://user-images.githubusercontent.com/102003395/159447781-1e6b923b-7af7-4d47-8566-5f0382c94f21.png)

========2022/3/21 16:40:52========
System.Runtime.InteropServices.COMException (0x80040154): 检索 COM 类工厂中 CLSID 为 {0C7FEF07-DCD9-4120-9647-D1CE32F289CD} 的组件失败，原因是出现以下错误: 80040154 没有注册类 (异常来自 HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))。
   在 System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   在 System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, Boolean nonPublic)
   在 System.Activator.CreateInstance(Type type)
   在 QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   在 QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__1()

========2022/3/21 16:41:07========
System.Runtime.InteropServices.COMException (0x80040154): 检索 COM 类工厂中 CLSID 为 {0C7FEF07-DCD9-4120-9647-D1CE32F289CD} 的组件失败，原因是出现以下错误: 80040154 没有注册类 (异常来自 HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))。
   在 System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   在 System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, Boolean nonPublic)
   在 System.Activator.CreateInstance(Type type)
   在 QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   在 QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__1()

**Comment by liwenqiang1990** [comment]
> The same to me. The Office installation is office365 desktop

========2022/3/20 22:39:55========
System.Runtime.InteropServices.COMException (0x80040154): 检索 COM 类工厂中 CLSID 为 {A1BBCFD9-B54C-443D-BC56-0BC3840120DB} 的组件失败，原因是出现以下错误: 80040154 没有注册类 (异常来自 HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))。
   在 System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   在 System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, Boolean nonPublic)
   在 System.Activator.CreateInstance(Type type)
   在 QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   在 QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__1()

**Comment by oxu118o** [comment]
> It says the COM component is not registered. Could you check your Office installation? Which version you're using?

All right. I am using WPS office, the latest version: 11.1.0.11566-release. Thanks!

**Comment by oxu118o** [comment]
> > It says the COM component is not registered. Could you check your Office installation? Which version you're using?
> 
> All right. I am using WPS office, the latest version: 11.1.0.11566-release. Thanks!

Oh one more thing, I think it was last year, I thought it might because I am using WPS Office, so I deleted it and used MS Office 2013 or 2010(I forget the version), but I could not preview files as well.

**Comment by xupefei** [comment]
So it might be WPS Office has not registered those COM components currently. I have no way to debug it, so the only solution I would recommend is to use another Office viewer which does not depend on Office installation.

**Comment by liwenqiang1990** [comment]
> 

I also installed wps with office 365, Most likely caused by wps

**Comment by liwenqiang1990** [comment]
> 
May be you can try this:
https://blog.csdn.net/qq_28539161/article/details/80079476

**Comment by oxu118o** [comment]
> So it might be WPS Office has not registered those COM components currently. I have no way to debug it, so the only solution I would recommend is to use another Office viewer which does not depend on Office installation.

I see,  I don't know anything about COM components, but would like to continue to try MS Office in the future. Thanks for the suggestion, Pefei!

**Comment by oxu118o** [comment]
> 

Thank you! I will browse it.

**Comment by oxu118o** [comment]
> > 
> 
> May be you can try this: https://blog.csdn.net/qq_28539161/article/details/80079476

 I don't know anything about COM components.

**Comment by oxu118o** [comment]
> > 
> 
> May be you can try this: https://blog.csdn.net/qq_28539161/article/details/80079476

Thank you, I will browse it.

**Comment by oxu118o** [comment]
> So it might be WPS Office has not registered those COM components currently. I have no way to debug it, so the only solution I would recommend is to use another Office viewer which does not depend on Office installation.

![image](https://user-images.githubusercontent.com/102003395/160036574-86596fb1-cf5a-4b7c-af2d-013ed9c78bb3.png)
Did you mean this one?

**Comment by liwenqiang1990** [comment]
https://github.com/QL-Win/QuickLook/issues/1182#issuecomment-1285188528
