### ISSUE TITLE
Locale emulator works exceptionally in win11

### ISSUE THREAD

**Issue by 610364023** [QL-Win/QuickLook#1115]
exe works， txt does not
win11 22000.588
![360截图20220323150622472](https://user-images.githubusercontent.com/45279039/159643937-096f1a7d-a50c-4fd7-ae9e-c589405cda71.jpg)
![360截图20220323150858549](https://user-images.githubusercontent.com/45279039/159643943-1cd08845-ab3e-4c65-996d-8467c7451e76.jpg)
t

**Comment by rabelux** [comment]
Wrong repo.
