### ISSUE TITLE
Can't preview pictures in word using OfficeViewer v4

### ISSUE THREAD

**Issue by AdoShan** [QL-Win/QuickLook#1117]
*For all's convenience, please use English to fill this issue.*
Can't preview pictures in word using OfficeViewer v4
*Please search within existing issues before the submission. Has this issue already been reported?*
No
**Describe the bug**
Can't preview pictures in word using OfficeViewer v4，Install Office 365 using office.exe
![image](https://user-images.githubusercontent.com/44154107/160078151-fc93904a-06d5-4ed0-8724-148ff3f83ef0.png)

**To Reproduce**
1. Open docx document with pictures
2. See error

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [Windows 11 21H2 22000.556 ]
 - QuickLook Version: [ 3.7.1 from Windows Store]

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/44154107/160077453-0b97ab07-5051-4488-b231-a941dd2abc97.png)
[07朱伟.docx](https://github.com/QL-Win/QuickLook/files/8348488/07.docx)

**Comment by emako** [comment]
![image](https://github.com/user-attachments/assets/7f881b45-e4f3-4352-add2-139b7fa4a8cb)

Not reproduced in latest version
