### ISSUE TITLE
Preview Window Position

### ISSUE THREAD

**Issue by photkey** [QL-Win/QuickLook#1120]
窗口位置
我使用PowerToys的FancyZones，将屏幕分为左右两部分，FancyZones可以把应用窗口绑定在屏幕固定的位置。
使用QuickLook 预览第一个文件的时候，可以正常的出现在上次绑定的位置上，但是切换下一个文件的时候 位置就发生变化了；
这个时候如果用FancyZones调整一次预览窗口，再次切换下一个文件 就可以一直固定在期望的位置上。

希望能够针对FancyZones优化一下上面描述的问题，如果这是不太麻烦的话。
--------------
I use FancyZones of PowerToys to divide the screen into two parts, FancyZones can bind the application window to a fixed position on the screen.
When I use QuickLook to preview the first file, it appears normally at the last bound position, but when I switch to the next file, the position changes.
If I use FancyZones to adjust the preview window once, and switch to the next file again, it stays in the desired position.

I hope to optimize the problem described above for FancyZones, if that is not too much trouble.

Translated with www.DeepL.com/Translator (free version)

 - OS Version: Windows11（21H2 ）
 - QuickLook Version: 3.7.1

![FancyZones](https://user-images.githubusercontent.com/60434581/160662891-9e257699-9790-4c85-8c4b-9b8e2e94e297.gif)

**Comment by ariefcfa** [comment]
hi, maybe this AutoHotkey code can be a workaround (i used it myself). It's not my code, i just assemble it together from several forum post. For your usage case, maybe modified it at the `WinMove` part become (maybe): 
`WinActivate, ahk_exe QuickLook.exe`
`Send, #{right}`
cheers!
**code** 

```
#persistent

SetTimer, MonProg, 1000

MonProg:
IfWinExist, ahk_exe QuickLook.exe 
{
   qwinHandle := WinExist("ahk_exe QuickLook.exe")
   VarSetCapacity(monitorInfo, 40), NumPut(40, monitorInfo)
   qmonitorHandle := DllCall("MonitorFromWindow", "Ptr", qwinHandle, "UInt", 0x2)
   DllCall("GetMonitorInfo", "Ptr", qmonitorHandle, "Ptr", &monitorInfo)
   
   qworkRight	:= NumGet(monitorInfo, 28, "Int") ; Right
   qworkBottom	:= NumGet(monitorInfo, 32, "Int") ; Bottom
   qxWinPos		:= (qworkRight / 2) - 30
   qWidth		:= (qworkRight - qxWinPos)
   qHeight		:= (qworkBottom - 1)

   WinGetPos,xPos,,wWidth,,ahk_exe QuickLook.exe
   
   ;MsgBox 1
   If (xPos = qxWinPos) AND (wWidth = qWidth) 
   {
       ;MsgBox 2
       Return
   }
   If (xPos <> qxWinPos) 
   {
       WinGet, TheProg, ProcessName, A
       ;MsgBox 3
       If (TheProg = "QuickLook.exe") 
       {
	   WinWaitClose, ahk_exe QuickLook.exe
           ;MsgBox 4	  
	  Return 
       }
       If (TheProg <> "QuickLook.exe") 
       {
           WinMove,ahk_exe QuickLook.exe,,qxWinPos,0,qWidth,qHeight
	   ;MsgBox 5
           Return
       }
   }
}
```

**Comment by emako** [comment]
QL有自己的窗口逻辑，这很复杂，你可以继续使用AutoHotkey满足你的需求
