### ISSUE TITLE
Hope to add the ability to preview normal binary files in hexadecimal.

### ISSUE THREAD

**Issue by lc6464** [QL-Win/QuickLook#1122]
When I preview a normal binary file (which Quick Look doesn't support parsing), I can display its data in hex.

Like [Hex Editor](https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor "Hex Editor Extension") in [VS Code](https://code.visualstudio.com/ "Visual Studio Code").

![Screenshot of Hex Editior 0](https://user-images.githubusercontent.com/64722907/161676387-f9e06f27-3177-450c-9a3e-85f34c8b164b.png "Screenshot of Hex Editior 0")

![Screenshot 1](https://user-images.githubusercontent.com/64722907/161676942-f8672a33-3b8c-4b1e-aee7-9cc40e35edcb.png "Screenshot 1")

**Comment by xupefei** [comment]
You could develop a plugin for this use case. See https://github.com/QL-Win/QuickLook/wiki/Develop%2C-build-and-integrate.

**Comment by lc6464** [comment]
I will try it during summer vacation.
(Unless the school directly stopped giving me summer vacation, which is not impossible)
