### ISSUE TITLE
Suddenly became very slow (delay of 8sec for 2kb file)

### ISSUE THREAD

**Issue by douteld** [QL-Win/QuickLook#1123]
I have been very happy with Quicklook for quite some time and everything was working fine just until a couple of days ago when of a sudden it started having this big lag between the space-bar hit and image/video/text pop-up.
Size of file doesn't matter at all, it can be a 2gb or a 2kb file, it takes the same amount of time.

Between space-bar hit image pop-up: 8-10 sec delay

Would appreciate if there is some solution for this problem.

Thank you all.

Windows 10 21H1
QuickLook Version: 3.7.1 from Windows Store

**Comment by FinleyF** [comment]
I also found this problem

**Comment by seanmamasde** [comment]
any updates on this?

**Comment by xupefei** [comment]
I never had this issue and have no idea how to reproduce it :(

**Comment by seanmamasde** [comment]
I only have this problem using Microsoft store version. I uninstalled it and reinstalled via chocolatey with several plugins running and it's working pretty well so far.

**Comment by Yijie-Ding** [comment]
> I only have this problem using Microsoft store version. I uninstalled it and reinstalled via chocolatey with several plugins running and it's working pretty well so far.

i tried to uninstall then install back from ms store, but still it's very slow, I think this should be the windows 11 problem as the right click menu pop up is also super slow on my end

**Comment by yiqiangjizhang** [comment]
Happened to me as well. Worked well in Windows Insider Preview, however, I did a clean Windows 11 install on my laptop and now it struggles to load anything...

**Comment by emako** [comment]
This should be an outdated issue I see
