### ISSUE TITLE
Quicklook is not functioning when used in Files app.

### ISSUE THREAD

**Issue by DarwinsRadioDNA** [QL-Win/QuickLook#1124]
Pressing spacebar within the Files app (listed in wiki as a supported app) does not result in preview of selected image  (.jpg, or any other file type present).
Quicklook performs as expected when using File Explorer.

Using:
 Quicklook version 3.7.1
 Files app version 2.1.15.0
Windows 11 Pro for workstations v. 21H2, Build # 22000.593 

Thanks in advance for your assistance.

**Comment by rabelux** [comment]
This has been reported numerous times. Pls look for existing issues before creating new ones.

**Comment by DarwinsRadioDNA** [comment]
I apologize.
I did look for an existing issue.
I found none.

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
04/10/22,
02:34:31 PM

**Comment by DarwinsRadioDNA** [comment]
According to the Issues tabs, this bug was reported 1 other time. That report was also labeled as closed and a duplicate. 
Again, I apologize. I didn't think that I should have to browse through closed issues to find reference to an open issue.
