### ISSUE TITLE
Running `choco install quicklook` does not work

### ISSUE THREAD

**Issue by dmonder** [QL-Win/QuickLook#1130]
Running `choco install quicklook` says it installs QuickLook but a search for quicklook.exe results in no files found. Re-running choco results in a warning that quicklook 3.7.1 is already installed.

I am running Windows 10 Enterprise LTSC Version 1809 OS build 17763.2686.

_Originally posted by @dmonder in https://github.com/QL-Win/QuickLook/issues/168#issuecomment-1104191777_

**Comment by rabelux** [comment]
I'll close this as the dev is not responsible and in no way linked to the choco package.
