### ISSUE TITLE
The selected page focus border on the pdf view is hard to see. 

### ISSUE THREAD

**Issue by faisalmh4045** [QL-Win/QuickLook#1150]
Hey, thanks for a great app!
In image 1, you can see that the selected page is hard to distinguish due to very thin border witdh.
A white border like in image 2 will be great for visibility.

![img 1](https://user-images.githubusercontent.com/64207960/173423816-1006107e-c461-4689-a046-d9c4026af910.png)
![img 2](https://user-images.githubusercontent.com/64207960/173423823-30302337-38e2-4f46-93e6-bf1c9ca60537.png)

**Comment by Kammreiter** [comment]
The Border should have a bold border line which marks the current page clearly 😎

**Comment by emako** [comment]
The built-in PDF viewer has limited features, it is recommended to use this plugin

https://github.com/QL-Win/QuickLook.Plugin.PdfViewer-Native

If you still have any questions, please continue to reply.
