### ISSUE TITLE
Integration with PowerToys?

### ISSUE THREAD

**Issue by ansshkki** [QL-Win/QuickLook#1155]
This app is very useful for all users and reflects as a default Windows app because of its fluent UI and good performance.
Thus, it shares these features with PowerToys, they are all things that extends Windows UX by a lot.

I think if it is included with it, it will reach more users and will acheive its goal.

Also, PowerToys is open source and accepts contributions and plugins.

Please note that I don't know if this could be made or not, just a thing that gets into my mind. And don't know if I should recommend that in this repo or in PowerToys one.

**Comment by liujiuzhou** [comment]
Request integration with XYplorer
