### ISSUE TITLE
Add support for .feather files

### ISSUE THREAD

**Issue by NathanDai5287** [QL-Win/QuickLook#1164]
A `.feather` file is essentially a `.csv` or `.xlsx` file, but it is much faster. While it may take 30 seconds to read a `.csv` in Python, it takes less than 1 second to read a `.feather`. 

I would like to be able to preview `.feather` files. 

Currently, to view `.feather` files, I open Python, import `pandas`, and use `pandas.read_feather()`, but I think this extra work could easily be circumvented. 

As of now, there is no preview support for `.feather` files in neither Windows 10 nor QuickLook:
![image](https://user-images.githubusercontent.com/61402904/181954969-a9f2e23f-dc65-4e8b-b53d-061c052f81a4.png)
![image](https://user-images.githubusercontent.com/61402904/181955162-a6eaf07d-db0e-4dfa-9936-97983aacb2a6.png)

**Comment by emako** [comment]
QL has no plans to support built-in feather plugin, please develop your own plugin
