### ISSUE TITLE
Close QL when window is unfocussed/ inactive

### ISSUE THREAD

**Issue by mickey4322** [QL-Win/QuickLook#1173]
Currently, we need to hit space key in order to close a quicklook window. ~~On macOS, it is possible to close the window when clicked somewhere else on the screen~~. Pls bring this option to windows as well.

**Comment by xupefei** [comment]
> On macOS, it is possible to close the window when clicked somewhere else on the screen

I use macOS, and I don't think so.

**Comment by mickey4322** [comment]
You are right. macOS does not have that function. 
But it would be nice to have it in QuickLook.

**Comment by rabelux** [comment]
On my opinion it would be very unpleasant if the window disappeared on losing focus

**Comment by emako** [comment]
Don't consider it for now
