### ISSUE TITLE
Improved plugin for viewing 3D files based on open source libraries Assimp and Filament

### ISSUE THREAD

**Issue by Dragoy** [QL-Win/QuickLook#1178]
### **Is your feature request related to a problem? Please describe.**
I always get frustrated when I have to view 3D files with standard viewer apps, especially when there are a lot of models it's not really convenient

### **Describe the solution you'd like**
It would be cool to have a plugin to view 3D files based on the [Assimp](https://github.com/assimp/assimp) library, which has the ability to read and render more than 40+ file types. And for rendering in the window use [Filament](https://github.com/google/filament), which is a real-time physical rendering engine.

### **Describe alternatives you've considered**
The standard 3D viewing tools in Windows, but they sometimes work incorrectly and slowly.

**Comment by rabelux** [comment]
Have you tried the HelixViewer plugin? See https://github.com/QL-Win/QuickLook/wiki/Available-Plugins.
Don't know whether it still works as it hasn't been updated in a while.
