### ISSUE TITLE
Office插件（OfficeViewer-Native v1）不能预览文件，出现闪退，然后显示没装插件那种默认预览界面

### ISSUE THREAD

**Issue by happyflyer** [QL-Win/QuickLook#1182]
# 环境

平台：Windows11
QuickLook 版本：3.7.1
OfficeViewer-Native v1 版本：2019-03-30

# 报错日志

```log
System.Runtime.InteropServices.COMException (0x80040154): 检索 COM 类工厂中 CLSID 为 {0C7FEF07-DCD9-4120-9647-D1CE32F289CD} 的组件失败，原因是出现以下错误: 80040154 没有注册类 (异常来自 HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))。
   在 System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   在 System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, Boolean nonPublic)
   在 System.Activator.CreateInstance(Type type)
   在 QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   在 QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__1()
```

**Comment by happyflyer** [comment]
同时安装了office2016和wps情况下会出现闪退，卸载了wps之后，就可以正常使用了。

**Comment by liwenqiang1990** [comment]
https://zhuanlan.zhihu.com/p/454259765 可以参考这个文章。

或者导入一下注册表项
-----------------------------------------
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\.docx\ShellEx\{8895b1c6-b41f-4c1c-a562-0d564250836f}]
@="{84F66100-FF7C-4fb4-B0C0-02CD7FB668FE}"
[HKEY_CLASSES_ROOT\.doc\ShellEx\{8895b1c6-b41f-4c1c-a562-0d564250836f}]
@="{84F66100-FF7C-4fb4-B0C0-02CD7FB668FE}"
[HKEY_CLASSES_ROOT\.xlsx\ShellEx\{8895b1c6-b41f-4c1c-a562-0d564250836f}]
@="{00020827-0000-0000-C000-000000000046}"
[HKEY_CLASSES_ROOT\.xls\ShellEx\{8895b1c6-b41f-4c1c-a562-0d564250836f}]
@="{00020827-0000-0000-C000-000000000046}"
[HKEY_CLASSES_ROOT\.pptx\ShellEx\{8895b1c6-b41f-4c1c-a562-0d564250836f}]
@="{65235197-874B-4A07-BDC5-E65EA825B718}"
[HKEY_CLASSES_ROOT\.ppt\ShellEx\{8895b1c6-b41f-4c1c-a562-0d564250836f}]
@="{65235197-874B-4A07-BDC5-E65EA825B718}"

**Comment by NYH951117** [comment]
Failed to preview VV.hdr Consider reporting this incident to QuickLook's author.13:07
Among them, VV.hdr is the header file of ENVI remote sensing image, which is a pure text file. Any modification of its suffix (such as'.hdrabc') can be previewed or displayed normally, but an error will be reported when using '.hdr '.
