### ISSUE TITLE
TSV (Tab separated) file support

### ISSUE THREAD

**Issue by samuel-pipelaunch** [QL-Win/QuickLook#1183]
**Is your feature request related to a problem? Please describe.**
Since we need to deal with regional settings with .CSV (the separator is not a comma in some countries) using tab separator will solve the issue.

**Describe the solution you'd like**
Just support .TSV files like .CSV ( it's a valid file extension: https://fileinfo.com/extension/tsv )

**Describe alternatives you've considered**
Just renaming the file to CSV will work but then we will lose the file association in Excel, so it's important to add TSV to the file list

**Comment by xupefei** [comment]
Since renaming the file works, the actual support is just a one line change to add the TSV extension to TextViewer. Could you send a PR?

**Comment by xupefei** [comment]
It's not based on MIME but extension: https://github.com/QL-Win/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.CsvViewer/Plugin.cs#L37

**Comment by emako** [comment]
Done
