### ISSUE TITLE
Can't View Video Files inside Winrar.

### ISSUE THREAD

**Issue by oscdat** [QL-Win/QuickLook#1190]
I simply "Stored" five videos inside a rar file without compressing it but when I clicked on the RAR file, I'm getting this [error message.](https://i.imgur.com/NuMU5dQ.png)

All the videos played just fine before rar'ing it and also after extracting it from the same rar file. Please look into this and thank you for this awesome piece of software.

**Comment by rabelux** [comment]
Your chances of receiving help are higher if you'd follow the issue template

**Comment by emako** [comment]
I don’t think this is a problem with QL
