### ISSUE TITLE
End preview when attempting to move files

### ISSUE THREAD

**Issue by JimMcBubbles** [QL-Win/QuickLook#1195]
**Is your feature request related to a problem? Please describe.**
Im attempting to move files (gifs in this case) as i preview them, but windows is complaining that the file is open in QuickLook

when i switch to a different file and try to drag the other one it switches back when i click to drag.

**Describe the solution you'd like**
I would love it if QuickLook would stop previewing the file when i try to move it.

**Describe alternatives you've considered**
alternatively if i could click and drag the file from the QuickLook preview to the folder im trying to move it to.

**Comment by rabelux** [comment]
I suggest you close the preview when moving files.

**Comment by JimMcBubbles** [comment]
I'm switching between files to review them before I move them. Every time I come across a file I need to move I have to close the preview window, move the file, then reopen the preview window to continue reviewing, rinse and repeat. I'm working with hundreds (sometimes thousands) of unique files so that gets a bit tedious after a while.
