### ISSUE TITLE
special character in filename makes .mp4 files unable to preview

### ISSUE THREAD

**Issue by Kosette** [QL-Win/QuickLook#1199]
**Describe the bug**
if a .mp4 file has a special character() in filename, the result turns an error `系统找不到指定的文件`.I paste the character in text editor, it seems it's an emoji(a computer?). it may not displayed correctly like in Win11. 

**To Reproduce**
1. copy this character()
2. paste it in a .mp4 filename
3. press Space to preview 

**Expected behavior**
correctly preview a video file.

**Desktop (please complete the following information):**
 - OS Version: Win11 22H2
 - QuickLook Version: [3.7.1 from Windows Store]

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/35268640/197280260-79cef976-2a04-4bd0-806b-12d5bd88561e.png)

**Comment by rabelux** [comment]
Duplicate
