### ISSUE TITLE
cant copy texts in pdf

### ISSUE THREAD

**Issue by birchmoonlight** [QL-Win/QuickLook#1201]
As the title indicates.
I'm using the Windows Store version, 3.7.1.

**Comment by birchmoonlight** [comment]
can't copy text in .pptx either, but officeviewer doesn't have an issue, so I have to say it here

**Comment by emako** [comment]
Use natived one as an alternative

https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native
https://github.com/QL-Win/QuickLook.Plugin.PdfViewer-Native
