### ISSUE TITLE
[Question] Privacy Policy

### ISSUE THREAD

**Issue by Looodon** [QL-Win/QuickLook#1205]
Hello!
I hope your day is going well!
1) I wanted to ask what this means "The software application exchange data only with https://github.com/ using the GitHub Releases API. If you are viewing a remote content via the software, data exchange will happen between you and the remote content." English is not my first language, if you dont mind can you please explain this?

2) do you recommend I download (official release 3.7.1 Latest on Nov 16, 2021) or the (master branch with Commits on Aug 3, 2022)?

**Comment by xupefei** [comment]
1. This software will do data exchange with Github to find if there's a new update. See the code here: https://github.com/QL-Win/QuickLook/blob/master/QuickLook/Helpers/Updater.cs#L47.
2. This software includes an HTML previewer, therefore when you preview an HTML file, data exchange will happen between this software and the remote sites (to load images, etc.)
3. You can now download version 3.7.2 :)

**Comment by xupefei** [comment]
That's correct :)
