### ISSUE TITLE
Windos 22H2 new multi-tag browser compatibility

### ISSUE THREAD

**Issue by Thundor404** [QL-Win/QuickLook#1213]
# BUG description
When using the new multi-tag file browser of Windows 22h2, the Quicklook will not preview the selected item of the selected tag if there already exists a selected tag in another tag (perhaps the tag selected before).

# System info
 - OS Version: Windows11 22H2
 - QuickLook: 3.7.1 installer version

# Screenshoot
For example:
![image](https://user-images.githubusercontent.com/41377351/201336890-5c9e70db-ead7-4ead-9e6c-6ee7cd3bde55.png)

**Comment by xupefei** [comment]
This is fixed in version 3.7.2: in https://github.com/QL-Win/QuickLook/releases/tag/3.7.2. Check it out!
