### ISSUE TITLE
Office插件（OfficeViewer-Native v1）不能预览文件

### ISSUE THREAD

**Issue by cherub0507** [QL-Win/QuickLook#1216]
平台：Windows10 professional 21H2
QuickLook 版本：3.7.2
OfficeViewer-Native v1 版本：2019-03-30

仅安装office 365（非Windows Store版），未安装其他office，添加了OfficeViewer-Native v1插件，所有office文档只显示一个文件属性，不能预览
换过OfficeViewer v4插件，也不行

![微信截图_20221115105656](https://user-images.githubusercontent.com/58015207/201815576-5f71ee7b-8ab2-4ff3-9cb7-8d9f4020edda.png)

已根据https://github.com/QL-Win/QuickLook/issues/1182 及 https://zhuanlan.zhihu.com/p/454259765 确认系统注册表正常

如有其他解决方案请予指导，非常感谢！

**Comment by asnfohsdgfbkxcv** [comment]
一个不能用就用另一个吧。
https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer

**Comment by cherub0507** [comment]
这个插件也试过了，也不行

上面特意说明 “换过OfficeViewer v4插件，也不行”

**Comment by ccmcher** [comment]
试试OfficeViewer v3插件

**Comment by lifugithub** [comment]
我安装OfficeViewer v4插件能预览word，不能预览，是否有解决办法

**Comment by gerfind** [comment]
此插件调用的是本地Office，可能需要确保本地Office正常才能使用，经测试在Win11 22H2搭配Office 365（非应用商店版本），此插件效果比另一个预览office的插件速度要快而且有一些另一个插件不能预览的此插件可以。

**Comment by Dr-S1x17** [comment]
遇见过相同情况，v4预览时会有加载文件内容的动作，但是最后还是渲染成文件信息。
换成v3可以成功预览文件内容，但是遇见大一点的excel，预览直接是空的，还是有点问题， 先将就着用

**Comment by Anphetamine** [comment]
使用V3版本可解决word excel文件打不开的问题

**Comment by emako** [comment]
365用户请使用非navite版插件作为替代
