### ISSUE TITLE
Pin the preview windows

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [QL-Win/QuickLook#1218]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Pin the preview windows, and fixed the windows size.

**Describe alternatives you've considered**
No.

**Additional context**
Pin the preview windows, and fixed the windows size, to arrange multiple windows and improve work efficiency.

**Comment by emako** [comment]
#45
