### ISSUE TITLE
can not preview DNG files

### ISSUE THREAD

**Issue by PriceWang** [QL-Win/QuickLook#1220]
this is what it looks like when previewing the dng file
![preview](https://user-images.githubusercontent.com/30796250/202926433-2ac553e1-8e4a-48a9-a56a-e0801a8387bd.PNG)

**Comment by xupefei** [comment]
Did you save this file with `maximal compatibility`?

**Comment by emako** [comment]
Fix in nightly build

https://github.com/QL-Win/QuickLook/releases
