### ISSUE TITLE
How can I enable quicklook to preview files in VoidTool's Everything Search?

### ISSUE THREAD

**Issue by andrewcincotta** [QL-Win/QuickLook#1227]
Title is question. Hoping to be able to press space and see a file or folder preview of the selected item in VoidTool's Everything Search

**Comment by rabelux** [comment]
Have you discovered [this](https://github.com/QL-Win/QuickLook/wiki/File-Managers) page yet?

**Comment by andrewcincotta** [comment]
> Have you discovered [this](https://github.com/QL-Win/QuickLook/wiki/File-Managers) page yet?

I checked this I don't see anything about VoidTool's Everything Search. Am I missing something?

**Comment by xupefei** [comment]
> > Have you discovered [this](https://github.com/QL-Win/QuickLook/wiki/File-Managers) page yet?
> 
> I checked this I don't see anything about VoidTool's Everything Search. Am I missing something?

See this:
```
Everything (requires Everything to be installed as a service and not be run as admin)
```

**Comment by andrewcincotta** [comment]
> > > Have you discovered [this](https://github.com/QL-Win/QuickLook/wiki/File-Managers) page yet?
> > 
> > 
> > I checked this I don't see anything about VoidTool's Everything Search. Am I missing something?
> 
> See this:
> 
> ```
> Everything (requires Everything to be installed as a service and not be run as admin)
> ```

How can I install Everything as a service?

**Comment by xupefei** [comment]
https://www.voidtools.com/support/everything/everything_service/

**Comment by andrewcincotta** [comment]
> https://www.voidtools.com/support/everything/everything_service/

I'm using the beta version of everything, which it installed as a service, and the issue still persists.

**Comment by xupefei** [comment]
Do not launch `Everything.exe` as admin.

**Comment by andrewcincotta** [comment]
@xupefei 

I haven't been, and the issue still persists.

**Comment by drixtol** [comment]
@xupefei this is still not working. I believe this is related to the window class name. Everything 1.5 defaults to having a instance which is included in the window title(it also sets a named pipe but i dont know how that all works). Everything 1.4 does not do this by default. If you put the dummy file into the folder it will disable the alpha instance and it immediately starts working again. 
It does not work with any instance names. 

Can this get reopened?

References
https://www.voidtools.com/support/everything/multiple_instances/#named_instances
"Everything 1.5 Alpha will be installed to C:\Program Files\Everything 1.5a and will run in a [1.5a instance]"
https://www.voidtools.com/forum/viewtopic.php?t=9787

![image](https://github.com/QL-Win/QuickLook/assets/20601906/88a5ff30-205c-412e-b386-fded74dbce6c)

**Comment by KongNan** [comment]
> disable the alpha instance

Nice! This works for my service-installed 1.5a

**Comment by pa-0** [comment]
Just to add for anyone who comes here looking.  You can also disable alpha instance (for Everything v1.5a) in the Tools > Options > Advanced menu.  Search for alpha and toggle the setting from 'true' to 'false.'  Restart Everything and it should work as expected now.
