### ISSUE TITLE
.md无法打开

### ISSUE THREAD

**Issue by POEG1726** [QL-Win/QuickLook#1231]
**Desktop (please complete the following information):**
OS version:
```
版本	Windows 11 专业工作站版
版本	21H2
安装日期	‎2022/‎6/‎25
操作系统版本	22000.1219
体验	Windows 功能体验包 1000.22000.1219.0
```
QuickLook Version:v3.7.3 from github releases .msi

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/73727028/204715576-8897ea42-cab1-407e-a090-3eff427179f7.png)
![image](https://user-images.githubusercontent.com/73727028/204715899-8fdca1ae-af86-400e-bacb-f022081d2a2c.png)
![image](https://user-images.githubusercontent.com/73727028/204716092-41d5e69a-68ed-4e54-9e83-b67391f18e5d.png)
无法在指定目录找到 .log 文件
我一开始用的是store版本,出问题更新后卸载重装.msi版本,还是一样
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by emako** [comment]
请完整安装Webview2
