### ISSUE TITLE
There is no longer a dark theme when viewing text files.

### ISSUE THREAD

**Issue by Dhyfer1** [QL-Win/QuickLook#1232]
**Describe the bug**
There is no dark theme in the display of text files in the latest version. Instead, in the previous version the text files had dark theme as you can see in the attached image. Please check the QuickLook.Plugin.TextViewer.dll file, because I noticed that if I change this dll file to the same file of version 3.7.2, then I can see txt files with dark theme again. The same bug also happens when I use the latest nightly version.

**Expected behavior**
I only want to see text files with dark background in each new version

**Desktop (please complete the following information):**
 - OS Version: Windows 11 compilation 22623.1020
 - QuickLook Version: 3.7.3 portable from releases

**Screenshots and Exception Log**

![2022-12-01_18-17-07](https://user-images.githubusercontent.com/50301201/205181196-589f3250-7fc1-45e0-ad03-1bccff85ec13.png)

**Comment by xupefei** [comment]
Yeah, the dark theme is disabled by default in version 3.7.3 because I consider syntax highlighting is more important (dark theme has no syntax highlighting). I wrote a few lines about how to re-enable it: [Enable/disable dark theme in the Text editor (since v3.7.3)](https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-dark-theme-in-the-text-editor-since-v373)

**Comment by Dhyfer1** [comment]
> Yeah, the dark theme is disabled by default in version 3.7.3 because I consider syntax highlighting is more important (dark theme has no syntax highlighting). 

Ah, I understand. Well, I'm not a programmer, so syntax highlighting isn't important to me, on the other hand viewing text files in dark theme is what I want. By the way, in many text editors with dark theme you can see syntax highlighting and it looks very nice. I know Quicklook isn't a text editor but if you find a way to view files with syntax highlighting in dark theme it will look very cool.

> I wrote a few lines about how to re-enable it: [Enable/disable dark theme in the Text editor (since v3.7.3)](https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-dark-theme-in-the-text-editor-since-v373)

Thanks for the link. I followed the instructions, but your workaround doesn't work. Before making any changes I have closed Quicklook from the system tray, then I open the QuickLook.Plugin.TextViewer.config file with Notepad++ text editor, and the file appears with only one line:

```xml
<?xml version="1.0" encoding="utf-8"?><Settings />
```

Then I edit the file to add `<AllowDarkTheme>True</AllowDarkTheme>`, at the end it looks like this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <AllowDarkTheme>True</AllowDarkTheme>
</Settings>
```
Then I open Quicklook and select any text file, but there is no dark theme, instead the light theme is still present as in the example image. Is there anything else missing here or have I done something wrong?

**Comment by xupefei** [comment]
You need to quit QuickLook **before** editing this file.

**Comment by xupefei** [comment]
Oh and your OS must be in the Dark Mode.

**Comment by Dhyfer1** [comment]
> You need to quit QuickLook **before** editing this file.
> Oh and your OS must be in Dark Mode.

**Comment by Dhyfer1** [comment]
> You need to quit QuickLook **before** editing this file.
> Oh and your OS must be in Dark Mode.

I know very well, and Windows 11 is in dark theme. And as I told you before I have followed the instructions, I have done these steps over and over again and the display of text files still doesn't appear in dark theme. This happens with the latest portable version of Quicklook.

Before making any changes to the `QuickLook.Plugin.TextViewer.config` file located in the UserData folder, I have done the following:

1. Right click on the Quicklook icon in the system tray and click on the Quit option.
2. With Notepad++ I open the QuickLook.Plugin.TextViewer.config file. The file appears with only one line that I indicated before, then I edit the file adding `<AllowDarkTheme>True</AllowDarkTheme>` as I showed in my previous answer, after the edit I just save the file.
3. I open Quicklook, then select any text file, press Space and the file doesn't appear with dark theme. 

I thought the problem was the encoding of the file, because when I open `QuickLook.Plugin.TextViewer.config` with Notepad++ or with Windows Notepad, the encoding appears as UTF-8 with BOM, but there is no difference because after editing the file and saving it with UTF-8 encoding or with UTF-8 with BOM, I still don't have a dark theme.

**Comment by mooflu** [comment]
It checks for AllowDarkTheme in Plugin.cs but not in the TextViewerPanel constructor.

```     
    Background = OSThemeHelper.AppsUseDarkTheme()
                ? new SolidColorBrush(Color.FromArgb(150, 255, 255, 255))
                : Brushes.Transparent;
```

to get the 3.7.2 dark background with light foreground you'd need something like this I think (added `if`):

```
        private void AssignHighlightingManager(TextViewerPanel tvp, ContextObject context)
        {
            var darkThemeAllowed = SettingHelper.Get("AllowDarkTheme", false, "QuickLook.Plugin.TextViewer");
            var isDark = darkThemeAllowed && OSThemeHelper.AppsUseDarkTheme();
            tvp.HighlightingManager = isDark ? _hlmDark : _hlmLight;
            if (isDark)
            {
                tvp.SetResourceReference(Control.ForegroundProperty, "WindowTextForeground");
                tvp.Background = Brushes.Transparent;
            }
        }

```

**Comment by Dhyfer1** [comment]
@mooflu I'm sorry, I don't understand what you mean, I'm not a programmer, I'm just a basic user. All I want is to see txt files with dark theme like I could see in the previous version.

**Comment by rabelux** [comment]
@Dhyfer1 is your issue fixed with the latest nightly?
