### ISSUE TITLE
PDF and docs thumbnail scrolling runs way too fast

### ISSUE THREAD

**Issue by Gezedka** [QL-Win/QuickLook#1233]
Is your feature request related to a problem? Please describe.

When previewing pdf or other documents containing more than 1 page, I scroll down the thumbnails with the 2-finger gesture and the scrolling speeds up faster than on any other application, making it difficult to land any closer to the page I need. 

Describe the solution you'd like
Can the scrolling be slowed down, e.g. similar to the speed on the pages pane?

Describe alternatives you've considered
I have used the scrollbar by clicking underneath the scroll bar notch several times. But it takes some time when the thumbnail I need is like 20 or 40 pages ahead. 

Additional context
If I adjust the scrolling speed in Windows 10 settings, then other programs would in turn scroll much slower. I have QuickLook 3.7.2

Thanks

**Comment by jiewangjs** [comment]
> 

I raised this problem long time ago, today, it still remains an issue people have to face.
I have tried many other similar apps: seer, quickeye, win-quicklook, they all handle pdf preview quite well, (smooth scrolling of all pages, not in a discrete thumnail fashion).
Just wonder why it is so hard in Quicklook to implement such similar functionality. Most people use quickview to preview pdf mostly, this jumpy thumbnail fashion preview really doesn't help much.

**Comment by mooflu** [comment]
Not sure if it's hard to do with PDFium. 
I think QL could probably get rid of the pdf plugin and just render the pdf via the HtmlViewer plugin and webview2.
If there is interest I can create a PR for that.  WDYT @xupefei ?

**Comment by Gezedka** [comment]
Thanks for the feedback and Happy New Year. As suggested by JieWang, I switched to Seer and I’m trailing it right now.

**Comment by emako** [comment]
PdfViewer is a fast PDF renderer by Google but there has been no update for a long time.

The UI/UX is not as good as using WebView2 supported by MS directly.

So, pls try it.

https://github.com/QL-Win/QuickLook.Plugin.PdfViewer-Native
