### ISSUE TITLE
Image flip buttons directly in the viewer.

### ISSUE THREAD

**Issue by bropines** [QL-Win/QuickLook#1239]
*For all's convenience, please use English to fill this issue.*

It would be convenient if when you clicked on the image preview window, you could scroll the photo with the left/right arrows. Let's say I've locked a window with an image, but how do I toggle it?

**Comment by rabelux** [comment]
No idea what you mean. Is this a feature request? Is this a question?

**Comment by bropines** [comment]
> No idea what you mean. Is this a feature request? Is this a question?

Feature request. It is very lacking to switch images using the arrows. Each time, instead of just tapping on the arrow in the QL window, you have to open the folder with files and switch the arrows UP/DOWN image. A little uncomfortable

**Comment by rabelux** [comment]
If you don't click in the preview window you can move the file selection with arrow keys.
