### ISSUE TITLE
与windows桌面整理插件有冲突

### ISSUE THREAD

**Issue by CZHALO** [QL-Win/QuickLook#1254]
在win10系统下使用wps桌面整理插件，结果在桌面下无法预览文件，只有从文件管理器查看桌面上的文件，才能预览。

**Comment by freezoc** [comment]
有同样的情况，目前是win11系统，使用的是腾讯桌面整理3.3.1475，quicklook版本为3.7.3

**Comment by freezoc** [comment]
有同样的情况
目前是win11系统，使用的是腾讯桌面整理3.3.1475，quicklook版本为3.7.3

**Comment by xupefei** [comment]
唯一确认和QL兼容的是[Stardock Fences](https://www.stardock.com/products/fences/)。
