### ISSUE TITLE
New versions are noticeably slower than old version

### ISSUE THREAD

**Issue by Darthagnon** [QL-Win/QuickLook#1257]
## Describe the bug
I did a quick test, comparing v3.6.10 (IE webview) with v3.7.1 (Edgium webview) and the older version was noticeably faster for previewing Markdown (*.md) and HTML files. I wasn't very scientific, but I'd estimate 0.5s to preview with the old version and at least 1s to preview with the new versions, accompanied by a noticeable stutter.

**Desktop (please complete the following information):**
 - OS Version: Win10 v1709
 - QuickLook Version: MSI, v3.6.10 and v3.7.1, both installed to SSD

**Comment by emako** [comment]
Will continue to upgrade webview version. Close.
