### ISSUE TITLE
Add AV1 Video playback support

### ISSUE THREAD

**Issue by technobulb** [QL-Win/QuickLook#1263]
Quick look does not work to display Videos compressed using the AV1 format.

Steps:
Press the spacebar over a Video encoded with the popular [AV1 video format](https://en.wikipedia.org/wiki/AV1)

Expected Behavior:
Video is played

Actual Behavior:
Quicklook displays a black box, and only the audio is played.

Windows 10
Quicklook version 3.7.3 (UWP)

![Screenshot 2023-02-05 231046](https://user-images.githubusercontent.com/84107091/216883428-57bbf9b5-f219-46e0-8e27-bf4659e19f98.png)

**Comment by neoOpus** [comment]
it works for me without problem, try installing the proper codecs (use K-lite Codec Pack)

**Comment by technobulb** [comment]
Now I am seeing its not specifically that file type, its just seemingly random videos that dont play, not sure what the similarities between them is. I tried this after downloading the codec pac. Here is another that wouldnt play:

Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : isom (isom/av01/iso2/mp41)
File size                   : 299 MiB
Duration                    : 16 min 59 s
Overall bit rate            : 2 463 kb/s
Writing application         : Lavf58.76.100

Video
ID                          : 2
Format                      : AV1
Format/Info                 : AOMedia Video 1
Format profile              : Main@L4.1
Codec ID                    : av01
Duration                    : 16 min 59 s
Bit rate                    : 2 325 kb/s
Width                       : 1 920 pixels
Height                      : 1 080 pixels
Display aspect ratio        : 16:9
Frame rate mode             : Constant
Frame rate                  : 60.000 FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Bits/(Pixel*Frame)          : 0.019
Stream size                 : 283 MiB (94%)
Title                       : ISO Media file produced by Google Inc.
Color range                 : Limited
Color primaries             : BT.709
Transfer characteristics    : BT.709
Matrix coefficients         : BT.709
Codec configuration box     : av1C

Audio
ID                          : 1
Format                      : AAC LC
Format/Info                 : Advanced Audio Codec Low Complexity
Codec ID                    : mp4a-40-2
Duration                    : 16 min 59 s
Source duration             : 16 min 59 s
Bit rate mode               : Constant
Bit rate                    : 129 kb/s
Channel(s)                  : 2 channels
Channel layout              : L R
Sampling rate               : 44.1 kHz
Frame rate                  : 43.066 FPS (1024 SPF)
Compression mode            : Lossy
Stream size                 : 15.6 MiB (5%)
Source stream size          : 15.6 MiB (5%)
Title                       : ISO Media file produced by Google Inc. Created on: 02/21/2023.
Default                     : Yes
Alternate group             : 1
mdhd_Duration               : 1019913

**Comment by neoOpus** [comment]
Do you have FFmpeg installed?

**Comment by Faeq-F** [comment]
I have the same issue; AV1 video playback does not work

I am using the Portable version of QuickLook

I am using the following video as a test file: http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Chimera-2397fps-AV1-10bit-960x540-1658kbps.mp4

When I try to play the video, an empty gray QuickLook window appears.
Neither audio or video is played / can be played (the play/pause button does not work)
When seeking, the Time Elapsed does change, but no frames are shown

**Comment by technobulb** [comment]
> Do you have FFmpeg installed? it could be anything from the splitter to video/audio codecs... make sure that you have everything properly installed (for your own benefit of course) try to set LAV codec merit to be priority and if possible upload the video file (anonymously) somewhere and send me the link, I will do the double check with you
> 
> PS: sorry for the late answer.

I tried installing FFmpeg and didnt help. I dont have a video file to upload now, but I can try later. I am not so sure what you mean by "have everything properly installed", and not sure if I want to start tinkering with registry values, for this...

**Comment by neoOpus** [comment]
[**@Faeq-F**](https://github.com/Faeq-F) commented on [May 7, 2023, 5:58 AM EDT](https://github.com/QL-Win/QuickLook/issues/1263#issuecomment-1537374737 "2023-05-07T09:58:31Z - Replied by Github Reply Comments"):
> I have the same issue; AV1 video playback does not work
> 
> I am using the Portable version of QuickLook (3.7.1) on Windows 11
> 
> I am using the following video as a test file: http://download.opencontent.netflix.com.s3.amazonaws.com/AV1/Chimera/Chimera-2397fps-AV1-10bit-960x540-1658kbps.mp4
> 
> When I try to play the video, an empty gray QuickLook window appears.
> Neither audio or video is played / can be played (the play/pause button does not work)
> When seeking, the Time Elapsed does change, but no frames are shown
> 
> I have the K-lite Codec Pack installed on the computer and am unsure on what to do with the FFmpeg binaries - they are currently in the root of the QuickLook folder
> 
> _Originally posted by @Faeq-F in https://github.com/QL-Win/QuickLook/issues/1263#issuecomment-1537374737_

Your video indeed do not play in QL, I am trying to investigate the issue.

**Comment by ramanmono** [comment]
Same issue here. No AV1 video encoded with ffmpeg av1_amf (AMD hardware encoder) in both mp4 and webm containers. I use the version installed from the windows store. I have k-lite codec pack installed.

**Comment by emako** [comment]
Does the current night build meet the format you need?

https://github.com/QL-Win/QuickLook/releases

**Comment by emako** [comment]
OK
