### ISSUE TITLE
Quick look stooped working...

### ISSUE THREAD

**Issue by DR-killer1109** [QL-Win/QuickLook#1266]
Whenever I press the spacebar a transparent vertical bar. It used to work just fine, but suddenly one day it stopped showing me any preview. 

I have a HP specter 13'' (2017) 

- OS Version: Edition Windows 11 Home
 - Version:	Dev
 - OS build :	21996.1
 - Experience :	Windows Feature Experience Pack 321.14700.0.3

 - QuickLook Version:
From Windows Store Publisher Paddy Xu
Version  3.7.3.0

The problem look something like this:

**for all kinds of files**

<img width="839" alt="Screenshot 2023-02-07 162550" src="https://user-images.githubusercontent.com/124677485/217226036-2a4a7352-f325-4038-9e11-c7c41fc6e97a.png">

**Comment by Camilo-Casdix** [comment]
I have the same issue .... also W11... if I double click the upper part of that bar image open up in full screen 
![Screenshot_5](https://user-images.githubusercontent.com/127968014/225348938-7e4c4b08-66ae-4666-8b49-b1e7fa75995e.png)
![Screenshot_6](https://user-images.githubusercontent.com/127968014/225349012-70654b37-1abe-436e-8298-b6ab9188add7.png)

**Comment by xupefei** [comment]
It looks like a Windows bug. Is the vertical bar still there when you kill the QuickLook process?

**Comment by xupefei** [comment]
Oh, I found something in the 3rd picture: the transparent title bar. This is a GPU render issue and definitely a Windows bug.

**Comment by Camilo-Casdix** [comment]
Yeah it's definitely a windows bug, W11 bug, I recently have to install "Avira free antivirus" i dont know what kind of open GL o graphic engine works with it, but have the same minimize problem.
![image](https://user-images.githubusercontent.com/127968014/226188366-908a901d-4c51-4fa5-838f-ff1e8cc33f0f.png)

**Comment by Camilo-Casdix** [comment]
I just double click the top corner and the window maximized, but this kill at least for the QuickLook, his functionality.

**Comment by DR-killer1109** [comment]
Is there any way to fix this issue?

**Comment by xupefei** [comment]
Switch to a stable version of Windows 11?
