### ISSUE TITLE
Button to reselect pinned item in file explorer

### ISSUE THREAD

**Issue by DraakjeYoblama** [QL-Win/QuickLook#1270]
**Is your feature request related to a problem? Please describe.**
When I pin a file and then close that file browser window, I lose the position of that file and I have to look for it again.

**Describe the solution you'd like**
A button on the quicklook window that brings me back to the location of that file and selects it in the file browser. Either it would bring you back to the original window/tab where you selected that file, or it could open a new one, or it could just open in the screen you have currently selected. I'm not sure which would be the best solution and if they are even all possible.

I would make it a seperate button, but maybe it could bring you back when you "unpin" a file (so clicking the pin button when it's already active, which doesn't do anything for me at the moment)

**Describe alternatives you've considered**
I saw someone else say they would like a file-hover quicklook, so that you don't have to unselect your file. But that's quite different thing from what quicklook does and it would still only allow one file to be selected.

**Comment by emako** [comment]
#1368

**Comment by DraakjeYoblama** [comment]
I don't really think that's the same thing, but ok

**Comment by emako** [comment]
OK

At present, we are not considering overly complex functions
and hope that QL remains intuitive, simple and easy to use.
