### ISSUE TITLE
"Quicklook is already running" daily popup is annoying

### ISSUE THREAD

**Issue by fredphoesh** [QL-Win/QuickLook#1281]
Hi,
I'm loving Quicklook but the daily popup to say "Quicklook is already running" is annoying and unnecessary.  Please disable it.
Thanks,
Mark.
![quicklook popup daily](https://user-images.githubusercontent.com/5565996/227156651-2bf9c0b6-228b-442c-b600-e1365525054a.png)

**Comment by fredphoesh** [comment]
I have discovered that there are TWO Quicklooks running on my system... I have NO IDEA what this other Quicklook is... do you know? Searching on my Start button menu, there are to Quicklooks, but I cannot tell which is which...

**Comment by rabelux** [comment]
Maybe you installed the store And the msi version?

**Comment by fredphoesh** [comment]
Thanks, I have uninstalled one of them and rebooted... message gone!
I will edit the first post to say SORTED... tx
