### ISSUE TITLE
FR translation not complete applied

### ISSUE THREAD

**Issue by Riki7745** [QL-Win/QuickLook#1282]
**Describe the bug**
Some words aren't translated in the preview window, in fact only Execute is translated.

**To Reproduce**
Go to preview window

**Expected behavior**
Just apply translation completely

**Desktop (please complete the following information):**
 - OS Version: Windows 10 22H2
 - QuickLook Version: 3.7.3

Thanx.

**Comment by rabelux** [comment]
This is adressed by #1116
