### ISSUE TITLE
Epub Viewer Plugin no longer works?

### ISSUE THREAD

**Issue by radarblack** [QL-Win/QuickLook#1286]
Everytime I try to do a quick look for a ".epub" file, a notification always appear that mentions that the QuickLook app failed to preview the file. Went through the proper method of installing plugins (install -> restart). Issue still happens after restarting the PC itself.

![image](https://user-images.githubusercontent.com/120578800/229304203-6461bc8b-525b-46a1-b3db-0e45d5adbfb0.png)

**Comment by rabelux** [comment]
You are not the first one to have this issue. See here: https://github.com/QL-Win/QuickLook.Plugin.EpubViewer/issues.
Also this is the wrong repo to report that issue.
