### ISSUE TITLE
Hope to be able to preview by space in the OPEN menu.

### ISSUE THREAD

**Issue by wanvfx** [QL-Win/QuickLook#1299]
Example: When importing video material in editing software, when the import panel is opened, it is hoped that you can press the space to preview directly

**Comment by rabelux** [comment]
https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions

**Comment by wanvfx** [comment]
> https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions

marvelous! This is exactly what I need, it turns out that the Microsoft store is not the latest version
