### ISSUE TITLE
View png info

### ISSUE THREAD

**Issue by zpengcom** [QL-Win/QuickLook#1301]
I would like to add the ability to view png info and support viewing information about images generated by stable diffusion

For example:
![image](https://user-images.githubusercontent.com/8217132/234833911-b5570c88-0624-4f2c-926f-78b9f8f6059f.png)

**Comment by emako** [comment]
There is no supported plan, if needed you can refer to https://github.com/QL-Win/QuickLook/tree/master/QuickLook.Plugin/QuickLook.Plugin.ImageViewer to develop custom plugins

**Comment by mooflu** [comment]
FYI, my [webviewplus](https://github.com/mooflu/QuickLook.Plugin.WebViewPlus) plugin shows image meta data via https://github.com/mattiasw/ExifReader
