### ISSUE TITLE
关于字体渲染显示问题

### ISSUE THREAD

**Issue by liulifeili** [QL-Win/QuickLook#1303]
部分电脑自行安装的字体在空格预览后显示乱码甚至是不显示。

以下是出现过问题的字体：思源宋体（Family）、思源黑体（Family）、旁门正道标题（Family）、霞鹭字体（Family）……

**Comment by emako** [comment]
针对简体中文，QL的文本预览插件配置了依次使用Consolas,Microsoft Yahei UI,Microsoft Yahei,SimSun

如果字体都不存在，可能会找不到能处理的字体。

如还有问题请继续回复。。
