### ISSUE TITLE
Support OCR and text selection in image viewer

### ISSUE THREAD

**Issue by chen3feng** [QL-Win/QuickLook#1304]
This feature is just like in Mac system.
User can select and copy text from an image via OCR.

**Comment by rabelux** [comment]
I think this is a bit too much to ask for as the dev doesn't have much time at the moment. I suggest you use something like powertoys.

**Comment by Likang1988** [comment]
Try this one: [https://github.com/Likang1988/QuickLook.Plugin.ImageViewer-with-LiveText](https://github.com/QL-Win/QuickLook/issues/url), I made it with AI programming tool.
