### ISSUE TITLE
QuickLook Randomly Stops Responding to Initiation Calls in Multi-Tab File Explorer Window 

### ISSUE THREAD

**Issue by raaomoka** [QL-Win/QuickLook#1306]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*
No.

**Describe the bug**
On initial launch of a File Explorer window with 1 tab, QuickLook functions as one would expect, no issues. However, as I keep using my computer with the same File Explorer window, adding and navigating directories on separate tabs in the same window, QuickLook randomly at some point, stops responding to me pressing my Space bar in that File Explorer window.

* If I open a new File Explorer window, it resumes responding again, but that totally hampers my productivity, having to renavigate to the multiple directories I want in tabs.
* If I open a new tab within the existing File Explorer window, it also resumes responding again, but again, that hampers my productivity as I loose my navigation history.
* Exiting and relaunching QuickLook (even as an administrator) does NOTHING.

**To Reproduce**
1. Open a File Explorer window and utilize it as normal
2. Add multiple new tabs to the File Explorer window and utilize them as normal
3. At some random point, you'll notice QuickLook no longer responds to you pressing your Space bar in that File Explorer window. Only way to get it working again is to open another File Explorer window.

**Expected behavior**
QuickLook keeps functioning as normal when called, without any delay, regardless of how long I've had a File Explorer window/tab open for.

**Desktop (please complete the following information):**
 - OS Version: Windows 11 22H2 (OS Build 22621.1413)
 - QuickLook Version: 3.7.3 from Microsoft Store

**Screenshots and Exception Log**
N/A, Log Contains No Exceptions for the Past 10 Days, and Issue has been Persisting.

**Comment by emako** [comment]
I can't reproduce it in Windows 11 Pro 24H2 (26100.2605 [Windows Feature Experience Pack 1000.26100.36.0]).

![image](https://github.com/user-attachments/assets/d9c8d3b3-ffe9-479b-9008-7e8cd47b3ddd)

If you have any questions, please continue to reply.
