### ISSUE TITLE
PDF cannot be previewed

### ISSUE THREAD

**Issue by NaSA675** [QL-Win/QuickLook#1308]
Simply PDF upon hiting spacebar is not previewing

Using the following device and OS Build:

Processor	12th Gen Intel(R) Core(TM) i7-1265U   1.80 GHz
Installed RAM	16.0 GB (15.7 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎28.‎09.‎2022
OS build	19044.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by rabelux** [comment]
Maybe related to #798? If not pls provide more information, like logs, screenshots, video.

**Comment by Bobesmj** [comment]
> Maybe related to #798? If not pls provide more information, like logs, screenshots, video.
I have the same issue with pdf, webp, webm and HTML, etc.
![image](https://github.com/QL-Win/QuickLook/assets/78360650/c6f012c6-03f6-4329-9c7b-8e99e09d6db7)
