### ISSUE TITLE
Weird artifacts on text and low quality cover art (previewing songs)

### ISSUE THREAD

**Issue by X3ONMUSIC** [QL-Win/QuickLook#1311]
**Describe the bug**
Text and images on songs previews look blurry, some letters have artifacts

**To Reproduce**
1. Press "Space" to QuickLook a song (mp3, flac, etc)
2. See error

**Expected behavior**
High quality on song cover art (if source allows), and high quality text (song title, album title, etc)

**Desktop (please complete the following information):**
 - OS Version: Windows 11 Pro (22H2) [22621.1702]
 - QuickLook Version: 3.7.3

**Screenshots and Exception Log**

![image](https://github.com/QL-Win/QuickLook/assets/112701219/71ab5d62-43c8-4117-9d84-783c33b74124)

**Comment by rabelux** [comment]
If you expect high quality then pls use a programm that's intended for listening to music. QuickLook's goal is to provide previews of a broad range of files and that maybe at 90% and not 100% quality.
