### ISSUE TITLE
Add a settings option to change the hotkeys.

### ISSUE THREAD

**Issue by Chummpp** [QL-Win/QuickLook#1313]
**Is your feature request related to a problem? Please describe.**
Add a settings option to change the hotkeys. For example lets say I want to replace the space bar with the left mouse click.

**Describe the solution you'd like**
Opening a settings menu allowing the user to change the hotkeys.

**Describe alternatives you've considered**
Add the option to change hotkeys using QuickLook.exe.config.

**Additional context**
No additional context.

**Comment by joshuagilbreath** [comment]
Was this feature added? I would also like to change QuickLook hot key?
