### ISSUE TITLE
wix miss /QuickLook.Installer/C_QuickLookComponents.wxs file

### ISSUE THREAD

**Issue by xingwozhonghua** [QL-Win/QuickLook#1316]
wix编译缺少/QuickLook.Installer/C_QuickLookComponents.wxs文件

**Comment by xingwozhonghua** [comment]
/QuickLook.Installer/C_QuickLookComponents.wxs

**Comment by xingwozhonghua** [comment]
https://github.com/QL-Win/QuickLook/blob/f1cbdd00f8b1c3facc5c2c5bac980922cb104df0/.gitignore#L290

**Comment by df-client-dev2** [comment]
https://raw.githubusercontent.com/QL-Win/QuickLook/db2450a0cb63615157f913ff976175bff950ce33/QuickLook.Installer/C_QuickLookComponents.wxs

**Comment by df-client-dev2** [comment]
http://t.csdn.cn/2gdyk
