### ISSUE TITLE
[Feature request] Buttons for changing the selected file.

### ISSUE THREAD

**Issue by bropines** [QL-Win/QuickLook#1318]
I already kind of made an offer, but then my arguments were miserable.

What is the point. QL has a function to pin a window to the top. The function is very convenient, but when we fix, for example, an audio or video file, we presumably want to include the next one, and for this we have to go back to the folder, change the track, and so on.

I understand that the application, first of all, is a quick preview, but it would be convenient to change the selected file not only by "clicking on the file" + "space", but also by using native buttons in the interface.

For example, as in this screenshot, we hang a window on top in the browser and .... That's all)
![image](https://github.com/QL-Win/QuickLook/assets/57861007/e4548cdd-5a06-403f-bc90-e0a9be647b0e)

**Comment by emako** [comment]
#1082
