### ISSUE TITLE
program crash after install powertoys 0.70.1 with peek funtion

### ISSUE THREAD

**Issue by djfix13** [QL-Win/QuickLook#1319]
on first reboot after installing powertoys 0.70.1 with integrated peek function, quicklook doesn't start and crashes continuously.
even if i remove everything and reinstall quicklook it doesn't restart.
reported under the event log
![Screenshot 2023-06-03 203304](https://github.com/QL-Win/QuickLook/assets/94961589/3e1268ab-9e27-49b2-a29d-9f0a5a3670b6)

Nome registro: Application
Origine:       .NET Runtime
Data:          03/06/2023 20:23:33
ID evento:     1026
Categoria attività:Nessuna
Livello:       Errore
Parole chiave: Classico
Utente:        N/D
Computer:      NitroFIX
Descrizione:
Applicazione: QuickLook.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: System.NotSupportedException

Informazioni sull'eccezione: System.IO.FileLoadException
   in System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   in System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   in System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   in System.Reflection.Assembly.LoadFrom(System.String)
   in QuickLook.PluginManager.<LoadPlugins>b__11_0(System.String)
   in System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1<System.__Canon>)
   in QuickLook.PluginManager.LoadPlugins(System.String)
   in QuickLook.PluginManager..ctor()
   in QuickLook.PluginManager.GetInstance()
   in QuickLook.App.RunListener(System.Windows.StartupEventArgs)
   in QuickLook.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   in System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   in System.Windows.Application.<.ctor>b__1_0(System.Object)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   in System.Windows.Threading.DispatcherOperation.InvokeImpl()
   in MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   in MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   in System.Windows.Threading.DispatcherOperation.Invoke()
   in System.Windows.Threading.Dispatcher.ProcessQueue()
   in System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   in MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   in System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   in System.Windows.Application.RunDispatcher(System.Object)
   in System.Windows.Application.RunInternal(System.Windows.Window)
   in QuickLook.App.Main()

XML evento:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name=".NET Runtime" />
    <EventID Qualifiers="0">1026</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>0</Task>
    <Opcode>0</Opcode>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2023-06-03T18:23:33.2339540Z" />
    <EventRecordID>66893</EventRecordID>
    <Correlation />
    <Execution ProcessID="10848" ThreadID="0" />
    <Channel>Application</Channel>
    <Computer>NitroFIX</Computer>
    <Security />
  </System>
  <EventData>
    <Data>Applicazione: QuickLook.exe
Versione framework: v4.0.30319
Descrizione: il processo è stato terminato a causa di un'eccezione non gestita.
Informazioni sull'eccezione: System.NotSupportedException

Informazioni sull'eccezione: System.IO.FileLoadException
   in System.Reflection.RuntimeAssembly._nLoad(System.Reflection.AssemblyName, System.String, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   in System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(System.Reflection.AssemblyName, System.Security.Policy.Evidence, System.Reflection.RuntimeAssembly, System.Threading.StackCrawlMark ByRef, IntPtr, Boolean, Boolean, Boolean)
   in System.Reflection.RuntimeAssembly.InternalLoadFrom(System.String, System.Security.Policy.Evidence, Byte[], System.Configuration.Assemblies.AssemblyHashAlgorithm, Boolean, Boolean, System.Threading.StackCrawlMark ByRef)
   in System.Reflection.Assembly.LoadFrom(System.String)
   in QuickLook.PluginManager.&lt;LoadPlugins&gt;b__11_0(System.String)
   in System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].ForEach(System.Action`1&lt;System.__Canon&gt;)
   in QuickLook.PluginManager.LoadPlugins(System.String)
   in QuickLook.PluginManager..ctor()
   in QuickLook.PluginManager.GetInstance()
   in QuickLook.App.RunListener(System.Windows.StartupEventArgs)
   in QuickLook.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   in System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   in System.Windows.Application.&lt;.ctor&gt;b__1_0(System.Object)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   in System.Windows.Threading.DispatcherOperation.InvokeImpl()
   in MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   in MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   in System.Windows.Threading.DispatcherOperation.Invoke()
   in System.Windows.Threading.Dispatcher.ProcessQueue()
   in System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   in MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   in MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   in System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   in System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   in System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   in MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   in MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   in System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   in System.Windows.Application.RunDispatcher(System.Object)
   in System.Windows.Application.RunInternal(System.Windows.Window)
   in QuickLook.App.Main()

</Data>
  </EventData>
</Event>

**Comment by djfix13** [comment]
don't understand why the Administrator account execute Quicklook without errors. maybe some permission is missing

**Comment by djfix13** [comment]
today i reviewed everything and removed the version downloaded on microsoft store. i ran the program from the ZIP version. no problem everything works.
so I guess it's a problem of the x MSstore container

**Comment by emako** [comment]
OK, Mark as MS Store problem
