### ISSUE TITLE
Switchable preview for some, e.g., HTML and SVG, files

### ISSUE THREAD

**Issue by rexdf** [QL-Win/QuickLook#132]
1. [ ] 右键支持
对于HTML格式，现在屏蔽了超链接的点击操作挺好的。希望可以在html显示界面支持选中右键复制，对于超链接希望有一个可以显示属性的右键。对于图片能复制图片内容那就更加美好了。就像系统的chm阅读器那样。
2. [ ] Toggle源码
HTML之类，假如能够Toggle源码，那最好了，其实我是在md预览的时候想复制链接。
3. [ ] 二进制也许可以Toggle成16进制。
这只是随口说的，也许效率会有问题，也许实现之后就会想能定位offset。
4. [x] 多窗口
可以同时打开多个窗口。其实是发觉当做播放器不错。然而一旦选中其他文件就停止了。要是有个按钮，能把窗口钉住，不会被重复利用，那样感觉很不错。

**Comment by xupefei** [comment]
4. 
![image](https://user-images.githubusercontent.com/1687847/32992852-92d32632-cd58-11e7-8823-ad45d155b3ec.png)

**Comment by jleaves** [comment]
Any update on this? Need an option to toggle behavior when previewing HTML / Markdown / SVG files. Thanks!
