### ISSUE TITLE
latest msi installer fails under windows 10

### ISSUE THREAD

**Issue by ClaireCJS** [QL-Win/QuickLook#1321]
**Describe the bug**
Installer fails

**To Reproduce**
1. Install the msi file
2. choose any folder to install
3. click ok

**Expected behavior**
successful installation

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 [Version 10.0.19045.2965]
 - QuickLook Version: QuickLook-3.7.3.msi

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).
![image](https://github.com/QL-Win/QuickLook/assets/789591/ba913586-ce3e-4ce0-87ec-5cc9b7402cfe)

**Comment by ClaireCJS** [comment]
[Trust me. I'm definitely choosing a local folder. I tried existing and new folders on both my harddrives, i tried browsing to them via file explorer instead of typing them in, it's a shame the installer works but is simply unwilling to let me install it.]

**Comment by ClaireCJS** [comment]
oh, it never got as far as creating any folders.

The zip version worked, though!  It's a great utility!!

**Comment by rabelux** [comment]
Closing this as the issue can't be reproduced

**Comment by ClaireCJS** [comment]
Try isntalling it with a different default command line than CMD.EXE

**Comment by rabelux** [comment]
Why would I do that?
