### ISSUE TITLE
When trying to preview an empty BMP

### ISSUE THREAD

**Issue by xingwozhonghua126** [QL-Win/QuickLook#1322]
Describe the bug
When trying to preview an empty BMP file by right-clicking on the desktop and selecting “Quick Look,” QuickLook displays a blank white window instead of showing a preview.

To Reproduce

Create an empty BMP file on the desktop or in any folder.
Right-click on the file and select “Quick Look.”
A blank white window is displayed instead of showing a preview of the image.
Expected behavior
No pop-up of notification in the lower right corner

Desktop (please complete the following information):

OS Version: Windows 10 1803
QuickLook Version: 3.7.3.13 from Windows Store
Screenshots and Exception Log
I do not have a screenshot or exception log for this issue.

![image](https://github.com/QL-Win/QuickLook/assets/18661883/c589cc3f-afbe-47d9-8ba8-69d76da6b4f7)

**Comment by rabelux** [comment]
Error message is valid as extension doesn't match the file type.
