### ISSUE TITLE
Animated WEBP files

### ISSUE THREAD

**Issue by NaitorStudios** [QL-Win/QuickLook#1324]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
Animated WEBP files will just preview as a static image.

**Describe the solution you'd like**
Please update the image plugin to work with animated WEBP files.

**Describe alternatives you've considered**
Making a plugin or software myself, but I'm not familiar with C#.

**Additional context**
Nothing else.

**Comment by rabelux** [comment]
Duplicate of #1024

**Comment by emako** [comment]
Done, BUT Limitations: Only supports x64 systems.

Check it out in nightly build.
https://github.com/QL-Win/QuickLook/releases
