### ISSUE TITLE
Trying to get QL to work with the new Alpha of Voidtools Everything

### ISSUE THREAD

**Issue by JimMcBubbles** [QL-Win/QuickLook#1330]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
I just updated VoidTools Everything to Version 1.5.O.1352a (x64) from Version 1.4.1.1024 (x64). Version 1.4.1.1024 (x64) works with QuickLook the same way as Windows Explorer, but the spacebar shortcut does nothing in the new version. posting this question here and trying to find support resources w VoidTools.

**To Reproduce**
install and run https://www.voidtools.com/Everything-1.4.1.1024.x64-Setup.exe
install and run https://www.voidtools.com/Everything-1.5.0.1352a.x64-Setup.exe

test quicklook spacebar shortcut

**Expected behavior**

quicklook preview displays for both versions.

**Desktop (please complete the following information):**
 - OS Version: Microsoft Windows 10 Pro Version	10.0.19045 Build 19045
 - QuickLook Version: 3.7.3 from Windows Store

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by rabelux** [comment]
Pls consult Everything, there is nothing QuickLook can do

**Comment by czqmike** [comment]
Just downgrade Everything to 1.4, Everything V1.4.1.1022 (x86) works well with QuickLook 3.7.3 :)
