### ISSUE TITLE
compile failed on win11 22621 with visual studio 2022

### ISSUE THREAD

**Issue by albertofwb** [QL-Win/QuickLook#1332]
after clone the repo and sync the submodule.

environment: 
win11 22621
visual studio 2022 community
.net framework 4.6.2 installed
win11 22621 sdk installed
already installed the uwp development kit

when building the QuickLook project get the below error:
1>D:\github\QuickLook\QuickLook\Helpers\ShareHelper.cs(26,15,26,31): error CS0234: 命名空间“Windows”中不存在类型或命名空间名“ApplicationModel”(是否缺少程序集引用?)
1>D:\github\QuickLook\QuickLook\Helpers\ShareHelper.cs(27,15,27,22): error CS0234: 命名空间“Windows”中不存在类型或命名空间名“Storage”(是否缺少程序集引用?)
1>D:\github\QuickLook\QuickLook\Helpers\ShareHelper.cs(80,56,80,75): error CS0246: 未能找到类型或命名空间名“DataTransferManager”(是否缺少 using 指令或程序集引用?)
1>D:\github\QuickLook\QuickLook\Helpers\ShareHelper.cs(80,84,80,106): error CS0246: 未能找到类型或命名空间名“DataRequestedEventArgs”(是否缺少 using 指令或程序集引用?)
1>D:\github\QuickLook\QuickLook\Helpers\ShareHelper.cs(112,23,112,42): error CS0246: 未能找到类型或命名空间名“DataTransferManager”(是否缺少 using 指令或程序集引用?)
1>D:\github\QuickLook\QuickLook\Helpers\ShareHelper.cs(127,13,127,32): error CS0246: 未能找到类型或命名空间名“DataTransferManager”(是否缺少 using 指令或程序集引用?)
========== 生成: 0 成功，1 失败，4 最新，0 已跳过 ==========
========= 生成 开始于 3:48 AM，并花费了 00.679 秒 ==========

**Comment by iamqiz** [comment]
我遇到相同的问题,解决方法是下载windows sdk 10.0.20348 (位于: visual studio installer > 使用c++的桌面开发 )
下载后的windows 模块属性如下:
![Clip_2024-02-04_15-01-39](https://github.com/QL-Win/QuickLook/assets/48077521/442e2bbd-1d84-47a9-8ff4-a6e7e6e8d157)

**Comment by emako** [comment]
过时的问题
