### ISSUE TITLE
QuickLook version 3.7.3 - Conflicts with other software taking over system Explorer, causing it to be unavailable

### ISSUE THREAD

**Issue by hadesen12** [QL-Win/QuickLook#1336]
Describe the error overview:
I used WPS 'Desktop Assistant and 360 Folder Software, which take over the local Explorer, so they clashed with QuickLook, causing it to be unresponsive when previewing files on the desktop using QuickLook, and unresponsive when using 360 Folder Software.
When you directly open the "This computer" the system's own resource manager, "QuickLook" can preview files normally.
Steps to reproduce the error result:
1. Go to WPS, search for "Desktop Assistant" and use it
2. Download the "360 Folder" software and use it to take over system file management
3. Download the latest version of the author's "QuickLook" V3.7.3 and use it
4. Select the desktop suffix ".png "file and click the space (can not preview, QuickLook does not respond)
5. Select any file under "This Computer" and click the space (no preview, QuickLook does not respond)
The following is the version information used:
• 360 folder version: 1.0.0.1090
• WPS Desktop Assistant version: V12.1.0.15128
• Laptop system version: Windows 11 Home Chinese version [OS version 22000.2245]
• QuickLook version: V3.7.3 on github

These are the problems I encountered, thank the author greatly

**Comment by Soromeister** [comment]
This also happens sometimes when using Directory Opus as Explorer replacement.
