### ISSUE TITLE
Viewing markdown files (.md, .markdown) doesn't display properly

### ISSUE THREAD

**Issue by Shnxxx** [QL-Win/QuickLook#1349]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*
Not yet. I saw one that also facing issue previewing markdown files using a portable version, but he gets an error. Mine's not displaying properly.

**Describe the bug**
Previewing markdown files not displaying properly. I can still see the markdown tags. 

**To Reproduce**
1. Have any markdown file, in my case it is "Favorites Inquire EAPI Specs v0.5.mdown"
2. Click on it.
3. Press "space bar"
4. No error but displaying incorrectly.

**Expected behavior**
A properly formatted markdown file.

**Desktop (please complete the following information):**
 - OS Version: Windows 11 22H2 (22621.2283)
 - QuickLook Version: 3.7.3 (UWP)

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).
![image](https://github.com/QL-Win/QuickLook/assets/48496678/40c77be9-5d31-497a-9312-8d00f4b5aa49)

No exception log since there is no error:
![image](https://github.com/QL-Win/QuickLook/assets/48496678/ed6cae83-c509-43e1-9323-69380d874950)

**Comment by 1111Al** [comment]
Quicklook has never been good for text previews, it is horrible and unusable. I deleted QL from my PC for this very reason.

**Comment by emako** [comment]
`.mdown` was added to markdown file extension list now.
