### ISSUE TITLE
在Windows11中，无法在打开/保存文件对话框中预览 Unable to preview in open/save file dialog in Windows 11

### ISSUE THREAD

**Issue by Firedoge1** [QL-Win/QuickLook#1351]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by rabelux** [comment]
A title doesn't make an issue and I'm pretty sure your issue is explained here:
https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions

**Comment by Firedoge1** [comment]
我是用的安装版

**Comment by Firedoge1** [comment]
I am using the installation version

**Comment by Firedoge1** [comment]
解决了，Listary的锅

**Comment by Firedoge1** [comment]
Solved, Listary’s fault
