### ISSUE TITLE
When I hit the spacebar, a COOKIES Window pops up, see attached screenshot, help

### ISSUE THREAD

**Issue by allenbisconti** [QL-Win/QuickLook#1354]
**When I click the space bar, a cookies folder window pops up?  Then if I try it more than once it crashes.  I have Windows 10.  It was working fine up until about 2 months ago.  :-(   I've uninstalled and reinstalled it, cleared out temporary files, etc.. nothing works.  I've attached a screenshot of what I see.  Help...  Miss having Quicklook.  PS:  I have Windows 10 Pro version 22H2, OS Build 19045.3570** 
![Screenshot 2023-10-27 133934](https://github.com/QL-Win/QuickLook/assets/149194807/80c30fb1-ad79-4a72-bb3d-bbfef67aafb4)

**Comment by rabelux** [comment]
So what you're saying is: it doesn't matter which file you select, you always get a preview of the cookies folder? Could you upload your crash report? How to do that is explained in the issue template.

**Comment by allenbisconti** [comment]
@rabelux  **Yep, no matter what file I hit the spacebar on, it's always the same preview of the cookies folder..  I downloaded Seer temporarily but they want $13 to buy it.  Hoping I can get this fixed since it's free.   :-(    As far as a crash report, there is no crash report, it just closes down.**

**Comment by rabelux** [comment]
Please have a look to see whether there's an error log. Location can be found here: https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location
Also my best guess is that you've installed some software that interferes with QuickLook. I've never heard of a problem like yours for the past years.

**Comment by allenbisconti** [comment]
@rabelux   **It's weird, about 2 months ago after a Windows update, my Windows 10 Photo program changed and Quicklook stopped working.  Have no idea what could have caused it?  I've uninstalled and reinstalled it a few times but it keeps popping up that cookies window?  There are no error logs.  **

**Comment by rabelux** [comment]
Are you using .msi or store version? If you're using store version pls try .msi

**Comment by allenbisconti** [comment]
@rabelux  I just tried the msi version, same thing happens.  :-(

**Comment by rabelux** [comment]
Okay a quick recap:
- you're using default windows explorer
- you haven't installed any overlays like rainmeter
- you've uninstalled the store version
- after trying to preview for a second time (third use of spacebar) QuickLook icon disappears from the bottom right (crashes) but there's no error log

Are these assumptions true?
What happenes if you're trying to use QuickLook in a open- or save-dialog?

**Comment by allenbisconti** [comment]
@rabelux  I don't know what you mean about using Quicklook in an open or save dialoag?   No matter what version I install, when I click the spacebar, it pops up that cookies window.  :(  I've tried the store version and the msi version.

**Comment by rabelux** [comment]
Open any program (use paint or your browser for example) then try to open a file (file - > open. A dialog pops up asking you to select a file. Try using QuickLook within this dialog.

**Comment by allenbisconti** [comment]
@rabelux  **I tried, there was no option to use Quicklook to open anything..  Wasn't available in the app list or on the computer when I searched.  I tried to open an image, a notepad doc, video, audio, nothing had the option to use Quicklook to open them.**

**Comment by rabelux** [comment]
What do you mean with "there was no option"?? You only had to press space on a supported & selected file

**Comment by allenbisconti** [comment]
@rabelux  When I press the space bar on a file the cookies folder image pops up remember?  When I right click on the file there's no option to open it with Quicklook like you mentioned above..  Nothing works.

**Comment by rabelux** [comment]
You were supposed to preview a file from within a open-dialog by pressing space. Stop trying to rightclick files. Pls reread my instructions and tell me whether you see the same behaviour if you hit space on a file in a open-dialog.

**Comment by allenbisconti** [comment]
@rabelux  How am I supposed to preview a file in a open dialog by pressing the space bar when every time I press the space bar the cookies folder image pops up?  I have tried everything you said above.

**Comment by rabelux** [comment]
It's a bit exhausting writing with you and I'm running out of patience. If you want better support buy seer. Closing this as this is the first time I hear about an issue like that and you weren't able to answer my questions and follow instructions. So probably a user's and not a software fault.

**Comment by allenbisconti** [comment]
**@rabelux I did EVERYTHING you said to do and you closed everything down saying I wasn't doing what you were suggesting. The reason I didn't get back to you right away after the last thing you had told me to do was because I GOT SICK for almost 2 weeks with the flu, then my wife needed to have surgery. So I reopened my question because I'm still having the same problem and don't want to have to pay $13 for Seer when I can just get Quicklook working again (somehow).**

**Comment by allenbisconti** [comment]
@rabelux  Can you please just delete this entire thread and the other two I opened related to it.  Would appreciate it.
