### ISSUE TITLE
unable to preview the office document

### ISSUE THREAD

**Issue by xiedonghua** [QL-Win/QuickLook#1358]
I install the officeViewer-Native,but can't preview the Office document.

in my laptop in only install the WPS

 - OS Version: Windows 11 123h2 22631
 - QuickLook Version:  3.7.3 from github release
 - WPS: 2023 15712

maybe the plugin update?

**Comment by rabelux** [comment]
Please follow the issue template, also a screenshot would have been nice.
Nevertheless:
When downloading the plugin you should have noticed following footnote:

> *1: Native installation only. Office 365 installed from Windows Store is not supported by this plugin. This plugin is not stable, meaning it may or may not work for you. We recommend using another Office plugin.

Therefore this ticket will be closed.
