### ISSUE TITLE
Wont staart from starup

### ISSUE THREAD

**Issue by schroef** [QL-Win/QuickLook#1363]
**Describe the bug**
ive noticed under Windows rs 250997, the app no longer shows in the tray menu. Ive seen more apps disappear. For instance Nvidia icon also disappeared.

**To Reproduce**
1. Restart/start Windows running rs 25997
2. Click on tray icon
3. Notice missing QuickLook icon

**Expected behavior**
QuickLook should start automatically from startup and should show in the Startup Apps

**Desktop (please complete the following information):**
 - Windows 11 rs 25997
 - QuickLook v3.7.3

**Comment by rw3iss** [comment]
Note that this doesn't work even if adding it or enabling it to "Startup Apps". It shows enabled, but then closing and re-opening startup apps has it Disabled again. How can we force it to stay Enabled?

**Comment by dulljo** [comment]
I have the same issue, I've enabled the auto lauch with Windows setting, and Quicklook does exist in the startup folder, but it failed everytime I turn on the computer.

**Comment by emako** [comment]
You can confirm whether it is disabled from Task Manager

![image](https://github.com/user-attachments/assets/4f7af450-0ae8-47c2-99f1-975b950d4e59)
