### ISSUE TITLE
how to configure disabling video preview

### ISSUE THREAD

**Issue by DuangXT** [QL-Win/QuickLook#1365]
I only need picture preview, usually I don't preview videos, but instead use the player directly.
sometime I accidentally pressed space on the video file, and quickly switched to other windows, but video is still playing.
and I see another issue #1352 , if this issue can be resolved, please ignore my issue

**Comment by xupefei** [comment]
You could install the MSI/ZIP version and delete the VideoViewer in the plugin folder.

**Comment by emako** [comment]
> You could install the MSI/ZIP version and delete `VideoViewer` in the plugin folder.

That is the solution
