### ISSUE TITLE
No Sound in audio mixer when playing a video or music

### ISSUE THREAD

**Issue by aunight** [QL-Win/QuickLook#1366]
When playing a video it had no sound and no quicklook in audio mixer
![image](https://github.com/QL-Win/QuickLook/assets/52199445/a2dbf8db-9ce4-4f74-830d-fa2f59e7e0df)
Play audio file had this issue
![image](https://github.com/QL-Win/QuickLook/assets/52199445/f584ef06-6c96-4698-92a9-a4534291fbca)

**Desktop:**
 - OS Version: Windows 10 22H2
 - QuickLook Version:  3.7.3 from Windows Store

**Comment by emako** [comment]
Audio mixer is no problem under Win11
![image](https://github.com/user-attachments/assets/9935dc57-2c17-474f-a8f6-c60d991ba417)

**Comment by emako** [comment]
If you still have any questions, please continue to reply.
