### ISSUE TITLE
开启【360桌面整理软件】后，桌面内容无法正常预览。

### ISSUE THREAD

**Issue by LuoZIren** [QL-Win/QuickLook#1367]
开启整理整理软件后，桌面上的A文件夹无法正常预览。此时，如果创建一个B文件夹，把A放入B后，A正常预览。不知道是桌面软件的问题还是这边的问题，所以两边都说一遍。两类软件都是刚需，希望早些解决。

**Comment by tfkzptzt** [comment]
我觉得是360桌面整理的问题，我这边也是这样，关闭360桌面整理就没事了

**Comment by emako** [comment]
360相关无法解答
