### ISSUE TITLE
The window cannot unpin after being pinned

### ISSUE THREAD

**Issue by BenWBerger** [QL-Win/QuickLook#1368]
https://github.com/QL-Win/QuickLook/assets/151447702/06d39b18-fff9-4ad7-942a-02f844db7a23

I doubt that was intended, especially considering [#46](https://github.com/QL-Win/QuickLook/issues/46). Currently, the window cannot unpin after being pinned.

**Comment by emako** [comment]
Add to Toast to notify that

**Comment by emako** [comment]
When trying to unpin it, `Cancellation of "Prevent Closing" is not supported` will be shown.

![image](https://github.com/user-attachments/assets/5f9716a0-b128-4bff-afff-8f09ea989928)

---

However, the Unpin function may also be supported in the future.
