### ISSUE TITLE
Hi Rabelux please read ASAP

### ISSUE THREAD

**Issue by allenbisconti** [QL-Win/QuickLook#1370]
**Hi Rabelux, you were trying to help me in a post I made and I think you thought I had given up and wasn't trying to do what you said but I had gotten sick, I was sick for 2 weeks, that's why I didn't reply.  I am ready to do what you say to do to get Quicklook working again, I was trying to do what you said before but had gotten confused and I'm pretty tech savvy (owned an Internet data business since 1997), just having a hard time figuring this one out.  I've attached a screenshot of what comes up every time I hit the spacebar not matter what file I click on.  I've uninstalled Quicklook several times, have cleared the temp and cache files, I want to get this working again so that I don't have to buy Quickeye or Seer.  :-(   I hope you'll help because like I said, I had gotten sick the first time we were talking and then immediately had to take care of my wife that had surgery after that.  Thank you.**
![Screenshot 2023-11-15 122346](https://github.com/QL-Win/QuickLook/assets/149194807/38e8acb9-d463-4812-b621-dfc611d438ea)

**Comment by rabelux** [comment]
This is the third issue you open for the same topic. To be honest, you behave like a 16 year old writing everything bold and complaining about the 10 bucks Seer asks for. You're saying you owned a business, how about supporting a developer by buying his software?
Sorry but I won't be helping you anymore. I get paid nothing for doing this. So if you make it such an unpleasant experience writing with you please solve it yourself.

**Comment by rabelux** [comment]
Duplicate of #1354

**Comment by allenbisconti** [comment]
I'm 49 years old, what the heck is wrong with you?  Talk about rude, did you even read what I said?  I told you I got SICK and my wife got surgery which is why I didn't get to finish doing what you were telling me to do!  I was trying to do what you said and you just cut me off because I misunderstood the last thing you were trying to get me to do.  If you don't want to help people then don't for cryin out loud, you don't have to be so rude.  If you don't have the patience to deal with people for free then DON'T, start charging!

**Comment by allenbisconti** [comment]
Please delete this thread.
