### ISSUE TITLE
Async plugin interface

### ISSUE THREAD

**Issue by Cologler** [QL-Win/QuickLook#1371]
Currently, previewing a big file is not cancellable. QuickLook may crash if I jump too fast.

Add the new async plugin interface with `CancellationToken`, which allows the user to cancel the current operator.

**Comment by xupefei** [comment]
The real problem is not all third-party components support cancel.
For example you see the TextViewer can be cancelled, but the ImageViewer can't. In this case it's beucase the ImageViewer does not provide a way to stop loading an image.

**Comment by emako** [comment]
I encountered the same doubts recently when maintaining ImageViewer.

Thank you for your suggestions.
