### ISSUE TITLE
System lag when starting QuickLook with the system

### ISSUE THREAD

**Issue by eduolivr** [QL-Win/QuickLook#1374]
Test carried out with two different computers using the .msi version of Quicklook.

PC 1
Windows 11
Ryzen 7 5800x3D
RTX 3070

PC 2
Linux Mint
Acer Aspire E1 Notebook

The problem happens when turning on the computer with the Quicklook active system booting and it causes this problem. I performed the test with each program launch installed on the computer and detected the problem with Quicklook

**Comment by emako** [comment]
Most of them are caused by other software conflicts.

If you still have any questions, please continue to reply.
