### ISSUE TITLE
How to preview .txt files?

### ISSUE THREAD

**Issue by vdmitx** [QL-Win/QuickLook#1375]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DejayRezme** [comment]
**Add your comment here**
Write a comment that is on topic and contains questions, clarifications or describes possible solutions or workarounds. Do not post off topic or silly meta jokes!
