### ISSUE TITLE
Let QuickLook open via CLI

### ISSUE THREAD

**Issue by LucOevel** [QL-Win/QuickLook#1378]
**Is your feature request related to a problem? Please describe.**
I am currently opening .html files in Python using os.startfile(filename) in windows10.  
When a browser (firefox, chrome,...) is associated with .html file this works fine, but when instead QuickLook is associated with .html files it does not work.

**Describe the solution you'd like**
Let QuickLook open a file using a CLI command.

**Comment by rabelux** [comment]
Already supported. You can invoke Quicklook from the command line as explained here:
https://github.com/QL-Win/QuickLook/wiki/Develop%2C-build-and-integrate#integrating-with-file-managers
