### ISSUE TITLE
Can you add support for the universal window closing shortcut key ctrl+w? It is not very convenient to close with a mouse click

### ISSUE THREAD

**Issue by fredeason** [QL-Win/QuickLook#1389]
可不可以加入对通用关闭窗口快捷键ctrl+w的支持？鼠标点击关闭不是很方便
Can you add support for the universal window closing shortcut key ctrl+w? It is not very convenient to close with a mouse click

**Comment by rabelux** [comment]
Fyi, you can also close by pressing space again or ESC button
