### ISSUE TITLE
Dark theme for text preview doesnt work

### ISSUE THREAD

**Issue by Shomnipotence** [QL-Win/QuickLook#1393]
**Dark theme for text preview doesnt work**

**To Reproduce**

UWP Version

User data location
Store version: %LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\.

1. Follow the wiki. Quit QuickLook if it is running.
Navigate to the [data location](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).
2. Open QuickLook.config with a text editor.
3. Add your desired config and save the file.

`<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <LastUpdateTicks>638419552821184708</LastUpdateTicks>
  <UseTransparency>True</UseTransparency>
  <AllowDarkTheme>True</AllowDarkTheme>
</Settings>`

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11 Build26052]
 - QuickLook Version: [e.g. 3.7.3 from Windows Store]

**Screenshots and Exception Log**
![image](https://github.com/QL-Win/QuickLook/assets/6630660/8478c15a-069c-42d4-a13a-cdd356dcdfee)

![image](https://github.com/QL-Win/QuickLook/assets/6630660/099fa80f-925e-4018-84d3-b29d6509751e)

**Comment by rabelux** [comment]
Could you try the latest nightly? I'm afraid this feature hasn't made it into any official release yet.

**Comment by emako** [comment]
Done
