### ISSUE TITLE
Add a copy icon when previewing images

### ISSUE THREAD

**Issue by Verlaire** [QL-Win/QuickLook#1399]
Hi,

Is it possible to add a copy icon in the toolbar to copy the image being previewed?

Thanks. I love the app and been using it for years! <3

**Comment by emako** [comment]
![image](https://github.com/user-attachments/assets/4ffce282-9484-4f56-8767-89cd32ca1491)

**Comment by Verlaire** [comment]
> ![image](https://github.com/user-attachments/assets/4ffce282-9484-4f56-8767-89cd32ca1491)

This never saw light, right? never got this to appear at all and I keep QuickLook updated.

**Comment by emako** [comment]
Check from nightly build named latest https://github.com/QL-Win/QuickLook/releases

**Comment by Verlaire** [comment]
> Check from nightly build named latest https://github.com/QL-Win/QuickLook/releases

Thanks my friend, but is not working. I mean, in that build the button is now displayed, but clicking it does nothing (quick test: pick an image, preview it with quicklook, click the button, paste it in a Facebook post and nothing happens).

**Comment by emako** [comment]
Can you paste it to Paint?

![Image](https://github.com/user-attachments/assets/2efb3d8c-84a4-42ae-8ecf-ff37f4a3d78a)
