### ISSUE TITLE
Won't work for me

### ISSUE THREAD

**Issue by jkmoz** [QL-Win/QuickLook#1405]
Hello,
When I press the space bar on a fits file I get code.
![Screenshot (1)](https://github.com/QL-Win/QuickLook/assets/163044711/175e4460-088b-4f6e-a46d-ea3afd77388a)

Windows 10 Home
Build 19045.4046
Most recent Quicklook

Please help, thank you.
John

**Comment by 1111Al** [comment]
By now QL is a discontinued program/project. It is full of bugs and weaknesses that make it basically unusable. I abandoned it long ago for PowerToys.

**Comment by emako** [comment]
There are no plans to support this format
