### ISSUE TITLE
Invalid self-start

### ISSUE THREAD

**Issue by SerMs** [QL-Win/QuickLook#1406]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission.     Has this issue already been reported?    *
Yes
**Describe the bug**
Set the software startup automatically, the software program is indeed started, but after selecting the file press the space and there is no response, you need to manually exit the software after manual startup can be used normally, what is the problem?
**To Reproduce**
1.     Go to '...'
2.     Click on '....'
3.     Scroll down to '....'
4.     See error

**Expected behavior**

**Desktop (please complete the following information):**
- OS Version: [Windows 11 专业版 23H2]
- QuickLook Version: [e.g. 3.7.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem.     The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by SantoGG** [comment]
I have the same problem, the program has an icon in the tray after self-boot, but the spacebar doesn't do anything..

**Comment by SantoGG** [comment]
I've reinstalled quicklook and the problem still hasn't improved.

**Comment by Da-ker** [comment]
**iGame Center** causes software conflicts

**Comment by Da-ker** [comment]
七彩虹显卡控制软件的锅

**Comment by SantoGG** [comment]
> 七彩虹显卡控制软件的锅

牛逼，我从来没想过是这个软件的问题，你是怎么发现的

**Comment by Da-ker** [comment]
> > 七彩虹显卡控制软件的锅
> 
> 牛逼，我从来没想过是这个软件的问题，你是怎么发现的

被这问题困扰好久了，搜遍全网也只发现了这一处反馈。
正好还有台电脑一直都能正常使用，就开始怀疑软件冲突了，
试着控制变量退了些软件，排查出了是igc，
真是可恶啊

**Comment by SantoGG** [comment]
> > > 七彩虹显卡控制软件的锅
> > 
> > 
> > 牛逼，我从来没想过是这个软件的问题，你是怎么发现的
> 
> 被这问题困扰好久了，搜遍全网也只发现了这一处反馈。 正好还有台电脑一直都能正常使用，就开始怀疑软件冲突了， 试着控制变量退了些软件，排查出了是igc， 真是可恶啊

我也是有两台电脑，一台正常一台有问题，没问题的那台是微星的显卡，怀疑是冲突，也退了一些软件，但就真的没想过是igc哈哈哈
