### ISSUE TITLE
[Feature Request] Adding .hwp support

### ISSUE THREAD

**Issue by jaylee171** [QL-Win/QuickLook#1421]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
In Korea for document editing we use a program called HanCom, its file extension is .hwp (It is similar to MS Word). However, currently this is the only extension I am not able to open with QuickLook

**Describe the solution you'd like**
It would be great to have support to open these kinds of files with QuickLook! 

**Describe alternatives you've considered**
I have searched many alternatives but with no avail :(  
So I was wondering if this feature might be developed in the future!

**Comment by emako** [comment]
Since .hwp is not widely available, if you frequently handle such files, it is recommended to install Hangul software or ask the sender to provide another format (such as PDF).

**Comment by syehoonkim** [comment]
Dear, I developed [Hwp Viewer Plugin](https://github.com/syehoonkim/QuickLook.Plugin.HwpViewer). I hope this work.
