### ISSUE TITLE
Send arrow  key inputs to (unfocused) explorer window If QuickLook is in focus

### ISSUE THREAD

**Issue by nitin2953** [QL-Win/QuickLook#1422]
**Is your feature request related to a problem? Please describe.**
When I click QuickLook window, the explorer window (or files on desktop) loose focus and I'm not able to switch files using arrow buttons.

**Describe the solution you'd like**
Only send arrow key inputs to unfocused explorer window/desktop If QuickLook is in focus

**Comment by emako** [comment]
Sorry for this type of operation is not supported

**Comment by nitin2953** [comment]
I think it is easy to add, since QuickLook know the currently focused explorer window and the file it is previewing.
If it receives left/right arrow key inputs then it just need to forward it to the explorer window/desktop.
