### ISSUE TITLE
pooi.moe is for sale?

### ISSUE THREAD

**Issue by mijorus** [QL-Win/QuickLook#1428]
If you don't own this domain anymore, could you please remote it from the description of the repo?

**Comment by 1111Al** [comment]
By now QL is a discontinued program/project. It is full of bugs and weaknesses that make it basically unusable. I abandoned it long ago for PowerToys.

**Comment by emako** [comment]
@xupefei  Could you please respond? I have the same question.

**Comment by KamilDev** [comment]
> By now QL is a discontinued program/project. It is full of bugs and weaknesses that make it basically unusable. I abandoned it long ago for PowerToys.

I've tried PowerToys Peek, but unfortunately it's not suitable for my use-case. For example:
- Can't bind to spacebar
- Doesn't work in "file open" dialogs
- Doesn't seem to have a plugin system
- QuickLook can work in external tools (for example, "Everything" search tool.)

I think if @xupefei doesn't have time, some co-maintainers should be assigned. QuickLook is such a great tool if maintained, I wish I could work on it fulltime 😝 .

**Comment by emako** [comment]
There is no conclusion yet,

**Comment by 1111Al** [comment]
> > By now QL is a discontinued program/project. It is full of bugs and weaknesses that make it basically unusable. I abandoned it long ago for PowerToys.
> 
> I've tried PowerToys Peek, but unfortunately it's not suitable for my use-case. For example:
> 
>     * Can't bind to spacebar
> 
>     * Doesn't work in "file open" dialogs
> 
>     * Doesn't seem to have a plugin system
> 
>     * QuickLook can work in external tools (for example, "Everything" search tool.)
> 
> 
> I think if [@xupefei](https://github.com/xupefei) doesn't have time, some co-maintainers should be assigned. QuickLook is such a great tool if maintained, I wish I could work on it fulltime 😝 .

You can use spacebar plus another key, I use ctrl+space
preview of documents works in dark mode, QL doesn't.
The last two points are missing for now; perhaps they will be implemented in the future.
