### ISSUE TITLE
FolderViewer plugin crashes QuickLook

### ISSUE THREAD

**Issue by DavidOfMA** [QL-Win/QuickLook#1429]
On an HP Laptop 17 running the latest release-level build of Windows 11 Pro, QL crashes when viewing folders with the FolderViewer
1. Install FolderViewer plugin
2. Press spacebar when cursor is on folder in Explorer
3. If folder contains more than a few files, or contains folders, QL crashes.
4. If folder contains only a few files, a list of files is displayed.

**Comment by emako** [comment]
The issue of FolderViewer is not here...

See https://github.com/adyanth/QuickLook.Plugin.FolderViewer/issues

**Comment by emako** [comment]
But we will develop the built-in FolderViewer in the future.
