### ISSUE TITLE
Suggestion: Zoom in/out the window when using the mouse wheel to zoom in/out the previewd image

### ISSUE THREAD

**Issue by YandLiu** [QL-Win/QuickLook#1437]
如题
一个细节：当窗口已经被放大至最大（宽度/高度之一达到屏幕宽度/高度）时，继续放大图像就没必要再放大窗口了，就像IrfanView一样。
As the title writes
Also, a trivial point, please don't zoom in the window further when it's already the maximized (I mean it reaches the max width or length of the screen). Just like how IrfanView behaves.

**Comment by emako** [comment]
目前应该是符合，有问题继续跟踪

**Comment by YandLiu** [comment]
我用了release中的最新版，预览窗口并不会随图片的缩放而缩放，可否release一个加上此feature的版本？

**Comment by emako** [comment]
目前是按窗口缩放而缩放图片，

没见过哪个软件是图片缩放而缩放窗口的。

**Comment by YandLiu** [comment]
看图类软件中尤其普遍啊，比如大名鼎鼎的Irfanview
