### ISSUE TITLE
自定义缩放后窗口尺寸过大

### ISSUE THREAD

**Issue by ZeppLu** [QL-Win/QuickLook#145]
![image](https://user-images.githubusercontent.com/17007549/33516484-7617e766-d7ae-11e7-84f3-13abda92f3e2.png)

如图（这是整个屏幕的截图），电脑缩放比例为125%.

顺便提个建议：窗口最大化和关闭时都没有动画，这应该是自定义了边框导致的，随手一搜找到了[一些解决方法](https://stackoverflow.com/questions/21418160/custom-window-style-with-minimize-animation)。当然，这只是个建议，而且窗口动画也仅仅是个锦上添花的功能而已 :)

**Comment by xupefei** [comment]
我无法复现问题。你是不是把预览窗口拖到了另一个屏幕上，且这个屏幕的缩放比和另一个不同？

> 窗口最大化和关闭时都没有动画
已经修好了。
