### ISSUE TITLE
When the QuickLook.Plugin.OfficeViewer plugin previews office documents, sometimes the window that comes out is blank

### ISSUE THREAD

**Issue by ridewindgo** [QL-Win/QuickLook#1452]
当使用QuickLook.Plugin.OfficeViewer插件对一个docx文档，点击空格时弹出预览窗口是空白的。
When using the QuickLook. Plugin. OfficeViewer plugin on a docx document, the pop-up preview window is blank when a space is clicked.
![屏幕截图 2024-08-15 171400](https://github.com/user-attachments/assets/c19753a1-f6eb-4eb8-b6a5-e4001070b2c1)

多试几次后，或者用wps打开该文档后，再次对该docx文档点击空格后，弹出预览窗口又能出现文档内容。
After a few more attempts, or after opening the document with wps, click the space on the docx document again, and the document content will appear in the pop-up preview window.

我尝试修改，只要将依赖库Syncfusion更新到最新版，重新编一个插件出来就行，但是Syncfusion需要授权码，我没有办法申请到长期的授权码，谁能帮忙一下。
I try to modify it, as long as I update the dependency library Syncfusion to the latest version and re-write a plug-in, but Syncfusion requires an authorization code, and I can't apply for a long-term authorization code. Who can help?

https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer?tab=readme-ov-file

**Comment by emako** [comment]
在新版本的license key能申请下来之前，可以先使用这边构建的试用版，能提供差不多的体验。
Before the license key of the new version can be applied for, you can first use the trial version built here.

https://github.com/emako/QuickLook.Plugin.OfficeViewer

**Comment by emako** [comment]
现在可以获取新版本插件了
The new version of the plugin is now available

https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer/releases
