### ISSUE TITLE
Alternate way to close the preview window

### ISSUE THREAD

**Issue by DGCK81LNN** [QL-Win/QuickLook#1458]
**Is your feature request related to a problem? Please describe.**
I've been using a [LiteLoaderQQNT](https://github.com/mo-jinran/LiteLoaderQQNT) [plugin](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/tree/master) which replaces QQ 9's builtin image preview window with QuickLook. However, as the QuickLook window does not automatically gain focus when opened, and pressing Esc / Space to close QuickLook only works in Explorer, I have to either move my mouse to the Close button and click it, or click on the QuickLook window and then press Esc to close it, which is very annoying.

**Describe the solution you'd like**
An alternate way to close the QuickLook window, such as by pressing the middle or 4th mouse button on it.

**Describe alternatives you've considered**
* It might also be possible instead for the QQNT plugin to implement pressing Esc or Space, while focusing the QQ window, to close QuickLook.
* Another possible solution is to give the QuickLook window focus by default, unless opened from Explorer.

**Additional context**

**Comment by emako** [comment]
The middle mouse button has its own operation logic in some plugins.
The 4th mouse button as a less commonly used button, it is difficult to use as close button by default.

Maybe you can develop your own QL plugin to impl it.
