### ISSUE TITLE
OfficeViewer Plugin not work well with WebViewPlus

### ISSUE THREAD

**Issue by dateno1** [QL-Win/QuickLook#1464]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

If WebViewPlus Installed OfficeViewer is broken

**To Reproduce**
1. Install OfficeViewer Plugin
2. Test result
3. Install WebViewPlus
4. Test result

**Expected behavior**
![Normal](https://github.com/user-attachments/assets/04a8b4f2-bcc8-44d1-9eaa-a5e1c37df465)
OfficeViewer Plugin only
![WebPlus](https://github.com/user-attachments/assets/68515314-db42-4bf4-9602-03c83023e9b1)
WebViewPlust Installed

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803] : 10 1809/22H2 Tested
 - QuickLook Version: [e.g. 0.3.3 from Windows Store] : QuickLook v3.7.3 MSI

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

========24-09-10 화 22:38:10========
QuickLook.Plugin.WebViewPlus using app from plugin

Log content

**Comment by mooflu** [comment]
Go to the webviewplus setting and turn off xls/xlsx under "tabluar data".

**Comment by emako** [comment]
If you have any questions, please contact mooflu, who is the developer of this plugin.
