### ISSUE TITLE
WebViewPlus plugin force to use Edge Webview 2 runtime

### ISSUE THREAD

**Issue by dateno1** [QL-Win/QuickLook#1465]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**
1. Install QuickLook
2. Test
3. Install WebViewPlus plugin
4. Test

**Expected behavior**

If WebViewPlus installed i can't see any documents without WebView 2 Runtime

If it not installed i can view txt or office document without runtime

**Desktop (please complete the following information):**
 - OS Version: 10 1607/1809/21H2 Tested
 - QuickLook Version: 0.3.7 (Lastest) MSI

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

![without](https://github.com/user-attachments/assets/77d6443b-6d67-4dc4-8018-3488bd0cb305)
without WebViewPlus Plugin
![with](https://github.com/user-attachments/assets/3928dae3-fc3b-4842-b4f6-a3a7358dcba4)
with plugin

**Comment by mooflu** [comment]
Not a QL bug. This error is shown by the plugin not QL: https://github.com/mooflu/QuickLook.Plugin.WebViewPlus/blob/master/WebpagePanel.cs#L115

WebViewPlus plugin requires edge webview2. If you don't have it installed or an older version, it's not going to work.

**Comment by dateno1** [comment]
> Not a QL bug. This error is shown by the plugin not QL: https://github.com/mooflu/QuickLook.Plugin.WebViewPlus/blob/master/WebpagePanel.cs#L115
> 
> WebViewPlus plugin requires edge webview2. If you don't have it installed or an older version, it's not going to work.

I know all

It not QL bug (plugin bug)

but I can't upload post on Plugin's repo

Also WebViewPlus is not work without Runtime is normal

but QL support txt file on box and this plugin affect to view many format

I think it not needs (WebView Plust plugin affect to too broad range format)

**Comment by mooflu** [comment]
WebViewPlus returns a higher priority so it gets chance to override preview for images, pdf, etc. If you don't want a specific file type (like txt, xls, etc.) to be previewed by WebViewPlus you can go to its settings and disable it. 

If you don't have the Edge Webview2 runtime installed then accessing WebViewPlus' settings is not going to work as it also requires webview2. WebViewPlus is pointless without webview2 and you might as well remove it or not install it in the first place.

**Comment by dateno1** [comment]
> WebViewPlus returns a higher priority so it gets chance to override preview for images, pdf, etc. If you don't want a specific file type (like txt, xls, etc.) to be previewed by WebViewPlus you can go to its settings and disable it.
> 
> If you don't have the Edge Webview2 runtime installed then accessing WebViewPlus' settings is not going to work as it also requires webview2. WebViewPlus is pointless without webview2 and you might as well remove it or not install it in the first place.

How can i exclude txt or something (I can't found all extension on setting menu)

Menu hasn't so many entries
