### ISSUE TITLE
OfficeViewer Native failed to open some of xlsx file

### ISSUE THREAD

**Issue by dateno1** [QL-Win/QuickLook#1466]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

Try to show xlsx file it failed

**To Reproduce**
1. Select file
2. Push spacebar
3. Failed

**Expected behavior**
Some of xlsx file not work with Native plugin (OfficeViewer is OK)

**Desktop (please complete the following information):**
 - OS Version: 10 1809 LTSC 2019 x64
 - QuickLook Version: 3.7.3
 - MS Office 2024 x64 installed
 -  No other plugins installed (It test enviroments)
**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

========24-09-12 목 11:45:53========
System.Runtime.InteropServices.COMException (0x86420004): 예외가 발생한 HRESULT: 0x86420004
   위치: QuickLook.Plugin.OfficeViewer.IInitializeWithFile.Initialize(String pszFilePath, UInt32 grfMode)
   위치: QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   위치: QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   위치: QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__1()
Log file

**Comment by rabelux** [comment]
From the wiki page:
*1: Native installation only. Office 365 installed from Windows Store is not supported by this plugin. This plugin is not stable, meaning it may or may not work for you. We recommend using another Office plugin

**Comment by dateno1** [comment]
> From the wiki page: *1: Native installation only. Office 365 installed from Windows Store is not supported by this plugin. This plugin is not stable, meaning it may or may not work for you. We recommend using another Office plugin

It not UWP

It work well with some of file but not work with another file

It just bug report (I don't want to use this plugin yet)
