### ISSUE TITLE
Is it possible to separate md2html.html into multiple files?

### ISSUE THREAD

**Issue by KamilDev** [QL-Win/QuickLook#1488]
Is it possible to separate [QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer/Resources/md2html.html](https://github.com/QL-Win/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer/Resources/md2html.html) into multiple files?

Currently, all the minified libraries are pasted inline into the HTML file, which:
- Makes it messy trying to work on the file
- Causes editor to lag due to the large minified libraries being in the same file
- Makes it harder to update library files
- Etc.

Is it a limitation of how plugins work, that causes the inability to separate into multiple files and import them into the HTML file?

Currently the way it seems to work is:
- The string contents of md2html.html file is embedded into the MarkdownViewer plugin
- This string gets loaded directly to the WebView, which means the page location is `about:blank`, thus importing files would not work.

The entire directory of `QuickLook.Plugin.MarkdownViewer/Resources` (or +`/Web`) would need to be copied somewhere, so that we can load the HTML file from there, and the WebView has knowledge of the relative directory for importing files to work.

Furthermore, it would be beneficial if the md2html.html and related files were accessible somewhere in the QuickLook data directory. This would allow users to easily customize the behavior, without needing to recompile the entire plugin.

---

Regardless of md2html.html, I would like to know if this is possible with plugins. I'm planning on creating a plugin that uses WebView similar to MarkdownViewer. I would really like to import files and have the files accessible to the user for easy customization.

This would also enable the use of `localStorage` in the WebView, which I need.

**Comment by emako** [comment]
Completed
