### ISSUE TITLE
Replace MessageBox with a modern implementation?

### ISSUE THREAD

**Issue by KamilDev** [QL-Win/QuickLook#1492]
The standard `MessageBox` doesn't support dark mode and is not modern (e.g. icons, XP-style buttons).
 
What are the thoughts of using a replacement such as [ModernWpf.MessageBox](https://github.com/OpenByteDev/ModernWpf.MessageBox)?

**ModernWPF.MessageBox**

![image](https://raw.githubusercontent.com/OpenByteDev/ModernWpf.MessageBox/master/screenshots/Screenshot-01.png)

**System.Windows.MessageBox**

![image](https://raw.githubusercontent.com/OpenByteDev/ModernWpf.MessageBox/master/screenshots/Screenshot-02.png)

I'm happy to work on the implementation.

**Comment by emako** [comment]
[ModernWpf](https://github.com/Kinnara/ModernWpf) had stopped updating.
I generally use [wpfui](https://github.com/emako/wpfui.violeta) as an alternative

**Comment by emako** [comment]
Wpf.Ui.Violeta.Controls.MessageBox:

![image](https://github.com/user-attachments/assets/5fb200ca-d265-467c-875e-a6f4ae5c860d)

**Comment by KamilDev** [comment]
This looks very nice! I'll work on implementing it.

**Comment by KamilDev** [comment]
Implemented: https://github.com/QL-Win/QuickLook/pull/1494
