### ISSUE TITLE
Sometimes, when viewing compressed files, they cannot be displayed.

### ISSUE THREAD

**Issue by Chigua-ye** [QL-Win/QuickLook#1496]
*For all's convenience, please use English to fill this issue.*
﻿
*Please search within existing issues before the submission. Has this issue already been reported?*
no 
**Describe the bug**
Sometimes, when viewing compressed files, they cannot be displayed.
**To Reproduce**
![PixPin_2024-12-08_10-42-24](https://github.com/user-attachments/assets/d61994c4-afc6-4f57-a4d7-99ec61a28f97)
v3.7.3 Can be used

![PixPin_2024-12-08_11-01-46](https://github.com/user-attachments/assets/c79dcf66-af7f-411c-991a-0261096e3822)

Overwriting v3.7.3 'QuickLook.Plugin.ArchiveViewer' to v3.7.3-58-g619f16b will work
![image](https://github.com/user-attachments/assets/5bd7d4fc-4548-4e3e-82f0-6cdc1a3cb6e1)

Test Documents:

**Expected behavior**
It can be used normally
﻿
**Desktop (please complete the following information):**
[test.zip](https://github.com/user-attachments/files/18050584/test.zip)

- OS Version: Windows 11 24H2 26120.2415
- QuickLook Version:  QuickLook-3.7.3-58-g619f16b.zip
﻿
**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by KamilDev** [comment]
My PR solves this issue: https://github.com/QL-Win/QuickLook/pull/1497

You can download the fixed version once the PR gets accepted.

**Comment by emako** [comment]
> My PR solves this issue: #1497
> 
> You can download the fixed version once the PR gets accepted.

Solved with your PR
