### ISSUE TITLE
Windows light/dark theme breaking Office preview

### ISSUE THREAD

**Issue by ioannis-rz** [QL-Win/QuickLook#1499]
**Describe the bug**
When using office viewer plugin in light mode, the background is white, and so is the text

**To Reproduce**
1. Set Windows to light theme
2. Preview a word/excel file using QL
3. This happens:
![image](https://github.com/user-attachments/assets/a813bec6-05b5-46b7-b72e-c4aa1a405bf4)
![image](https://github.com/user-attachments/assets/b964541b-5508-49e1-a9e7-939be5b4d918)
As you can see, the text appears white-ish on a white background. It is almost impossible to read

**Expected behavior**
I expected a behavior like this one, white background with "normal" black text. 
![image](https://github.com/user-attachments/assets/89daa33f-2395-42b5-8ada-17eae3745e34)

This happens when I have dark mode enabled. 

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11 Version	10.0.26100 Build 26100]
 - QuickLook Version: [v. 3.7.3 (UWP)]
 - Office 2010

**Comment by emako** [comment]
Are you using native plugin (https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native) and which OFFICE version?

Can restarting QL solve the problem?

**Comment by emako** [comment]
I have no recurrence of the problem when using Office 2024.
It is recommended to use non-native OfficeViewer as an alternative
https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer
