### ISSUE TITLE
HEIC failed to preview

### ISSUE THREAD

**Issue by rn1604** [QL-Win/QuickLook#1501]
Issue:
"Failed to preview heic file" error appeared when trying to quicklook it
It used to be ok, showing the full image when I press spacebar. But it suddenly broke couple of weeks back. Other file type works fine (eg. jpg, png)

 - OS Version: Windows 11 24H2
 - QuickLook Version: 3.7.3.0

![quicklook error](https://github.com/user-attachments/assets/15ba8d45-aebe-4a6f-9b0a-e9d92cbb66c6)

**Comment by KamilDev** [comment]
Is this for all HEIC files or only this specific file? If only for this specific file, please provide a download to the file.

**Comment by rn1604** [comment]
> Is this for all HEIC files or only this specific file? If only for this specific file, please provide a download to the file.

It's for all the heic files from my iPhone 16 Pro.

**Comment by rn1604** [comment]
[Logitech MX Master 2S (1).zip](https://github.com/user-attachments/files/18062901/Logitech.MX.Master.2S.1.zip)
Attached an example
