### ISSUE TITLE
QuickLook.Plugin.OfficeViewer 使用问题

### ISSUE THREAD

**Issue by laycher** [QL-Win/QuickLook#1502]
![image](https://github.com/user-attachments/assets/d3ebe883-3547-4bee-a716-decb54b5b92d)

我刚下完v4版本，然后测试了，只能展示这个样子。
然后下了V5后还是这个样子，
为啥我预览ppt变成这个样子了？而不是ppt内容。
是不是插件之间有冲突？但是看不出来到底是不是用的这个officeviewer插件。

**Comment by emako** [comment]
你可以安装latest版本的QL，然后打开数据文件夹里查看已安装的插件：
![image](https://github.com/user-attachments/assets/5022d035-43f1-4952-b2fd-e409c9bede00)

**Comment by emako** [comment]
安装 https://github.com/QL-Win/QuickLook/releases/tag/latest 版本Quicklook，
试试其他office文件比如excel或者word，
然后排除其他插件，看是否复现问题。

QuickLook.Plugin.OfficeViewer在显示ppt前是会转成pdf格式的，如果excel或者word的能显示，说明可能是ppt转pdf时发生了错误。

**Comment by emako** [comment]
看图标才反应过来，这是WPS吧？

**Comment by emako** [comment]
WPS下Word和Excel能正常预览吗？

**Comment by emako** [comment]
如果是同时安装MS WPS导致，可能需要修复注册表或重装office

https://github.com/QL-Win/QuickLook/issues/1182
https://github.com/QL-Win/QuickLook/issues/1216
https://zhuanlan.zhihu.com/p/454259765

**Comment by laycher** [comment]
非常感谢回复，试了一些方法都不行，我直接全部删除，然后新安装，现在好了。
后期新增的插件不敢乱加了。

**Comment by emako** [comment]
OK，不过跟新不新增插件没有关系，插件只读注册表

**Comment by emako** [comment]
后续版本>=QuickLook-4.0.2-54-gf897ce4，可以用管理员权限运行QuickLook并预览对应文件时可以自动修复WPS污染的注册表信息（仅限修复回MS Office版本）
