### ISSUE TITLE
OfficeViewer-Native can't view the protected view

### ISSUE THREAD

**Issue by emako** [QL-Win/QuickLook#1503]
![image](https://github.com/user-attachments/assets/27061c8f-7492-4228-b6d1-5e4c0f65f07f)

OfficeViewer-Native can't view the protected view, until you open it using Microsoft Office and click `Enable Editing`.

The test PPTX file from https://github.com/QL-Win/QuickLook/issues/363

**Comment by emako** [comment]
This case is the same as #1.

**Comment by emako** [comment]
Fix with https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native/commit/0f9049f5bdbc09116ea844ecdceaa17db64b7dce

**Comment by emako** [comment]
I also need to test the performance under WPS

**Comment by VictoriousRaptor** [comment]
是否有可能自动允许查看保护视图？每次都点击实在有点麻烦。

**Comment by emako** [comment]
> 是否有可能自动允许查看保护视图？每次都点击实在有点麻烦。

暂不考虑，这个是防病毒措施
