### ISSUE TITLE
Nightlies after #16 crash on secutive PDF preview

### ISSUE THREAD

**Issue by Svetloslav** [QL-Win/QuickLook#1508]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
Ever since nightly version #16 I can crash QL by just previewing a folder with some PDF, TEXT files. On a first preview all works well. Than if I try to repeat previewing any of the files I just previewed, QL would crash and would need a restart. I have following plug-ins loaded: ApkViewer, epub viewer, FolderViewer, MarkmapViewer,  OfficeViewer, PostScriptViewer, WebViewPlus. I have the latest versions of all this plug-ins, but it is the same even if I use older versions. Any nightly up to #81 will crash. Than I uninstall with RevoUninstaller (thoroughly) and repeat with nightly #16. Everything works rock solid. In fact I am unable to crash nightly #16 no matter what I do, even previewing over wired network files like: videos, folder views, epubs, pdfs, web links. I can not imagine more solid version than the nightly #16. 

**To Reproduce**
1. Pick a folder with several file formats
2. Preview them in line
3. Close QL
4. Try again with any of those files in the folder and QL would crash.

**Expected behavior**
To be able to preview any supported file in any order and in any place in explorer.

**Desktop (please complete the following information):**
 - OS Version: [Windows 11 24H4]
 - QuickLook Version: [ nightlies from Github starting from v16, up to v81]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by emako** [comment]
MarkmapViewer and WebViewPlus use some different versions of WebView.

I will fix the MarkmapViewer later.

**Comment by emako** [comment]
https://github.com/emako/QuickLook.Plugin.MarkmapViewer/issues/2

**Comment by emako** [comment]
If you just use PDF preview, you can use this plugin instead

https://github.com/QL-Win/QuickLook.Plugin.PdfViewer-Native/releases

**Comment by emako** [comment]
MarkmapViewer v1.0.1 is released now

https://github.com/emako/QuickLook.Plugin.MarkmapViewer/releases
