### ISSUE TITLE
Question regarding copyright names for contributions

### ISSUE THREAD

**Issue by KamilDev** [QL-Win/QuickLook#1509]
I noticed the Get Associated App For Scheme code was moved to a separate file in a [recent commit](https://github.com/QL-Win/QuickLook/commit/822b22df47b8e3877c7fda6ba1887152ff256496#diff-f064d3e39da6eaa7e33220c72e0ce6578d39a5d34b634f6622a0a0c45a3e2829L162). Though the copyright name is incorrect, since I was the one who wrote this code during my [Improved MarkdownViewer PR](https://github.com/QL-Win/QuickLook/commit/ec62cb42389bc079f3e143a94bd61b8cda8a11b4).

I haven't added my name to any of the copyright names in any of my contributions, since I'm unsure what the deciding factor is. I'm assuming it should be added for significate additions to the file, and any new files created?

I'd love some clarification on when it's appropriate to add your name to the copyright notice for the future.

**Comment by emako** [comment]
While we retain the copyright information for existing files, I think it would be more appropriate to use "QL-Win" to refer to all contributors for new files added in the future.

**Comment by KamilDev** [comment]
Thanks for the clarification. I believe you should change [ShlwApi.cs](https://github.com/QL-Win/QuickLook/blob/822b22df47b8e3877c7fda6ba1887152ff256496/QuickLook.Plugin/QuickLook.Plugin.HtmlViewer/NativeMethods/ShlwApi.cs) copyright name to QL-Win, since it was written by me, not the person currently named there.
