### ISSUE TITLE
directory opus 13 无法使用 quicklook 

### ISSUE THREAD

**Issue by 2451965602** [QL-Win/QuickLook#1510]
![image](https://github.com/user-attachments/assets/76f380b0-3e64-4402-9fbd-3590c79fbffe)
在directory opus 13 中使用报错
![image](https://github.com/user-attachments/assets/ae08c63e-82db-44ab-a8d1-37ac6613f78a)

在Windwos 11 自带的资源管理器运行正常

 OS Version: 23H2  22631.4602
QuickLook Version v3.7.3 和  v3.7.3-86-g51a7fe0

**Comment by emako** [comment]
![image](https://github.com/user-attachments/assets/c6e26218-a618-4eba-b0a9-90ab67fa823b)

挺正常的

**Comment by 2451965602** [comment]
请问一下这个报错日志会保存在哪里

**Comment by emako** [comment]
<img width="191" alt="image" src="https://github.com/user-attachments/assets/412d2926-637c-4583-95c9-30d696d2ac9d" />

and QuickLook.Exception.log here
