### ISSUE TITLE
Can not preview a DNG picture

### ISSUE THREAD

**Issue by s3qazx** [QL-Win/QuickLook#1513]
Using quicklook for DNG format
 - OS Version:Windows 11 Professional 版本	10.0.26100 版本 26100
 - QuickLook Version: 3.7.3 form github

**Screenshots and Exception Log**
![屏幕截图 2024-12-22 210445](https://github.com/user-attachments/assets/9f50779b-9e7a-4493-87a0-4f29684568a9)

**Comment by emako** [comment]
https://github.com/QL-Win/QuickLook/issues/1220

**Comment by s3qazx** [comment]
> #1220

how can i solve the problem? I have installed version 3.7.3 of quicklook

**Comment by emako** [comment]
Fix in nightly build and this feature will be as version `4.0.0`
https://github.com/QL-Win/QuickLook/releases

Since there are too many issues, I will close the issues first if they are fixed in the nightly build.

If you still have any questions, please continue to reply.

**Comment by s3qazx** [comment]
OK thank you
