### ISSUE TITLE
Update Readme to mention install scoop extras bucket before attempting to install Quicklook

### ISSUE THREAD

**Issue by Jetfly56** [QL-Win/QuickLook#1519]
Cannot install via scoop without extras being installed. This is unintuitive. I have a fresh install of windows so I didnt have 'extras' bucket installed yet.

**Bug re-production**
Install scoop via terminal application. ****linked notes already exist to know how to do this****
"scoop install quicklook"
Returns "Couldn't find manifest for 'Quicklook'."

**Expected behavior**
Returns "Installing 'quicklook' (X.y.z) [64bit] from 'extras' bucket"....
proceeds to install Quicklook

**Desktop:**
 - OS Version: [e.g. Windows 11 23H2]
 - QuickLook Version: [3.7.3 from scoop.sh extras]

**Screenshots and Exception Log**
![image](https://github.com/user-attachments/assets/4623dd90-15ec-449f-b7e8-eaafef761660)
![image](https://github.com/user-attachments/assets/638d5a62-b2a7-4944-b008-0b37855fb5a2)
![image](https://github.com/user-attachments/assets/2e6b3388-eacf-463b-bc7d-e4f0d9c25db2)

**Comment by emako** [comment]
It seems that the README needs to be modified

**Comment by emako** [comment]
```sh
scoop bucket add extras

scoop install extras/quicklook
```
