### ISSUE TITLE
password-protected Pdf

### ISSUE THREAD

**Issue by xupefei** [QL-Win/QuickLook#155]

**Comment by Xelbayria** [comment]
Yup. You should add something that would say that it's passworded or protected

some files have the option to be protected or not-access-allowed OR passworded. I was going to report this issue.

**Comment by emako** [comment]
This feature has been implemented in the nightly build.

https://github.com/QL-Win/QuickLook/releases

**Comment by emako** [comment]
![image](https://github.com/user-attachments/assets/accb91b9-68f7-4b36-ac4a-89a22ace6798)
