### ISSUE TITLE
error code 2503 2502

### ISSUE THREAD

**Issue by bentigovai** [QL-Win/QuickLook#157]
安装QuickLook-0.3.2.1-39-gc7d9d25时遇到问题，win10 X64机器。the installer has encountered an unexpected error installing this package.

**Comment by xupefei** [comment]
我刚刚试了试这个版本，是可以正常安装的。这个错误应该是你的系统问题。
你可以试试 zip 免安装版。

**Comment by emako** [comment]
Issue has passed too long will be closed.
