### ISSUE TITLE
Enlarging of Preview Window Size when Zooming instead of zooming into Preview

### ISSUE THREAD

**Issue by demolitionb** [QL-Win/QuickLook#160]
I encounter the following situation: 
Quicklook previews something and it's too small. Let's say a JPG with low pixel dimension. When Zooming the Image gets zoomed in, but the dimensions of the preview Window remain the same. 

That's not what I want. Much better would be, that the preview window also gets enlarged to fit the enlarged pixel dimensions of the zoomed image. Of course - when the preview window approaches the max. dimensions of the screen, the image has to be cropped when further zoom is applied.

Further: The maximum zoom factor of 300% seems not enough! 500 or 600% would be a reasonable factor. When the image gets crappy, the user will stop zooming anyway. But it's important for High DPI monitors. Interpolation would also be nice. 

Screenshot and Test Image in the attachment.
![capture](https://user-images.githubusercontent.com/11042335/34759248-e1453df0-f5da-11e7-91b3-6f10726762cf.PNG)

![physics lut](https://user-images.githubusercontent.com/11042335/34759273-eff3cc0e-f5da-11e7-9efe-754fb0da2689.png)

**Comment by xupefei** [comment]
Thanks got your idea.
However, I am afraid changing window size dynamically may affect user experience as the window flickers when its size has been changed.

I am thinking about another solution: instead of changing the window size, it sets the window initially to the _maximum size_ (defined the same as in your text), while the content is zoomed accordingly.
In the above case, the image you provided will be much larger, something like (made my MS Paint, apologies for hurting your eye):

![34759248-e1453df0-f5da-11e7-91b3-6f10726762cf](https://user-images.githubusercontent.com/1687847/34812977-c4371130-f6b0-11e7-8d47-5cc87cabda6b.png)

**Comment by demolitionb** [comment]
From imagej I do not experienced flickering up to now. The zooming should be implemented in steps of course, otherwise with very fine zooming steps can indeed become a problem.

https://youtu.be/FiFwxoxOmNo?t=8m40s

Steps like 30%, 50%, 70%, 90% (in the largest dimension, so X or Y) of the screen seems reasonable for me. That would require 3 window size refreshes at maximum. Personally - but that's maybe my wish, that setting should be stored in the configuration to personalize the user experience and monitor / resolution demands. 

Another option would be to implement two zooming behaviours:
Strg&Wheel or Strg&+/- for zooming into preview with constant window size
Shift&Wheel or Shift&+/- for zooming window size and adjusting of image to new window size until maximum or mininum size is reached. Extending this zoom levels could result in same zooming as Strg+Wheel.
Step size of window (30, 50, 70, 90% setting) should be stored.

Starting with maximum size could be a solution, but I think the user experience will be unpleasant when using large screens and there will be a large preview window popping up every time.

**Comment by xupefei** [comment]
Thanks for your reply. I will take a try at changing the window's size.
However, the `Shift + Wheel` will not be added, since it is, unlike the `Ctrl + Wheel`, rarely seen in other image viewers. This cause confusion for many users.
