### ISSUE TITLE
Issue with RAR5

### ISSUE THREAD

**Issue by wloczykij69** [QL-Win/QuickLook#161]
QuickLook open RAR5 files with error and without preview.
[Screenshot](https://imgur.com/bnXCYib)

Can you fix it?

**Comment by xupefei** [comment]
QuickLook utilises [adamhathcock/sharpcompress](https://github.com/adamhathcock/sharpcompress) for viewing archive files. RAR5 is currently to-do on his list.

**Comment by emako** [comment]
Done
