### ISSUE TITLE
Feature request: Add a Chocolatey package

### ISSUE THREAD

**Issue by hsiktas** [QL-Win/QuickLook#168]
With a Chocolatey package we could install the `.msi` installer just by invoking `choco install quicklook` inside the PowerShell and updating to newer releases would also be handled by it.

More info:
https://chocolatey.org/
https://chocolatey.org/docs

**Comment by xupefei** [comment]
That looks interesting, but I do not have enough time for maintaining an extra distribution channel. I will be happy if some guy from the Chocolatey community willing to help me out.

**Comment by CSP197** [comment]
@xupefei, I'd be willing to try my hand at this :+1:

**Comment by xupefei** [comment]
I think this has been done: https://chocolatey.org/packages/quicklook

**Comment by dmonder** [comment]
Running `choco install quicklook` says it installs QuickLook but a search for quicklook.exe results in no files found. Re-running choco results in a warning that quicklook 3.7.1 is already installed.

I am running Windows 10 Enterprise LTSC Version 1809 OS build 17763.2686.
