### ISSUE TITLE
Keep windows size and position

### ISSUE THREAD

**Issue by carloda** [QL-Win/QuickLook#169]
Hello, and thanks for the excellent work. Would it be possible to implement this function?

Thanks

**Comment by xupefei** [comment]
The nightly version already include some enhancement:
Window size are preserved **when switching preview** once you have adjusted the preview size. Whereas the position are always preserved.

**Comment by carloda** [comment]
I have tested the nightly version but also it does not keep the resizing of the window in the next opening. Thank you

**Comment by xupefei** [comment]
This is intended. The window size will be kept only when switching preview. It will be reverted after closed.

cheers,
Paddy

**Comment by jjw24** [comment]
Hi @xupefei how's it going?

I understand QuickLook is to work out-of-the-box, seeing the Topmost option has been added to save and load from QuickLook.config, would you and the team consider adding the window size and position to save and load from the file as well? 

Whilst manual resizing and moving the window keeps it the same size and position through out the switching, maybe sometimes a user may want to close the window to do something else and then come back to traversing files, and may not want the window to fire up in the center of the screen blocking what's already in focus.

**Comment by superluig164** [comment]
+1 on this, I'd like to be able to move the window somewhere on the screen and always have the preview show up there (in my case, bottom right, but it should be available for anyone to change).  Perhaps another button on the title bar would suffice?

**Comment by emako** [comment]
It's challenging to accommodate the requirements of every plugin.

If there is a plan to implement it, we will reopen it.

**Comment by superluig164** [comment]
Apologies for replying to a closed topic but, how exactly does this interfere with plugins in any way?  Isn't the size and position of the window something that's common to the entire program?

**Comment by emako** [comment]
> Apologies for replying to a closed topic but, how exactly does this interfere with plugins in any way? Isn't the size and position of the window something that's common to the entire program?

 - The most suitable window size calculated by each plugin can vary greatly, which can easily lead to a poor user experience, so it can only be used as a hidden config.

 - Some other programs that implement similar functions are prone to problems when using multiple screens. We must also consider restoring them.

 - Some people also want different plugins to be displayed in different default positions.

and so on ..., it feels like there will be a lot of maintenance work.

Everyone‘s needs are different, but the current Pin function of QL is simple and easy to use, and it can meet the expectations of most people.

**Comment by superluig164** [comment]
None of these seem like roadblocks to me - if a user chooses to enable remembering the window position, then just use the user's set position.  If not, position it based on the plugin.  If the plugin doens't fit well the way the user positioned the window, they can... just resize it.  It's really not that deep.  However, it isn't my program after all, and I appreciate your insight.  Regardless I will continue to enjoy QuickLook.  Thank you for your reply.
