### ISSUE TITLE
Markdown file is not displaying

### ISSUE THREAD

**Issue by Vijay-Nirmal** [QL-Win/QuickLook#172]
.md file is not displaying

![2018-01-26_17-52-24](https://user-images.githubusercontent.com/24755596/35439714-e4ede134-02c1-11e8-856b-4b193348268b.png)

**Comment by xupefei** [comment]
Can you send me this .md file?

**Comment by Vijay-Nirmal** [comment]
Its just readme of [UWPCommunityToolkit](https://github.com/Microsoft/UWPCommunityToolkit).

If I create a .md file (using VS Code) then also it's not working.

![code_2018-01-27_19-50-21](https://user-images.githubusercontent.com/24755596/35472765-6c614a64-039b-11e8-8860-732980823556.png)

![2018-01-27_19-50-31](https://user-images.githubusercontent.com/24755596/35472767-79b2ec04-039b-11e8-80d3-bc5a819df961.png)

**Comment by emako** [comment]
This issue has expired
