### ISSUE TITLE
Possible to resize?

### ISSUE THREAD

**Issue by examinedliving** [QL-Win/QuickLook#182]
Can the window be resized?  Apart from maximizing, I don't see a way.  I tried to resize it programatically, and it worked, but then Quicklook crashed.  Is this possible already, and I'm blind?  Or could this be implemented?

**Comment by xupefei** [comment]
Sorry but I don't understand your problem. Resizing a preview window should be the same as for other windows - move your mouse to the edge, click and drag.
Hava you encountered any problems with that?

**Comment by examinedliving** [comment]
@xupefei - Exactly - that's what I can't do.  I don't get the resize 'double arrow'.  It won't change when I try and size it.  I'm running Windows 7 64 bit.

**Comment by examinedliving** [comment]
Alright - maybe I'm crazy.  It's now working, but I think there are some times that it doesn't work.  However - I couldn't recreate it, so we can close this.  I'll reopen if I can recreate and/or isolate the issue.  Thanks.  This is an awesome app.

**Comment by examinedliving** [comment]
Since this is still open, I will add to it.  I have figured out what the issue is.  It is only with Markdown files.  I cannot resize markdown files opened with quicklook horizontally.  I can resize them top to bottom, but not left to right or diagonally.

**Comment by xupefei** [comment]
I can confirm this issue. It is an [airspace issue](https://blogs.msdn.microsoft.com/dwayneneed/2013/02/26/mitigating-airspace-issues-in-wpf-applications/) brought by the embed web browser control. The same issue can also be reproduced by HtmlViewer or EmailViewer.
I do not have any idea on how to solve this easily. The hard way will be attaching four transparent windows to all edges of the preview window and response to mouse drag (Visual Studio and many custom Window frameworks are doing this right now), but it will increase the loading time overhead. I will leave this open and think more.

**Comment by examinedliving** [comment]
It appears that this now works.  Can you confirm that Microsoft has fixed this, or that it got fixed somehow?
