### ISSUE TITLE
Medical imaging file support (i.e. nifti) and .obj

### ISSUE THREAD

**Issue by braincharter** [QL-Win/QuickLook#186]
Hello,

I wondered how difficult it would be for you to port this quicklook plugin into your infrastructure http://dti-tk.sourceforge.net/pmwiki/pmwiki.php?n=QuicklookPlugin.Main

It uses the nifti opensource library for a 3-slices preview of a nifti 3D or 4D acquisition. It would be amazingly useful for the neuroscience community.

Also, do you support 3D mesh/object files as now (.obj, .ply, etc.)? On MacOS, it is supported naturally, but there is also this plugin which does a nice static preview: https://github.com/alecjacobson/MeshQuickLookPlugin

Mike

**Comment by xupefei** [comment]
I don't have any experience in such file, don't know how it looks like and how you work with it.
Can you give me some sample files, and explain to me how to view it, and what should QuickLook preview be like?

**Comment by tanguyduval** [comment]
This feature would be awesome I agree! NIFTI files are composed of a header and a N-dimensional volume. They can be loaded using  C++ library ITK NiftiImageIO.
A good display is:
![image](https://user-images.githubusercontent.com/7785316/40609899-7d98551e-6270-11e8-9bfa-01bf419561bf.png)

Meaning that you take the mid slice of the first 3D volume in three orientation (saggital, coronal; axial).
And on the bottom right you display the size of the volume, the size of the pixels, and the intensity range.

**Comment by tanguyduval** [comment]
@xupefei please find an example file attached
[VFAData.nii.gz](https://github.com/xupefei/QuickLook/files/2044861/VFAData.nii.gz)
Best

**Comment by zhenglukai** [comment]
> I don't have any experience in such file, don't know how it looks like and how you work with it.
> Can you give me some sample files, and explain to me how to view it, and what should QuickLook preview be like?

Hi Paddy, are you still working on the NIfTI plugin? If so, you may take [the macOS plugin](http://dti-tk.sourceforge.net/pmwiki/pmwiki.php?n=QuicklookPlugin.Main) and [Linux alternative](https://www.vincentkoppelmans.com/neuroscience/quick-visualization-of-nifti-images/) as references. 

I am not sure if you speak Chinese... A big 谢谢 in advance :-3

**Comment by emako** [comment]
We have no experience in working with such professional nifti images.

This requires people who know how to develop well as a QL 3rd-party plugins.
https://github.com/search?q=nifti+language%3AC%23&type=repositories

**Comment by marcoduering** [comment]
I have just released such a plugin: [MIQ](https://github.com/marcoduering/MIQ-Win) v1.0.0 | 2026-06-09

**Interactive preview of medical volume images in research formats:** 

- NIfTI-1 & NIfTI-2 `.nii`, `.nii.gz`
- FreeSurfer `.mgh`, `.mgz`
- MRtrix `.mif`, `.mif.gz`
- NRRD `.nrrd`

This is the Windows QuickLook counterpart of my [macOS Quick Look extension](https://github.com/marcoduering/MIQ). The macOS extension implements all parsers in Swift, and they have been ported to C# for the Windows plugin.

[Download Release v1.0.0](https://github.com/marcoduering/MIQ-Win/releases)

More info also on [miq-win.marco-duering.net/](http://miq-win.marco-duering.net/).
