### ISSUE TITLE
DAE (collada) file 

### ISSUE THREAD

**Issue by carloda** [QL-Win/QuickLook#187]
Hello, thanks for the great work you are doing, it would be possible to increase compatibility with the files collada (.dae) and those of indesign (.indd) Thanks.

P.S. Those illustrators function perfectly =)

**Comment by xupefei** [comment]
I am not quite sure about Collada files, but I have found [something](https://github.com/dsrbecky/ColladaDOM) that might be useful.

Support InDesign files are not possible. This file type relies heavily on Adobe InDesign application.

**Comment by carloda** [comment]
Thanks for the answer, I deal with graphics and the only thing that envy the MAC is just the quicklook but thanks to you now also exists for windows =) On mac you can see the previews of the files collada font and also indesign that's why I asked if they could be implemented.
