### ISSUE TITLE
Applying sRGB profile makes image loading slower

### ISSUE THREAD

**Issue by ashokleyland** [QL-Win/QuickLook#188]
Hi,

the new version is very slow compare to 0.3.1.
For example, it takes approximately 3sec to open a regular ios camera picture (jpg, 4032x3024, 6Mo) where 0.3.1 took less than 1sec.

Is that something you are aware ? Let me know how I can help.

Cheers

**Comment by xupefei** [comment]
The image viewer tries to load small thumbnails before loading the full image, which is fast. I guess your slowness is because your image does not contain such thumbnail.

Can you upload a photo taken by your iOS device?

**Comment by ashokleyland** [comment]
Sure. There you are.
But I don't understand why this doesn't occur with 0.3.1

![20180126_161530911_ios](https://user-images.githubusercontent.com/33458721/36422224-7640c944-163b-11e8-84dd-41a022cf0624.jpg)

**Comment by xupefei** [comment]
QL employs [exiv2.exe](http://www.exiv2.org/download.html) for getting image meta data and extracting thumbnails from version 0.3.2. Maybe it causes your slowness.
Can you try executing `...\QuickLook\QuickLook.Plugin\QuickLook.Plugin.ImageViewer\exiv2\exiv2.exe path_to_a_image.jpg` on your machine? Is it slow?

**Comment by ashokleyland** [comment]
When i execute exiv2.exe from a command prompt, it is giving me the exif data instantly

**Comment by ashokleyland** [comment]
I did some more research and it has to do with the Color profile generated by the iphone 7 because pictures taken by an earlier iphone do not cause any issue. For the ones taken with an iphone 7 : 
- either it shows a blurry picture during 3sec before displaying the right image
- either it shows the loader during 3sec

It seems that if you remove the color profile / ICC_profile from the file, the issue disappears.

**Comment by xupefei** [comment]
> it shows a blurry picture during 3sec before displaying the right image

Actually this is the correct behavior. The blurry picture is the thumbnail embed in the image file. 3sec is for loading the full image in the background.

> the issue disappears

Could you elaborate how it behaviours after you removing that line?

**Comment by ashokleyland** [comment]
Yes but 3 sec is a lot.
Anyway, if you remove the ICC profile (I did that with XNConvert), QuickLook behavior is normal and quick as it should.
Here is the picture without ICC profile 
![36422224-7640c944-163b-11e8-84dd-41a022cf0624_no icc](https://user-images.githubusercontent.com/33458721/36437187-9a18d75a-1666-11e8-84bd-b5769642fd0d.jpg)

**Comment by xupefei** [comment]
I remember that there is a way to load a JPEG or PNG faster by skipping some lines. That might be helpful to solve this issue. I'll add this to the further work.
