### ISSUE TITLE
Does not work on remote desktop environments

### ISSUE THREAD

**Issue by maylom** [QL-Win/QuickLook#196]

**Comment by xupefei** [comment]
QuickLook should work once it has been installed on the server. Can you elaborate your scenario?

**Comment by xupefei** [comment]
Seems an issue with the named pipe. 

> this works for the first user, any "later" users will get an errormessage.
During the later run, is QL still running for the first user?

It would be nice if you can try the follows:
1) Run QL for the first user;
2) **Switch** to the second user, run QL again. Does it crash?
3) Quit QL for the first user, then run it for the first user again;
4) **Logout** the first user, log in the second user and run QL. Does it crash?

**Comment by RomanGross** [comment]
it is like you expected

Run QL for the first user; --> done
Switch to the second user, run QL again. Does it crash? --> yes

when the first user quit QL the second one can start it - it runs like a charm.
then it crashes when the first user start QL again.

Eventlog:

_Anwendung: QuickLook.exe
Frameworkversion: v4.0.30319
Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
Ausnahmeinformationen: System.UnauthorizedAccessException
   bei System.IO.__Error.WinIOError(Int32, System.String)
   bei System.IO.Pipes.NamedPipeServerStream.Create(System.String, System.IO.Pipes.PipeDirection, Int32, System.IO.Pipes.PipeTransmissionMode, System.IO.Pipes.PipeOptions, Int32, Int32, System.IO.Pipes.PipeAccessRights, SECURITY_ATTRIBUTES)
   bei System.IO.Pipes.NamedPipeServerStream..ctor(System.String, System.IO.Pipes.PipeDirection, Int32, System.IO.Pipes.PipeTransmissionMode, System.IO.Pipes.PipeOptions, Int32, Int32, System.IO.Pipes.PipeSecurity, System.IO.HandleInheritability, System.IO.Pipes.PipeAccessRights)
   bei System.IO.Pipes.NamedPipeServerStream..ctor(System.String, System.IO.Pipes.PipeDirection)
   bei QuickLook.PipeServerManager..ctor()
   bei QuickLook.PipeServerManager.GetInstance()
   bei QuickLook.App.Application_Startup(System.Object, System.Windows.StartupEventArgs)
   bei System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
   bei System.Windows.Application.<.ctor>b__1_0(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
   bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   bei MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   bei System.Windows.Threading.DispatcherOperation.Invoke()
   bei System.Windows.Threading.Dispatcher.ProcessQueue()
   bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   bei System.Windows.Application.RunDispatcher(System.Object)
   bei System.Windows.Application.RunInternal(System.Windows.Window)
   bei QuickLook.App.Main()_

followed by:
_Name der fehlerhaften Anwendung: QuickLook.exe, Version: 0.3.5.0, Zeitstempel: 0x5a9eded8
Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.14393.2363, Zeitstempel: 0x5b31ad75
Ausnahmecode: 0xe0434352
Fehleroffset: 0x0000000000033c58
ID des fehlerhaften Prozesses: 0x4b80
Startzeit der fehlerhaften Anwendung: 0x01d428db8fba5fcf
Pfad der fehlerhaften Anwendung: HDD:\Path\to\QuickLook\QuickLook.exe
Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
Berichtskennung: 5aec41f0-f291-4248-af13-ca76716f52fc
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:_

**Comment by xupefei** [comment]
Good to hear that. When the first user runs QL, it registers a named pipe to the system. Then, QL for the second user tries to register another pipe, but a pipe with the same name is already there.

The fix should be easy: attach a unique identifier to each user's pipe so that their names become different.

I will fix it soon.

**Comment by RomanGross** [comment]
thanks a lot!

**Comment by xupefei** [comment]
Can you try the new version at https://ci.appveyor.com/project/xupefei/quicklook/build/511/artifacts?

**Comment by RomanGross** [comment]
it works! :)
