### ISSUE TITLE
预览office文件时无法看清楚文字内容

### ISSUE THREAD

**Issue by komazhou** [QL-Win/QuickLook#198]
Windows 10 秋季版，安装UWP v0.3.4版本
空格键打开word、excel等office文件，只要quicklook预览窗口底部的程序窗口是白色，就完全看不清楚office文件的内容，移动quicklook预览窗口到深色背景的程序窗口上方，在深色部分可以看清楚文字。
请问是我电脑的问题还是需要什么其他的设置，我在quicklook里面没有找到设置的选项

**Comment by xupefei** [comment]
#139也报告过类似问题，但我这里无法复现。
能否告知你的 Office 版本号和显卡型号/显卡驱动版本？

**Comment by komazhou** [comment]
我在家里面的笔记本电脑和公司的台式机上都出现这个情况，应该跟电脑配置无关，两台电脑所使用的office版本都一样，都是office professional plus 2010，word版本14.0.4760.1000（32位）

**Comment by razgrizdemon** [comment]
win10下uwp和msi都是这种情况，win7下正常，同样office professional plus 2010

**Comment by xupefei** [comment]
这似乎是 Office 2010 的 bug。等我再确认一下。
