### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by SeanRao** [QL-Win/QuickLook#201]
建议在对文件夹进行空格预览时显示的不是文件夹属性，而是修改为显示文件夹内的文件列表。通过对文件夹进行空格预览其中的文件，而不需要打开文件夹，特别是在文件夹内嵌套有多层文件夹时，这个功能对于预览文件夹内的内容将会相当的方便。

**Comment by xupefei** [comment]
我以前也想过这个：左侧是一个列表，显示文件夹下的文件，右侧是选中文件的预览。
不过我近期空闲时间很少，最近是不会有时间搞这个了。

**Comment by licovery** [comment]
强烈建议可以预览文件夹里面的内容，然后支持树状展开文件夹，可以双击打开，那就完美了。感觉可以完全摆脱资源管理器了，不需要开一大堆窗口。

**Comment by emako** [comment]
1. 文件夹后续开发独立的内置插件，但功能不会有多强大
2. 建议在对文件夹进行空格预览时显示的不是文件夹属性，而是修改为显示文件夹内的文件列表 -> 目前还是参考 macOS 的实现，暂不考虑
