### ISSUE TITLE
Affinity Designer previews looking weird

### ISSUE THREAD

**Issue by levrik** [QL-Win/QuickLook#202]
![image](https://user-images.githubusercontent.com/9491603/37258248-46b24f88-2575-11e8-833e-685a77171651.png)

On the right the preview showed by the Windows Explorer in the preview pane.

**Comment by xupefei** [comment]
Well, as QuickLook is basically just using file thumbnails provided by Windows. Can you share this file with me?

**Comment by levrik** [comment]
@xupefei No, sorry. Also you would need to own a copy of Affinity Designer.

**Comment by emako** [comment]
Thumbnails are built via the system or Affinity Designer, not QL generated
