### ISSUE TITLE
Problems in .ico files / ico文件预览问题

### ISSUE THREAD

**Issue by the1812** [QL-Win/QuickLook#204]
`.ico` files couldn't be correctly rendered. / `.ico` 文件无法正确地渲染.

**Screenshots**
![image](https://user-images.githubusercontent.com/26504152/37265576-4009e1ee-25ef-11e8-955b-31afd82e0b4a.png)
![image](https://user-images.githubusercontent.com/26504152/37265593-56cc33fa-25ef-11e8-93d2-dd6c2e8b5355.png)

**Comment by xupefei** [comment]
可否给个ico文件？

**Comment by the1812** [comment]
[Icons.zip](https://github.com/xupefei/QuickLook/files/1805465/Icons.zip)
这是上图使用的两个图标

**Comment by emako** [comment]
目前最新nightly build版本未发现问题
