### ISSUE TITLE
Powerpoint Preview not working

### ISSUE THREAD

**Issue by cadu022** [QL-Win/QuickLook#205]
Powerpoint preview since update not working: Most of the texts and images on each slide are washed out / hidden / deleted

**Screenshots:**
![unbenannt](https://user-images.githubusercontent.com/37367427/37397306-8fb3df00-277b-11e8-88f4-6b0f5435fc83.PNG)
![image](https://user-images.githubusercontent.com/37367427/37397383-bf6c626c-277b-11e8-9d19-98002d6476bb.png)

**Comment by xupefei** [comment]
Are you using Office 2010?

**Comment by cadu022** [comment]
No, office 2016

 

Von: Paddy Xu <notifications@github.com> 
Gesendet: Samstag, 24. März 2018 10:17
An: xupefei/QuickLook <QuickLook@noreply.github.com>
Cc: cadu022 <cadu22@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [xupefei/QuickLook] Powerpoint Preview not working (#205)

 

Are you using Office 2010?

**Comment by dorlyneto** [comment]
I have the same problem and I'm using Office 2010!

**Comment by rabelux** [comment]
As this issue is quite old I'm closing it. If anyone still has problems with powerpoint chime in on #888.
