### ISSUE TITLE
Total Commander and Q-Dir support, please

### ISSUE THREAD

**Issue by Dunkelicht** [QL-Win/QuickLook#210]
Thank you about for offering such good software. 
It is nice that Quicklook is working well in Everything. Actually Everything also has the function preview by click (Alt + P). Author of Everything is nice. I think you may contact him about preview function.

Total Commander from: https://www.ghisler.com/ 
Q-Dir : https://www.softwareok.com/?seite=Freeware/Q-Dir 

These two software are very welcomed and widely used, please consider to support them. 
I know it is not easy, as they all are not open-sourced software.
Please tell me about the possibility, because of QuickLook I am now learning C# and hope to make enhancement.
Thank you.

**Comment by xupefei** [comment]
The integration with Total Commander is mentioned here: https://github.com/xupefei/QuickLook/wiki/File-Managers.
For Q-Dir, there is, unfortunately, no way to integrate.

**Comment by Dunkelicht** [comment]
Thank you for reply,  

I will try to do something good and contribute to this. 

This issue could be closed by now.
