### ISSUE TITLE
"Fluent" design transparency sometimes makes text unreadable

### ISSUE THREAD

**Issue by Darthagnon** [QL-Win/QuickLook#214]
When previewing a text-containing document, the "Fluent" transparency meant that we could see the lighter elements of our desktop wallpaper through the preview. The text was consequently unreadable. NB we were using the Windows Store version at the time. Would it be possible to add a config option to disable the Fluent design feature?

**Comment by xupefei** [comment]
How light is it? Can you provide a screenshot?

**Comment by Darthagnon** [comment]
Apologies for my delayed reply; did a bit more research and found the following:
1) *.txt files render fine; previewing is always legible
2) *.docx files (and most likely any other files that share the same preview rendering mode) render with Fluent transparency that makes text illegible on light backgrounds.

Screenshots attached :)
![sketch](https://user-images.githubusercontent.com/20792748/38177291-f8acd97e-35f6-11e8-8043-6ce901c5f15c.png)
![sketch1](https://user-images.githubusercontent.com/20792748/38177292-f8cabc96-35f6-11e8-949c-13a165600162.png)
![quicklook 26_03_2018 09_37_05](https://user-images.githubusercontent.com/20792748/38177293-f8e00ace-35f6-11e8-94ea-6bcb009aecba.png)
