### ISSUE TITLE
导致休眠无法唤醒的BUG

### ISSUE THREAD

**Issue by Jack-ban** [QL-Win/QuickLook#222]
**简述**
我使用的版本是UWP版本，出现的问题是程序运行在后台的情况下直接盖上笔记本进入睡眠状态，再打开的时候会无法唤醒导致重启。
**漏洞复现**
我平常的使用习惯是晚上结束工作后不会关闭电脑，而是盖上电脑使其进入睡眠状态，等第二天早上要用再开启唤醒，这样能直接进入昨天的工作。开始正常，之后出现无法唤醒重启的时候，我并没有想到是这款软件的问题。
**粗略分析推测**
昨天早上又一次出现这个问题，我特意去分析了内存转储dump文件。由于是网上的windbg教程现学现卖的，不一定准确。但！process执行结果显示，导致ntkrnlmp.exe奔溃的程序指向了quicklook.exe。
出于谨慎考虑，我关闭了quicklook并像往常一样盖上笔记本使其进入睡眠状态，试验了两次都没有出现无法唤醒的问题，第一次是2-3小时，第二次是一个晚上。
**总结**
综上所述，应该是软件bug，希望开发者尽快排查修复一下。
软件商店上的低分是为了引起你的注意，修复后会及时更改评分，还望谅解。
**小小建议**
顺带提一句，虽然是小工具，但是功能实现来讲很完美，还原了mac上的使用体验。其实你既然上架了商店，可以考虑付费的。至少10-20块关紧，我都会接受的。不过最好是买断制，本人对于订阅制不感冒。如果有打算扩展功能可以大版本更新重新付费。小小建议，如果觉得有些冒犯了你，还望见谅。

**Comment by xupefei** [comment]
QL不进入内核，不可能造成内核崩溃的。

应该是你电脑里其他什么东西加载了驱动，这个驱动把内存分配搞坏，正好搞到了QL的内存区域。就算你退了QL，如果这驱动动到了其他程序的内存，你会看到了其他程序造成崩溃。

Cheers,
Paddy

**Comment by Jack-ban** [comment]
那好，我再试试吧！看看明天早上还会不会出现崩溃。明天给你答案。
打扰了。。。。

**Comment by emako** [comment]
问题久远未回应，关闭
