### ISSUE TITLE
在任意程序ctrl+o打开窗口预览会造成假死

### ISSUE THREAD

**Issue by Marsbee** [QL-Win/QuickLook#223]
打开窗口开着的时候， 按空格键预览会毫无反应，不论在任何位置。

**Comment by xupefei** [comment]
每当这个时候，打开文件窗口是不是有焦点的？
cheers,
Paddy

**Comment by Marsbee** [comment]
破案了，是listary和quicklook不兼容，在关闭listary之后，quicklook可以在ctrl+o内正常预览。

**Comment by xupefei** [comment]
QL 的设置是在有 Listary 工具栏显示的时候不预览。这是为了解决在Listary搜索框里敲空格时的冲突问题。

cheers,
Paddy

**Comment by Marsbee** [comment]
但listary在ctrl+o窗口内要触发，必须按激活快捷键，或者点一下搜索框才可以正确触发。所以QL的设置可以取消吧？

**Comment by xupefei** [comment]
Listary 不捕获焦点，造成 QL 无法判断当前是否正在输入。换句话说，QL不能判断用户有没有“按激活快捷键，或者点一下搜索框”。唯一的解决办法是有Listary 显示时直接不预览。
