### ISSUE TITLE
预览xls文件时弹出“不能预览”的错误消息

### ISSUE THREAD

**Issue by PureTeufel** [QL-Win/QuickLook#225]
才使用您的软件没几天，今天在预览一个xls文件时，出现了下图的错误消息提示。
![snipaste_2018-04-20_15-57-19](https://user-images.githubusercontent.com/26618621/39037992-c9c9208c-44b4-11e8-96ec-b1aa51da2270.png)

**Comment by xupefei** [comment]
`C:\Users\your_name\AppData\Roaming\pooi.moe\QuickLook\`下应该有个`QuickLook.Exception.log`，把里面最新的异常信息贴上来？

**Comment by PureTeufel** [comment]
![image](https://user-images.githubusercontent.com/26618621/39080790-1cdc93d6-4568-11e8-9c77-a5b38493e9d6.png)

**Comment by SeanYuXuan** [comment]
Hi，我也遇到了相同的问题。
[https://i.loli.net/2018/06/08/5b1a334e8d54e.png](url)
