### ISSUE TITLE
4K H265 video is not playing

### ISSUE THREAD

**Issue by dearanswer** [QL-Win/QuickLook#226]
链接: https://pan.baidu.com/s/1D9Jn1bcfUkUs0poDb9dJQw 密码: zmjz
以上测试视频

**Comment by xupefei** [comment]
4K 播放是已知问题。
VLC 3.0 版本支持了 H265 的播放，但是 QL 用的 MetaVLC 目前不支持 VLC3.0：https://github.com/higankanshi/Meta.Vlc/issues/250

**Comment by Rictusempra** [comment]
@xupefei 然而依旧是一样的丑 UX细节依旧不如很多个人作品 依旧明显I/O高占

**Comment by xupefei** [comment]
Fixed in 10460da435f53acdbafdf56add11c0a810a71454.
