### ISSUE TITLE
Preview README.md if the directory include sub-directory named `.git`.

### ISSUE THREAD

**Issue by Cologler** [QL-Win/QuickLook#229]
如果一个目录包含以下子目录，说明它是被版本管理目录：

* `.svn`
* `.git`

如果这个目录还包含以下文件：

* `README.md`
* `README.rst`

之类的文件，则显示这些文件（而不是计算目录中文件的大小）。

**Comment by xupefei** [comment]
I agree. This will surly be useful.

Cheers,
Paddy
