### ISSUE TITLE
a tiny personal desire

### ISSUE THREAD

**Issue by DuckHK** [QL-Win/QuickLook#231]
Can you please add a setting option that allows the software to hide its icon from the notification area? Personally, I like my notification area as clean as possible. So the less icons, the better, not that I don't want to see your very useful tool there.
Many thanks to you!

**Comment by xupefei** [comment]
Unfortunately no. The taskbar icon is the only way to quit QuickLook.
You can modify the source code if you want. Just comment out this line:
https://github.com/xupefei/QuickLook/blob/master/QuickLook/App.xaml.cs#L106

**Comment by DuckHK** [comment]
Got it! Thank you very much :)
Love what you’ve done with Quicklook, hope things are going well with the MS office files preview.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: Paddy Xu <notifications@github.com>
发送时间: Saturday, May 5, 2018 12:53:17 AM
收件人: xupefei/QuickLook
抄送: DuckHK; Author
主题: Re: [xupefei/QuickLook] a tiny personal desire (#231)


Unfortunately no. The taskbar icon is the only way to quit QuickLook.
You can modify the source code if you want. Just comment out this line:
https://github.com/xupefei/QuickLook/blob/master/QuickLook/App.xaml.cs#L106

―

**Comment by DuckHK** [comment]
Hi Xu, it’s me writing about the tray icon of quicklook again.
Sorry to bother you but I have tried to compile the source code with VS2017 but it constantly warned me that there were all kinds of GitVersion.CS file missing. For your information, I even installed the wix toolset extension for the .wixproj project.
I’m no expert in coding so I am truly looking forward to your instruction. But please feel free to ignore me, of course.
Thank you!
在 2018年5月5日，00:53，Paddy Xu <notifications@github.com<mailto:notifications@github.com>> 写道：


Unfortunately no. The taskbar icon is the only way to quit QuickLook.
You can modify the source code if you want. Just comment out this line:
https://github.com/xupefei/QuickLook/blob/master/QuickLook/App.xaml.cs#L106

**Comment by xupefei** [comment]
Well, you need to do two things.
1. Have Git in your $PATH (basically, you need to install Git).
2. Allow local PowerShell scripts: https://www.tenforums.com/tutorials/54585-change-powershell-script-execution-policy-windows-10-a.html

Everything should be fine after doing these.

**Comment by xupefei** [comment]
Solved in https://github.com/QL-Win/QuickLook/issues/729.
