### ISSUE TITLE
希望可以添加隐藏右下角图标的选项，或者直接干掉图标。

### ISSUE THREAD

**Issue by Wangfashuai** [QL-Win/QuickLook#238]
我用的是win10 商店版本的，感觉软件很不错，就是右下角的有图标有点强迫症，如果可以话加个右下角图标显示不显示的功能。

**Comment by CyshallChan** [comment]
可以尝试“PSTrayFactory”这款软件隐藏托盘图标。

**Comment by Wangfashuai** [comment]
OK，我看看。

**Comment by cathaysia** [comment]
emm，两年了，我也希望能隐藏托盘栏。反正重启可以用任务管理器

**Comment by Geeyun-JY3** [comment]
[3.6.10](https://github.com/QL-Win/QuickLook/releases/tag/3.6.10) 已实现。见 #729

@xupefei 你好像漏了关这个🤣
