### ISSUE TITLE
无法预览任何格式的图片

### ISSUE THREAD

**Issue by godwings** [QL-Win/QuickLook#243]
系统版本为 1803 (17134.48)

**Comment by xupefei** [comment]
Please try to report a problem as presise as possible. What version does
your QL have and what's the error?

**Comment by godwings** [comment]
- 软件版本
v0.3.5

- 具体情况
打开任何图片都是窗口一闪而过，然后就弹出failed to preview的通知

- log
> System.TypeInitializationException: “NativeMagickSettings”的类型初始值设定项引发异常。 ---> System.TypeInitializationException: “X64”的类型初始值设定项引发异常。 ---> System.DllNotFoundException: 无法加载 DLL“Magick.NET-Q8-x64.Native.dll”: 找不到指定的模块。 (异常来自 HRESULT:0x8007007E)。
   在 ImageMagick.Environment.NativeMethods.X64.Environment_SetEnv(IntPtr name, IntPtr value)
   在 ImageMagick.Environment.NativeEnvironment.SetEnv(String name, String value)
   在 ImageMagick.MagickNET.InitializePrivate(ConfigurationFiles configFiles, String newPath)
   在 ImageMagick.Environment.NativeMethods.X64..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 ImageMagick.Environment.NativeMethods.X64.Environment_Initialize()
   在 ImageMagick.Environment.Initialize()
   在 ImageMagick.MagickSettings.NativeMagickSettings..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 ImageMagick.MagickSettings.NativeMagickSettings..ctor()
   在 ImageMagick.MagickSettings..ctor()
   在 ImageMagick.MagickImage..ctor()
   在 QuickLook.Plugin.ImageViewer.AnimatedImage.ImageMagickProvider.GetAnimator(ObjectAnimationUsingKeyFrames animator, String path)
   在 QuickLook.Plugin.ImageViewer.AnimatedImage.AnimatedImage.LoadFullImageCore(Uri path)
   在 QuickLook.Plugin.ImageViewer.AnimatedImage.AnimatedImage.LoadFullImage(DependencyObject obj, DependencyPropertyChangedEventArgs ev)
   在 QuickLook.Plugin.ImageViewer.AnimatedImage.AnimatedImage.LoadImage(DependencyObject obj, DependencyPropertyChangedEventArgs ev)
   在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   在 System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   在 System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   在 System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   在 MS.Internal.Data.ClrBindingWorker.NewValueAvailable(Boolean dependencySourcesChanged, Boolean initialValue, Boolean isASubPropertyChange)
   在 MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   在 MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   在 System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   在 System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   在 QuickLook.Plugin.ImageViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__0()

**Comment by godwings** [comment]
不管是将 Magick.NET-Q8-x64.Native.dll 放到 Quicklook.exe 的同级目录下 还是 \QuickLook.Plugin\QuickLook.Plugin.ImageViewer\ 下都不行

**Comment by xupefei** [comment]
删除C:\Users\username\AppData\Local\Temp\下的Magick.NET.???文件夹试试看。

**Comment by godwings** [comment]
然而那个目录下没有这个文件夹

**Comment by xupefei** [comment]
这个文件夹是图片预览组件的临时目录。如果在你的机器上没有，那你只能自己看看是不是被什么软件拦截了。

**Comment by godwings** [comment]
好吧，那我看看杀毒软件之类的东西...不过估计是找不到的
