### ISSUE TITLE
RW2 Picture format not correctly supported

### ISSUE THREAD

**Issue by Sandros94** [QL-Win/QuickLook#252]
Panasonic RAW picture format is not correctly supported. When previewing a RW2 file it gets the right gamma but it has a green tint on it.

Windows 10 Pro 1803
v0.3.5 (UWP) Windows Store

**Comment by xupefei** [comment]
Test file please?

**Comment by Sandros94** [comment]
Sure, here it is. [https://drive.google.com/file/d/1Ke2Gd1v0_duaoEPHVlIoHStSoQeyMKFl/view?usp=sharing](url)

**Comment by pascalllc** [comment]
Same issue with Canon CR2 raw file. When you hit space bar, the file open with the correct colors and no scroll bar but after a few seconds the picture is gets a green tint and the windows have vertical and horizontal scroll bars that appear. I have tried opening raw files from the 200D and the 77D
