### ISSUE TITLE
Can't preview .mov (Prores)

### ISSUE THREAD

**Issue by lehtiniemi** [QL-Win/QuickLook#254]
**Is your feature request related to a problem? Please describe.**
When I hit SPACE on a .mov-file (ProRes-format from Blackmagic Pocket Cinema Camera), nothing happens. It should open in QuickLook like any other video file.

**Describe the solution you'd like**
I wish QuickLook was able to preview .mov-files as well (ProRes).

**Describe alternatives you've considered**
I can always open these files with Quicktime, even Windows' own player don't open them (oddly, Seer does though), but that's not quick at all.

**Additional context**
Seer is able to preview ProRes .mov-files so it seems to be technically possible.

**Comment by noquierouser** [comment]
Is VLC able to see those files?

**Comment by lehtiniemi** [comment]
Hmm, suddenly they work. I don't know if it was a human error or related to that I installed VLC but problem solved. Thank you!
