### ISSUE TITLE
QuickLook无法预览文件，显示区域一片空白

### ISSUE THREAD

**Issue by holdenxie** [QL-Win/QuickLook#255]
从两天前开始，QuickLook无论是.msi版/ 商店版都无法预览文件，只会显示毛玻璃背景。但可以正确识别文件类型、打开合适大小的窗口，可以打开Office文件，但工具栏无法渲染。

**系统环境**
- OS Version: Windows 10 Enterprise 1803
- QuickLook Version: 0.3.5(UWP) / 0.3.5 (.msi)

**截图**
![image](https://user-images.githubusercontent.com/34213478/41510456-8924363c-7297-11e8-91f0-8146134cfef4.png)
无法预览大部分文件
![image](https://user-images.githubusercontent.com/34213478/41510469-c64a1fb8-7297-11e8-8cd4-10075720155e.png)
可以预览Office文件，但是工具栏无法显示

**Comment by xupefei** [comment]
更新显卡驱动试试？

Cheers,
Paddy

**Comment by Miosolo** [comment]
已经更新了驱动，问题依旧

**Comment by Miosolo** [comment]
经过确认，原因是目前的1803系统和Intel核显驱动不兼容，已经回滚，问题解决

**Comment by OnionRun** [comment]
1903系统貌似又出现了这个问题...
