### ISSUE TITLE
Use UWP WebView to display webpages

### ISSUE THREAD

**Issue by n-gao** [QL-Win/QuickLook#258]
Consider using the UWP WebView to display webpages available through the Windows Community Toolkit. https://docs.microsoft.com/en-us/windows/uwp/xaml-platform/xaml-host-controls

**Comment by xupefei** [comment]
🚫 Controls properly responding to changes in DPI and scale.
🚫 Adding a WebView control to a custom user control, (Either on-thread, off-thread, or out of proc).

Seems not very useful yet.
