### ISSUE TITLE
Set window background fully transparent when it is necessary

### ISSUE THREAD

**Issue by FuweiChin** [QL-Win/QuickLook#262]
When using QuickLook to preview transparent PNG files, background of the window gets black. That's a little bit, you see, weird.

I want QuickLook window background to be fully transparent when it is necessary. e.g. previewing images with alpha-channel.

There is an example about how to set window background transparent in WinForms, see [
C# Ui Academy - Fully Transparent Background in Winform App C#](https://www.youtube.com/watch?v=BmuS-XGP120)

If controversial, this feature can be added as  an option in settings/preferences.

**Comment by xupefei** [comment]
The latest Nightly version have a switch to change the colour of window
background. Try it out!
