### ISSUE TITLE
Stretches some vertical videos 

### ISSUE THREAD

**Issue by fabiotp91** [QL-Win/QuickLook#263]
**Describe the bug**
When I try to preview some vertical videos it stretches them, I have seen that it only happens to videos that have the width and height switched for some reason, but VLC still opens them correctly.
I have attached a screenshot to show what happens.

**To Reproduce**
1. Select Vertical Video
2. Press Space
3. See Vertical Video Streched

**Expected behavior**
The video should show vertically like it shows in VLC Player.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
![nvidia share_2018-06-23_16-55-44](https://user-images.githubusercontent.com/2072484/41811376-565e65f6-7706-11e8-9c2b-d3c0023ad1b2.png)

**Comment by xupefei** [comment]
Can you provide a sample file?

**Comment by fabiotp91** [comment]
Here's a Drive Link with some videos that I have at the moment on my PC that do that.
Some where recorded with a Samsung Galaxy s7 and a Huawei P8 I think.

https://drive.google.com/drive/folders/1ZoR67SuY7_m8y1hSHNFvMVrIC6lLt40s?usp=sharing
