### ISSUE TITLE
Show small png files on 100% , don't them scale up.

### ISSUE THREAD

**Issue by adms-hu** [QL-Win/QuickLook#276]
**Is your feature request related to a problem? Please describe.**
When I inspecting my UI or webdesign PNG assets I'd like to see them on their 100% pixel perfect view to see everything is correct.

**Describe the solution you'd like**
With ctrl+mousewheel I can scale it up If I want, but the default size should be at 100% scale. If the object larger than the default quicklook window, it shouldn't be at 100% of course and it has to be remain how it was before.

**Comment by emako** [comment]
Outdated issue.

Do it double click
