### ISSUE TITLE
using space bar in explorer opens search tools

### ISSUE THREAD

**Issue by derridadada** [QL-Win/QuickLook#277]
Hi,
My apologies if this is an issue that's already been addressed, but I could not find a solution after extensive searches. Quicklook works great for me in combo with Dopus, but every time I try to use it in Windows Explorer, the space bar just opens up search tools. I've no clue why, since I have not set any keyboard shortcuts, and there's nothing associated with it, at least as far as I can tell. Any suggestions? (working in win 10 pro).

**Comment by xupefei** [comment]
See https://github.com/xupefei/QuickLook/issues/107 <https://github.com/xupefei/QuickLook/issues/107>.

Cheers,
Paddy
