### ISSUE TITLE
Crash when opening .html file

### ISSUE THREAD

**Issue by trungdoan2507** [QL-Win/QuickLook#281]
**Expected behavior**
QuickLook crashed when opening this .html file: https://yadi.sk/d/1ISJRPHu3YbboF
**Desktop (please complete the following information):**
 - OS Version: Windows 10 Insider Preview 17704.1000
 - QuickLook Version: 0.3.5-43-g8cd957d from AppVeyor

**Comment by xupefei** [comment]
Seems the WebBrowser control provided by Microsoft has crashed. No fix unless QL switches to WebKit HTML viewer. However, it will add about 120MB to the install size.
