### ISSUE TITLE
View STL 3D Forms

### ISSUE THREAD

**Issue by jvegaf** [QL-Win/QuickLook#282]
It's would be great can do a preview of a STL files. Thanks

**Comment by jeremyhart** [comment]
@jvegaf I have just uploaded a beta 3D viewer plugin: https://github.com/jeremyhart/QuickLook.Plugin.HelixViewer

It can load .stl, .obj, .3ds, .lwo & .ply

It is very much in beta so I would appreciate any feedback before I submit a pull request here.

**Comment by jvegaf** [comment]
how can instalm the beta ? i want be a beta tester 😋

**Comment by jeremyhart** [comment]
Follow the instructions on the read me in the repo of the link and please leave feedback.

**Comment by ArtanisLovesZeratul** [comment]
> @jvegaf I have just uploaded a beta 3D viewer plugin: https://github.com/jeremyhart/QuickLook.Plugin.HelixViewer
> It can load .stl, .obj, .3ds, .lwo & .ply
> It is very much in beta so I would appreciate any feedback before I submit a pull request here.

It would be greater to do a previewer of .stp/step files.😋
Can you update it?  Thanks

**Comment by jeremyhart** [comment]
Yeah, that would be very beneficial for me too, I can't find a suitable library to use for these file formats. If you can find my something that would work, I would gladly integrate it.

**Comment by olofolshall** [comment]
Any progress on this? Would still be an amazing feature.
