### ISSUE TITLE
Icon DPI, button cursors, image canvas

### ISSUE THREAD

**Issue by justrealmilk** [QL-Win/QuickLook#286]
Hey! So this is all very awesome but...

- As a Surface Pro 2 owner, I love the HiDPI consideration, but I do all my work on $100 displays leaving icons a little burry. Assets for both targets?
- The button cursors leave me feeling like I'm on a web page instead of using a native app, and as this is a native app, it detracts negatively from an awesome experience. Not super significant but it's feedback.
- When previewing icons of all things, that have alpha transparency but are otherwise #000000 black, it's difficult to see them. Could you use a canvas that's closer to 50/50 grey?

Thanks!

**Comment by xupefei** [comment]
1. Can you provide a screen capture?
2. Well, that is intended. It's hard (at least) to me to find whether I have moved the mouse to the button without any significant visual change.
3. The newest Nightly version has a switch controlling the colour of the background. Have a try!
