### ISSUE TITLE
预览的文件列表里如果有Excel文件，焦点会丢失，无法通过键盘箭头按键前往下一个文件

### ISSUE THREAD

**Issue by IceWeet** [QL-Win/QuickLook#291]
*You can use either Chinese or English when filling this issue. 你可以使用中文或英语填写以下问题。*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in `C:\Users\username\AppData\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log`

**Comment by xupefei** [comment]
没办法，这是因为微软提供的Excel预览组建过于垃圾。
