### ISSUE TITLE
Unable to move/delete/rename text file after being loaded at QuickLook

### ISSUE THREAD

**Issue by supermartzin** [QL-Win/QuickLook#295]
**Describe the bug**
When I try to open a text file in QuickLook by pressing the space button and then I close it, I can't move/delete/rename the file because I get the 'File is use' error. After exiting the QuickLook, everything works fine.
The file is not being opened by other program that could block these operations. So far it happened only with text files, not with other types.

**To Reproduce**
Not sure if you can reproduce it every time, but try this
1. Create a basic text file and fill it with some text.
2. Now open it with QuickLook by pressing the space.
3. Try to switch to fullscreen.
4. Close the QuickLook by clicking on the close button.
5. Now try to move/rename/delete the file, it should raise an error about the file being opened in System.

**Expected behavior**
After closing the QuickLook it should not block me working with the file.

**Desktop information:**
 - OS Version: Windows 10 April Update (build no. 17134.165)
 - QuickLook Version: 0.3.5 UWP from Microsoft Store

**Screenshots and Exception Log**
No exception log found.
Screenshot of the error I'm getting when trying to delete the file:
![Deleting the file](https://image.ibb.co/hvywST/quick_look_block.png)

**Comment by xupefei** [comment]
It seems like a bug in the Windows UWP framework since it shows the file is using by `System`, instead of `QuickLook`. Can you try using the .msi or .zip Nightly version for a few days?

**Comment by supermartzin** [comment]
Yes, sure. I'll let you know if the same error occurs.

**Comment by weigaow** [comment]
The same problem I met with UWP version. @xupefei
