### ISSUE TITLE
Windows 10, cannot toggle a quickLook on desktop.

### ISSUE THREAD

**Issue by pharazone** [QL-Win/QuickLook#299]
*You can use either Chinese or English when filling this issue. 你可以使用中文或英语填写以下问题。*

**Describe the bug**
Windows 10, cannot toggle a quickLook on desktop.

**To Reproduce**
1. Go to Desktop
2. Find a file or a folder.
2. Click SPACE.
3. And.....It didnt work.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.5 from Windows Store and Git release]

**Comment by TheStruggleForAntiSpaghetti** [comment]
I just tested with several files and here it works.
Could you possibly have another application that conflicts with it? You can
start to try to close all apps from the system tray, etc.

OS Version: Windows 10 1803 x64
QuickLook Version: 0.3.5 GitHub.

**Comment by pharazone** [comment]
I just try it as you say, and it didnt work as before.

**Comment by emako** [comment]
The question is old. If you have any questions, please continue to reply.
