### ISSUE TITLE
无法预览 .ppt/.pptx 文件？

### ISSUE THREAD

**Issue by ZaiDAP** [QL-Win/QuickLook#301]
**Describe the bug**
无法预览 .ppt/.pptx 文件，使用 Office 365 ，按空格后一直是加载中并且无法关闭，只能从任务管理器结束任务/进程

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803
 - QuickLook Version: 0.3.5 from Windows Store

**Screenshots and Exception Log**
![tim 20180725111924](https://user-images.githubusercontent.com/41657393/43177815-b51b859c-8ffc-11e8-8412-e974b99bb27a.jpg)

**Comment by Roger-WIN** [comment]
I didn't meet the same problem. Maybe you could try to reset the app.
I'm also running the Store version of QuickLook 0.3.5 on Windows 10 Version 1803.
Besides, I'm also an Office 365 subscriber.

![2018-07-31_21-21-47](https://user-images.githubusercontent.com/25821208/43462174-f8cf117c-9507-11e8-8586-05376a757b96.png)
