### ISSUE TITLE
Microsoft office files preview support

### ISSUE THREAD

**Issue by foguetes** [QL-Win/QuickLook#302]
Quick look is much better than Seer in many respects. I just wish I was able to preview word documents and excel sheets like I am using Seer.

**Comment by Kenya-West** [comment]
QuickLook is already can preview any of Office documents (Word, Excel and Powerpoint) if user has Office installed.
What is different from Seer experience? Can you provide some screenshots? I am not familiar with that app.

**Comment by foguetes** [comment]
I have office365 installed. When I open QuickLook on a .doc or .docx file this is what I get: 

![image](https://user-images.githubusercontent.com/25814516/43266451-bdd341e4-90eb-11e8-863b-d75c9b376334.png)


Using Seer I get an actual preview of the document's content, as if I opened it with Word like shown here: 

![image](https://store-images.s-microsoft.com/image/apps.37446.14248499545339565.3c0cd682-c071-44e6-9553-319151e40384.7c4d0431-5d0e-45ac-ba19-8ab4bdea44bf?w=1399&h=876&q=60)

I'm using the latest version of windows 10 and QuickLook v0.3.5

**Comment by Kenya-West** [comment]
Well, something is wrong... Have you installed the app through Microsoft Store?

My case is:
1. I installed QuickLook through Microsoft Store.
2. I have Office 365 installed in my Windows 10.

Here's a screenshot of DOCX file preview. QuickLook uses Word/Excel/PowerPoint engines to render thier files.
![quicklook_office_apps_1](https://user-images.githubusercontent.com/12271104/43268004-776314b6-912a-11e8-9770-76b2047c3542.png)

**Comment by foguetes** [comment]
There's no "Office 365" listed on my computer. I have Microsoft Office Desktop Apps. When I open any office app it shows as Office 365. I selected Microsoft Office Desktop Apps and repaired it. Still doesn't work.

**Comment by xupefei** [comment]
Unfortunately, Office 365 from Windows Store does not support COM preview handlers.

Cheers,
Paddy

**Comment by xupefei** [comment]
As I said, Office 365 **installed from Windows Store** is not supported. Install from installer instead.
The installer can be found at some webpages like this:
![image](https://user-images.githubusercontent.com/1687847/43381088-2455af5e-93dc-11e8-8add-cea48a718ba7.png)

**Comment by xupefei** [comment]
@ccigas Try turn on File Explorer's preview pane, select a docx file and see if its contents shows up.

https://www.tenforums.com/tutorials/35230-show-hide-preview-pane-file-explorer-windows-10-a.html

**Comment by foguetes** [comment]
@xupefei I understand. However, this is my company's computer and there's a very complicated procedure involving reinstalling Office. My point was, if Seer does it then there's a way to do it using the Microsoft Store version. It's up to you if you want to implement it or not. I think for now I'll use Seer instead, even though I like QuickLook more.

**Comment by xupefei** [comment]
I know the way to invoke Office like what Seer did, but will not do the same since it is really a slow and unstable method.

I am afraid the best solution is still to use some third-party libraries, however they are actually quite expensive: https://github.com/QL-Win/QuickLook/issues/94 <https://github.com/QL-Win/QuickLook/issues/94>.

Cheers,
Paddy

**Comment by ccigas** [comment]
@xupefei thanks for that but sadly it didnt work, All files, docx, notepad files, and more still come up without a preview. My personal computers work fine, slow, I could open the normal file in that time but it works.

**Comment by ForzaAaRon** [comment]
I currently have the latest version of desktop office installed and quicklook is also up to date. However this isssue still exists.

**Comment by rabelux** [comment]
You now have to intall the OfficeViewer-plugin.
Link and description here: https://github.com/QL-Win/QuickLook/wiki/Available-Plugins
Native office-support has been removed in version 3.6.x i think
