### ISSUE TITLE
Select and copy text from a PDF file

### ISSUE THREAD

**Issue by Weasy666** [QL-Win/QuickLook#304]
**Is your feature request related to a problem? Please describe.**
Currently it's not possible to select and copy text from a previewed PDF file.

**Describe the solution you'd like**
I'd like to be able to select and copy text from a previewed PDF file.

**Comment by xupefei** [comment]
Supporting selection is really complicated despite it looks easy to implement. Please use a PDF viewer instead.

PS: If someone is willing to add this feature, please send me a PR.

**Comment by raaomoka** [comment]
Any luck with this? It's a pretty major feature that will be super useful in speeding up processing of documents...
