### ISSUE TITLE
Failed to add QuickLook to Startup folder

### ISSUE THREAD

**Issue by rabelux** [QL-Win/QuickLook#311]
Autostart doesn't work. When toggling this feature via right click on the traybar icon a small popup says "Failed to add QuickLook to Startup folder".
Launching Quicklook.exe as admin also doesnt change this behaviour.

 - OS Version: Windows 7 64bit
 - QuickLook Version: 0.3.5-62-g6b72f38.msi nightly

No logfile found to attach. There is only a config-file in that folder

**Comment by xupefei** [comment]
I have added a line of code to write log when error occurs. Can you try the latest version and paste the log here?

https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts

**Comment by rabelux** [comment]
Thanks for the quick reaction!
(German) Log says:
```
System.InvalidCastException: Das COM-Objekt des Typs "System.__ComObject" kann nicht in den Schnittstellentyp "Shell32.Shell" umgewandelt werden. Dieser Vorgang konnte nicht durchgeführt werden, da der QueryInterface-Aufruf an die COM-Komponente für die Schnittstelle mit der IID "{286E6F1B-7113-4355-9562-96B7E9D64C54}" aufgrund des folgenden Fehlers nicht durchgeführt werden konnte: Schnittstelle nicht unterstützt (Ausnahme von HRESULT: 0x80004002 (E_NOINTERFACE)).
   bei QuickLook.Helpers.ShellLinkHelper.OpenShellLink(String path)
   bei QuickLook.Helpers.AutoStartupHelper.CreateAutorunShortcut()
```
My translation:
```
COM-Object of type "System.__ComObject" can't be changed into interface type "Shell32.Shell". Procedure was aborted because QueryInterface-Call to COM-component of interface with ID "{286E6F1B-7113-4355-9562-96B7E9D64C54}" was not possible due to:
interface not supported (exception from HRESULT: 0x80004002 (E_NOINTERFACE)).
Happened at
  QuickLook.Helpers.ShellLinkHelper.OpenShellLink(String path)
  at QuickLook.Helpers.AutoStartupHelper.CreateAutorunShortcut()```

**Comment by xupefei** [comment]
Can you provide the full stack trace?

**Comment by rabelux** [comment]
That's all there is, here you have the logfile found in `AppData\Roaming\pooi.moe\QuickLook\`
[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/2260607/QuickLook.Exception.log)

**Comment by xupefei** [comment]
Thanks! I can't reproduce this issue on my Windows 10 OS.
I guess it is related to  Windows 7 because I was once observed the same problem on another Win7 system, but have not paid much attention. Let me find a virtual machine and see what's happened.

**Comment by xupefei** [comment]
This should help: https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts
If no, feel free to re-open this issue :)

**Comment by rabelux** [comment]
Well that was fast and effective, autostart ist working fine now.
Thanks a lot for this tool and your effort!!
Startet using it yesterday and already love it :]
