### ISSUE TITLE
Oversized images cannot be scaled

### ISSUE THREAD

**Issue by szlytlyt** [QL-Win/QuickLook#312]
Since the minimum zoom level is 10%, the oversized image does not display properly.
Image resolution that caused the problem: 31460 x 11811

**Comment by xupefei** [comment]
Will be fixed along with #278.

**Comment by RichieChow** [comment]
This problem still exists with some 960p image (like 1280x960) 
![snipaste_2018-08-29_16-06-34](https://user-images.githubusercontent.com/34783557/44774365-88549c00-aba5-11e8-8a0e-d0504af8963c.png)
and this icon  should adapt to the dark mode
![snipaste_2018-08-29_16-13-22](https://user-images.githubusercontent.com/34783557/44774750-7c1d0e80-aba6-11e8-8237-9fd039fff292.png)

 - OS Version: Windows 10 1803
 - QuickLook Version: Nightly build QuickLook-0.3.5-75-g75cbc90.msi

**Comment by xupefei** [comment]
Now it should be okay. 
The anchor at the right-bottom corner has been removed. The rest is the problem of WPF, which can only be fixed by MS.

**Comment by khoshiro** [comment]
Stilll I have the same issue. Scrolling with mouse / touchpad or right bottom anchor results in 0% Zoom. 
Pressing fullscreen also results in 0% Zoom.
- Panning works
- Zooming in / then Back not
