### ISSUE TITLE
Office file priview with office365 UWP

### ISSUE THREAD

**Issue by 1349422030** [QL-Win/QuickLook#315]
开发者大大你好，
目前quicklook（UWP）可以调用office2016（win32版本）达到预览office文件的目的，
但我目前使用的是应用商店提供的office365（UWP）版本，请问再技术上能不能也增加预览office文件的功能呢

**Comment by xupefei** [comment]
不能。这是 Office 和 Windows UWP 框架的限制，不是 QL 的问题。

Cheers,
Paddy
