### ISSUE TITLE
space bar brings up a small window not a preview

### ISSUE THREAD

**Issue by RSL8TR** [QL-Win/QuickLook#316]
*You can use either Chinese or English when filling this issue. 你可以使用中文或英语填写以下问题。*

**Describe the bug**

**To Reproduce**

**Expected behavior**
Pressing space bar does not bring a preview.

**Desktop (please complete the following information):**
 - OS Version  HomeFeature update to Windows 10, version 1803
 - QuickLook Version: v0.3.5(UWP)
**Screenshots and Exception Log**

If applicable, add screenshots and logs to help explain your problem. The log file is located in `C:\Users\username\AppData\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log`
![image](https://user-images.githubusercontent.com/42299625/43993254-86bdd6aa-9d58-11e8-94ba-b38eb5e76bb1.png)
![problem](https://user-images.githubusercontent.com/42299625/43993281-cafab39c-9d58-11e8-93e8-0b6b2ded436c.jpg)

**Comment by xupefei** [comment]
Please upgrade to at least Office 2013.
