### ISSUE TITLE
Please ignore this issue and delete the thread.

### ISSUE THREAD

**Issue by usvendor** [QL-Win/QuickLook#317]
Please ignore this issue and delete the thread. I found out what the problem is.

**Comment by xupefei** [comment]
Are you selecting to use a single mouse click for opening a file?

From: usvendor
Sent: 16 August 2018 15:19
To: QL-Win/QuickLook
Cc: Subscribed
Subject: [QL-Win/QuickLook] QuickLook causes Windows to open associated file'sapplication (#317)

When I install QuickLook, every time I hit space Windows additionally opens the associated application along with the QuickLook preview.
Hence, I get two windows after using QuickLook. One is the QuickLook window in front, and the other is the Windows application behind.
If I deactivate QuickLook by pressing space again, both windows disappear. But if I close the QuickLook preview window using X button, then the application that Windows opened remains opened and I have to manually close it.
Is this supposed to happen? I can't find a way to get rid of it.
Thank you for any insight. I'm running a clean install of Windows 10 Enterprise.
