### ISSUE TITLE
QuickLook not activating on startup

### ISSUE THREAD

**Issue by designtodevelop** [QL-Win/QuickLook#319]
I just purchased a brand new PC with Windows 10. I installed Quicklook from the Microsoft Store. When I first installed Quicklook it works fine. However when I restart my PC Quicklook doesn't enable on startup. I went and initiated Quicklook I can see a Quicklook icon on the tray but it disappears very quickly and it doesn't work. When I press space bar nothing happens. It seems Quicklook is not active. 

I uninstalled Quicklook (very difficult to uninstall as it doesn't appear in the uninstall list - but finally managed to uninstall this). I reinstalled Quicklook again it works first time but when you restart it doesn't work anymore. 

**To Reproduce**
1) Install Quicklook from the Microsoft Store
2) Restart your computer
3) Quicklook doesn't work anymore

**Expected behavior**
1) Quicklook should auto start on startup
2) when you press space bar it should pop up with a preview

**Desktop:**
 - OS Version: Windows 10 OS Build: 16299.15
 - QuickLook Version: Not sure as it doesn't say anywhere. But I downloaded it last night. 

**Screenshots and Exception Log**
Log attached 
[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/2301855/QuickLook.Exception.log)
`

**Comment by xupefei** [comment]
The error log says Access Denied when creating a named pipe. I am not quite sure what's the problem but can you try the latest Nightly? It contains a few changes to the named pipe.

**Comment by designtodevelop** [comment]
Sorry, what do you mean the latest nightly? What is that? Do you mean
reinstalling it again?


Steven

**Comment by xupefei** [comment]
No. I mean this: https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts

Ref: https://github.com/QL-Win/QuickLook/wiki/Difference-between-distributions

**Comment by designtodevelop** [comment]
ok sure I will give this a try

thanks

Steven

**Comment by designtodevelop** [comment]
Just tried installing the Nightly build you mentioned and this is working
now!

Thanks

Steven
