### ISSUE TITLE
Multiple Windows 10 Accounts - Fail

### ISSUE THREAD

**Issue by jdrbp1224** [QL-Win/QuickLook#320]
**Describe the bug**
Quicklook does not install across multiple Windows 10 accounts upon installation from the Windows store. When downloading the application individually per account from that account's relevant store, the application installs, launches, and then crashes. It seems to not be possible to run Quicklook on more than one Windows 10 account when fast switching between more than one account per machine.

**To Reproduce**

Install on more than one Windows 10 account. 
Run

**Expected behavior**
Application will fail out of system tray or simply not allow being installed

**Desktop (please complete the following information):**
v0.3.5

**Comment by xupefei** [comment]
This issue has been fixed in https://github.com/QL-Win/QuickLook/issues/196. Try the latest Nightly :)
