### ISSUE TITLE
Preview not available for files with Chinese names

### ISSUE THREAD

**Issue by AbdulkaderBaradi** [QL-Win/QuickLook#321]
Great job for the app,

**Describe the bug**
No preview for files that have a non-Latin name, anything with Chinese name won't work

**To Reproduce**
1. English window with a Chinese keyboard 
2. Go to 'any Chinese named file'
3. Click space 
4. Preview not available 

**Expected behavior**
I expect the preview to show up wither its Chinese or English.

**Info**
 - OS Version: OS WIN10 build 1803
 - QuickLook Version: v0.3.5 (UWP) Windows Store]

**Screenshots and Exception Log**

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/2307353/QuickLook.Exception.log)
![error](https://user-images.githubusercontent.com/3344873/44418103-c3d4e200-a577-11e8-9fca-1e249ba94ee6.jpg)

**NOTE:**
- Once I change the name to English or with Latin characters it works perfectly. 
- It's important to mention that my OS is English but I have the Chinese Language set-up

Love your work man
Thank you

**Comment by xupefei** [comment]
This bug has been fixed some days ago. You can try the Nightly version: https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts
