### ISSUE TITLE
一些优化的建议

### ISSUE THREAD

**Issue by cooper1x** [QL-Win/QuickLook#322]
反馈几个问题：
1、空格打开的loading时间有点长，看起来有些慢，大概要2s吧。
2、如果图片的文件名较长，那么标题是显示不完整的，这样我就看不到后面的尺寸了。
3、希望添加左下角或右下角尺寸显示图片尺寸功能，而不是点击右上角的感叹号。
4、希望加入软件设置菜单，比方说开关默认下方图片尺寸显示的功能。

**Comment by xupefei** [comment]
1. Fixed in latest Nightly.
2. I am aware of the issue, but unfortunately, I can't fix it because it leads to changes in other plugins.
3. Unless the filename is too long, you can read the size from the title.
4. Won't fix.

**Comment by cooper1x** [comment]
如果title名称稍微有点长或者图片尺寸比较小的话，就不能快速看到图片尺寸了，对于前端开发人员和设计师来说这个功能可以击中痛点，希望可以考虑下用其他方式更好的展现，比方说在预览图片下方加一个条默认显示图片尺寸和大小，这个功能可以手动开启或者关闭。 @xupefei
