### ISSUE TITLE
Can the icon in notification bar support hiding?

### ISSUE THREAD

**Issue by specter1024** [QL-Win/QuickLook#323]
**Is your feature request related to a problem? Please describe.**
**No**

**Describe the solution you'd like**
**No solution.**

**Describe alternatives you've considered**
**No idea!.**

**Additional context**
**Can the icon in notification bar support hiding?**

**Comment by xupefei** [comment]
No. If so, then there will be no way to quit QuickLook. Please make use of https://winaero.com/blog/show-hide-system-icons-tray-windows-10/.

**Comment by xupefei** [comment]
Solved in https://github.com/QL-Win/QuickLook/issues/729.
