### ISSUE TITLE
无法在everything中使用

### ISSUE THREAD

**Issue by FantasyDream** [QL-Win/QuickLook#326]
不知道为什么，我的电脑中quiclook在everything中无法使用，我看到网上都说可以使用的，难道是我哪里没设置好吗？

**Comment by xupefei** [comment]
Please, follow the guideline when asking for help.

For your problem, I guess you are running Everything as administrator. This can be bypassed by installing the _Everything indexing service_: https://www.voidtools.com/support/everything/installing_everything/
