### ISSUE TITLE
About archive with a password

### ISSUE THREAD

**Issue by vidamcmillan** [QL-Win/QuickLook#327]
Hi there, thank you for bring this QuickLook to Windows users.

**Describe the bug**
QuickLook can't show a password input form while using this to preview an archive with password, of course, only this archive enctypted file name when creating it.

**To Reproduce**
1. Go to “any archive(rar, zip, 7z...) checked option encrypted file name when creating it ”.
2. Click on "Space(keyboard)"
3. See error

**Expected behavior**
I wish QuickLook to support password input when I opening an "encrypted file name" archive, thank you.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803 x64 pro
 - QuickLook Version: 0.3.5 from Github

**Screenshots and Exception Log**
Here is Screenshot:
![image](https://user-images.githubusercontent.com/26226049/44648696-7394ce80-aa14-11e8-94e2-864b3735815b.png)

Here is log:
========2018/8/27 15:58:05========
System.Threading.Tasks.TaskCanceledException: 已取消一个任务(A task has been cancelled)。
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   在 System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   在 MS.Internal.WeakEventTable.OnShutDown()
   在 MS.Internal.ShutDownListener.HandleShutDown(Object sender, EventArgs e)

**Comment by xupefei** [comment]
I can reproduce this issue, however, there is no method to tell if an archive is encrypted in SharpCompress lib. I guess what I can do is to notify you that the previewing failed because of a possibly encrypted file.

**Comment by vidamcmillan** [comment]
@xupefei Ok, notification better than nothing. I can try fixing this problem when I'm free see if there have any methods to help with this.
