### ISSUE TITLE
PDF not showing on v0.3.5-75-g75cbc90  

### ISSUE THREAD

**Issue by jeremyhart** [QL-Win/QuickLook#330]
**Describe the bug**
PDF pages not showing in preview window, thumbnails are showing though.

 Windows 10 1803, v0.3.5-75-g75cbc90  

![quicklook pdf issue](https://user-images.githubusercontent.com/2062475/44761230-5f78da80-ab96-11e8-9cae-40065defe68b.JPG)

**Comment by xupefei** [comment]
Got it. I'll fix it.
