### ISSUE TITLE
反馈两个bug

### ISSUE THREAD

**Issue by dearanswer** [QL-Win/QuickLook#331]
bug1:系统默认办公软件为金山WPS，不管对着PPT文档还是表格文档或是Word文档，按空格键预览后再按空格键，预览窗口不会自动消失

bug2:系统默认pdf浏览器为金山pdf阅读器，预览失败，看不到pdf文件内容

**Comment by xupefei** [comment]
Please, follow the guideline when submitting a feature request.

Regarding your question:
1. A new Office viewer is coming, which will solve this problem: https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer (It is still empty now but I hope I can fill it during this weekend.)

2. There is a known problem with non-ASCII characters (Chinese, Japanese,  etc.) in the filename. It has been resolved a few months ago in the Nightly release: https://ci.appveyor.com/project/xupefei/quicklook/build/516/artifacts
