### ISSUE TITLE
QuickLook can not peek into files in folder portals of Fences

### ISSUE THREAD

**Issue by guxuanjun** [QL-Win/QuickLook#332]
Thank you for bring us that great software.

Fences is a software that help to automatically organizing desktop shortcuts and icons. You once recommended it to users who need to organizing desktop and quickly previewing files at same time. But I find that QuickLook can only peek into files on desktop in Fences, it can not peek into files which in folder portals of Fences. I do not know whether it is a bug or QuickLook does not support this feature.

My OS version is windows 10 家庭中文版; my QuickLook version is v0.3.5 msi from Github; my Fences version is 3.0.9.11.

**Comment by xupefei** [comment]
They are not common Desktop icons and hence can't be previewed like such.
I think you should ask Stardock for help.
