### ISSUE TITLE
Direct file association to open files

### ISSUE THREAD

**Issue by Jogai** [QL-Win/QuickLook#334]
Happy to have found this useful utility. I have no proplems, but a feature request. Is it possible to have Quicklook as the default file handler for some files? I would prefer to open any image with your program.

**Comment by xupefei** [comment]
I don't recommend this. QuickLook is not designed for being a default handler.
If you insist, you can create a custom assignment because QuickLook supports command line: https://github.com/QL-Win/QuickLook/wiki/Integration-and-Development

**Comment by Jimmm** [comment]
Why it is not recommended?

**Comment by emako** [comment]
QL supports files with any extension, even .exe. If you also specify which ones can be used as the default program, this will lead to very confusing maintenance, so it is not recommended.
