### ISSUE TITLE
Switchable preview for SVG images

### ISSUE THREAD

**Issue by Riajyuu** [QL-Win/QuickLook#336]
While previewing SVGs, I expect a button to toggle between image view and plain text

**Comment by xupefei** [comment]
This is known. I can't find a good svg2pdf library yet.

**Comment by Riajyuu** [comment]
@xupefei 

> svg2dpf

excuse me? I failed to catch up. What I request here is simply to process SVGs as text file, just like opening them in text editor, when hitting the button

**Comment by xupefei** [comment]
Sorry, it is a typo. Should be "svg2pdf".

What I mean is I can't find a good SVG renderer. Since SVG is a vector
format, the best option would be to render it as a PDF, which is also a
vector format and can easily be previewed.

**Comment by xupefei** [comment]
Oh sorry again. I misunderstood again. Now  I think SVG files are already
previewed as texts.

**Comment by xupefei** [comment]
Thanks for the clarification. Now I understand what you mean.

This issue is related to https://github.com/QL-Win/QuickLook/issues/132. It will be a fraction of the next release.

**Comment by xupefei** [comment]
The reason is that we have switched to NConvert to provide faster image previewing since v0.3.6. NConvert, unfortunately, does not support SVG.

**Comment by WalterMa** [comment]
@xupefei 
Seems NConvert support SVG.
https://www.xnview.com/en/nconvert/#formats

**Comment by whywaitwebs** [comment]
I would rather the image preview be slow than not work at all.

**Comment by runxel** [comment]
Not the guy to necromancing, but a true svg preview is much needed and appreciated.
At the moment it just shows... some pixel mess? :/

**Comment by xupefei** [comment]
Since the year 2019 I have been busy with various things: first writing a paper, then drafting a thesis, and now working. I haven't got much time feeling good enough to sit down and implement a complex feature. I would really appreciate if someone can spare some time to implement this feature. The idea is:

1. Add a new pipe message to preview a file with a specific viewer (now there's only the message to preview a file without specifying a viewer).
2. Add a button on the top-right side of the previewer (just like the existing EXIF and dark/light switch buttons) for SVG format. The button will call the new pipe message before closing itself.

**Comment by princeeze** [comment]
Any updates on this yet?

I have had to downgrade to 0.3.5 to view SVGs

**Comment by rabelux** [comment]
@princeeze SVG previews work fine in the current version. This ticket is about switching between source and image view.

**Comment by princeeze** [comment]
Are you sure about that? I couldn't preview svg files. I had to downgrade for it to work.

**Comment by rabelux** [comment]
I tested it and it works. Have you tried different SVGs?

**Comment by Hard-Wired** [comment]
Such a switch for all file types would be useful as well as turning off previews for file types like .url (Internet Shortcut).

**Comment by emako** [comment]
1. Open with Button can implement similar functions

2. Another solution to a similar problem:

Create a new plugin by yourself, use a higher priority such as 100, and then call TextViewer to display the url / svg and other suffixes you need.
