### ISSUE TITLE
image are NOT displayed as pixel size

### ISSUE THREAD

**Issue by RichieChow** [QL-Win/QuickLook#340]
![snipaste_2018-09-05_11-05-27](https://user-images.githubusercontent.com/34783557/45068782-ab2e0580-b0fb-11e8-878f-6f1d0f0d2543.png)
[Scan_04.zip](https://github.com/QL-Win/QuickLook/files/2351070/Scan_04.zip)

 - OS Version: Windows 10 1803
 - QuickLook Version: 0.3.6.1

**Comment by xupefei** [comment]
Strange, I should have fixed this yesterday. Let me see...

**Comment by RichieChow** [comment]
it seems to be displayed as real size(print size, not pixel size)
![snipaste_2018-09-05_22-45-33](https://user-images.githubusercontent.com/34783557/45101667-a2bae680-b15e-11e8-9936-c25a884ddb32.png)
![snipaste_2018-09-05_22-46-32](https://user-images.githubusercontent.com/34783557/45101671-a484aa00-b15e-11e8-842d-a7bc2ed9e278.png)
![join](https://user-images.githubusercontent.com/34783557/45101673-a64e6d80-b15e-11e8-9e8f-d822431f2e79.jpg)

**Comment by xupefei** [comment]
After some researches, I decided to leave this as-is. This image has 1200 DPI so it _should looked like that_.

Another reason is that WPF lacks a way to ignore DPI data in the image. Converting by myself will greatly increase the image load time.

**Comment by RichieChow** [comment]
the current display mode is also correct, but the window is too large for this image. will it be fixed?

**Comment by xupefei** [comment]
This issue has been fixed in 3.6.8.
