### ISSUE TITLE
PSD file shows for a split second and then goes blank

### ISSUE THREAD

**Issue by dgreen97** [QL-Win/QuickLook#341]
When using quick look to view PSD files, it opens the PSD file and then goes blank immediately. So I see a really low res version of the PSD file and then it disappears. Any idea why this happens? 

Im on windows 10 pro latest version.

**Comment by xupefei** [comment]
Please submit an issue according to the guideline:

**Desktop (please complete the following information):**
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Comment by dgreen97** [comment]
Quicklook version is 0.3.6.1 downloaded from github

**Comment by xupefei** [comment]
I think this issue is related to #340. I will look into it again and update there.

**Comment by dgreen97** [comment]
Thanks

**Comment by dgreen97** [comment]
I can take a screenshot if you want, the file doesn't fully render and then it goes blank. 

![1](https://user-images.githubusercontent.com/3385778/45098583-e4aa4500-b0ea-11e8-973f-daf423c22276.jpg)


![2](https://user-images.githubusercontent.com/3385778/45098582-e4aa4500-b0ea-11e8-8fd6-026a88782a9f.jpg)

**Comment by xupefei** [comment]
Thanks. Seems like a different issue.

**Comment by xupefei** [comment]
Hi, can you share your PSD file? I tried with a random one but I can't reproduce this issue.

**Comment by rockdengj** [comment]
Try to set Maximize PSD and PSB File Compatibility to Always or Ask in your Photoshop Preferences. Then Save As your psd file.

**Comment by rabelux** [comment]
Closed for inactivity
