### ISSUE TITLE
Performance issue when previewing large PDF files

### ISSUE THREAD

**Issue by anye1998** [QL-Win/QuickLook#342]
使用的是微软商店最新版，在打开大型pdf（一百多兆）时，打开了一半就关闭窗口，但软件在后台还在不断打开，不会自动停止，直到将内存爆满，这个情况只能强制停止才能解决，退出都不行。

**Comment by anye1998** [comment]
我试了一下，最新编译的0.3.6.1也有这个问题，还有，希望有开发者有空的话能够更新一下UWP版，毕竟那个更新安装什么的更方便。

**Comment by xupefei** [comment]
Please, follow the submission guideline and use English.

For your problem: how many pages does this file have?

**Comment by anye1998** [comment]
I used the latest version of the Microsoft Store. When I open a large pdf (more than one hundred MB，about 200 pages), I close the window when I open it halfway, but the software is still open in the background and will not stop automatically until the memory is full. Forced stop can be solved, and exit will not work.

The latest zip also has this problem。

I hope that if you have time, you can update the UWP version. After all, it is more convenient to update and use.

Sorry, I don't know that you don't understand Chinese.

**Comment by xupefei** [comment]
Thanks for the reply. I actually can read Chinese, but now QuickLook has many no-read-Chinese users and some of them may have encountered the same issue.

I guess your PDF page is very large. Can you share it with me by email?

**Comment by anye1998** [comment]
Do you mind pdf related to 18+？
 Is it more convenient for you to use Baidu network disk or OneDrive?

**Comment by xupefei** [comment]
Well, I don't mind. OneDrive will be better.

**Comment by xupefei** [comment]
PS: Don't post the link here. Send an email instead.

**Comment by anye1998** [comment]
Ok, I will notify you by email when I upload it.

**Comment by anye1998** [comment]
I have sent the link to you by email. Please check it.
