### ISSUE TITLE
Crashed when open QuickLook.exe

### ISSUE THREAD

**Issue by Joaxin** [QL-Win/QuickLook#345]
### Description：
 问题事件名称:	CLR20r3
  问题签名 01:	QuickLook.exe
  问题签名 02:	0.3.6.1
  问题签名 03:	5b8ed02e
  问题签名 04:	mscorlib
  问题签名 05:	4.7.2117.0
  问题签名 06:	59cf513d
  问题签名 07:	4240
  问题签名 08:	a4
  问题签名 09:	System.IO.FileLoadException
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	3c17
  其他信息 2:	3c17158c19ccd4a13b5d2117fdcc2005
  其他信息 3:	849f
  其他信息 4:	849fea09c3ebde54ace3c398cfd20cd2
### OS Version：
OS 名称:          Microsoft Windows 7 旗舰版
OS 版本:          6.1.7601 Service Pack 1 Build 7601
OS 制造商:        Microsoft Corporation

**Comment by xupefei** [comment]
Have you tried https://github.com/QL-Win/QuickLook/issues/1?

**Comment by Joaxin** [comment]
Thanks **xupefei**, the problem has been solved by #1, but its only working when you use default explorer, so I uninstall the *Clover*, it worked finally.
