### ISSUE TITLE
QuickLook latest version can not preview word and excel, but former version 0.3.4 can

### ISSUE THREAD

**Issue by waithope** [QL-Win/QuickLook#348]
**Describe the bug**
I updated quicklook to the latest version, now quicklook can not preview word and excel. Quicklook version 0.3.4 works fine. How can I fix it? 
By the way, I've already looked up **Issues**,  but can not find solution. 

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803
 - QuickLook Version: 0.3.6.1 from Github Release

**Comment by xupefei** [comment]
Right click on the taskbar icon and choose "Plugins", then you will see.
