### ISSUE TITLE
Blurred image preview at 100%

### ISSUE THREAD

**Issue by DrBones** [QL-Win/QuickLook#352]
**Describe the bug**
When previewing any image it seems there is some interpolation applied instead of displaying the pixels directly.

**To Reproduce**
1. Press space when viewing any image
2. The image appears a little blurry (mostly noticeable with text, see screenshot 1)
3. zoom in ONCE with the mouewheel and the zoom goes from 100% to 100% and two scroll bars appear (see screenshot 2), now the image is sharp. See also the gif for the transition.
![blurry_image](https://user-images.githubusercontent.com/212259/45433855-5bc47800-b6ad-11e8-97c7-80b189810672.gif)

**Expected behavior**
The first shown image should be displayed at original size and only interpolated when zooming. Of course no scrollbars should be present when viewing at 100% size.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 17134.165
 - QuickLook Version: zip package, version: 0.3.6.1
 - No display scaling

**Screenshots**
Screenshot 1
![image](https://user-images.githubusercontent.com/212259/45433482-89f58800-b6ac-11e8-9daa-062008870857.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/212259/45433130-c4aaf080-b6ab-11e8-8484-08819f7f2297.png)

**Comment by xupefei** [comment]
I guess the first 100% is not the real 100%, but something like 99.9%.

What is your screen resolution? Can you upload the image so I can test?

**Comment by DrBones** [comment]
Sure, 

here is the image:
![time_dependence_nofk](https://user-images.githubusercontent.com/212259/45436730-b8c32c80-b6b3-11e8-84fc-1171b9a663ab.png)

My screen resolution is 1920x1080
