### ISSUE TITLE
Win10 can not open this image

### ISSUE THREAD

**Issue by cooper1x** [QL-Win/QuickLook#353]
**Describe the bug**
Win10 can not open this image.
https://i.loli.net/2018/09/14/5b9b2a3aae140.jpg

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 1809]
 - QuickLook Version: [3.6.2 from GitHub]

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/9080789/45527928-ac081b00-b810-11e8-9e49-8c8dd4b5086c.png)

**Comment by xupefei** [comment]
This image has incorrect DPI info = 1, which means that each pixel is scaled to 96 pixels.
Please fix it with some image editor. Just Open and Save As should enough to fix it.
