### ISSUE TITLE
APK Icon & Information Support

### ISSUE THREAD

**Issue by faltupangay** [QL-Win/QuickLook#354]
### APK Icon & Information Support
Quick Look is a very useful and fast utility, So far I am Having no problem with it But, I have a feature request Is it possible to add **Support for Android Package files** (.apk) to view some information like 
**APK Icon**
**APK Name**
**APK Package Name**
**APK Version**
So Far i am new in programming So i cant help in developing the plugin But here is a open source project Which can help Some Developer seeking to help 
[ApkShellExt2](https://github.com/kkguo/apkshellext)
Will Be Happy to See someone help in it THANKS

**Comment by xupefei** [comment]
It would be nice if the info can be shown as in [InfoPanel](https://github.com/QL-Win/QuickLook/tree/master/QuickLook/Plugin/InfoPanel).

**Comment by emako** [comment]
At the same time, special APK support plugins will be developed in the future.
