### ISSUE TITLE
Couldn't preview MS files 

### ISSUE THREAD

**Issue by 1244176894** [QL-Win/QuickLook#355]
*For all's convenience, please use English to fill this issue.*

**Describe the bug**
The Word, Excel and PowerPoint files couldn't be previewed suddenly since yesterday(2018/9/14).

**Expected behavior**
It could have been previewed.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Comment by xupefei** [comment]
It has been moved to a plugin: https://github.com/QL-Win/QuickLook/wiki/Available-Plugins

**Comment by 1244176894** [comment]
Thanks for your quick response! I've installed the plugin, it works well but there is still some problem with the PowerPoint, which couldn't be previewed. And I think the previous edition is quite practical and has a quicker response. From my experience, the quick response should be the first factor that should be considered.  Anyway, thanks a lot for your awesome project!

**Comment by xupefei** [comment]
PowerPoint files are converted to PDF and then previewed. However, now there is a known issue of previewing PDF (see #356). Only Windows Store version is affected.

Quick response is certainly a main factor of QL, but the usability and stability are more important. The previous version requires MS Office installation, and often crash when previewing files. Now it may be slower, but at least do not require MS Office and do not crash anymore :)
