### ISSUE TITLE
Quicklook for PDF not working after recent update

### ISSUE THREAD

**Issue by jakkaas** [QL-Win/QuickLook#356]
*For all's convenience, please use English to fill this issue.*

**Describe the bug**
After updating to Quicklook version 3.6.2, PDF view not working. Showing error, failed to preview, consider reporting the incident to the author. A small preview opens but a complete preview was not seen

**To Reproduce**
1. Go to 'any pdf file'
2. Click on 'space bar'
3. See error

**Expected behavior**
Like the previous version, a preview of complete PDF was to be seen

**Desktop (please complete the following information):**
 - OS Version: 1803, Built 17134.285
 - QuickLook Version: 3.6.2

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/2385485/QuickLook.Exception.log)

![screenshot 134](https://user-images.githubusercontent.com/43289832/45583875-6702e800-b8e7-11e8-9461-73100a8dffcc.png)

**Comment by xupefei** [comment]
Windows Store version?

**Comment by xupefei** [comment]
I have found that, for some reason, the pdfium.dll is not in the Windows Store package. I have submitted a new version to the Store, and it will take a few days to see it.

For now, you can use .msi or .zip version instead.

**Comment by jakkaas** [comment]
Store Version 11808.1001.9.0

Ok. I will wait for the update. Thanks

**Comment by xupefei** [comment]
I will leave this issue open, and close it when the new release is published.

**Comment by xupefei** [comment]
The new version is now in the Store. Case closed.
