### ISSUE TITLE
Can't open Powerpoint file (ppt, pptx)

### ISSUE THREAD

**Issue by Thanhtho96** [QL-Win/QuickLook#357]
*For all's convenience, please use English to fill this issue.*

**Describe the bug**
After updating to Quicklook version 3.6.2, Powerpoint view not working. Showing error, failed to preview, consider reporting the incident to the author. ppt file just show file name and size and pptx is show loading icon then error

**To Reproduce**
1. Go to 'any ppt or pptx file'
2. Click on 'spacebar'
3. See error

**Expected behavior**
As I try Office Plugin for first time, doc file and xls work fine except ppt file

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803
 - QuickLook Version: 3.6.2 from Windows Store

**Screenshots and Exception Log**
[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/2385792/QuickLook.Exception.log)

![capture1](https://user-images.githubusercontent.com/16351165/45587454-ed431c80-b92f-11e8-9df9-2196569a60cf.PNG)
![capture3](https://user-images.githubusercontent.com/16351165/45587456-eddbb300-b92f-11e8-8f0a-c246cea03136.PNG)
![capture2](https://user-images.githubusercontent.com/16351165/45587455-eddbb300-b92f-11e8-8455-1e32394748b8.PNG)

**Comment by xupefei** [comment]
Please see #355.
