### ISSUE TITLE
Use MS Office to preview Word, Excel, and Powerpoint files

### ISSUE THREAD

**Issue by xupefei** [QL-Win/QuickLook#358]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
The new [OfficeViewer](https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer) renders documents not as good as the old [MS Office viewer](https://github.com/QL-Win/QuickLook/tree/cdc5f0f2f45f5b164a0016b79f1c4e53a961c276/QuickLook.Plugin/QuickLook.Plugin.IPreviewHandlers).

**Describe the solution you'd like**
Refactor the old Office viewer according to the new plugin infrastructure.

**Additional context**
The Plugin name can be the same as QuickLook.Plugin.OfficeViewer, so there can be only one of both plugins exist (QL will overwrite the existing plugin with the new one).
The Priority of the new plugin should also be the same with QuickLook.Plugin.OfficeViewer.

**Comment by lifangzheng** [comment]
I really hope you can roll it back...

The new render is ugly.. Refactor the old one if possible please...

![_20180919163901](https://user-images.githubusercontent.com/12532311/45741573-8ae96500-bc2a-11e8-85a1-c4191d4c58e8.png)

**Comment by bwiernik** [comment]
I primarily use QL to preview Office files, and the slowness of the new OfficeViewer plugin makes versions 0.3.6 and onward pretty much unusable for me. Any update on when you might be able to implement this refactor?

**Comment by xupefei** [comment]
Fixed.
