### ISSUE TITLE
Win10家庭版+预装Office无法实现Word等文件预览

### ISSUE THREAD

**Issue by soulans** [QL-Win/QuickLook#360]
sorry i don't good at English, so I describe my issue in Chinese.

操作系统：Win10家庭版1803
Office：预装Office2016学生与家庭版
QuickLook：store版本

截图：

![2](https://user-images.githubusercontent.com/9351549/45592103-2d89b580-b997-11e8-8394-afce0ff2d7ad.png)

**Comment by xupefei** [comment]
安装插件：https://github.com/QL-Win/QuickLook/wiki/Available-Plugins。

**Comment by soulans** [comment]
> 安装插件：https://github.com/QL-Win/QuickLook/wiki/Available-Plugins 。

可是我已经安装了MS Office，为什么还需要安装这个插件呢？我看插件的描述为：“View Word, Excel, and PowerPoint files without installing MS Office”

**Comment by shamork** [comment]
因为只需要安装插件就可以预览了，不需要安装ms office。

**Comment by shamork** [comment]
安装步骤：
1.打开命令行提示符：输入 mkdir %APPDATA%\pooi.moe\QuickLook\QuickLook.Plugin 回车 
打开资源管理器，地址栏输入 %APPDATA%\pooi.moe\QuickLook\QuickLook.Plugin
复制下载的 QuickLook.Plugin.OfficeViewer.qlplugin 到上面的文件夹中
在启动quick look的情况下，用鼠标选中 QuickLook.Plugin.OfficeViewer.qlplugin，按下空格键，会弹出预览框，其中按钮为 Click Here To Install Plugin，点一下，系统通知栏，右键QuikLook图标，点退出，找到QuikLook.exe 双击运行即可@soulans

**Comment by songtengfei95** [comment]
安装插件后打开好卡，没有不安装快，可是不安装又没办法查看word
