### ISSUE TITLE
Don't confuse Share icon with OpenWith icon...

### ISSUE THREAD

**Issue by Kenya-West** [QL-Win/QuickLook#361]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm confused with Share icon that does "Open with" action. Windows uses Share icon to actually call sharing dialog.

**Describe the solution you'd like**
Replace Share icon with OpenWith one.

**Describe alternatives you've considered**
No alternatives, it harms UX.

**Additional context**
This icon that app uses to "Open with" is actually for sharing: ![e72d 1](https://user-images.githubusercontent.com/12271104/45592615-7187b500-b9ad-11e8-9b3f-426498c22d93.png)
Replace it with OpenWith: ![e7ac 1](https://user-images.githubusercontent.com/12271104/45592618-83695800-b9ad-11e8-9b63-97ef5a78d8b0.png)

**Comment by Pythians** [comment]
他的意思是 功能是 OpenWith 时用 

![image](https://user-images.githubusercontent.com/7250578/45725611-2c05fa80-bbee-11e8-9763-4b8172f13697.png)

功能是 Share 时， 用
![image](https://user-images.githubusercontent.com/7250578/45725649-4fc94080-bbee-11e8-9bf8-3cd7a04f4638.png)

不同功能对应不同图标

**Comment by xupefei** [comment]
I am not confident about this by just looking at his words.
I _thought_ he means what you said and just asking for his confirmation.

Cheers,
Paddy

**Comment by Kenya-West** [comment]
OK, let me explain. There's "Open With" button:

![image](https://user-images.githubusercontent.com/12271104/45746334-fab51b00-bc3d-11e8-8310-499311d5ae71.png)

It actually should be this:

![image](https://user-images.githubusercontent.com/12271104/45746462-54b5e080-bc3e-11e8-9415-27bf8418079a.png)

Have you noticed the change? The current version QuickLook uses wrong icon for "Open With" button. Replace the icon with appropriate one.

I am running QuickLook 3.6.2 (UWP) on the latest Windows 10 April 2018 Update

**Comment by xupefei** [comment]
Thanks for the clarification, now I understand.
The icon should be like:
On Windows 10 >= 16299:

- having the "Share" icon
- having tip "Share..."
- opening the Sharing UI

Otherwise:

- having the "Open with" icon
- having tip "Open With..."
- opening the Open With dialogue

Your Windows 10 April 2018 Update belongs to the first group.
