### ISSUE TITLE
.msi package version can't preview powerpoint file (pptx)

### ISSUE THREAD

**Issue by spindensity** [QL-Win/QuickLook#362]
**Describe the bug**
.msi package version (v3.6.2) can't perview .pptx files, but is ok for word documents (docx). The program behavior is the same as #357 depicted, but as #355 and #356 said, the root cause of #357 is missing pdfium.dll in Windows Store package, .msi package should not be affected.

**To Reproduce**
1. Select any pptx file;
2. Press spacebar;
3. The same error as #357 described happens.

**Desktop (please complete the following information):**
 - OS Version: Win10 1803;
 - QuickLook Version: .msi package v3.6.2;
 - Plugin Version: https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer/releases/download/1/QuickLook.Plugin.OfficeViewer.qlplugin

**Screenshots and Exception Log**
See #357.

**Comment by xupefei** [comment]
Are there two pdfium.dll in QuickLook/Plugins/PDFViewer/x86[x86] folder?

**Comment by xupefei** [comment]
Fixed: https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer/releases
