### ISSUE TITLE
.msi package v3.6.2 can't render some pptx files contained Chinese characters correctly

### ISSUE THREAD

**Issue by spindensity** [QL-Win/QuickLook#363]
**Describe the bug**

.msi package v3.6.2 can't render some pptx files contained Chinese characters correctly, all Chinese characters disappeared in the preview window. See screenshot.

The bug probably caused by default Syncfusion PDF converter settings not properly handle font infomation. New Syncfusion version provide parameters to embed fonts into target PDF, see [official docs](https://help.syncfusion.com/cr/cref_files/file-formats/Syncfusion.PresentationToPdfConverter.Base~Syncfusion.PresentationToPdfConverter.PresentationToPdfConverterSettings_members.html). Maybe it would work.

**To Reproduce**
1. Download then select [DICOM.pptx](https://github.com/QL-Win/QuickLook/files/2386596/DICOM.pptx);
2. Press spacebar;
3. All Chinese characters disappeared in the preview window.

**Expected behavior**
All characters display correctly.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803;
 - QuickLook Version: .msi package v3.6.2;
 - Plugin Version: [OfficeViewer Plugin v2](https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer/releases/download/2/QuickLook.Plugin.OfficeViewer.qlplugin)

**Screenshots and Exception Log**
Office:
![pptx_in_office](https://user-images.githubusercontent.com/33576822/45596825-c1d63580-b9f4-11e8-98c3-c254db4ce37e.png)

Quicklook:
![pptx_in_preview](https://user-images.githubusercontent.com/33576822/45596828-c4d12600-b9f4-11e8-8377-9e444a7db3fe.png)

**Comment by xupefei** [comment]
Unfortunately, `EmbedFonts` does solve the problem. Maybe it is better to use https://github.com/QL-Win/QuickLook/issues/358 to solve this issue.

**Comment by spindensity** [comment]
I have "华文楷体" installed on my PC.

Indeed this font is bundled together in office 365.
![font_installed](https://user-images.githubusercontent.com/33576822/45600035-b6046680-ba28-11e8-9ba6-88b9a55a6051.png)
![fonts_dir](https://user-images.githubusercontent.com/33576822/45600054-11365900-ba29-11e8-8f31-98a1692d94df.png)

**Comment by emako** [comment]
现在可以获取新版本插件了，问题没有复现
The new version of the plugin is now available

https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer/releases
