### ISSUE TITLE
add full metadata view and edit feature.

### ISSUE THREAD

**Issue by MadPerson** [QL-Win/QuickLook#364]
Quciklook is a great app.

and it's need full enhancement, so quick look means full look in every angle
but we miss the metadata in here.
so i request you to add full support of full metadata.  
you can add metadata icon in top left corner and you can center the file name also.
please add metadata view and and option to edit it.

thanks and sorry for bad english..

**Comment by xupefei** [comment]
Metadata viewing will land along with #183. Editing, however, will never be supported. Use separate tool instead.
