### ISSUE TITLE
QuickLook in File Browsing Dialog

### ISSUE THREAD

**Issue by bearz314** [QL-Win/QuickLook#366]
Hi, first of all thanks so much for this app! You're really amazing!

I realised QuickLook works almost everywhere in Windows File Explorer, except in file browsing dialogs. For example, when choosing a file for internet upload or attaching to an email, it is not possible to preview the files with QuickLook.

Support for File Browser Dialogs could be added.

Thanks! <3

**Comment by xupefei** [comment]
This issue has been raised multiple times.
See https://github.com/QL-Win/QuickLook/wiki/Difference-Between-Distributions.

**Comment by florinb19** [comment]
Hi, I see this is a closed ticket. I came across this issue recently and I can't seem to find the content of the link above. Can someone help regarding previewing files in browsing file dialog?

**Comment by xupefei** [comment]
> Hi, I see this is a closed ticket. I came across this issue recently and I can't seem to find the content of the link above. Can someone help regarding previewing files in browsing file dialog?

https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions
