### ISSUE TITLE
0.3.5 works fine, later versions don't preview audio and video on fresh latest Win10 install

### ISSUE THREAD

**Issue by Jimmm** [QL-Win/QuickLook#371]
**Describe the bug**
Install any msi git version greater than 0.3.5 on a fresh Win10. All video and audio files give error, that some dll can't be read (the error message goes beyond visible window)

**To Reproduce**
1. Install latest Win10
2. Install version 3.6.2
3. Check any video or audio

**Expected behavior**
Video or audio preview

**Desktop (please complete the following information):**
 - Windows 10 1803
 - QuickLook Version - msi 3.6.2 from git

**Screenshots and Exception Log**
Will add them as I return home, my PC at work gives no errors.

**Comment by xupefei** [comment]
> (the error message goes beyond visible window)

Is there still a part of it showing? If so, put it here.

**Comment by Jimmm** [comment]
QuickLook.Exception.log shows nothing
Screen: 
![screenshot 788](https://user-images.githubusercontent.com/960136/45852223-e9076c80-bd3e-11e8-9a71-41f04c10028e.jpg)

**Comment by xupefei** [comment]
I guess this is due to your graphics card. What card and CPU you have?

**Comment by bantya** [comment]
CPU: Intel(R) Core(TM) i5-3210M CPU @2.50GHz
GPU: NVIDIA GeForce GT 640M
