### ISSUE TITLE
Pic preview is damaged for some files

### ISSUE THREAD

**Issue by Jimmm** [QL-Win/QuickLook#372]
**To Reproduce**
1. Try this picture https://yadi.sk/i/2U4CfKeY1the_g
2. I see this: https://yadi.sk/i/I1Qn4uUwm2fwlw

**Expected behavior**
See a pic in a preview

**Desktop (please complete the following information):**
 - Windows 10 1803
 - QuickLook 3.6.2, msi git

**Screenshots and Exception Log**
logs are clean

**Comment by xupefei** [comment]
The image has a wrong resolution data. See https://github.com/QL-Win/QuickLook/issues/353 about how to fix it.
