### ISSUE TITLE
GIF Playback Speed

### ISSUE THREAD

**Issue by KuroChloe** [QL-Win/QuickLook#374]
When viewing GIFs with browser or video player, be it Firefox/IE or MPV.. GIFs seem to play at faster speed than with QuickLook or even IrfanView.
Is this something that can be fixed?

**Comment by xupefei** [comment]
Unfortunately no. There is no good gif render which ensures both memory efficiency and playing speed.

**Comment by KuroChloe** [comment]
> 
> 
> Unfortunately no. There is no good gif render which ensures both memory efficiency and playing speed.

Thanks for the reply.
