### ISSUE TITLE
i want that quicklook can Compatible with qdir，how to？

### ISSUE THREAD

**Issue by heartacker** [QL-Win/QuickLook#376]
there two question

1.  it seems that qidr is compatible with qdir，how to fix？

**Comment by xupefei** [comment]
https://github.com/QL-Win/QuickLook/wiki/Integration-and-Development:

> It also can be used together with other File Managers via a custom hotkey that fires event QuickLook.exe "C:\path\to\your\file.txt"

I am not sure if QDir supports this...


What's your second question?

**Comment by fournoas** [comment]
Q-Dir does not support custom hotkey

**Comment by rabelux** [comment]
Then the dev of qdir has to integrate QuickLook.
A how-to can be found in the wiki: https://github.com/QL-Win/QuickLook/wiki/Develop%2C-build-and-integrate
