### ISSUE TITLE
Office powerpoint load very slow since 0.3.6

### ISSUE THREAD

**Issue by billyjinshi** [QL-Win/QuickLook#378]
Office powerpoint load very slow since 0.3.6 with plugin mode: 28MB pptx need about 15 seconds, even slower than open with powerpoint.
Version 0.3.5 loading is much faster, same 28MB pptx only takes 3~4 seconds.

**Comment by xupefei** [comment]
Can be solved by https://github.com/QL-Win/QuickLook/issues/358.
I will now close this issue.
