### ISSUE TITLE
QuickLook Program Crash

### ISSUE THREAD

**Issue by Mornwind** [QL-Win/QuickLook#384]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
When I was trying to preview some music in turn, QuickLook got crashed unexpectedly.
我正在用 QuickLook 挨个预览一些音乐，它突然就崩溃了。
I saved some error logs from Event Viewer in Computer Management, and uploaded them as attachments with the logs from QuickLook itself.
我从计算机管理的事件查看器里保存了一些错误信息，并和 QuickLook 自身的日志一起上传为附件。

**To Reproduce**
1. Go to my music files (.mp3/.wav)
    找到我的音乐文件（.mp3/.wav）
2. Click on 'Space', and start to listen
    按 Space 键预览音乐
3. Click on 'Space' to close
    按 Space 键停止预览
4. Change music files in turn, and repeat the above steps
    依次更换音乐文件，并重复以上操作
5. Program crashed suddenly after repeating several times
    在几次操作以后，程序突然就崩溃了

**Expected behavior**
Prevent QuickLook from crashing.
让 QuickLook 不再崩溃。

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 1809
 - QuickLook Version: v3.6.2 from .msi version

**Screenshots and Exception Log**
[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/2453601/QuickLook.Exception.log)

[QuickLook_Crash_181007.txt](https://github.com/QL-Win/QuickLook/files/2453605/QuickLook_Crash_181007.txt)

**Comment by xupefei** [comment]
I have observed this issue some days ago and tried a fix: 49d0c9eebedcb117283f846c9a54db550eb376f0.

Can you try with the latest Nightly: https://ci.appveyor.com/project/xupefei/quicklook/build/572/artifacts?

**Comment by Mornwind** [comment]
> I have observed this issue some days ago and tried a fix: [49d0c9e](https://github.com/QL-Win/QuickLook/commit/49d0c9eebedcb117283f846c9a54db550eb376f0).
> 
> Can you try with the latest Nightly: https://ci.appveyor.com/project/xupefei/quicklook/build/572/artifacts?

I've tried the latest Nightly version you mentioned above. It works well. No crash occurs this time when I switch media files quickly. Thanks for a lot!
