### ISSUE TITLE
[FeatureRequest] Any plan to support vector image files preview? Such as emf, wmf, svg...

### ISSUE THREAD

**Issue by WalterMa** [QL-Win/QuickLook#385]
Want to to do we have any plan to support vector images?
For example, emf, svg, wmf and eps.

Currently when preview emf, it shows like:
![image](https://user-images.githubusercontent.com/7560132/46599447-f7fd6580-cb19-11e8-94b9-940ba73394f0.png)

**Additional Information**
I'm not fammilar with development of windows appliction. But I tried to search related posts on Google (Hope these will be useful):
For emf and wmf:
[How to: Load and Display Metafiles](https://docs.microsoft.com/en-us/dotnet/framework/winforms/advanced/how-to-load-and-display-metafiles)
For svg:
[SVG.NET](https://github.com/vvvv/SVG)
For eps and ai:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/a28b4305-7f58-48ad-ad63-03fce656fb93/cwpf-viewing-and-eps-ai-vector-looking-for-tutorial-examples-api?forum=wpf

**Comment by WalterMa** [comment]
Update:
Related Issues: https://github.com/QL-Win/QuickLook/issues/336

1. NConvert (used for image preview now) does support svg, eps, emf, wmf... 
    https://www.xnview.com/en/nconvert/#formats
2. There has a GFL sdk also supports these formats.
    https://www.xnview.com/en/GFL/index.php
    Moreover, found a c# wrapper for this sdk: https://newsgroup.xnview.com/viewtopic.php?f=4&t=33986&sid=62e852aa1f50633c2845221050ce4eaa
3. Actually, GFLSDK, Nconvert, XnView, ... use same library. 
    According to [their author](https://newsgroup.xnview.com/viewtopic.php?t=23113)

**Comment by xupefei** [comment]
For .ai, I am afraid the link you provided is a plugin for Adobe Illustrator, it just allows Adobe Illustrator to save a file into .xaml.

For .eps, it can be converted into PDF first.

Let me test NConvert for emf and wmf.

**Comment by JacobDB** [comment]
Any status update on this?

**Comment by StefanKrapf** [comment]
I would like to have previews of EPS files too. SVG and the other vector formats would be even nice. Thanks a lot for considering to integrate it.

**Comment by rabelux** [comment]
@xupefei did you get to try emf files with nconvert? I don't know if my thinking is too narrow here but if formats are supported by NConvert (see _NConvert/docs/Formats.txt_) shouldn't it be possible to just add them to the format-list in _QuickLook.Plugin.ImageViewer/Plugin.cs_?
[Here](https://github.com/QL-Win/QuickLook/files/3526613/Sicherungstypen.txt) is a sample file if you need one, rename it to .emf first

**Comment by rabelux** [comment]
@xupefei may I remind you of my last unanswered question?

**Comment by xupefei** [comment]
Sorry for not answering your question.

I just switched the ImageVIewer from NConvert to ImageMagick in the latest Nightly. ImageMagic might be able to handle all formats the OP mentioned (haven't tried).

Yes, just add it to the format list is enough.

**Comment by rabelux** [comment]
No problem, thx for replying now ;)
Maybe to be of some form of help, I looked up which of the requested formats are supported by imagemagick und what notes they mention on https://imagemagick.org/script/formats.php

file extension | notes from imagemagick
---|---
emf|Only available under Microsoft Windows. Use [-size](https://imagemagick.org/script/command-line-options.php#size) command line option to specify the maximum width and height.
eps|Requires [Ghostscript](http://www.cs.wisc.edu/~ghost) to read
wmf|Requires [libwmf](http://sourceforge.net/projects/wvware/). By default, renders WMF files using the dimensions specified by the metafile header. Use the -density option to adjust the output resolution, and thereby adjust the output size. The default output resolution is 72DPI so -density 144 results in an image twice as large as the default. Use -background color to specify the WMF background color (default white) or -texture filename to specify a background texture image.

**Comment by xupefei** [comment]
EPS plugin is now available: https://github.com/QL-Win/QuickLook/wiki/Available-Plugins

Enjoy :)

**Comment by rabelux** [comment]
Thanks a lot!!!! :tada: 
Have really been looking forward to emf-support for almost 2 years :innocent:
