### ISSUE TITLE
can't preview avi file

### ISSUE THREAD

**Issue by erickksun** [QL-Win/QuickLook#386]
**Describe the bug**
can't play "C:\Program Files\Common Files\Microsoft Shared\ink\en-US\delete.avi"

**To Reproduce**
1. Go to directory "C:\Program Files\Common Files\Microsoft Shared\ink\en-US"
2. hit spacebar in any avi file 
3. See error in the black screen
![error](https://raw.githubusercontent.com/iamsunxing/images/master/1.png)
**Desktop (please complete the following information):**
 - OS Version: windows7 sp1
 - QuickLook Version: 3.6.2  .zip

**Comment by iamsunxing** [comment]
> Are you able to play this file with Windows Media Player?

yeah

**Comment by rabelux** [comment]
On my Win 7 Windows Media Player plays the file and I can confirm the weird behaviour of previewing avi.
It Takes about 8 seconds to load an avi. With the mentioned "Delete.avi" from microsoft the seekbar is not correct and the preview stutters. With a private avi it also takes about 8 sec to load, let's say the video is 10s, I do now get to see the last 2 sec. Pressing play plays the loaded private avi without problems

**Comment by emako** [comment]
Outdated question, please continue to reply if you have any questions
