### ISSUE TITLE
this Gif animation does not play normally

### ISSUE THREAD

**Issue by iamsunxing** [QL-Win/QuickLook#388]
**Describe the bug**
this Gif animation does not play normally
![gif](https://raw.githubusercontent.com/iamsunxing/images/master/webwxgetmsgimg.gif)

**To Reproduce**
Download this GIF, and have a try
by the way,  played well in Internet Explorer

**Desktop (please complete the following information):**
 - OS Version: windows 7 sp1
 - QuickLook Version: 3.6.2 .zip

**Comment by xupefei** [comment]
I can reproduce. Seems like an issue of the .NET Gif Decoder.

**Comment by SheldonCurtiss** [comment]
@xupefei This is still an issue 3 years later. Any suggestions?

**Comment by s0urcelab** [comment]
#767 same issue

**Comment by xupefei** [comment]
Let's continue in #767.
