### ISSUE TITLE
“.md” file support

### ISSUE THREAD

**Issue by erickksun** [QL-Win/QuickLook#391]
if support Markdown file(“.md”) , will be better.

**Comment by xupefei** [comment]
QuickLook has already supported such format. Isn't it?

**Comment by xupefei** [comment]
How about other formats?

**Comment by WalterMa** [comment]
In my PC with .msi version, md preview works fine.

**Comment by rabelux** [comment]
Also working perfectly with .msi version on Win7 64bit

**Comment by notastudio** [comment]
I have the same problem. Any other formats work fine but when previewing markdown, QuickLook just shows a white screen. I am using v3.6.6 (the bug also exists in the older versions) .msi distribution on Win10 1909 64-bit.

**Comment by emako** [comment]
Markdown viewer is depends on webview2
