### ISSUE TITLE
failed to preview pdf file

### ISSUE THREAD

**Issue by iamsunxing** [QL-Win/QuickLook#392]
when I preview a pdf file,it occasionally occured  that:
![](https://raw.githubusercontent.com/iamsunxing/images/master/5.bmp)

I recommend to focus on stability first, then become more powerful.

**Comment by xupefei** [comment]
https://github.com/QL-Win/QuickLook/issues/new/choose:
> Please follow this template or your issue will be closed

**Comment by iamsunxing** [comment]
I don't know that somehow it crashed Occasionally! No complexed procedures.
