### ISSUE TITLE
how to hide the icon in notifications area

### ISSUE THREAD

**Issue by chhsgithub** [QL-Win/QuickLook#393]
Is it possible that hidden the icon in notifications area? 
I dont want too many icons in notifications area.

![image](https://user-images.githubusercontent.com/19844522/46796480-1eefad80-cd4d-11e8-88de-7dfbe06c0516.png)

**Comment by rabelux** [comment]
A quick search for the keyword "hide" in issues brought following results:
- #191 
- #231
- #323
- #368 

feel free to pick any answer in one of those

**Comment by sqqqs** [comment]
I think that a lot of users want to have this option. Maybe you need to add it?

**Comment by chhsgithub** [comment]
> I think that a lot of users want to have this option. Maybe you need to add it?

I made changes in the source code and compiled it. It works now perfectly.

**Comment by maximang** [comment]
> > I think that a lot of users want to have this option. Maybe you need to add it?
> 
> I made changes in the source code and compiled it. It works now perfectly.

Can you share it?

**Comment by xupefei** [comment]
Solved in https://github.com/QL-Win/QuickLook/issues/729.

**Comment by rabelux** [comment]
you forgot to close this one
