### ISSUE TITLE
MATLAB code display bug

### ISSUE THREAD

**Issue by TheAnsIs42** [QL-Win/QuickLook#398]
an error hapened in display MATLAB code
![matlabcode](https://user-images.githubusercontent.com/44214674/47051205-38ed1e00-d19b-11e8-861c-be76c88b71d7.png)
![displaycode](https://user-images.githubusercontent.com/44214674/47051206-38ed1e00-d19b-11e8-9d3a-ca07c64bb6f5.png)
upper screenshot is the matlab code and the other is display from the programme
notice that the wrong displayed '（' is not the bracket in english which like'('
os version:windows 1803
QuickLook Version: 3.6.2 from windows store

**Comment by xupefei** [comment]
This is due to file encoding. Quite a hard-to-solve problem because our `CharDet` component will not return GBK encoding by only seeing a single Chinese/Japanese/Korean character.

I guess we can make an ad-hoc tweak for this. Can you share this file with me?

**Comment by TheAnsIs42** [comment]
alright, but how can i share this file, github does not support the file type of it.

**Comment by xupefei** [comment]
Zip it then you can upload it.

**Comment by TheAnsIs42** [comment]
[lab2task_11.zip](https://github.com/QL-Win/QuickLook/files/2521277/lab2task_11.zip)
here it is

**Comment by rabelux** [comment]
seems like the file is corrupt. matlab displays it the same way quicklook does and that means showing `('Vc/Vin£¨dB)`
