### ISSUE TITLE
HEIC or H.265 Support in Windows

### ISSUE THREAD

**Issue by wss7932** [QL-Win/QuickLook#400]
Since Windows 10 now has HEIC file support, and Apple has made HEIC the native format (I know jpg is still there but, the file size savings is substantial) I'd like to be able to preview .heic files.  I don't have the first clue as to how to build a plugin but, since I've adopted this format and am working across both Mac and PC with a shared library, this would be fantastic.

**Comment by xupefei** [comment]
If you change the file extension to `.jpg`, can you preview it in QL?

**Comment by xupefei** [comment]
Fixed.
