### ISSUE TITLE
cannot view static gif files in QuickLook 

### ISSUE THREAD

**Issue by chaloots** [QL-Win/QuickLook#401]
Hitting the spacebar results in nothing but a blank, black window, though functioning normally with animated gifs.

64-bit Windows 10 Pro 1803
QuickLook github Version 3.6.2

**Comment by helixfinder** [comment]
I have the same issue for Dilbert strip gifs (that is, gifs saved from the dilbert.com site).

**Comment by kekukui** [comment]
**Confirmed, the Dilbert GIFs do not render** (sample below)

![SQL](https://user-images.githubusercontent.com/20834957/54875760-f5967b80-4dda-11e9-8af4-5e249c2aac5c.gif)

**For reference, the complete specification for this format is here**
http://www6.uniovi.es/gifanim/gif89a.txt

**Comment by DejayRezme** [comment]
Same problem with almost all static gifs I save. QuickLook is an amazing software, absolutely love it, but that is the one thing that is somewhat annoying (having to convert gifs to png for viewing)

**Comment by glocalglocal** [comment]
Same here. QuickLook opens but shows a chequered black screen. Other formats inclusing png work as expected.

**Comment by xupefei** [comment]
Fixed! A new build will appear here: https://ci.appveyor.com/project/xupefei/quicklook/builds/33225541/artifacts

**Comment by glocalglocal** [comment]
Wow! This was super-fast. I can confirm v3.6.9-1 fixes the static gif issue. Thanks!

**Comment by chaloots** [comment]
So far, so good. Thank you for the update.
