### ISSUE TITLE
ICC profiles are not loaded

### ISSUE THREAD

**Issue by Venzo92** [QL-Win/QuickLook#403]
**Describe the bug**
The image should use colors of the icc profile but instead loads the file without applying the icc color profile. The same issue happens with windows photo app which does not support icc profiles while the image is viewed correctly with the old windows image viewer.
The difference is clearly visible because the color appear richer and more saturated than what they should be.

**Expected behavior**
The image should use icc calibrated profile colors

**Desktop (please complete the following information):**
 - Windows 10 Latest Build
 - QuickLook Version: Windows Store latest version

**Comment by xupefei** [comment]
Further discussion goes to https://github.com/QL-Win/QuickLook/issues/329.
