### ISSUE TITLE
Make QuickLook per monitor DPI aware

### ISSUE THREAD

**Issue by Verrickt** [QL-Win/QuickLook#407]
**Is your feature request related to a problem? Please describe.**
QuickLook gets blurry when DPI changes, which is one of the following
- Change scaling factor of main display
- Move QuickLook to another monitor with different scaling factor
- Open QuickLook on another monitor with different scaling factor

**Describe the solution you'd like**
Make QuickLook per monitor DPI aware.

**Additional context**
Here's how QuickLook on my two different displays

Secondary 1080P 125% scaling
![blurry](https://user-images.githubusercontent.com/11483783/47498839-00330000-d891-11e8-9ef6-3facace8c71a.PNG)

Main 768P 100% scaling
![cleary](https://user-images.githubusercontent.com/11483783/47498842-02955a00-d891-11e8-80bc-e4df51150fa1.PNG)

**It does not look good**

Here's an awesome table I stole from https://docs.microsoft.com/en-us/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows

DPI Awareness Mode | Windows Version Introduced | Application's view of DPI | Behavior on DPI change
-- | -- | -- | --
System | Vista | All displays have the same DPI (the DPI of the primary display at the time the Windows session was started) | Bitmap-stretching (blurry)
Per-Monitor | 8.1 | The DPI of the display that the application window is primarily located on | Top-level HWND is notified of DPI change No DPI scaling of any UI elements.
Per-Monitor V2 | Windows 10 Creators Update (1703) | The DPI of the display that the application window is primarily located on | Top-level and child HWNDs are notified of DPI change   Automatic DPI scaling of:  Non-client area Theme-drawn bitmaps in common controls (comctl32 V6) Dialogs (CreateDialog*)

Right now QuickLook is System aware, so the blurry is caused by Bitmap-stretching

However, since .net framework 4.6.2, Microsoft [introduced](https://github.com/Microsoft/WPF-Samples/blob/master/PerMonitorDPI/Developer%20Guide%20-%20Per%20Monitor%20DPI%20-%20WPF%20Preview.docx?raw=true) the ability for WPF application to be natively per monitor aware when running on Windows 10 1607
> **Introduction**
> This developer guide provides developer info on how to test your WPF application with our Per Monitor DPI feature released in .NET 4.6.2 along with the Windows 10 Anniversary Update.

I've make a fork at https://github.com/Verrickt/QuickLook/tree/feature/Per-Monitor-DPI-Awareness and will open a PR once the issue is submitted.

Here's the result

Main 768P 100% scaling
![main](https://user-images.githubusercontent.com/11483783/47500125-7e44d600-d894-11e8-8416-52ff02262949.PNG)

Secondary 1080P 125% scaling
![secondary](https://user-images.githubusercontent.com/11483783/47500147-90267900-d894-11e8-994f-b3b245450ff4.PNG)

Text is not blurry any more

**Comment by Verrickt** [comment]
See PR #408

**Comment by xupefei** [comment]
I can confirm this issue. Will check your PR and merge soon.
Thank you!

**Comment by xupefei** [comment]
It's done! Thanks!
