### ISSUE TITLE
Add doc, docx, ppt visualization by default

### ISSUE THREAD

**Issue by michelecafagna26** [QL-Win/QuickLook#410]
It would be useful provide visualization for document in doc, docx format and presentation (ppt) without plugin installation

**Comment by xupefei** [comment]
Then there is a legal issue: https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer#syncfusion-components

> Customer shall not distribute any Syncfusion binaries as part of an open-source project. The open-source project will not be licensed under any viral code license or General Public License to include, but not be limited, to GNU or GPL.
