### ISSUE TITLE
Unable to view videos

### ISSUE THREAD

**Issue by umang-m** [QL-Win/QuickLook#413]
The app is unable to play video files.
![st1](https://user-images.githubusercontent.com/20592189/47635053-a032a700-db79-11e8-9c9f-45cc31758e5a.PNG)

**Comment by xupefei** [comment]
Seems related to UWP. Can you try the `.msi` version: https://github.com/QL-Win/QuickLook/releases/tag/3.6.2?

**Comment by umang-m** [comment]
Thanks for your reply.
Even after installing .msi version, the error in the screenshot still occur.

**Comment by xupefei** [comment]
I tried with a freshly installed Windows 10 and I can't reproduce the problem.

Can you run the msi version, preview a video and resize the window larger, then upload a screenshot here?

**Comment by umang-m** [comment]
Sure.

**Comment by umang-m** [comment]
Screencap(Enlarged)
![screenshot 1](https://user-images.githubusercontent.com/20592189/47874262-61327900-de39-11e8-8412-5cc2343d6acd.png)

**Comment by xupefei** [comment]
Do you have a `VCRUNTIME140.DLL` file in `C:\windows\system32`?

**Comment by xupefei** [comment]
Can you tr overwriting `EVRPresenter32.dll` and `EVRPresenter64.dll` in `C:\Users\<username>\AppData\Local\Programs\QuickLook\QuickLook.Plugin\QuickLook.Plugin.VideoViewer`?
[EVRPresenter-MT.zip](https://github.com/QL-Win/QuickLook/files/2540141/EVRPresenter-MT.zip)

**Comment by umang-m** [comment]
Thank you for your responses. The app is now able to view videos, by overwriting the mentioned files with your attachment.

Also, the vcruntime140.dll file is present in system32, but is within different folders of system32.

**Comment by xupefei** [comment]
Thanks! The issue is now fixed.

**Comment by nobef** [comment]
> Can you try overwriting `EVRPresenter32.dll` and `EVRPresenter64.dll` in `C:\Users\<username>\AppData\Local\Programs\QuickLook\QuickLook.Plugin\QuickLook.Plugin.VideoViewer`? [EVRPresenter-MT.zip](https://github.com/QL-Win/QuickLook/files/2540141/EVRPresenter-MT.zip)

This fix worked, but the problem still exists...
Win 11 x64
