### ISSUE TITLE
Quicklook won't start?

### ISSUE THREAD

**Issue by Godly75** [QL-Win/QuickLook#414]
Hi I used Quicklook before from the Windows Store, and I love it.
I was trying to run the portable version from QL, but after uninstalling the previous (chinese?) version and starting the portable, the icon always disappears from the system tray.
What is wrong?

I have this error message from windows log:

Beschrijving
Pad naar toepassing met fout:	C:\Program Files\WindowsApps\21090PaddyXu.QuickLook_3.6.3.0_neutral__egxr34yet59cg\Package\QuickLook.exe

Probleem met handtekening
Naam van probleemgebeurtenis:	CLR20r3
Probleemhandtekening 01:	QuickLook.exe
Probleemhandtekening 02:	3.6.2.0
Probleemhandtekening 03:	5b9cbb01
Probleemhandtekening 04:	QuickLook.Plugin.VideoViewer
Probleemhandtekening 05:	3.6.2.0
Probleemhandtekening 06:	5b9cbb02
Probleemhandtekening 07:	3f
Probleemhandtekening 08:	7
Probleemhandtekening 09:	System.NullReferenceException
Versie van besturingssysteem:	10.0.17134.2.0.0.256.48
Landinstelling-id:	2067
Aanvullende informatie 1:	2a08
Aanvullende informatie 2:	2a080567cb65b8e686310d77a361738a
Aanvullende informatie 3:	b53f
Aanvullende informatie 4:	b53f35aeb9ce35e4ad3013cb7af5a00d

Extra informatie over het probleem
Bucket-id:	9824061c58261c0f230688f909300909 (1370933739763271945)

**Comment by xupefei** [comment]
You have encountered a bug in the video viewer.
Use this newer version which has this bug fixed: https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts

**Comment by Godly75** [comment]
Thank you, unfortunate, the same happens with this last version.
The icon appears and then dissapears.
I installed from the windows store now but prefer the portable.
Also, the windows store version crashes on a regular base (latest W10)


Op ma 29 okt. 2018 om 23:06 schreef Paddy Xu <notifications@github.com>:

**Comment by xupefei** [comment]
Have you tried https://github.com/QL-Win/QuickLook/issues/1?

**Comment by Godly75** [comment]
Thank you, that worked indeed ! :)

Op ma 29 okt. 2018 om 23:11 schreef Paddy Xu <notifications@github.com>:
