### ISSUE TITLE
PDF thumbnails are too low quality

### ISSUE THREAD

**Issue by jeremyhart** [QL-Win/QuickLook#416]
The thumbnails on a multipage PDF are too low quality, can't really tell what's on the page.
This happened after a recent update, I can't remember which one sorry.

Was this done to increase performance or just overlooked?

**Comment by xupefei** [comment]
It is to reduce memory usage.
Thumbnails are occupying a lot of memory and cannot be released when scrolling. I am afraid that increasing the resolution will make things even worse.

**Comment by lingliugithub** [comment]
one vote for this issue.
Is there any possible option/configuration/setting to let the user decide a balance between the quality and loading speed of PDF thumbnail.
The quick look is very useful but sometime the low-quality rendering of pdf file undermines the functionality.

**Comment by emako** [comment]
In the current version, you can use Ctrl+mouse wheel key to zoom PDF
