### ISSUE TITLE
PDF file annotations (un-flattened) do not show

### ISSUE THREAD

**Issue by SevoMan** [QL-Win/QuickLook#421]
When a PDF document is edited in another program (Adobe/Foxit/Edge), with annotations, text boxes, shapes, etc.. and saved... QuickLook **will not show the annotations** and instead shows the pre-annotation original file.  

Then only time QuickLook will show these annotations is if the file is 'flattened'/made permanent.  Windows thumbnails/explorer preview (and also the original Mac QuickLook) all show these unsaved annotations and so should QuickLook.  Please fix.  Excellent program otherwise.

**Comment by rabelux** [comment]
@xupefei I tried digging into this issue and stumbled upon a few things.
First possible solution from [stackoverflow](https://stackoverflow.com/questions/42133552/how-to-show-annotations-in-a-pdf-using-pdfium-viewer) is using following code snippet:
```
doc = PDDocument.load(FilePath);
PDPage page = (PDPage)doc.getDocumentCatalog().getAllPages().get(pageNum);
int rotPD = page.findRotation();
PDRectangle pageBound = page.findCropBox();
PDRectangle rect = ModifyRectAccordingToRotation(rectangle, rotPD, pageBound);
PDAnnotationLink txtLink = new PDAnnotationLink();
    PDBorderStyleDictionary borderULine = new PDBorderStyleDictionary();
                    borderULine.setStyle(PDBorderStyleDictionary.STYLE_UNDERLINE);
borderULine.setWidth(0);
txtLink.setBorderStyle(borderULine);
PDActionRemoteGoTo remoteGoto = new PDActionRemoteGoTo();
PDComplexFileSpecification fileDesc = new PDComplexFileSpecification();
fileDesc.setFile(System.IO.Path.GetFileName(path));
remoteGoto.setOpenInNewWindow(true);
remoteGoto.setFile(fileDesc);
txtLink.setAction(remoteGoto);
txtLink.setRectangle(rect);
page.getAnnotations().add(txtLink);
```

Second approach is using the FPDF_ANNOT flag. The render()-function can take this flag as an input (found in [PdfiumViewer/PdfiumViewer/PdfDocument.cs](https://github.com/pvginkel/PdfiumViewer/blob/b253afcfa00bb2f94ef3e8e15efc066e6b3af0f1/PdfiumViewer/PdfDocument.cs) but you're using a different overload of this function `PdfDocumentWrapper.Render(CurrentPage, factor)` that I couldn't find in the library, so I don't where your functions comes from and whether it can handle this flag. Hope this helps.

**Comment by mooflu** [comment]
The code passes the an annotation flag here: https://github.com/QL-Win/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.PDFViewer/PdfPageExtension.cs#L65
