### ISSUE TITLE
Double click the preview window

### ISSUE THREAD

**Issue by i5151** [QL-Win/QuickLook#423]
双击窗口应该以默认程序打开正在预览的文件，一般人习惯都是这个操作。

**Comment by i5151** [comment]
The same, QuickLook is also opened with the default program shown in the upper right corner. In doing so, it is in line with general usage habits and is more efficient.

**Comment by rabelux** [comment]
I strongly agree with @xupefei here, double-clicking text should highlight it and not open a program. IMHO pressing enter is fast enough as a shortcut and meets usage habits
