### ISSUE TITLE
Can't uninstall from Microsoft Store

### ISSUE THREAD

**Issue by starpotion** [QL-Win/QuickLook#431]
Attempting to uninstall the program from Microsoft Store prompts Windows to change my language to Japanese, and attempting to uninstall it from Settings greys out the uninstall button.
![applicationframehost_2018-11-22_11-54-33](https://user-images.githubusercontent.com/10054020/48921634-7f463480-ee4d-11e8-9e45-ed7f1698daf4.png)

**Comment by xupefei** [comment]
I am very sure that your issue is not related to QL. Maybe just another Windows 10 bug.
