### ISSUE TITLE
Unable to open multiple windows and despite "prevent closing" being off, the window does not close

### ISSUE THREAD

**Issue by DragoCubed** [QL-Win/QuickLook#432]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
I'm unable to open multiple windows and despite "prevent closing" being off, the window does not close. When I select a different file in file explorer it opens it in that same window, replacing the previous file preview.

**To Reproduce**
1. Go to File Explorer
2. Hit space on a file
3. Go back to File Explorer
4. Hit space on another file
5. Issue. The other file preview opens in the Quicklook preview window the first file was previewed in.

**Expected behavior**
There should be two Quicklook windows.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803
 - QuickLook Version: 3.6.4 exe

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log` (`.msi` or `.zip` version) or `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log` (Windows Store version).

Don't have screenshots. No exception log available.

**Comment by xupefei** [comment]
This is expected. You will have two windows if you do the following:

1. Go to File Explorer
2. Hit space on a file
3. Click the "Prevent Closing" button <- you missed this
4. Go back to File Explorer
5. Hit space on another file
