### ISSUE TITLE
When a QuickLook window is launched, it does not become the active window

### ISSUE THREAD

**Issue by DragoCubed** [QL-Win/QuickLook#433]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
When I launch a QuickLook window, the QuickLook window does not become the active window and File Explorer stays active. Clicking on File Explorer does not bring the QuickLook window behind as File Explorer is currently active. It's particularly annoying when I open a preview and press the up and down arrow keys and the file changes in the same window 

For some odd reason, QuickLook is the last of the list of windows on alt+tab. I have no idea if this is related or not so I just put this here. I believe this may be related to #432

**To Reproduce**
1. Go to File Explorer
2. Select a file
3. Press the space bar

**Expected behavior**
It expect QuickLook to be active when I preview something with it,
**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803
 - QuickLook Version: 3.6.4 exe

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log` (`.msi` or `.zip` version) or `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log` (Windows Store version).

N/A

**Comment by fauzie811** [comment]
I believe that is the intended behavior. This software is trying to replicate MacOS's Quick Look feature, and that's exactly how it behaves in MacOS.

**Comment by xupefei** [comment]
Yes, this is expected.
