### ISSUE TITLE
Program stops responding when attempting to preview from Everything

### ISSUE THREAD

**Issue by ghost** [QL-Win/QuickLook#435]
**Describe the bug**
Program stops responding when I press `spacebar` inside an `Everything` (everything is a desktop search program, available for free at http://www.voidtools.com/) window.

**To Reproduce**
1. Search for a file using everything
2. Select a file
3. Press spacebar

**Expected behavior**
Quicklook should display the file. Instead, it permanently stops responding. It then no longer display any file even from windows explorer, and does not respond to context menu.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803 x64
 - QuickLook Version: latest version from Windows Store

**Screenshots and Exception Log**
There are no logs available in any of these folders.

**Comment by Cxin-Kong** [comment]
I also encountered the same problem, quicklook did not react in everything.
OS Version: Windows 10 1809 x64
QuickLook Version: 3.6.4 msi
everything Version：V1.4.1.895 (x64)

**Comment by xupefei** [comment]
QL sends CTRL+C key to Everything to get the currently-selected file - this operation should work in most cases.
Are you using any HIPS software? Also, try to temporary disable your antivirus software.

**Comment by pedrogarcia** [comment]
> Are you using any HIPS software? Also, try to temporary disable your antivirus software.
No HIPS. Anti-virus is default Windows Defender. Even when it is turned off, the issue is reproducible.

**Comment by rabelux** [comment]
Old issue so I guess this is not present anymore.
