### ISSUE TITLE
*.mid midi player

### ISSUE THREAD

**Issue by Godly75** [QL-Win/QuickLook#436]
I love quick look ! 
It would be handy to have a midi file splayer, it's played by the windows media player now, but preview in Quicklook would be great

**Comment by Godly75** [comment]
bump :)

**Comment by xupefei** [comment]
I guess the LAVFilters component does already support MIDI files. Let me try.

**Comment by CitizenBen** [comment]
Hello,
What about .mid files, are you close find a way to ear them through Quicklook (it would be really fine) or is it not that easy ?
Thanks

**Comment by xupefei** [comment]
It's not that easy. Both FFmpeg and LAVFilters are not playing MIDI files, so QuickLook, which ultilises FFmpeg and LAVFilters, is unable to play MIDI either.

**Comment by xupefei** [comment]
Old thread but still effective today: https://lists.libav.org/pipermail/ffmpeg-user/2007-May/008983.html
