### ISSUE TITLE
Windows focus switching issue in Total commander

### ISSUE THREAD

**Issue by FrankSFLYS** [QL-Win/QuickLook#437]
I am using Total Commander and I need to use F3 to perform preview, but it's not a problem. ~~The problem is that I have to click on the X button or press F3 again **without moving my cursor on another file**. Which means when I actived the NC choosing option, I have to move my cursor back to the file name I opened and press F3 to close the preview window, and it slows down my action. (nobody wants to locate on a X button on middle of a screen right?) So I suggest the ESC to close feature be added soon.~~ Thanks!

**Comment by FrankSFLYS** [comment]
It is related with another issue #2 but it was closed so I opened a new one.

**Comment by FrankSFLYS** [comment]
Sorry but I found the problem was not about Esc key, it came up because the windows focus didn't switch automatically to the preview window so no key events been responsed. May it also be a problem?

**Comment by xarthurx** [comment]
Yeah, the problem is not which key to press. The problem is when press F3, it doesn't work, but rather shows "access denied".

**Comment by dandan78** [comment]
The focus issue remains in October 2019. Unfortunately, it's quite annoying because although pressing F3 a second time does close the window, interacting with the window (scrolling etc) it is not possible because it doesn't have focus... would be great if this could be fixed.

**Comment by h13m9** [comment]
Bump up. Has anyone already found a solution to this annoying problem?

**Comment by rabelux** [comment]
Recently @kostenelo created a [tutorial for Total Commander](https://github.com/QL-Win/QuickLook/wiki/File-Managers:-Total-Commander) and he didn't mention any drawbacks. Does he have a different approach which doesn't show the focus issue?

**Comment by rabelux** [comment]
No response so I guess this issue is solved
