### ISSUE TITLE
show icon windows in task bar

### ISSUE THREAD

**Issue by hamerstandr** [QL-Win/QuickLook#440]
show icon windows in task bar
to switch windows.
Opened multi file (Music,HTML ,text ,...).

**Comment by xupefei** [comment]
I have once tried to show taskbar icon for pinned QL windows, but then I find that the window will flicker once when it is pinned. The bug is related to and should be fixed by Windows. I will not add this feature again unless Windows fixed it.

**Comment by hamerstandr** [comment]
I put the icon in the windows and responded

1-	File QuickLook>ViewerWindow.xaml
                 ShowInTaskbar="True"
2-	File QuickLook.Common\Plugin>IViewer.cs
                 Bitmapimage Icon
3-	**Set to all Plugin icon**

**Comment by hamerstandr** [comment]
**### I tried it and answered!**

**Comment by rabelux** [comment]
+1 for having a pinned window showed in the task bar

**Comment by xupefei** [comment]
With the icon you'll see a weird animation when pinning a window. That's why I didn't do it.

**Comment by rabelux** [comment]
So the bug is still present?

**Comment by xupefei** [comment]
Don't know. I didn't check.

**Comment by emako** [comment]
Stay current. Will not be shown in TaskBar
