### ISSUE TITLE
Set icon window , Type File

### ISSUE THREAD

**Issue by hamerstandr** [QL-Win/QuickLook#441]
Set icon window> Type File , example : Music 🎶,Move🎞 ,picture🖼 ,...

**Comment by xupefei** [comment]
Sorry, I didn't catch that. Can you elaborate?

**Comment by hamerstandr** [comment]
https://github.com/QL-Win/QuickLook/issues/440

**Comment by emako** [comment]
Stay current. Will not be shown in TaskBar
