### ISSUE TITLE
Preview shows as white rectangle on Intel HD Graphics 4000 (?)

### ISSUE THREAD

**Issue by bantya** [QL-Win/QuickLook#442]
Hi, I have used QuickLook before and must confess that it is the best file preview tool out in the wild. It worked perfectly. 

This was the case **before the recent Windows update.**

After the update, the QuickLook just stopped working. It just can't start. I have tried almost all the installation methods as described in [wiki](https://github.com/QL-Win/QuickLook/wiki/Difference-Between-Distributions), but no luck. It just **displays the app-icon in system tray** and **can't be invoked** upon hitting <kbd>Spacebar</kbd>. 

It seems like it is not even using any **CPU resources**.

![image](https://user-images.githubusercontent.com/16685565/50055578-c71f5980-0176-11e9-93b2-1dffac334604.png)

My system config is:
**QuickLook 3.6.4**
**System:** Windows 10 x64 1809 (17763.194)
**CPU:** Intel Core i5 3210M @ 2.50GHz
**GPU 1:** Intel HD Graphics 4000
**GPU 2:** NVidia Geforce GT 640M
Both the GPU drivers are **updated to their latest versions.**

I also have all the required **vc-redist files** installed as shown below:

![image](https://user-images.githubusercontent.com/16685565/50055651-aacfec80-0177-11e9-923f-164364dd6adf.png)

Can't find any **error logs** or **user.config** files in the `C:\Users\USERNAME\AppData\Local\Programs\QuickLook-3.6.4` or `C:\Users\USERNAME\AppData\Roaming\pooi.moe\QuickLook`

**Comment by Mario-Hofstaetter** [comment]
`3.6.4` working fine for me on `Windows 10 x64 1809 (17763.195)`, both the Win Store App and the normal version (installed via chocolatey).

@bantya are you using the store app or the normal desktop version?

**Comment by HASJ** [comment]
Same thing here. It only works immediately after running the executable. After an unspecified amount of time, hitting the spacebar does nothing at all and I have to kill and run QuickLook again.

**Comment by bantya** [comment]
@Mario-Hofstaetter, I used both store app and desktop version.

**Comment by xupefei** [comment]
Are all you guys having an Intel HD Graphic GPU?

**Comment by bantya** [comment]
Yes **Intel HD Graphics 4000**

**Comment by xupefei** [comment]
According to my observation, this issue only appears on PCs with HD 4000 graphics card. The driver seems failed to show semi-transparent windows.
Is there a driver update available? If no, I guess I should disable all transparency for such graphics card.

**Comment by chaloots** [comment]
Intel HD 4600 user here using v3.6.4 in 1809 (17763.134). Installed definitely did NOT come from MS Store. Have experienced no similar issues since installing. Sorry.

**Comment by bantya** [comment]
> According to my observation, this issue only appears on PCs with HD 4000 graphics card. The driver seems failed to show semi-transparent windows.
> Is there a driver update available? If no, I guess I should disable all transparency for such graphics card.

@xupefei If Intel HD Graphics 4000 is a culprit, please then disable the semi-transparency, or let us have an option to disable it manually. This is because, I double checked the driver for an update today but it's sad to say that there are no updates available.

**Comment by xupefei** [comment]
@bantya Yeah, but we still need more confirmations from other users. I don't know if there are more models affected.

**Comment by bantya** [comment]
Got you! 🤨

**Comment by bantya** [comment]
Meanwhile reinstalled Windows 10 1809 to new SSD. Today updated the Intel Graphics driver to its latest one. The problem still persists!

![image](https://user-images.githubusercontent.com/16685565/58541284-c6f0b300-8218-11e9-9a3c-5c846e2ca974.png)

👆 This changelog file gets opened correctly. That means QL works (to say 😒).

It suffers the defeat when it comes to being invoked using <kbd>Spacebar</kbd>.

**Comment by xupefei** [comment]
Can you run this GPU info utility and paste the output here?
[GPU.exe.zip](https://github.com/QL-Win/QuickLook/files/3249400/GPU.exe.zip)

**Comment by bantya** [comment]
Here's the output:

### Win32_VideoController instance

AcceleratorCapabilities:
AdapterCompatibility: NVIDIA
AdapterDACType: Integrated RAMDAC
AdapterRAM: 2147483648
Availability: 8
CapabilityDescriptions:
Caption: NVIDIA GeForce GT 640M
ColorTableEntries:
ConfigManagerErrorCode: 0
ConfigManagerUserConfig: False
CreationClassName: Win32_VideoController
CurrentBitsPerPixel:
CurrentHorizontalResolution:
CurrentNumberOfColors:
CurrentNumberOfColumns:
CurrentNumberOfRows:
CurrentRefreshRate:
CurrentScanMode:
CurrentVerticalResolution:
Description: NVIDIA GeForce GT 640M
DeviceID: VideoController1
DeviceSpecificPens:
DitherType:
DriverDate: 20161229000000.000000-000
DriverVersion: 21.21.13.7654
ErrorCleared:
ErrorDescription:
ICMIntent:
ICMMethod:
InfFilename: oem1.inf
InfSection: Section058
InstallDate:
InstalledDisplayDrivers: C:\WINDOWS\System32\DriverStore\FileRepository\nvltwu.inf_amd64_0221ce4ec0827f74\nvd3dumx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvltwu.inf_amd64_0221ce4ec0827f74\nvwgf2umx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvltwu.inf_amd64_0221ce4ec0827f74\nvwgf2umx.dll,C:\WINDOWS\System32\DriverStore\FileRepository\nvltwu.inf_amd64_0221ce4ec0827f74\nvwgf2umx.dll
LastErrorCode:
MaxMemorySupported:
MaxNumberControlled:
MaxRefreshRate:
MinRefreshRate:
Monochrome: False
Name: NVIDIA GeForce GT 640M
NumberOfColorPlanes:
NumberOfVideoPages:
PNPDeviceID: PCI\VEN_10DE&DEV_0FD2&SUBSYS_390217AA&REV_A1\4&2A7FCA01&0&0008
PowerManagementCapabilities:
PowerManagementSupported:
ProtocolSupported:
ReservedSystemPaletteEntries:
SpecificationVersion:
Status: OK
StatusInfo:
SystemCreationClassName: Win32_ComputerSystem
SystemName: Garuda
SystemPaletteEntries:
TimeOfLastReset:
VideoArchitecture: 5
VideoMemoryType: 2
VideoMode:
VideoModeDescription:
VideoProcessor: GeForce GT 640M

-----------------------------------

### Win32_VideoController instance

AcceleratorCapabilities:
AdapterCompatibility: Intel Corporation
AdapterDACType: Internal
AdapterRAM: 2214592512
Availability: 3
CapabilityDescriptions:
Caption: Intel(R) HD Graphics 4000
ColorTableEntries:
ConfigManagerErrorCode: 0
ConfigManagerUserConfig: False
CreationClassName: Win32_VideoController
CurrentBitsPerPixel: 32
CurrentHorizontalResolution: 1366
CurrentNumberOfColors: 4294967296
CurrentNumberOfColumns: 0
CurrentNumberOfRows: 0
CurrentRefreshRate: 60
CurrentScanMode: 4
CurrentVerticalResolution: 768
Description: Intel(R) HD Graphics 4000
DeviceID: VideoController2
DeviceSpecificPens:
DitherType: 0
DriverDate: 20181227000000.000000-000
DriverVersion: 10.18.10.5069
ErrorCleared:
ErrorDescription:
ICMIntent:
ICMMethod:
InfFilename: oem12.inf
InfSection: iIVBM_w10
InstallDate:
InstalledDisplayDrivers: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll
LastErrorCode:
MaxMemorySupported:
MaxNumberControlled:
MaxRefreshRate: 60
MinRefreshRate: 60
Monochrome: False
Name: Intel(R) HD Graphics 4000
NumberOfColorPlanes:
NumberOfVideoPages:
PNPDeviceID: PCI\VEN_8086&DEV_0166&SUBSYS_390217AA&REV_09\3&11583659&0&10
PowerManagementCapabilities:
PowerManagementSupported:
ProtocolSupported:
ReservedSystemPaletteEntries:
SpecificationVersion:
Status: OK
StatusInfo:
SystemCreationClassName: Win32_ComputerSystem
SystemName: Garuda
SystemPaletteEntries:
TimeOfLastReset:
VideoArchitecture: 5
VideoMemoryType: 2
VideoMode:
VideoModeDescription: 1366 x 768 x 4294967296 colors
VideoProcessor: Intel(R) HD Graphics Family

**Comment by xupefei** [comment]
@chaloots Can you also run the utility provided in https://github.com/QL-Win/QuickLook/issues/442#issuecomment-498418943 and report the output?

**Comment by bantya** [comment]
That's output of that utility. Pasting raw output of that utility presented undesired styling according to GitHub Markdown syntax. Thus, I modified it to be consistent. I have not changed any output.

**Comment by xupefei** [comment]
> That's output of that utility. Pasting raw output of that utility presented undesired styling according to GitHub Markdown syntax. Thus, I modified it to be consistent. I have not changed any output.

Your output is alright. I just want to see the log from @chaloots before the fix, since he is using HD 4600.

**Comment by chaloots** [comment]
> 
> 
> @chaloots Can you also run the utility provided in [#442 (comment)](https://github.com/QL-Win/QuickLook/issues/442#issuecomment-498418943) and report the output?

Apologies, as I was unsure of whether my installed 4600 details from the GPU.exe would be of any assistance to a user with a different graphics setup, but here are the results. Again, sorry for the delay.

-----------------------------------
Win32_VideoController instance
-----------------------------------
AcceleratorCapabilities:
AdapterCompatibility: Intel Corporation
AdapterDACType: Internal
AdapterRAM: 1073741824
Availability: 3
CapabilityDescriptions:
Caption: Intel(R) HD Graphics 4600
ColorTableEntries:
ConfigManagerErrorCode: 0
ConfigManagerUserConfig: False
CreationClassName: Win32_VideoController
CurrentBitsPerPixel: 32
CurrentHorizontalResolution: 3840
CurrentNumberOfColors: 4294967296
CurrentNumberOfColumns: 0
CurrentNumberOfRows: 0
CurrentRefreshRate: 59
CurrentScanMode: 4
CurrentVerticalResolution: 2160
Description: Intel(R) HD Graphics 4600
DeviceID: VideoController1
DeviceSpecificPens:
DitherType: 0
DriverDate: 20171016000000.000000-000
DriverVersion: 20.19.15.4835
ErrorCleared:
ErrorDescription:
ICMIntent:
ICMMethod:
InfFilename: oem2.inf
InfSection: iHSWD_w10
InstallDate:
InstalledDisplayDrivers: igdumdim64.dll,igd10iumd64.dll,igd10iumd64.dll,igd12umd64.dll
LastErrorCode:
MaxMemorySupported:
MaxNumberControlled:
MaxRefreshRate: 75
MinRefreshRate: 23
Monochrome: False
Name: Intel(R) HD Graphics 4600
NumberOfColorPlanes:
NumberOfVideoPages:
PNPDeviceID: PCI\VEN_8086&DEV_0412&SUBSYS_1998103C&REV_06\3&11583659&0&10
PowerManagementCapabilities:
PowerManagementSupported:
ProtocolSupported:
ReservedSystemPaletteEntries:
SpecificationVersion:
Status: OK
StatusInfo:
SystemCreationClassName: Win32_ComputerSystem
SystemName: DESKTOP-M228O9O
SystemPaletteEntries:
TimeOfLastReset:
VideoArchitecture: 5
VideoMemoryType: 2
VideoMode:
VideoModeDescription: 3840 x 2160 x 4294967296 colors
VideoProcessor: Intel(R) HD Graphics Family

**Comment by 888zhima** [comment]
oh, I just noticed that my pc's GPU is Intel HD Graphics 4000.

**Comment by xupefei** [comment]
Hi All,
I believe this issue is fixed in the new build: https://ci.appveyor.com/project/xupefei/quicklook/builds/25500982/artifacts.
Can someone try it and confirm?

**Comment by 888zhima** [comment]
![批注 2019-06-25 160118](https://user-images.githubusercontent.com/45889843/60080505-a3ab1c00-9762-11e9-929a-b5b3c8942d03.png)
 It turns to a transparent rectangle.

**Comment by xupefei** [comment]
What it shows when you use a version before 3.6.5-2?

**Comment by 888zhima** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    Hi,
        1、It looks like a white translucent rectangle on a version of 3.6.5 , and that pic was in #512, which was closed (so I don't have that pic anymore)2、It looks like a white  transparent rectangle on a version of 3.6.5-2，like this pic.
    
        end
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2108772928
                            
                    
                        
                            
                                    2108772928@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 6/24/2019 23:17，Paddy Xu<notifications@github.com> wrote： 


Closed #442 via e303c52.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by xupefei** [comment]
Thanks for the reply. Can you try this EXE, in which hardware acceleration is disabled?
[QuickLook.exe.zip](https://github.com/QL-Win/QuickLook/files/3340628/QuickLook.exe.zip)

**Comment by 888zhima** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        Wow, It works normally now. It's awesome! Thank you so much. I love QuickLook!(I replaced the old EXE with the new one you gave me. )
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2108772928
                            
                    
                        
                            
                                    2108772928@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    On 6/29/2019 03:44，Paddy Xu<notifications@github.com> wrote： 


Thanks for the reply. Can you try this EXE, in which hardware acceleration is disabled?
QuickLook.exe.zip

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by 888zhima** [comment]
It works normally now！
(I replaced the old EXE with the new one you gave me. )

**Comment by joemaller** [comment]
I'm also getting the translucent white box instead of a preview with v3.6.5. Nightly AppVeyor build v3.6.5-2-ge303c52 (linked earlier) did not work, neither did v3.6.5-4-gdbab12d (latest).  All were installed from the .msi installers. The above-linked .exe would not launch. 

Running Windows 10 Pro Insider Preview v1903 build 18936.1000

GPU.exe output:

-----------------------------------
Win32_VideoController instance
-----------------------------------
AcceleratorCapabilities:
AdapterCompatibility: Intel Corporation
AdapterDACType: Internal
AdapterRAM: 1073741824
Availability: 3
CapabilityDescriptions:
Caption: Intel(R) UHD Graphics 620
ColorTableEntries:
ConfigManagerErrorCode: 0
ConfigManagerUserConfig: False
CreationClassName: Win32_VideoController
CurrentBitsPerPixel: 32
CurrentHorizontalResolution: 1920
CurrentNumberOfColors: 4294967296
CurrentNumberOfColumns: 0
CurrentNumberOfRows: 0
CurrentRefreshRate: 60
CurrentScanMode: 4
CurrentVerticalResolution: 1080
Description: Intel(R) UHD Graphics 620
DeviceID: VideoController1
DeviceSpecificPens:
DitherType: 0
DriverDate: 20181210000000.000000-000
DriverVersion: 25.20.100.6472
ErrorCleared:
ErrorDescription:
ICMIntent:
ICMMethod:
InfFilename: oem34.inf
InfSection: iKBLD_w10_DS
InstallDate:
InstalledDisplayDrivers: C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_0f8979bd5ff63efa\igdumdim64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_0f8979bd5ff63efa\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_0f8979bd5ff63efa\igd10iumd64.dll,C:\WINDOWS\System32\DriverStore\FileRepository\igdlh64.inf_amd64_0f8979bd5ff63efa\igd12umd64.dll
LastErrorCode:
MaxMemorySupported:
MaxNumberControlled:
MaxRefreshRate: 60
MinRefreshRate: 48
Monochrome: False
Name: Intel(R) UHD Graphics 620
NumberOfColorPlanes:
NumberOfVideoPages:
PNPDeviceID: PCI\VEN_8086&DEV_5917&SUBSYS_225C17AA&REV_07\3&11583659&1&10
PowerManagementCapabilities:
PowerManagementSupported:
ProtocolSupported:
ReservedSystemPaletteEntries:
SpecificationVersion:
Status: OK
StatusInfo:
SystemCreationClassName: Win32_ComputerSystem
SystemName: JOES-X1
SystemPaletteEntries:
TimeOfLastReset:
VideoArchitecture: 5
VideoMemoryType: 2
VideoMode:
VideoModeDescription: 1920 x 1080 x 4294967296 colors
VideoProcessor: Intel(R) UHD Graphics Family

**Comment by xupefei** [comment]
@joemaller Intel UHD 620 is a quite new model so I have been thinking it has no such issue.
Can you try updating the driver? Does this exe https://github.com/QL-Win/QuickLook/issues/442#issuecomment-506855174 work?

**Comment by joemaller** [comment]
@xupefei That works! I had some trouble getting it to run and ended up installing the latest nightly msi, then replacing the installed exe with the one linked in the comment.

**Comment by bantya** [comment]
Replaced the exe with provided one, but no luck in my case. 😒

**Comment by AsuraLG** [comment]
This issue also occur in my laptop. I use Windows 1909 with Intel HD 630 and nividia gtx1060, and I also try to use v3.6.5-2-ge303c52, bud didn't works

**Comment by emako** [comment]
Please set `UseTransparency` to false for legacy system with the same GPU problems.

Setting method:
https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations
