### ISSUE TITLE
Add a option for user, make loading file more fastter

### ISSUE THREAD

**Issue by Zeroto521** [QL-Win/QuickLook#443]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
When _QuickLook_ loads more than **100MB file** (e.g. a zip file), it is so lower.

**Describe the solution you'd like**
Maybe it can add a **option** for user, **no** showing **details** just showing file size, the number of files or other **simple information**.

**Describe alternatives you've considered**
I think I using it just for **having a quickly look**, and I don't want to **wait for loading**.
Whatever loading is bad.

**Comment by xupefei** [comment]
In your example, you can just press the spacebar again to stop the loading.
