### ISSUE TITLE
Opening .png in the wrong scale

### ISSUE THREAD

**Issue by salmivas** [QL-Win/QuickLook#445]
Hello,

I tried to open various 48x48 .png files and they were in the wrong scale. The minimum scale is limited to 417%. So I think it's a bug.
Example screenshots:
![image](https://user-images.githubusercontent.com/35002517/50393369-385e9e00-076f-11e9-93e8-e3e5e88e5d13.png)
![image](https://user-images.githubusercontent.com/35002517/50393372-3b598e80-076f-11e9-8362-beaa7fba15be.png)

My OS Version: Windows 10 1803.
And I have no any .log files in path %LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\.

You can download .png examples [there](https://icons8.com/).

**Comment by DingJunyao** [comment]
I also find the same problem on many pictures (not only PNG) . 

It seems that the horizontal resolution and the vertical resolution cause the problem, for these pictures have these in details.

The follwoing screenshots show the 100% scales of the pictures in both app Picture and in QuickLook: 

![284](https://user-images.githubusercontent.com/11372753/52465551-f7550880-2bb9-11e9-9f95-405ef26cc192.png)

![281](https://user-images.githubusercontent.com/11372753/52465596-1a7fb800-2bba-11e9-83d5-e261470f13d5.png)

![282](https://user-images.githubusercontent.com/11372753/52465611-266b7a00-2bba-11e9-9ac7-db15c5279ab6.png)

And the following screenshot shows the details of them:

![283](https://user-images.githubusercontent.com/11372753/52465716-8eba5b80-2bba-11e9-8d56-ed9ac7ac3b71.png)

[Pictures.zip](https://github.com/QL-Win/QuickLook/files/2844140/Pictures.zip) is the pictures in my test.

**Comment by xupefei** [comment]
This issue has been fixed in 3.6.8.
