### ISSUE TITLE
User config to override default handler

### ISSUE THREAD

**Issue by PlanetWilson** [QL-Win/QuickLook#446]
It would be good to have an ability to override the default handling of a particular file type so that it displays as text. In my case for .htm / .html files I want to see them as text, not rendered in a browser.

**Comment by rabelux** [comment]
This is related to #132 and might be implemented with a toggle-button as suggested in #336. @xupefei is on it as he mentioned [here](https://github.com/QL-Win/QuickLook/issues/336#issuecomment-418259118). I guess he just doesn't find the time to work on it at the moment.
Would a toggle-button be satisfactory for you?

**Comment by PlanetWilson** [comment]
Sure, that would work.

**Comment by emako** [comment]
Solution to a similar problem:

Create a new plugin by yourself, use a higher priority such as 100, and then call TextViewer to display the html and other suffixes you need.
