### ISSUE TITLE
windows10 preview video(.mp4) : only have sound without pictures

### ISSUE THREAD

**Issue by mod3021** [QL-Win/QuickLook#447]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
only have sound without pictures  preview video(.mp4) on windows10

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: windows10 企业版
 - QuickLook Version: 3.6.4 from msi

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log` (`.msi` or `.zip` version) or `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log` (Windows Store version).

**Comment by xupefei** [comment]
Does this happen to all videos, or just *this* one?

**Comment by sirius-fan** [comment]
I have this problem too，I try to reinstall uwp version and exe version, but it doesn't work.

**Comment by xupefei** [comment]
What graphics card are you using?

**Comment by sirius-fan** [comment]
> What graphics card are you using?

AMD HD8500m

**Comment by xupefei** [comment]
> > What graphics card are you using?
> 
> AMD HD8500m

Is there also an Intel one?

**Comment by sirius-fan** [comment]
Now, there is no problem in my computer(uwp verson). you could close this issue.
