### ISSUE TITLE
Make QuickLook also work in Open and Save As windows

### ISSUE THREAD

**Issue by marhurram** [QL-Win/QuickLook#449]
This program was made based on the Mac preview option, which also works when previewing files on Open and Save As windows.

I do miss it the most when attaching files to my emails. On Mac I'd preview files every single time before  attaching the document to make sure it's the right one. And this is when I miss it the most when working on Windows

Please allow QuickLook to preview files on system windows like Open, Save As and the likes.

In case it's not clear which system windows I'm talking about, I'm referring to these:
![preview1](https://user-images.githubusercontent.com/5196679/50576015-567c6c00-0e09-11e9-8b79-8a2a33511081.png)
![preview2](https://user-images.githubusercontent.com/5196679/50576016-567c6c00-0e09-11e9-81a6-1dcb40648c9e.png)

Thank you for your time and your magnificent program.

**Comment by marhurram** [comment]
Thank you for your prompt response.
My life is now 1000 times better thanks to your comment. Thank you thank you thank you!!!
I can't believe I wasn't aware of this.

Thank you xupefei!

**Comment by tdy** [comment]
Will this feature eventually be added to the MS Store version, or is this just a limitation of UWP?
