### ISSUE TITLE
Don't launch QuickLook if I type letters to search for file/folder with spaces

### ISSUE THREAD

**Issue by NightMean** [QL-Win/QuickLook#450]
So my issue is that I have a few folders/files with spaces in them. (ex. Discord Folder) When I want to search for it I have to type Discord (I don't mean the search box but just typing the letters while in explorer) but as soon as I press space explorer ignores it and QuickLook will open. 
What I want is that QuickLook will ignore spacebar if any letter was pressed before it or have it as an option in settings somewhere.
I thought that solution for this would be to listen for keys while explorer is active but I'm not sure if it won't be marked as keylogger.

**Comment by xupefei** [comment]
This is unfortunately impossible to fix, or at least requires a huge amount of work. I do not want to give any configurable option because QL is designed to be simple, headless replacement of the macOS Quick Look function.
I am afraid, the best solution is: do not type space.
