### ISSUE TITLE
Window position issue on the secondary monitor

### ISSUE THREAD

**Issue by tsanie** [QL-Win/QuickLook#452]
**Describe the bug**
When I switch the files on the secondary monitor, the QuickLook window doesn't keep a well position.
**There is no problem in the primary monitor.**
*And it is different with https://github.com/QL-Win/QuickLook/issues/260*

**To Reproduce**
1. Select a file in the secondary monitor
2. Press the <kbd>Space</kbd> button
3. Then press the <kbd>↓</kbd> button to switch to another file
4. Now the QuickLook window move to the center of the two monitors (and be separated)

**Expected behavior**
The QuickLook window stays in the current monitor.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1809 (OS Build 17763.195)
 - QuickLook Version: 3.6.4 from the released .msi

**Screenshots and Exception Log**
![b1](https://user-images.githubusercontent.com/980449/50768975-583ca880-12bd-11e9-8600-73713169f364.jpg)
![b2](https://user-images.githubusercontent.com/980449/50768980-5c68c600-12bd-11e9-9323-b3ccc3137538.jpg)

**Comment by tsanie** [comment]
I can't reproduce the problem in my work computer, which also have two monitor. 😭 The two versions (3.6.2-27-g6768f44 and 3.6.4) both looks well.

I'll try this version after work later.

**Comment by tsanie** [comment]
@xupefei Yes, the 3.6.2 version would keep the right position in the secondary monitor.
But another problem appeared, the window text in the secondary monitor looks blur. (The zoom scale in the primary monitor is 125%, and the secondary monitor is 100%.)

**Comment by xupefei** [comment]
There are some known issues with DPI scaling now, see https://github.com/QL-Win/QuickLook/issues/420.
In short, we have to choose either (i) correct window position and blurry UI on one of the screens or (ii) incorrect window position and clear UI on all screens.
Blame Microsoft for this.

I prefer to choose (i) which means to revert the DPI-related changes for now. Could you give any comment, @Verrickt?

**Comment by Verrickt** [comment]
I'd prefer (i) so let's revert the changes and blame Microsoft

**Comment by xupefei** [comment]
After reverting changes, the window will be clear on your *primary display*, i.e., the one showing all desktop icons. When the window shows on your secondary screen, it (always) becomes blurry -- unless two screens have the same DPI scaling factor.

**Comment by xupefei** [comment]
I noticed that NET framework 4.8 finally adds mixed DPI support: https://docs.microsoft.com/en-us/dotnet/framework/whats-new/index#wpf48

Any volunteer with a multiple-monitor setup?

**Comment by renecum** [comment]
I have a multiple-monitor setup, I was unable to reproduce the problem.

**Comment by CodyPredy** [comment]
Same problem on a multi desktop setup. 
Primary - 4K, Secondary - 1080p. 
Secondary is shifted bottom aligned with the primary. On initial preview it's completely centered. Shifting to other files using bottom or top arrow keys shifts the position of the preview pane.

**Comment by xupefei** [comment]
Yes, the problem happens when monitors are in different DPI.

**Comment by xupefei** [comment]
This is issue should be fixed in https://ci.appveyor.com/project/xupefei/quicklook/builds/35688242/artifacts. Could you try?

**Comment by tsanie** [comment]
> This is issue should be fixed in https://ci.appveyor.com/project/xupefei/quicklook/builds/35688242/artifacts. Could you try?

It seems correct through the Team viewer. I will try it on the local side in the evening, now here is only macOS.

**Comment by tsanie** [comment]
@xupefei There is no position issues any more, but the quick look is too large in the main monitor now. (correct in the secondary monitor)

1 display: 2560x1440, dpi 125%
2 display: 1080x1920, dpi 100%

![screen](https://user-images.githubusercontent.com/980449/95745099-111bec80-0cc7-11eb-99fc-ce58d6fadd41.jpg)

**Comment by xupefei** [comment]
The second issue should have been fixed in https://ci.appveyor.com/project/xupefei/quicklook/builds/35688332/artifacts.

**Comment by tsanie** [comment]
> The second issue should have been fixed in https://ci.appveyor.com/project/xupefei/quicklook/builds/35688332/artifacts.
> 
> Nice pic BTW :)

Resolved, perfect 👍
