### ISSUE TITLE
1809暗色模式下 预览图片点击旋转按钮没用。

### ISSUE THREAD

**Issue by youngerruan** [QL-Win/QuickLook#453]
1809暗色模式下 预览图片点击旋转按钮没用。

**Comment by xupefei** [comment]
There is no Rotate button in the image previewer. Do you mean something else?

**Comment by youngerruan** [comment]
> There is no Rotate button in the image previewer. Do you mean something else?

sry, i made a mistake. there is no rotate button,  i mix up.
