### ISSUE TITLE
Modification date changed

### ISSUE THREAD

**Issue by jgarces02** [QL-Win/QuickLook#454]
Hi @xupefei, 

Thanks for this wonderful (and very useful) software! I've noticed, with the current version (3.6.4), that the modification date changes every time I pre-visualize any file, is there any option to avoid this?

Thanks for your help. Regards.

**Comment by jgarces02** [comment]
For being more specific, this only happens using the Office plugin... Thanks again!

**Comment by xupefei** [comment]
There are two Office plugins. How about the other one?

**Comment by jgarces02** [comment]
Ok, it seem with the native one ([that one](https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native)) the error disapears. Thanks!
