### ISSUE TITLE
Preview from Open and Save File Dialog don't work

### ISSUE THREAD

**Issue by lesir831** [QL-Win/QuickLook#455]
**Describe the bug**
I can use it normal in explorer，but it don't work in preview from open and save file window.

**Desktop (please complete the following information):**
 - OS Version:Windows 1809 (OS Build 18312.1001.195)
 - QuickLook Version:3.6.4 from the released .msi

**Comment by xupefei** [comment]
https://github.com/QL-Win/QuickLook/issues/449
