### ISSUE TITLE
A bug of Preview from Open and Save File Dialog don't work

### ISSUE THREAD

**Issue by lesir831** [QL-Win/QuickLook#456]
**Describe the bug**
In #455,my QuickLook is .msi from the released page.But I know what cause the bug,It may clash with listary.When I close the listary,it can work well.I  really hope you can fix this bug.

**Comment by nicolafarina** [comment]
> Thank you,I will do that.

Have you any update about this? Listary + QuickLook is an amazing combo for me, but in Save&Open dialogs QuickLook doesn't work as you mention.

Thanks.

**Comment by qupear** [comment]
> You should report this issue to Listary and ask for a solution.
Unfortunately, developer of Listary is no longer support this product.
