### ISSUE TITLE
[BUG][FEAT REQ] Prevent preview to go behind the origin folder

### ISSUE THREAD

**Issue by teolaz** [QL-Win/QuickLook#461]
Hi again,
if you select the "Stay on top" button, the preview section will stay in front of everything else, instead if you don't selected the button and try to close and open the same folder again, the folder will go in front of the preview.
The main idea of OSX preview windows is to be closed and reopened in front of the same folder automatically... Dunno if im clear...

Is it possible to add a "Link preview to folder" option on the preview interface? 

Another thing i noted is when you click on quicklook in osx and want to switch between files, the focus is automatically moved to the explorer view, so you can change between files also being from quicklook... Do you think that as possible to implement here?

**Comment by rabelux** [comment]
Answered in #914
