### ISSUE TITLE
access problem for TC when installing from windows store

### ISSUE THREAD

**Issue by xarthurx** [QL-Win/QuickLook#464]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
Cannot use QuickLook installed from windows store in 3rd party programme, such as TotalCommander.

**To Reproduce**
1. Install QuickLook from Windows Store
2. Associate the `exe` file with the viewer of TotalCommander
3. Quick look on any supported files
4. Access Denied

**Expected behavior**
Files can be quick looked.

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 1803]
 - QuickLook Version: [newest from Windows Store]

**Comment by embql** [comment]
Do you assign the 'external viewer' to be QuickLook?
Also, do you assign the filetypes you want to view individually in the "Associations" menu/button?
I can get it to work that way.
![image](https://user-images.githubusercontent.com/19207128/52783181-69619d80-3051-11e9-804b-26e733514d37.png)

**Comment by xarthurx** [comment]
@embql 
Yes. But still not working.

I uninstall the version from windows store and install with the released msi file.
Now things work fine.

**Comment by xupefei** [comment]
The problem is that Windows Store uses sandbox so QL is inaccessible by invoking directly. I will update the Wiki page to indicate this problem.
