### ISSUE TITLE
[feature] invoking QuickLook from the command line in a powershell window

### ISSUE THREAD

**Issue by kkdd** [QL-Win/QuickLook#469]
Hello,
I think that it would be helpful if QuickLook could open files by invoking from the command line in a powershell window.

*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xupefei** [comment]
See this: https://github.com/QL-Win/QuickLook/wiki/Integration-and-Development
