### ISSUE TITLE
打开CP936格式TXT时乱码

### ISSUE THREAD

**Issue by MerrickZ** [QL-Win/QuickLook#471]
打开CP936（GB2312）格式的TXT文件时显示乱码
文件示例：

[无标题1.txt](https://github.com/QL-Win/QuickLook/files/2903625/1.txt)

**Describe the bug**
Text displayed wrong while previewing GB2312/CP936 encoding plain text files.

**To Reproduce**
1. check the file attached
2. preview it

**Expected behavior**
Encoding auto detection

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 1803]
 - QuickLook Version: [latest from Windows Store]

**screenshot**

![image](https://user-images.githubusercontent.com/1021332/53385660-1aedc080-39ba-11e9-9269-1be6bdc8a0f1.png)

**Comment by anphorea** [comment]
which should be
![image](https://user-images.githubusercontent.com/1021332/53385680-335ddb00-39ba-11e9-92b4-8c0caf081a88.png)

**Comment by emako** [comment]
文本过短，快速预测编码就能可能失效，目前会先与泰语匹配。

目前是文本过短导致的问题，因此先不考虑解决（比如也先不考虑增加偏码选项等）。

**Comment by emako** [comment]
考虑重开issue解决该问题

**Comment by emako** [comment]
Fixed in nightly build

https://github.com/QL-Win/QuickLook/releases
