### ISSUE TITLE
OfficeViewer 插件效能不好

### ISSUE THREAD

**Issue by zhanghang20032006** [QL-Win/QuickLook#476]
针对一些比较大型的office文件，出现读取过慢无法显示的问题，某些特定的图片格式也会导致主程序卡死

**Comment by dreistein543** [comment]
或许可以考虑对office插件进行修订，比如仅显示前三页，如果有往下预览的需求才继续读取数据，或者向mac的quicklook学习，仅显示内容而忽视格式

**Comment by dreistein543** [comment]
另外，也发现在对PowerPoint文件进行预览时，会出现内容丢失的情况

**Comment by zhanghang20032006** [comment]
> 或许可以考虑对office插件进行修订，比如仅显示前三页，如果有往下预览的需求才继续读取数据，或者向mac的quicklook学习，仅显示内容而忽视格式

这个建议比较好，但是如何处理预载入的问题？如果插件参数能自己设定就比较好了，我可以预读取6页，但是仅显示前3页

**Comment by dreistein543** [comment]
> > 或许可以考虑对office插件进行修订，比如仅显示前三页，如果有往下预览的需求才继续读取数据，或者向mac的quicklook学习，仅显示内容而忽视格式
> 
> 这个建议比较好，但是如何处理预载入的问题？如果插件参数能自己设定就比较好了，我可以预读取6页，但是仅显示前3页

其实我本来希望更加极端一点只加载第一页，考虑到许多文件第一页没有实质性内容才说到三页。预载入问题我个人感觉可以有以下几种可能：
1. 优先展示前三页，后台继续加载剩余的数据（貌似pdf预览就是这么做的）
2. 仅加载三页数据，除非有下翻的指令则加载剩余数据
3. 永远加载比目前展示多三页的数据（比如刚打开则加载前三页，浏览第n页时加载第n+3页数据）

**Comment by Wanger-SJTU** [comment]
请问怎么卸载这个office插件，好像跟onedrive的自动上传冲突了

**Comment by xupefei** [comment]
@Wanger-SJTU https://github.com/QL-Win/QuickLook/wiki/Available-Plugins#how-to-remove-a-plugin

Fixed. Try the new plugin: https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native
