### ISSUE TITLE
Preview .jfif images

### ISSUE THREAD

**Issue by ilfarpro** [QL-Win/QuickLook#477]
Now .jfif images preview looks like this. Please add support of this type of images
![{293C4E13-D7B6-47F5-985D-29A94D82B17D} png](https://user-images.githubusercontent.com/16963651/54122678-bfd2b980-440e-11e9-8ce3-a7c644dd4c40.jpg)

**Comment by Cyberdroid1** [comment]
Even now, QuickLook doesn't support JFIF formats. Please add this functionality.

**Comment by rabelux** [comment]
Just did a quick research, seems like jfif is a sub-form of jpeg and should be able to be interpreted exactly the same as jpeg

**Comment by xupefei** [comment]
I'll solve these formats request this weekend. The fix is actually very simple: add one string here: https://github.com/QL-Win/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.ImageViewer/Plugin.cs#L37.
