### ISSUE TITLE
configure proxy to check for updates

### ISSUE THREAD

**Issue by gotson** [QL-Win/QuickLook#485]
**Is your feature request related to a problem? Please describe.**
I am running QuickLook behind a corporate proxy, and the update checker cannot reach the internet.

**Describe the solution you'd like**
I would like an option to specify a proxy in the form of `ip:port`. An extended option to support login/password could also be interesting, even though at the moment i use a local proxy (CNTLM) so i don't need to specify any login/password.

**Describe alternatives you've considered**
The only alternative is to manually check for updates.

**Comment by xupefei** [comment]
Try the nightly build: https://ci.appveyor.com/project/xupefei/quicklook/builds/23475645/artifacts.
Now the updater will read your system HTTP proxy settings.

**Comment by gotson** [comment]
there's no artifact for download, and the build is in failed status

**Comment by xupefei** [comment]
That particular build is failed for some wired seasons. Try this: https://ci.appveyor.com/project/xupefei/quicklook/builds/23476675/artifacts

**Comment by gotson** [comment]
with the new version i have an error 407. I think it's reading default proxy settings, which require a login/password for authentication.

I would like to be able to specify a proxy, so i can use a CNTLM local proxy which doesn't require authentication.
