### ISSUE TITLE
.md files don't show pictures

### ISSUE THREAD

**Issue by TheLight8** [QL-Win/QuickLook#499]
**Describe the bug**
.md files don't show pictures

**To Reproduce**
1. Spacebar on a .md files
2. Look at the file
3. Notice pictures are not loading

**Expected behavior**
I would like to see the picture in the file.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1809
 - QuickLook Version: v.3.6.4 UWP

**Comment by Lightczx** [comment]
me too

**Comment by xupefei** [comment]
You need to write a full path to make it work.
