### ISSUE TITLE
Can not display comments and marks of pdf

### ISSUE THREAD

**Issue by hhhuang18** [QL-Win/QuickLook#505]
When preview pdfs, the comments, highlights and marks are not shown. Hope that they can also be previewed.

**Comment by shuxiansheng2** [comment]
I meet the same problem when I updated  it to v3.6.5. It is ok when using v0.3.5.

**Comment by shuxiansheng2** [comment]
This problem was introduced by v0.3.6 firstly.

**Comment by shuxiansheng2** [comment]
v0.3.5 failed to preview some pdfs and the problem was fixed by versions after v0.3.6

**Comment by Zhou-Yucheng** [comment]
I meet the same problem and hope it can be fixed. 
BTW this problem is same as #421
