### ISSUE TITLE
Crash during quick looking *.xlsx file when the file is opening with WPS on Windows 10.

### ISSUE THREAD

**Issue by ant0x00** [QL-Win/QuickLook#507]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
Crash during quick looking *.xlsx file when the file is opening with WPS on Windows 10.

**To Reproduce**
1. Open my .xlsx file with WPS.
2. select the file and press spacebar.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [v3.6.5 from github release]
- QuickLook.Plugin.OfficeViewer v3  17.1.0.38.

**Comment by rabelux** [comment]
Without exception log no help can be provided
