### ISSUE TITLE
No Markdown Image Display 

### ISSUE THREAD

**Issue by hschmiedhofer** [QL-Win/QuickLook#508]
The Markdown viewer does not display images, neither .png nor .jpg. 

Is this on purpose?

**Comment by xupefei** [comment]
Unfortunately, the markdown viewer does not recognise **relative local URLs**. You have to either upload the image to some hosting websites or use absolute URLs such as `file://C:/Users/paddy/Desktop/pro.jpg`. Such URLs can be obtained by dragging images into Chrome then copy the address texts.

**Comment by hschmiedhofer** [comment]
Dear xupefei, thanks for letting me know. Can this be fixed?

**Comment by Yari27** [comment]
Is there a chance to correct this error, other applications somehow manage to display local images.

**Comment by emako** [comment]
After 72d3c3187bc811189d7ba7c3c4ca235d01de1009 support to display local images.

**Comment by emako** [comment]
#82
