### ISSUE TITLE
Files kept open in 'system'

### ISSUE THREAD

**Issue by 9UnderDog** [QL-Win/QuickLook#513]
**Describe the bug**
Hi, just started using the program and started realising that a lot of my files were open in 'system' (unable to rename, edit, delete, etc.). Not long and I narrowed it down to QuickLook (which I tested on random files)

**To Reproduce**
1. Press space bar to preview file in QuickLook (for example a .ini file to see contents)
2. Try to edit contents of file with any program, try to rename or delete from Explorer
3. Fails. Errors are nothing out of the ordinary (eg. "The action can't be completed because the file is open in system" dialogue box)

The QuickLook is not open/previewing the file and the only way to fix is to close QuickLook

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1803
 - QuickLook Version: v3.6.5 UWP

**Comment by xupefei** [comment]
This is a bug caused by Windows 10 UWP sandbox, probably together with antivirus software (not confirmed). A switch from UWP to either `.zip` or `.msi` version should solve the problem.

**Comment by 9UnderDog** [comment]
I did have bit defender (free) installed at the time. I did uninstall bit defender but am unable to tell if it made a difference as files being kept open in system weren't always occurring (even when I still had bit defender). Using the .msi version now seems to work well.
Thanks!
