### ISSUE TITLE
Cannot add plugin to Widnows store Version due to Permission issues

### ISSUE THREAD

**Issue by nathanatgit** [QL-Win/QuickLook#514]
I googled many methods to gain access to WindowsApps folder but still can't move plugin file to "...WindowsApps\21090PaddyXu.QuickLook_3.6.5.0_neutral__egxr34yet59cg\Package\QuickLook.Plugin"

After updating to Windows 1903, Permission of folder "WindowsApps" and all its sub-folders are already granted to 'Everyone' but access denied when move "*.qlplugin" files to "...\Package\QuickLook.Plugin"

![image](https://user-images.githubusercontent.com/20399271/59605727-f6bd1780-9141-11e9-95da-a30e2524e773.png)

move files in PowerShell as administrator still won't work.

**Comment by xupefei** [comment]
What is your purpose of modifying `WindowsApps` folder?
Read the guide: https://github.com/QL-Win/QuickLook/wiki/Available-Plugins#how-to-install-or-upgrade-a-plugin
