### ISSUE TITLE
Random image files don't fit the frame and scale to 0

### ISSUE THREAD

**Issue by AlexPetrov108** [QL-Win/QuickLook#515]
I've encountered that random image files (.jpg and .png) may not fit the viewer window when opening - they show at 100% scale and when you try to zoom such files, they disappear scaling to 0%. While the majority of files open correctly. It may happen randomly if the folder contains the images from different sources, but if the folder has a group of photos from one source (a camera e.g.) then they all will either work or not.

**To Reproduce**
1. Download the image samples of the issue files with the links below:
https://drive.google.com/open?id=1q6YTImylK8Br3SiHWLKlfGEG3oWBJ2kY
https://drive.google.com/open?id=1jNi6S7qldLJ8jf_nzCAUGnpJqEzAZrgk
2. Try previewing them with the spacebar
3. These samples will not fit the frame and will scale to 0% when trying to zoom

**Expected behavior**
Any image file (png or jpeg) should fit the frame and zoom when needed

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 1903 64-bit Build 18362.175
 - QuickLook Version: 3.6.5 (I tried the versions from the Store and msi)

**Comment by AlexPetrov108** [comment]
I tried to Reproduce the issue with the files I shared, on my work PC with Windows 10 1803 and they worked just fine, no problem... Actually, I've had no such issues on that work PC ever so there must be something wrong with that particular installation on my home PC. 
But I don't know what to think of because I've made a clean installation of Windows just a couple of days ago and installed QuickLook first from Windows Store, and when I saw that issue I uninstalled it and downloaded the msi file from here, and tried that one. Still no go... What could be the issue?

**Comment by xupefei** [comment]
Is there any new exception log in Windows Event Viewer after the images goes blank?

**Comment by AlexPetrov108** [comment]
I could find nothing related to QuickLook in Windows Events. Does the app leave the logs somewhere else?

**Comment by AlexPetrov108** [comment]
Ok, I found it. This what happens when I Ctrl+Scroll to zoom the image which doesn't fit the frame and which goes 0% scale when scaling:
========25-Jun-2019 20:55:16========
System.OverflowException: The image data generated an overflow during processing. ---> System.ArithmeticException: Overflow or underflow in the arithmetic operation.
   --- End of inner exception stack trace ---
   at System.Windows.Media.Imaging.TransformedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapImage.EndInit()
   at QuickLook.Plugin.ImageViewer.AnimatedImage.NativeImageProvider.<>c__DisplayClass1_0.<GetThumbnail>b__0()

**Comment by RockyMM** [comment]
Hey all,

I just wanted to report that I have exact same issue. 

Do you need some more debug info/logs?

**Comment by xupefei** [comment]
This issue has been fixed in 3.6.8.
