### ISSUE TITLE
Background color in png preview

### ISSUE THREAD

**Issue by BautistaCRP** [QL-Win/QuickLook#516]
When I'm looking at black png icons, although this is the option to put the background clear, when I go to the next image with the arrows, the background is put back in black.
It would be good to keep it clear.

**Comment by xupefei** [comment]
Hi, I can't reproduce the issue. When I switch the BG colour and to another image, the BG colour stays the same. Can you post an GIF or short screen recording?

**Comment by rabelux** [comment]
no response -> closed
