### ISSUE TITLE
I can change the shortcut spacebar to ctrl+spacebar?? 

### ISSUE THREAD

**Issue by abelesco** [QL-Win/QuickLook#517]
Hello every body Iwant to change the shortcut to start preview to ctrl+spacebar. Thanks!!

**Comment by Chris2011** [comment]
I also want to change that to a different one (not ctrl + space). So we need need an option for that. When I open a folder, my first keyboard shortcut is space but not for QuickLook, but for selecting the file/folder to navigate.

**Comment by rabelux** [comment]
Explained in #272
