### ISSUE TITLE
Quicklook v3.6.5 cause Everything by Voidtools "Copy Full Name to Clipboard" when opening file with Enter key

### ISSUE THREAD

**Issue by ariefcfa** [QL-Win/QuickLook#521]
**Description**
When QuickLook is active, opening file with Enter key in Everything by Voidtools also do "Copy Full Name to Clipboard"

**Steps to reproduce the behavior:**
1. Search in Everything
2. Open a file with Enter key in Result List
3. Clipboard changed to the file's Full Name path

**Expected behavior**
Enter key in Everything is only for opening file. To copy Fullname is by press Ctrl+Shift+C keys

**Desktop (please complete the following information):**
 - Windows 10 64 bit version 1903
 - QuickLook Version: v3.6.5 from Github releases

Thanks

**Comment by xupefei** [comment]
Copy the path is the only method to make QL works with Everything. The author said there might be some changes in the upcoming 1.5 version, so I think I shall wait: https://github.com/QL-Win/QuickLook/issues/84#issuecomment-342710248

**Comment by ariefcfa** [comment]
Thanks

**Comment by albino1** [comment]
Since Quick Look uses the Spacebar to preview, is there any reason why it has to copy to clipboard when the Enter key is used?  If you could just make it so the Enter key was left alone, then I think most of the problems with this bug would go away since you don't use Spacebar in Everything, but you use Enter constantly.

**Comment by xupefei** [comment]
Oh, I just realized that it's not the Spacebar but the Enter key. I will investigate this issue.

**Comment by xupefei** [comment]
Fixed!
Can you try the latest Nightly (DL here: https://ci.appveyor.com/project/xupefei/quicklook/builds/27605418/artifacts) and confirm?

**Comment by xupefei** [comment]
Sorry, the previous fix does not fully solve the problem. Try this one instead:  https://ci.appveyor.com/project/xupefei/quicklook/builds/27605885/artifacts

**Comment by albino1** [comment]
> 
> 
> Sorry, the previous fix does not fully solve the problem. Try this one instead: https://ci.appveyor.com/project/xupefei/quicklook/builds/27605885/artifacts

This one seems to mostly work.  If you hit Spacebar it copies the path, but if you hit Enter it doesn't copy anything, which is correct.

The only strange thing is it seems like if you hit Spacebar in Everything and *then* hit Enter it still leaves the QuickLook preview window open in the background.  If you do this in Windows Explorer it exits the preview window and then opens the program with the file.  I tried it with text files and images, and in both cases it left the preview window open in Everything, but exited in Explorer.

Hope this helps, let me know if you need me to test another version.  Thanks!

**Comment by xupefei** [comment]
> if you hit Spacebar in Everything and then hit Enter it still leaves the QuickLook preview window open in the background

Now it should be alright. Try https://ci.appveyor.com/project/xupefei/quicklook/builds/27667726/artifacts.

**Comment by albino1** [comment]
> Now it should be alright. Try https://ci.appveyor.com/project/xupefei/quicklook/builds/27667726/artifacts.

Works perfect, thanks so much for fixing this!
