### ISSUE TITLE
Enchantment | Edit text functionality

### ISSUE THREAD

**Issue by yedhrab** [QL-Win/QuickLook#532]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Can u add edit functionality especially for text formatted file

**Additional context**
For example:
Typing some text here will be nice :)
![image](https://user-images.githubusercontent.com/49655146/62416646-38007c80-b647-11e9-9b7b-5f3c85e8445a.png)

**Comment by rabelux** [comment]
I'd say the best way to achieve your wanted behaviour is to press enter and thereby open the file in the default program.
Quickview is intended to (as the name suggest) give you a quick view of many different filetypes and not to edit all of those
