### ISSUE TITLE
Preview failure in everything

### ISSUE THREAD

**Issue by shadow1ng** [QL-Win/QuickLook#533]
安了空格，但是预览不出来，没任何反应

**Comment by DennisKassel** [comment]
How did you get Everything previewing files using QuickLook?

**Comment by xupefei** [comment]
You must not run the Everything GUI as the administrator.

Install Everything as a service then the preview will work.

**Comment by cvidkal** [comment]
> You must not run the Everything GUI as the administrator.
> 
> Install Everything as a service then the preview will work.
I reinstall Everything as a service but still failed.
My Everything is v1.4.1.935 Win10 18363

**Comment by cvidkal** [comment]
> You must not run the Everything GUI as the administrator.
> 
> Install Everything as a service then the preview will work.

I reinstall Everything as a service but still failed.
My Everything is v1.4.1.935 Win10 18363

**Comment by DennisKassel** [comment]
On my system I can confirm that it works. Thanks for the advice.

**Comment by xupefei** [comment]
> > You must not run the Everything GUI as the administrator.
> > Install Everything as a service then the preview will work.
> 
> I reinstall Everything as a service but still failed.
> My Everything is v1.4.1.935 Win10 18363

After installing Everything as a service, do **not** run Everything with the administrator right.

**Comment by rsyqvthv** [comment]
I had same problem, 

use Everything portable version, 

**my condition is**

in option > general
* unchecked `run as administrator`
* checked `everything service`

right click Everything.exe, 
in properties window
the `run this program as admin` has been unchecked

**issue**

restart Everything, Quicklook preview won't work.
even restart computer, still not work.

**more info**

* sometimes, I press spacebar constantly, it will flash out the Quicklook ui, but as I press quickly, it will soon closed by following spacebar pressing. so it's not a way to workaround.
* It did work for me before. once when I preview a video, I pressed Esc habitually, the Quicklook and Everything quit together. After then, this problem occur, tried following, but still not work.
* * reinstall the early version of Quicklook, 
* * delete the setting files in `AppData\Roaming\pooi.moe` 
* * use a brand new portable Everything, 
* * use admin purview for both Everything and Quicklook


**please help**

**Comment by rsyqvthv** [comment]
> I had same problem,
> **please help**

restart computer resolved my problem.
