### ISSUE TITLE
Open from File selection dialog

### ISSUE THREAD

**Issue by foguetes** [QL-Win/QuickLook#535]
I would like the ability to use Quicklook from a dialog window:

![image](https://user-images.githubusercontent.com/25814516/62867213-14a69300-bd13-11e9-9444-51f37b049b9e.png)

So, pressing the right shortcut (space key or another) I would be able to preview the selected file.

Alternatively, a context menu item that would perform this action.

**Comment by rabelux** [comment]
Are you using the store- or the msi-version?
The store-version has a limitation and "does not preview selected files in the Open- and Save-File Dialogs." (quoted from [wiki](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions))

**Comment by rabelux** [comment]
So I guess this issue can be closed?

**Comment by foguetes** [comment]
yes, that works! thanks
