### ISSUE TITLE
Please add support for HAP video codec

### ISSUE THREAD

**Issue by dj-matt-e** [QL-Win/QuickLook#538]
Currently the app doesn't support video files encoded with HAP. As the HAP codec is fast becoming the codec of choice for most professional media playback platforms it would be very helpful if it could be implemented in the QuickLook app. Great app by the way.

**Comment by xupefei** [comment]
QL employs LAVFilters to decode videos, so the supported formats are limited to what LAVFilters actually supports.
Is this codec playable by using [LAVFilters](https://github.com/Nevcairiel/LAVFilters/releases)?

**Comment by emako** [comment]
No reply for a long time, close the issue
