### ISSUE TITLE
Consider using WebView2 when available

### ISSUE THREAD

**Issue by flamott** [QL-Win/QuickLook#539]
The new WebView2 is powered by Chromium Edge, and has better support for the web than the old IE-powered WebView.
Please consider using it (when it's out of preview ofc) for users with Edge Chromium, which will be the default browser for Windows in the future.

https://docs.microsoft.com/en-us/microsoft-edge/hosting/webview2

**Comment by xupefei** [comment]
> Supported Platforms
> Developer preview is first available for Win32 C++ on Windows 10. In the future, we plan to have WebView2 on all the supported versions of Windows supporting C++, .NET and XAML.

Looks nice. We have to wait though.

**Comment by mooflu** [comment]
Tried it here https://github.com/mooflu/QuickLook/commit/99c8e4d13047f8afa5aaa615c5ab85c41451842f

Also a nice alternative to PdfiumViewer/PdfViewer plugin. 

And possibly other file types, too, like svg.

**Comment by xupefei** [comment]
@mooflu Since Webview2 is available on all Windows versions, I choose to completely deprecate the old one.

**Comment by Darthagnon** [comment]
@xupefei Does this mean a prerequisite/dependency of QuickLook is now Microsoft Edgium browser? e.g. will it still work if I don't have Edgium installed?

**Comment by rabelux** [comment]
All you need is the edge runtime package. If you run QuickLook and don't have it installed it will show you a link where you can download said package.

**Comment by xupefei** [comment]
It's depending on `Microsoft Edge WebView2`. It's an independent package to the Edge browser.

**Comment by Darthagnon** [comment]
Thank you so much! [Here's the download link to Edgium Webview 2](https://developer.microsoft.com/en-us/microsoft-edge/webview2/) for any future user who comes across this thread

**Comment by rabelux** [comment]
Direct download-link: https://go.microsoft.com/fwlink/p/?LinkId=2124703

**Comment by Harriser** [comment]
When installing "Webview2", error "0x8004070c" is reported. After deleting "C:\Program Files (x86)\Microsoft", download and install "Evergreen Standalone Installer"
Ready to use after restarting
https://developer.microsoft.com/en-us/microsoft-edge/webview2/?form=MA13LH#download-section
