### ISSUE TITLE
与 Clover 不兼容

### ISSUE THREAD

**Issue by lidongcheng88** [QL-Win/QuickLook#542]
Win7 下不能用空格预览，在打开方式中使用 QuickLook 可以，卸了 Clover 可以空格预览
ps： 使用 Seer 没有兼容性问题

**Comment by ANNEALLING** [comment]
this question also appears in my Windows 8

**Comment by 0-yy-0** [comment]
this problem also appears in my Windows 7.What should we do?

**Comment by xupefei** [comment]
I got an email from a kind guy a few days ago in which he states he is working on a fix.
Stay tuned!
