### ISSUE TITLE
Wiki page with available plugins got deleted

### ISSUE THREAD

**Issue by Ullmie02** [QL-Win/QuickLook#544]
**Describe the bug**
The available plugins wiki page got deleted in https://github.com/QL-Win/QuickLook/wiki/_compare/aa40bfcdc49edf35a89c242b675422e1e33fcbdf

**To Reproduce**
1. Right Click the tray icon
2. Click "search plugins"
3. Github pages opens in edit mode without any content

**Expected behavior**
The wiki should open and display the available plugins

**Desktop:**
 - OS Version: Windows 10 1809
 - QuickLook Version: 3.6.5 from Windows Store

**Comment by rabelux** [comment]
Confirming your issue and happy to report that I was able to fix it.
No idea why @wis-w did this but I guess it was a mistake as he's new to github.
