### ISSUE TITLE
I can't read my .md files.

### ISSUE THREAD

**Issue by cuiko** [QL-Win/QuickLook#558]
**Describe the bug**
I can't read my .md files, the other day, it was work :(

**To Reproduce**
1. click my .md files
2. just show white background... :(

**Expected behavior**
i want to see my .md files, it's important.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1709]
 - QuickLook Version: [e.g. v3.6.5 from .msi]

**Screenshots and Exception Log**
[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/3720163/QuickLook.Exception.log)
![GIF](https://user-images.githubusercontent.com/33982919/66694193-7ff4ed00-ece3-11e9-830b-423dffc3fbcf.gif)

**Comment by a224515a** [comment]
The same problem.
QuickLook works fine in any other file formats.
I am using QuickLook v3.6.9 (msi) on Windows 10 1909.

**Comment by emako** [comment]
Markdown viewer is depends on webview2
