### ISSUE TITLE
Windows Defender Threat Detected: Trojan:Win32/Fuerboos.A!cl - False Positive?

### ISSUE THREAD

**Issue by albino1** [QL-Win/QuickLook#561]
Hey there,

I'm using [QuickLook-3.6.5-11-gcb00051.msi](https://ci.appveyor.com/project/xupefei/quicklook/builds/27667726/artifacts) which [you posted here](https://github.com/QL-Win/QuickLook/issues/521#issuecomment-535152095) as a fix for the Everything Search problem.

It's been working fine, but the other day I got a popup warning from Windows Defender saying it has quarantined a severe threat from QuickLook.  Here's a screenshot:

![quicklook-virus](https://user-images.githubusercontent.com/12164957/66988096-cd23e680-f076-11e9-85bd-ce8be1f6362f.jpg)

And here's the page it links to:

https://www.microsoft.com/en-us/wdsi/threats/threat-search?query=Trojan:Win32/Fuerboos.A!cl

I'm guessing (hoping) this is a false positive, and if so, you might want to look into what's causing it and how to avoid it in the future.

Hope this helps, thanks.

**Comment by albino1** [comment]
Virus Total reports it as 11/57 with a virus detected:

https://www.virustotal.com/gui/file/d182835cf7418262456f5366961985f8daaefd7fba0958925eebb5217ddda04f/detection

**Comment by xupefei** [comment]
It's a false positive. The `Wow64HookHelper.exe` is used for capturing keypresses in Open/Save File Dialogs. It's flagged by antivirus software because it injects itself into another process, which is a trojan-like behaviour.

I don't know any fast way to keep this away from happening again, but one way that proved to be useful is to report it to the developer of your antivirus software. If you also have a chance to send a few comments to them, you can provide them with a link to this issue :)

**Comment by albino1** [comment]
I figured it was something like that :)

Thanks for clearing it up!

**Comment by N3pp** [comment]
> The `Wow64HookHelper.exe` is used for capturing keypresses in Open/Save File Dialogs.

How come QuickLook still works in "Open/Save File" windows even if I delete/quarantine `Wow64HookHelper.exe` then? Shouldn't it stop working?

**Comment by N3pp** [comment]
> The `Wow64HookHelper.exe` is used for capturing keypresses in Open/Save File Dialogs.

How come QuickLook still works in "Open/Save File" windows even if I delete/quarantine `Wow64HookHelper.exe` then? Shouldn't it stop working?

@xupefei

**Comment by xupefei** [comment]
@N3pp 

> How come QuickLook still works in "Open/Save File" windows even if I delete/quarantine Wow64HookHelper.exe then? Shouldn't it stop working?

Wow64HookHelper.exe is used for enabling QuickLook for "Open/Save File" dialogues opened by a 32-bit application running on a 64-bit operating system.

QuickLook works without Wow64HookHelper.exe for dialogues opened by a 64-bit application.

**Comment by KiruyaMomochi** [comment]
I'm trying to submit it to winget but stuck at Microsoft Defener: <https://github.com/microsoft/winget-pkgs/pull/476>

Since it's a false positive, can we submit to Microsoft for a review?
I'll submit it as a Home customer now. However, it maybe better to submit by the developer.
**Submit link**: <https://www.microsoft.com/en-us/wdsi/filesubmission>

**Comment by xupefei** [comment]
Thanks for the link. I have submitted the claim as a developer and let's what will happen next.

**Comment by xupefei** [comment]
I got the message from Microsoft. This false positive has been removed.

--------

quicklook.wow64hookhelper.exe.zip

Submission ID: 5de5c8b8-be00-4e62-9c98-44e8caea0876
Status: Completed
Submitted by: [email address removed]
Submitted: May 22, 2020 10:12:27

User Opinion: Incorrect detection

Analyst comments:


We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.

1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

**Comment by KiruyaMomochi** [comment]
Great! I have pushed the package again, now waiting for manual review from Microsoft.
