### ISSUE TITLE
App doesn't use appropriate locale

### ISSUE THREAD

**Issue by maximmax42** [QL-Win/QuickLook#566]
**Describe the bug**
QuickLook launches with English locale, despite my Windows being in Russian and QL having Russian translation.

**To Reproduce**
1. Have a Russian Windows install
2. Launch QL
3. It's in English

**Expected behavior**
QL launching with Russian translation

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1809
 - QuickLook Version: 3.6.5 standalone

**Screenshots and Exception Log**
I guess as a screenshot I can prove it's in English while showing some Windows app in Russian.
![image](https://user-images.githubusercontent.com/2225711/68075143-b3e49f00-fdc5-11e9-9e91-c7ad555d528e.png)

**Comment by maximmax42** [comment]
Should be ru-RU, my own app that has localization shows in Russian as well, checking CultureInfo.CurrentCulture and CultureInfo.CurrentUICulture show ru-RU as well.
![image](https://user-images.githubusercontent.com/2225711/68232308-a8d87b80-001e-11ea-9853-78f60041a797.png)

**Comment by xupefei** [comment]
Oh, I figured out. In the translation file, Russian is labelled as `<ru_RU>` instead of `<ru-RU>`. I'll fix it right now. You can also fix it by yourself by modifying Lines 362 and 386 of the `Translations.config` file in the QuickLook installation folder.
