### ISSUE TITLE
[Feature request] Integration with FreeCommander

### ISSUE THREAD

**Issue by peterwx** [QL-Win/QuickLook#569]
QuickLook works well with existing file managers as mentioned in the wiki.
But using space(bar) (which hasn't a keybinding by default in FC) doesn't work with FC.
It would be nice if it did, although i don't have a clue of the feasibility of such integration.

**Comment by xupefei** [comment]
It seems that FreeCommander does not have any API exposed to get the currently-selected file.

The workaround is to add QuickLook as an external viewer: https://freecommander.com/fchelpxe/en/SettingsExternalViewers.html and use `Shift+F3` to open and close preview windows.

Note that you have to use `.msi` or portable version of QuickLook to do this.

**Comment by peterwx** [comment]
I've done as per your instructions and it works. As filter i've used *(global wildcard) since it is not possible in Freecommander(FC) to add all file formats supported by Quicklook and its plugins (must be some filter text size limitation and the notation ext=fext1,ext=fext2 also isn't short). In my case i now use Quicklook with FC  which complements other FC plugins like cudalister and SQLiteViewer.
Thanks for your help.
