### ISSUE TITLE
Can‘t open files which are not set "Open with" 

### ISSUE THREAD

**Issue by rainin9** [QL-Win/QuickLook#571]
**Describe the bug**
Can‘t open files which are not set "Open with" 

**To Reproduce**
The .java files are not associate with any software.
![9QJShNGjHWkXbvK.png](https://i.loli.net/2019/11/08/9QJShNGjHWkXbvK.png)
![11.gif](https://i.loli.net/2019/11/08/zL6CaKUNlSmEMiJ.gif)
**Expected behavior**
The .java file are open with notepad in the preview window.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1903
 - QuickLook Version: 3.6.5

**Comment by xupefei** [comment]
What happened with you double-click this file?

**Comment by IlO0OlI** [comment]
> What happened when you double-click this file?

![无标题.png](https://i.loli.net/2019/11/18/9JmY83Vh6ofLSeF.png)

**Comment by xupefei** [comment]
First assign `.java` files to Notepad and try again.
