### ISSUE TITLE
Option to not display quicklook splash screen upon starting

### ISSUE THREAD

**Issue by mcascone** [QL-Win/QuickLook#577]
*For all's convenience, please use English to fill this issue.*
I would like the option to not see the quicklook "Quicklook is installed and this is what it does" popup when it starts. I have QL set to load at startup, and I don't need to see that window every time.

**Describe the solution you'd like**
An option to configure the splash screen to not display when starting QL.

**Comment by xupefei** [comment]
QuickLook should not display anything upon start.
Can you give a picture?

**Comment by mcascone** [comment]
I get this on startup of my machine:
![QL](https://user-images.githubusercontent.com/8335079/69094150-757def80-0a15-11ea-9b9b-3337b6cd2339.jpg)

**Comment by rabelux** [comment]
That window only appears if you run/start quicklook although it's already running. Have you manually added it to autostart or anything like that? All that is needed to have Quicklook be launched at startup is to tick "run at startup" found in the right-click-menu of the toolbar-icon

**Comment by mmn6d6d6e** [comment]
In my case, I happened to have both Microsoft Store & GitHub versions installed.

As both run at startup, the last one run will cause the message popping up.
