### ISSUE TITLE
quicklook cant preview music and video

### ISSUE THREAD

**Issue by 72888hshu** [QL-Win/QuickLook#578]
**Describe the bug**
Welp when i want to preview any music or video file, it give me this error:
(Look Screenshot below)
**To Reproduce**
1. Welp just preview any music or video file, i think it just happen to me.

**Expected behavior**
Play the music/video file?

**Desktop (please complete the following information):**
 - OS Version: [ Windows 6.1 Build 7601 32bit]
 - QuickLook Version: [3.6.5 from zip version

**Screenshots and Exception Log**
![quicklook bug](https://user-images.githubusercontent.com/48046222/69148992-81021100-0b10-11ea-99fd-e9a3694fcba4.PNG)

![quicklook bug 2](https://user-images.githubusercontent.com/48046222/69149383-52d10100-0b11-11ea-8e65-8b6acc316575.PNG)

**Comment by xupefei** [comment]
Do you have the graphic card driver installed?

**Comment by 72888hshu** [comment]
it was Intel(r) Graphics Media Accelerator 3150
It OpenGL version is 1.4 and DirectX version is 9 (Yep it was old)
Maybe its the problem with OpenGL?

**Comment by xupefei** [comment]
I think it's because of DX9. QuickLook uses LAV Filter to play videos, which requires DX11.

No solution, sorry :(

**Comment by 72888hshu** [comment]
ok then, thanks for replying me.
