### ISSUE TITLE
Windows 10 (Nov. 2019 Update) Explorer Search + Space Bug

### ISSUE THREAD

**Issue by lotsacaffeine97** [QL-Win/QuickLook#579]
**Describe the bug**
I just updated to the Windows 10 November Update, which touts an improved search functionality within windows explorer that ties into the Windows Search on the taskbar, as well as the current windows explorer files. In summary, they have been changing how search works. I have now noticed an issue when using search in windows explorer which causes QuickLook to launch a preview of any passively selected file while typing a query into the windows explorer search box that contains a space. I don't recall ever experiencing this issue before, so I imagine it has to do with the November 2019 update to Windows. 

**To Reproduce**
1. Open Windows Explorer
2. Navigate to any folder you want to search
3. Passively click a file so that it is selected (but not opened. Also do not hit space.)
4. Click in the Windows Explorer search box and type a query with a space (i.e. Facts Document)
5. The document that was selected in step 3 will open in QuickLook preview - Even though system focus should be in the search box, not the file list. 

**Expected behavior**
In step 5 from above, I would expect that QuickLook would be able to ignore the space being entered into the search box query, rather than interpreting it as a request to preview the file.

**Desktop (please complete the following information):**
 - Windows 10 1909
 - QuickLook Version: 3.6.5

**Screenshots and Exception Log**
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/57977128/69210948-ad6e5b00-0b19-11ea-85df-72c05004b6fd.gif)

**Comment by SplitGemini** [comment]
Yeah, I want it be fixed too.

**Comment by xupefei** [comment]
This might be a new bug since Explorer have added a Dark Mode, since I noticed the search textbox now looks different than in old Windows versions.

I will check.

**Comment by xupefei** [comment]
Fixed! You can try it here: https://ci.appveyor.com/project/xupefei/quicklook/builds/32983144/artifacts

**Comment by SplitGemini** [comment]
Don't work

**Comment by SplitGemini** [comment]
![1](https://user-images.githubusercontent.com/34861918/82415512-348d9300-9aab-11ea-9c53-d2e9f4912703.gif)

My windows version is win10 1909 (build 18363.863)

**Comment by SplitGemini** [comment]
Must cancel selected first before tap space in search box

**Comment by xupefei** [comment]
It works for me. Are you sure the latest version is running?
You can right-click on the tray icon and read the version number. It should be "v3.6.8-10-g3f587c7".

**Comment by SplitGemini** [comment]
> It works for me. Are you sure the latest version is running?
> You can right-click on the tray icon and read the version number. It should be "v3.6.8-10-g3f587c7".

Yeah, it's this version, it works when no item is selected, but if select an item, it doesn't work.

**Comment by xupefei** [comment]
It should be okay now: https://ci.appveyor.com/project/xupefei/quicklook/builds/33000705/artifacts
