### ISSUE TITLE
Command line protocol for Windows Store version

### ISSUE THREAD

**Issue by bwiernik** [QL-Win/QuickLook#584]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
I maintain a [QuickLook plugin for the Zotero reference manager](https://github.com/mronkko/ZoteroQuickLook). Many users install the Windows Store version of QuickLook, which doesn't work with the plugin because there is no way to access QuickLook from the command line. I'd like to be able to support this installation. 

**Describe the solution you'd like**
I'd like both the `.msi` and Windows Store versions of QuickLook to register a `quicklook:` protocol (e.g., https://docs.microsoft.com/en-us/windows/uwp/launch-resume/handle-uri-activation) so that file paths can be passed to either version of the program using the same command.

**Describe alternatives you've considered**
Using a NamedPipe isn't possible, because the Zotero program is built on a base of Firefox, so it is not possible to access the user's SID to construct a NamedPipe.

Currently, the only alternative is to direct my users to not use the Windows Store version.

**Comment by xupefei** [comment]
A custom protocol has to be registered in the Registry so I don't want to support that unless necessary. Instead, I can make a small EXE that connects to the pipe of both versions of QL. You can then ship it with your plugin and call it instead of calling QuickLook.

-- Is this okay for you?

**Comment by bwiernik** [comment]
That would work too. Thanks!

**Comment by xupefei** [comment]
Glad to hear that. Try this one: [Bridge.zip](https://github.com/QL-Win/QuickLook/files/3929358/Bridge.zip)

**Comment by xupefei** [comment]
After some search, I found that Zotero seems better than Mendeley regarding LaTeX/BibTeX integration. Let me try for a few days and see :P

**Comment by bwiernik** [comment]
I definitely think so. You will want to install the BetterBibTeX plugin, which further expands the robustness and customizability of BibTeX support: https://github.com/retorquere/zotero-better-bibtex/releases

**Comment by bwiernik** [comment]
This is working great, thanks! One request: I'd like to display a more informative warning message if neither version of QuickLook is installed. Could you possibly change the Exception message to:
`QuickLook not found. Please install QuickLook (http://pooi.moe/QuickLook/) or specify a custom view command instead.` and recompile Bridge.exe?

**Comment by xupefei** [comment]
Sure. Here it is!

[Bridge.zip](https://github.com/QL-Win/QuickLook/files/3952155/Bridge.zip)

**Comment by bwiernik** [comment]
Thanks!

**Comment by bwiernik** [comment]
Sorry to bother. I'm trying to compile the exe myself from source. When I do, each time I lauch `Bridge.exe`, a command prompt window opens before either the QuickLook window or the error message appears. When I run the compiled exe you provide, that doesn't happen. Do you know how I can compile `Bridge.exe` so that it runs quietly like yours does?

(I'm compiling it using Visual Studio 2019 Build Tools, running csc.exe from the command line.)

**Comment by xupefei** [comment]
You have to specify the EXE type as WINEXE:
```
csc /target:winexe Bridge.cs
```

**Comment by bwiernik** [comment]
Thanks!
