### ISSUE TITLE
PCM Audio Not Working When Playing Video

### ISSUE THREAD

**Issue by KLEPTOROTH** [QL-Win/QuickLook#585]
When attempting to QuickLook MP4's with PCM audio, no audio will play.

**To Reproduce**
Play an MP4 with PCM audio via spacebar.

**Expected behavior**
Audio should play alongside video

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 1903]
 - QuickLook Version: [3.6.5 from Github MSI]

No log was generated for me.

**Comment by emako** [comment]
It has been a long time and no sample file has been provided.

If you have any questions, please continue to reply.
