### ISSUE TITLE
When the music is playing, I hear nothing at 50% volume.

### ISSUE THREAD

**Issue by aiurye** [QL-Win/QuickLook#588]
When the music is playing, I hear nothing at 50% volume.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1903]
 - QuickLook Version: [e.g. 3.6.2 from Windows Store]

**Comment by xupefei** [comment]
I also observed the same issue. For some reason, `1` is not the maximal volume as stated here: https://github.com/Sascha-L/WPF-MediaKit/blob/8db992125d11abc400d237ff9dfeba3f32afd872/Source/DirectShow/MediaPlayers/BaseClasses.cs#L377. I haven't had any research on the root cause yet.

**Comment by Rutherford1895** [comment]
I observed the same problem. It seems the volume while playing music or video is not linearly proportional to the volume bar's position.

**Comment by mooflu** [comment]
Looks like the DirectShow interface uses a logarithmic scale for volume. See https://docs.microsoft.com/en-us/previous-versions/windows/embedded/ms939532(v=msdn.10)
