### ISSUE TITLE
Add reference to Files UWP in the wiki

### ISSUE THREAD

**Issue by yaichenbaum** [QL-Win/QuickLook#592]
A UWP File Manager called Files UWP recently added support for Quick Look. I saw that there was a page in the wiki for File Managers and was wondering if Files UWP can be added to the list. The app detects if Quick Look is installed and if it is added support for holding down on the space bar to view a file as well and it also adds an item to the right click context menu.

The project is open source on GitHub:
https://github.com/duke7553/files-uwp

And is also available on the store:
https://www.microsoft.com/store/apps/9NGHP3DX8HDX

**Comment by xupefei** [comment]
Of course! Feel free to modify the wiki page :)

**Comment by yaichenbaum** [comment]
Should I put it under out of box support?

**Comment by xupefei** [comment]
Yes, please!

**Comment by yaichenbaum** [comment]
Done! Thank you so much 😃
