### ISSUE TITLE
Is there any ways to hide the QuickLook icon in the taskbar?

### ISSUE THREAD

**Issue by alanjyu** [QL-Win/QuickLook#596]
So far love it, but am wondering if there is a way to hide the icon in the taskbar (not in the collapsable menu but hidden completely)?

**Comment by xupefei** [comment]
You need to modify the code and compile by yourself: https://github.com/QL-Win/QuickLook/issues/191

**Comment by xolom** [comment]
I really like this tool, but the main drawback for me is the unnecessary tray icon. I don't want to install visual studio, .net sdk, ... to compile my own version. If any update will come, i need to compile it again. With a simple checkbox or tray menu entry this "issue" could be easily solved and would help many users out there. you could trigger a popup message after disabling the tray icon, where it explains the user how to get it back..

**Comment by Therzok** [comment]
Would having a registry value for the tray icon (meaning only advanced users turn it off) be a good compromise?

**Comment by xolom** [comment]
Or run the whole thing as a service?

**Comment by xupefei** [comment]
Solved in https://github.com/QL-Win/QuickLook/issues/729.
