### ISSUE TITLE
cannot adapt to the picture's size while viewing

### ISSUE THREAD

**Issue by cat1k** [QL-Win/QuickLook#597]
hey, I'm an old user with Quicklook, I remembered it used to be able to adjust the viewing zoom size  based on the picture's size. For example, when I view a small picture(446 x 220px for example), it can still show the whole view(adjust the zoom rate automatically), not just a very small part of it. But now when I open some pictures, the smallest zoom rate cannot let me see the whole picture(and it always be 90%), just an unclear part. I have to adjust by myself, that's not convenient. Hope to fix this problem. Thx.

the view automatically
![Snipaste_2020-01-07_22-09-12](https://user-images.githubusercontent.com/47454235/71901209-74a64600-319a-11ea-946e-8c3cd3965f82.png)
the view I want to show(is without zoom bar)
![Snipaste_2020-01-07_22-09-24](https://user-images.githubusercontent.com/47454235/71901231-825bcb80-319a-11ea-9ae7-cc7277bc004b.png)

**Comment by cat1k** [comment]
some picture even show like this.(this is the smallest I can zoom in, cannot show more part of the pic)
![Snipaste_2020-01-07_22-43-28](https://user-images.githubusercontent.com/47454235/71903639-7d4d4b00-319f-11ea-9f14-f7ecd5d6a062.png)

**Comment by rabelux** [comment]
related to #640 and #610 and should be fixed in the meantime
