### ISSUE TITLE
Cannot work in XYplorer software

### ISSUE THREAD

**Issue by Chilled-ops** [QL-Win/QuickLook#598]
Cannot work in XYplorer software

**Comment by daslicht** [comment]
XYPlorer has a built preview no ?

**Comment by daslicht** [comment]
see:
https://github.com/QL-Win/QuickLook/wiki/File-Managers

**Comment by JannesMeyer** [comment]
The builtin preview of XYplorer doesn't have as many features as QuickLook. For example, source code doesn't have syntax highlighting, etc.

I tried the method that's suggested in the wiki, but unfortunaly I can't achieve full integration. I always have to press the hotkey to update QuickLook. It doesn't automatically update when I move the selection with the up, down arrow keys or when I press tab to switch the file pane.

**Comment by xupefei** [comment]
You need to ask XYplorer to integrate QL.
Alternatives with better integration are Files UWP and Directory Opus.

**Comment by JannesMeyer** [comment]
Thanks! I love QuickLook, by the way

**Comment by Geeyun-JY3** [comment]
> https://github.com/QL-Win/QuickLook/wiki/File-Managers

This page is missing?

**Comment by rabelux** [comment]
Yeah thanks @mmasters1287 who deleted that page for no reason. Page has been restored.
