### ISSUE TITLE
当文本文件的编码是GBK时预览显示的中文乱码

### ISSUE THREAD

**Issue by YukiIsait** [QL-Win/QuickLook#600]
当文本文件的编码是GBK时预览显示的中文乱码

![对比截图](https://user-images.githubusercontent.com/26496323/72241457-e1e62b00-3621-11ea-8588-48d15f75f531.png)

**Comment by xupefei** [comment]
文本编码检测用了Chardet库，这个库在文字很少的情况下可能判断错误，没办法。大文件一般不会出错。

**Comment by diligamer** [comment]
WAT

**Comment by emako** [comment]
Fixed in nightly build

https://github.com/QL-Win/QuickLook/releases

**Comment by Chen-HT** [comment]
这个问题在4.0.2还是存在呀

**Comment by Chen-HT** [comment]
[test.txt](https://github.com/user-attachments/files/20736857/test.txt)
