### ISSUE TITLE
Folder view suggestion

### ISSUE THREAD

**Issue by ghost** [QL-Win/QuickLook#601]
I would like to suggest that it would be handy to be able to view whats inside folders, just like you can view whats inside archives.
I know the program "seer" has this, but i prefere quicklook so it would be cool to see this feature here aswell

**Comment by Experien1985** [comment]
yes! please!

**Comment by brucefeng10** [comment]
Same question as #491

**Comment by rabelux** [comment]
Duplicate of #491
