### ISSUE TITLE
Getting trojan warnings after installing nightly

### ISSUE THREAD

**Issue by wss7932** [QL-Win/QuickLook#602]
This may or may not be legitimate but, I just re-installed my PC yesterday and used the QL nightly.  I got a warning while installing but, supposed it to be a false positive.  Today I got another prompt.  Is this correct or is Windows Defender just flagging it incorrectly?

![Annotation 2020-01-20 143709](https://user-images.githubusercontent.com/3491677/72756367-99cf8700-3b92-11ea-8760-50ed6b92c57a.png)

**Comment by rabelux** [comment]
Did you stumble upon issue #561? Seems fitting

**Comment by wss7932** [comment]
Thanks for pointing that out.  Good to know.
