### ISSUE TITLE
Smaller UI for prelistening Audio Samples

### ISSUE THREAD

**Issue by daslicht** [QL-Win/QuickLook#604]
When prelistening a huge collection auf audio samples, we dont need a big floating window as it is at the momnet. If you minimize teh window it cant be dragged anymore so we have to keep it bigger or there a way to remove the Open in Groove Muisc Button which takes unnesesary space ?

**Comment by xupefei** [comment]
This is currently impossible. The preview window should be consistent across all file types IMO so I would not remove the button.

A workaround is to put the preview window in the background. Meanwhile, if you select another file the preview window will also change.

**Comment by daslicht** [comment]
Why is that Groove Music Button Important ?

**Comment by daslicht** [comment]
Another thing would be nice if Quicklook would not Lock previewed files. Lets say you browse files. Now you find one nice and want to do something with it. Currently we have to select another file first other case quicklook keeps locking it.

**Comment by xupefei** [comment]
The button is there since this software is designed to replicate macOS Quick Look:
<img width="478" alt="image" src="https://user-images.githubusercontent.com/1687847/73964712-6bd09d80-491b-11ea-8c30-f8d153782e70.png">


> At the moment we cant move the window when at smallest size.

Can you describe the problem in detail, maybe with screenshots?

**Comment by daslicht** [comment]
Have a look that this , :
![](https://www.youtube.com/watch?v=2tAjvELm7BU&feature=youtu.be)

**Comment by xupefei** [comment]
I see. It's a bug.

**Comment by daslicht** [comment]
the pin feature doesnt work either'

**Comment by xupefei** [comment]
It is as expected. Pinning a window will keep that preview open, regardless of how your selection changes.

**Comment by daslicht** [comment]
hm that doent make sense, when you pin a window it should play any files you further select

**Comment by daslicht** [comment]
Thank you for thesmaller  button !
