### ISSUE TITLE
Cannot preview pdf files on Windows 10 Enterprise

### ISSUE THREAD

**Issue by juliusgabrielalba** [QL-Win/QuickLook#605]
**Describe the bug**
Error. Cannot preview pdf files. Error always appears.

**To Reproduce**
I select a file and then I press space to view it.

**Expected behavior**
It should make a contents preview screen as it does normally...

**Desktop (please complete the following information):**
 - OS Version: Windows 10 E
 - QuickLook Version:  3.6.5

![Screenshot_2](https://user-images.githubusercontent.com/42362706/73158241-39a28d00-411e-11ea-85cc-f30ee323c8fa.png)

**Comment by xupefei** [comment]
Could you paste the exception log?

**Comment by rabelux** [comment]
Closed due to missing response
