### ISSUE TITLE
如果图片DPI小于24，预览时，图片不能适应窗口。

### ISSUE THREAD

**Issue by PYT2022** [QL-Win/QuickLook#606]
我下了一套图，预览时放大了N倍只能看到图片的极小一部分，别的图片可以正常预览。我发现DPI不同，用faststone查看DPI时300*300，用win10资源管理器查看却是1*1，看来QL采用的时WIN10这个不准确的值。进一步测试发现DPI小于24的话，预览就不能适应窗口，图片会比窗口要大，大多少取决于DPI有多小。

**Comment by xupefei** [comment]
这是正常的。你这些图片的DPI值有问题。
用工具批量删除DPI信息就好了。
