### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by daslicht** [QL-Win/QuickLook#608]
It would be useful if the quickview popup would open anytime at the last position where it was dragged.
At the moment it always opens in teh middle of the screen and most times above the file we actually preview/listen :)

**Comment by fsjwlf** [comment]
Agree with you!
If quicklook can remember the window position, I would put explorer on the left, and quicklook on the right of screen. It looks like an Evernote!

**Comment by emako** [comment]
https://github.com/QL-Win/QuickLook/issues/169
