### ISSUE TITLE
OpenOffice Integration for previewing word, excel, powerpoint

### ISSUE THREAD

**Issue by MrPickles2009** [QL-Win/QuickLook#609]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
I would like to quickly preview the contents of word, excel and powerpoint documents instead of seeing this:
![image](https://user-images.githubusercontent.com/20229190/74156894-41196a00-4be5-11ea-9156-d8f37ebc3b4a.png)

**Describe the solution you'd like**
I haven't looked too far into this but possibly integrating the OpenOffice sdk with quicklook would allow you to do this? [https://www.openoffice.org/api/SDK/](https://www.openoffice.org/api/SDK/)

**Describe alternatives you've considered**
A more difficult alternative could maybe using visual studio's office dev tools to do something similar? [https://visualstudio.microsoft.com/vs/features/office-tools/](https://visualstudio.microsoft.com/vs/features/office-tools/)

**Additional context**
n/a

**Comment by rabelux** [comment]
But you do have the appropriate [plugin](https://github.com/QL-Win/QuickLook/wiki/Available-Plugins) installed, right?

**Comment by MrPickles2009** [comment]
Oh wow! nope! I didn't realise there were plugins for this app. Thanks!

**Comment by rabelux** [comment]
@xupefei my colleagues had the same problem, managed to install quicklook but didn't know about plugins. As previewing office-files is probably a feature many users need, wouldn't it be a good idea to include the native plugin in the installer? It is only 4 kb in size and I think a lot of users (only those with MS office, I know) would benefit from it.

**Comment by xupefei** [comment]
@rabelux It was shipped with QuickLook sometimes ago, but I decided to not do it because it crashes A LOT :(

**Comment by MrPickles2009** [comment]
that's too bad. thanks for letting us know
