### ISSUE TITLE
ruby file highlight support?

### ISSUE THREAD

**Issue by xxjapp** [QL-Win/QuickLook#613]
ruby file highlight support?

**Comment by xupefei** [comment]
Copy the content of this file: https://github.com/Dirkster99/AvalonEditHighlightingThemes/blob/09f02f9353bb28c7543116cfec00570904a68166/source/HL/Resources/Light/Ruby.xshd
and name it as `<Install_Dir>/QuickLook.Plugin/QuickLook.Plugin.TextViewer/Syntax/Ruby.xshd` then restart QuickLook.

Does it work?

**Comment by xxjapp** [comment]
Try a lot but no way to copy downloaded Ruby.xshd to <Install_Dir>/QuickLook.Plugin/QuickLook.Plugin.TextViewer/Syntax/.

**Comment by xupefei** [comment]
You will need to test using the portable version.

**Comment by xxjapp** [comment]
@xupefei 
portable version with above Ruby.xshd works.
Thank you for your great work.

**Comment by xupefei** [comment]
Thanks for the feedback! I have added the syntax file to QuickLook. You can switch back to the Store version starting from the next release :)
