### ISSUE TITLE
DDS image format

### ISSUE THREAD

**Issue by Darklocq** [QL-Win/QuickLook#614]
**Is your feature request related to a problem? Please describe.**
Not a problem in the outright bug sense, just some utility that's lacking, especially given the blurb "Supported File Types: Almost all image formats".  This is a particular common format (leading UV mapping texture used in games and other 3D modeling, though has some other uses as well).

**Describe the solution you'd like**
It would be mega-awesome if this supported .DDS texture files the way it does other images. It's a pretty well-documented format (it has several variations, but all are standardized in detail).  Probably the easiest place to get open-source code for it would be the GIMP DDS Plugin: https://code.google.com/archive/p/gimp-dds/

**Describe alternatives you've considered**
GIMP can read DDS files with that plugin (there's also one for Photoshop), and IrfanView supports them to an extent (it does very poorly with images mostly consisting of alpha, since it puts them on a black background instead of GIMP's neutral grey with checkerboard pattern). But both of these require opening the images in an app. GIMP is painfully slow and (being a Photoshop competitor) a total memory hog, while IrfanView is no good for alpha-heavy examples, which makes up quite a large percentage of them.  GraphicConverter on the Mac also supports them, faster than GIMP and better than IrfanView, but that's only practical when I'm working in a Windows VM on a Mac and have a shared directory between the two OSes. Moving files around and flipping back and forth between OSes ends up only being marginally faster than just firing up GIMP in Windows. Photoshop would probably be even slower, and I decline to pay a zillion dollars to Adobe when GIMP works for what I need in a graphics editor.

**Additional context**
It's a format I work with near-daily, as does anyone else modding popular games like _Skyrim_, _Fallout 4_, etc., etc.  I actually downloaded QL-Win with the intent/hope of using it for this (per "Almost all image formats"). The format has been the main one used in games for UV since at least the early 2000s (in _Morrowind_ and other games of the era).

**Comment by zhangkaihua88** [comment]
I created [QuickLook.Plugin.DDSViewer](https://github.com/zhangkaihua88/QuickLook.Plugin.DDSViewer)
, which preview dds file by using [Pfim](https://github.com/nickbabcock/Pfim) convert dds to png. Now it supports Rgba32, Rgb24, R5g5b5a1, R5g5b5, R5g6b5 and Rgb8 image formats.

**Comment by rabelux** [comment]
This issue seems to be solved.

**Comment by Darklocq** [comment]
> I created [QuickLook.Plugin.DDSViewer](https://github.com/zhangkaihua88/QuickLook.Plugin.DDSViewer)

Schweet!  Got it and it's working great so far.  Thanks!
