### ISSUE TITLE
Error when previewing image/video/HTML files in WSL

### ISSUE THREAD

**Issue by Stanzilla** [QL-Win/QuickLook#617]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
When using QL on a file on a network share/UNC path, in my example inside of a WSL container, it errors.

**To Reproduce**
1. Have a file in a WSL container and open an Explorer window to it
2. Trigger QL

**Expected behavior**
Image should open as normal

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - QuickLook Version: 3.6.5.0 installed via .msi

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log` (`.msi` or `.zip` version) or `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log` (Windows Store version).

```

========04.03.2020 20:05:14========
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at QuickLook.Plugin.ImageViewer.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass5_0.<BeginShow>b__0()

========07.03.2020 03:55:33========
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at QuickLook.Plugin.ImageViewer.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass5_0.<BeginShow>b__0()

========07.03.2020 04:02:43========
System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at QuickLook.Plugin.ImageViewer.Plugin.View(String path, ContextObject context)
   at QuickLook.ViewerWindow.<>c__DisplayClass5_0.<BeginShow>b__0()

```

**Comment by JacobDB** [comment]
I'm also seeing this issue, drives me crazy since I use WSL for literally all of my work projects.

**Comment by xupefei** [comment]
Can you give an example of the path?

**Comment by Stanzilla** [comment]
`\\wsl$\Ubuntu\home\stan\projects\personal\WeakAuras2`

**Comment by JacobDB** [comment]
Is this related to the *:Zone.Identifier issues I've seen? I've suspected that it was QuickLook causing it, but had a hard time reliably reproducing.

**Comment by xupefei** [comment]
> Is this related to the *:Zone.Identifier issues I've seen? I've suspected that it was QuickLook causing it, but had a hard time reliably reproducing.

No.

**Comment by JacobDB** [comment]
Has this been fixed? Seems to be much improved lately, using Windows 10 21H1 19043.1023, QuickLook v3.6.11.

**Comment by Stanzilla** [comment]
It has not, it just no longer crashes but the images don't load either
