### ISSUE TITLE
Deletion delayed after quickview

### ISSUE THREAD

**Issue by MerrickZ** [QL-Win/QuickLook#620]
After I use QuickView to view a video file, I hit spacebar and Quickview window disappeared, then I hit "delete" to delete that video, it fails everytime because QuickView is using that file

![image](https://user-images.githubusercontent.com/1021332/77251633-6db3ad80-6c8a-11ea-8c98-f801764f224e.png)

It seems Quickview will hold that file for 1 or 2 seconds after quickview window disappeared, so, could this be improved ?

Thank you ~

**Comment by rabelux** [comment]
This should be solved soon by #603

**Comment by xupefei** [comment]
Fixed :)

**Comment by daslicht** [comment]
![](https://i.imgur.com/CUenC7E.png)
