### ISSUE TITLE
Image In MD Bug

### ISSUE THREAD

**Issue by Nyameliaaaa** [QL-Win/QuickLook#621]
**Describe the bug**
Images In MD Files Don't Appear

**To Reproduce**
1. Add An MD File With Image
2. Press Space In File Explorer On Said MD File

**Expected behavior**
Image Pops up Like Normal

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2009
 - QuickLook Version: v3.6.5 from Windows Store

![image](https://user-images.githubusercontent.com/32780515/77781524-c73f2200-7066-11ea-9648-d531064e2c9c.png)

**Comment by diligamer** [comment]
@xupefei Can This Be Looked Be Into?

**Comment by emako** [comment]
Done, pls check nightly build

https://github.com/QL-Win/QuickLook/releases
