### ISSUE TITLE
Windows Security detects as Unwaders.A!ml

### ISSUE THREAD

**Issue by ak1dd** [QL-Win/QuickLook#622]
downloaded 3.6.6 msi.   Install completes but then Windows Security displays this dialog

![Untitled](https://user-images.githubusercontent.com/38289720/77817147-f4242100-70c8-11ea-968a-70a1c14e5bda.jpg)

I downloaded the ZIP and tried again.  Once everything is copied the same Windows Security event occurs.  Went back to 3.6.5 and it does not occur (whatever is detected is not a new false positive it is new to 3.6.6)

**Comment by ZUIcat** [comment]
Me too.

**Comment by rabelux** [comment]
Its a false positive, see https://github.com/QL-Win/QuickLook/issues/561#issuecomment-543184036

**Comment by ak1dd** [comment]
i said it was a false positive.   Doesn't mean it shouldn't be corrected.   The author can submit to MS
