### ISSUE TITLE
预览快捷方式时有BUG

### ISSUE THREAD

**Issue by ZUIcat** [QL-Win/QuickLook#623]
- 当预览快捷方式时，比如指向txt文件的快捷方式时，会先显示该快捷方式的预览，卡一下之后才会显示指向的txt文件的预览。

- 当再次按下空格试图关闭此预览时，指向的txt文件的预览会消失，但是该快捷方式的预览依然存在，需要再次按下空格键才会消失。

- 上一个版本3.6.5则无此问题。

***

- OS Version: Windows 10 1803

- QuickLook Version: QuickLook zip 3.6.6

- QuickLook.Exception.log并未出现报错信息。

***

1. 首先会显示该快捷方式的预览：

![图片](https://user-images.githubusercontent.com/35529568/77838180-176fce80-71a4-11ea-8ec0-ba8085466955.png)

2. 卡一下之后才会显示指向的txt文件的预览：

![图片](https://user-images.githubusercontent.com/35529568/77838185-1fc80980-71a4-11ea-8269-fbb9bc781036.png)

3. 再次按下空格试图关闭此预览时，快捷方式的预览依然存在

![图片](https://user-images.githubusercontent.com/35529568/77838180-176fce80-71a4-11ea-8ec0-ba8085466955.png)

**Comment by xupefei** [comment]
Fixed. Thank you!
