### ISSUE TITLE
Powertoys

### ISSUE THREAD

**Issue by acseven** [QL-Win/QuickLook#626]
Hi,
Have you considered adding your (excellent) tool to Microsoft's Powertoys (https://github.com/microsoft/PowerToys)?
Cheers

**Comment by Darthagnon** [comment]
Please don't move exclusively there; PowerToys only supports Win10 v1803 and higher (technically, the EXEs, once extracted from the installer, can work on lower Windows, but it's a pain, and they are not "installed"). QuickLook does, however, work on earlier versions of Windows.

**Comment by xupefei** [comment]
You should ask PowerToys developer to what they did to Wox: create a fork and include it into PowerToys. But I am afraid that the GPL license might become a problem then.
