### ISSUE TITLE
New fluent design icon suggestion

### ISSUE THREAD

**Issue by Donnnno** [QL-Win/QuickLook#627]
Hey, I'm new here and really love QuickLook But I was looking at the new fluid design icons for all Microsoft apps. And then I was thinking wouldn't it be cool if QuickLook had a fresh updated icon too. 
So I created a quick mockup how it would look with the new design guidelines and this is my result:

![quicklook_dark](https://user-images.githubusercontent.com/31142286/78271956-22f92780-750d-11ea-8efb-4007df512cf5.jpg)
![quicklook_light](https://user-images.githubusercontent.com/31142286/78271958-2391be00-750d-11ea-9e9f-64378eca5319.jpg)

Let me know what you think :^)

**Comment by QubitsDev** [comment]
Hi, I am the designer of the current icon and a few days ago I am working on the new icon.
![Quicklook](https://user-images.githubusercontent.com/25881789/78275160-3b524d80-74df-11ea-9360-adfaf8ac375f.png)
**Tray Icon (Dark & White Theme)**
![Tray-Black@100%](https://user-images.githubusercontent.com/25881789/78275228-4f964a80-74df-11ea-8624-654998e48491.png) ![Tray-Black@100%](https://user-images.githubusercontent.com/25881789/78275334-794f7180-74df-11ea-95d4-4b52ecae8d11.png)
this new version is very different from the current one. Please I want to know your opinions.

**Comment by Donnnno** [comment]
Oh haha didn't know that oops :)
It looks great! The colors look very good and the eye magnifying glass combination is also super cool.
Maybe put some subtle gradient in the magnifying glass shape. Great work :^)

**Comment by QubitsDev** [comment]
I used as a reference the Whiteboard icon "the pencil has no gradient".
![Calendar](https://user-images.githubusercontent.com/25881789/78278284-cc2b2800-74e3-11ea-8aac-45ccb8409eb3.png)![Photos](https://user-images.githubusercontent.com/25881789/78278288-cd5c5500-74e3-11ea-8161-170152d5a072.png)![Quicklook](https://user-images.githubusercontent.com/25881789/78278290-ce8d8200-74e3-11ea-822f-e2f323afc086.png)![Whiteboard](https://user-images.githubusercontent.com/25881789/78278295-d0574580-74e3-11ea-9a1e-6fd90c2893d1.png)

I want to replace the blue color, there are many blue icons in windows and add a gradient in the magnifying glass lens, I will publish some tests

**Comment by Donnnno** [comment]
Maybe use some subtle rounded corners like with the other icons.

**Comment by QubitsDev** [comment]
**QuickLook Icon V2**
![Quicklook](https://user-images.githubusercontent.com/25881789/78284930-1c0eec80-74ee-11ea-80a0-580769c1375b.png)
**Icon Tray preview mockup**
![Tray Preview](https://user-images.githubusercontent.com/25881789/78284932-1ca78300-74ee-11ea-9224-538c2cbc1024.png)

**Comment by WilliamDrt** [comment]
@QubitsDev That's nice

Here's a (crazy) though. 
Lose the eye all together and put an iris (a dot) inside the circle. That way the circle will be double serving as the eye and the magnify glass. 
Hey now that I am thinking of it why not triple serving. Make the handle same color as the circle and make it a little bit shorter so that it will be a magnifying glass and the capital letter Q. 
So, we have a circle with a dot in the middle with a little handle on the right lower side. 
I like minimalism. I got the idea when I looked the tray icon. 

Just a crazy thought...

**Comment by simioni** [comment]
Great work on these new icons!

IMHO this is one that best matches the new Microsoft icons. It's also a straight update to the current one, which already feels familiar. I don't see the need to redesign the icon entirely.

![image](https://user-images.githubusercontent.com/31142286/78271958-2391be00-750d-11ea-9e9f-64378eca5319.jpg)

**Comment by xupefei** [comment]
Great works! I am thinking the same as @simioni: the current icon + gradient looks very nice.

I am wondering -- will it looks better after adding a dark grey handle in the magnifier (like @QubitsDev's design V2/V3) in the OP's design?

**Comment by QubitsDev** [comment]
I like the @simioni icon, the blue color and the gradient looks great.
I still believe in using another color, I made a gray version of my icon.
![Quicklook - Gray](https://user-images.githubusercontent.com/25881789/78453248-69aa6700-765e-11ea-9b1e-790856b0dbe7.png) ![Quicklook – Bue](https://user-images.githubusercontent.com/25881789/78453252-6d3dee00-765e-11ea-821a-045c61ab6556.png)
i don't know what other color could work...

**Comment by Donnnno** [comment]
>I think the design and color of the icon should look good on the light and dark theme...

I could make some adjustments to make it work on light/dark themes. 
Either way I like both versions (the eye one and the updated one).

**Comment by xupefei** [comment]
> I could make some adjustments to make it work on light/dark themes.
Could you do it and post it here? Note that it should be a single icon that looks good on both light and dark themes.

**Comment by Donnnno** [comment]
I've created these adjustments & variations so that you can see how it looks in light/ dark modes.

![Artboard 17](https://user-images.githubusercontent.com/31142286/78456574-cfb9dd00-76a4-11ea-925d-166044f1cb7a.png)

**Comment by QubitsDev** [comment]
This design looks better, use a color palette similar to the other Windows icons so it will be consistent.
![20200404_141837](https://user-images.githubusercontent.com/25881789/78458488-b8b4c400-767f-11ea-95fb-2685e32ac317.png)

**Comment by Donnnno** [comment]
Ah thanks, so something like this then (I used the calendar & camera colors).
![Artboard 31](https://user-images.githubusercontent.com/31142286/78458764-25e24c80-76b4-11ea-82aa-7ba36f9d69bf.png)

**Comment by xupefei** [comment]
This one looks nice to me:
![image](https://user-images.githubusercontent.com/1687847/78461278-43251400-76d0-11ea-8b04-2bb528cf447a.png)

Can you provide the PNG so I can try? You can send it to me by email `xupaddy#gmail` if you don't want to upload it here.

**Comment by Donnnno** [comment]
sure, I also can send you the svg file if you need that :)

**Comment by Donnnno** [comment]
Here's a zip with the png & svg file. If there's anything else you'll need just let me know :)
[QuickLook_icon.zip](https://github.com/QL-Win/QuickLook/files/4432691/QuickLook_icon.zip)

**Comment by xupefei** [comment]
So it looks like this (MSI version, the Store version will be slightly different):
![image](https://user-images.githubusercontent.com/1687847/78503368-d7de4f00-776e-11ea-8dcf-64d0339b47c0.png)


Looks perfect to me :) Thank you, guys!

**Comment by Donnnno** [comment]
Woah nice! should I make the drop shadow more visible? and is the size right?

**Comment by xupefei** [comment]
I think the size is correct - it is auto-generated according to the guideline anyway.
The current shadow is okay. Since Windows 10 shows the EXE icon in the start menu, adding more shadows will make the EXE icon itself unrecognisable.

**Comment by rabelux** [comment]
Thank you guys for the update, really like the new design! :+1: :tada:

**Comment by jonaskuske** [comment]
> Since Windows 10 shows the EXE icon in the start menu

Not if you add a `{exeName}.VisualElementsManifest.xml` :)

(in case you don't yet, I'm using the Store version myself so don't know)

**Comment by simioni** [comment]
This looks incredible! Thank you, everyone!

**Comment by eman613** [comment]
@xupefei hi, I like this new icon, but I found that the tray icon is still in old style, and I am using the zip version, so is there anything I missing? 
![Snipaste_2020-04-18_19-32-06](https://user-images.githubusercontent.com/9261623/79636677-09620c00-81ac-11ea-82db-de456fdb635d.png)

**Comment by xupefei** [comment]
@eman613 The tray icon is not changed. The new icon is used in the start menu.

**Comment by eman613** [comment]
@xupefei OOOK, looking forward to the new tray icon

**Comment by simioni** [comment]
@eman613 Colored system tray icons are being phased out. The standard for system tray icons in Windows 10 is monochrome. Those are displayed in white or in black, depending if you have windows displaying in dark or light mode. The current Quicklook tray icon is already up to standard, and behaves just like Microsoft own icons in this regard, changing from dark to light depending on your theme.

**Comment by diligamer** [comment]
This Issue Now Needs To Be Closed.
