### ISSUE TITLE
Can not quick look images in non-english path

### ISSUE THREAD

**Issue by aoxzhou007** [QL-Win/QuickLook#628]
hi, i installed quicklook(v3.6.6) from microsoft store and my os is win 10 1909.

everything works fine but it **does not open jpg images in non-English character in path**. 
it would show me only upper left corner of the image when i try to quick look.  see below
![1](https://user-images.githubusercontent.com/54088596/78316544-8ee78a00-7525-11ea-9677-3600c76e18cb.PNG)
![2](https://user-images.githubusercontent.com/54088596/78316553-91e27a80-7525-11ea-8fc9-6829eea3a43e.PNG)

and the whole window become blank but only a "0%" when i push my mouse wheel  

![3](https://user-images.githubusercontent.com/54088596/78316560-99a21f00-7525-11ea-963f-aa011fb04648.PNG)

other formats, including mp4 mkv zip, could be quicklooked in any kind of path 

does anyone have same issue?

thank you

**Comment by iamshilov** [comment]
I haz it.

Just started recently noticing that bug and your issue helped me narrow it down to, yep, non-english characters in path. I wouldn't say I can't quick look images, I can though they open at 100% zoom ('top-left corner').

**Comment by xupefei** [comment]
I'm working on fixing this issue :)

**Comment by xupefei** [comment]
Try this and report again :) https://ci.appveyor.com/project/xupefei/quicklook/builds/32586205/artifacts

**Comment by aoxzhou007** [comment]
thanks, xupefei
i tried and it works well

**Comment by iamshilov** [comment]
> Try this and report again :) https://ci.appveyor.com/project/xupefei/quicklook/builds/32586205/artifacts

worked for me as well, thanks

but did something change in anti-aliasing algorithm?
that's how it rendered before…
![before](https://user-images.githubusercontent.com/64053730/80856840-1a078d00-8c56-11ea-8043-a91311835d4f.png)

…and that's how it renders now
![now](https://user-images.githubusercontent.com/64053730/80856852-2e4b8a00-8c56-11ea-8868-9691fa02368d.png)

**Comment by xupefei** [comment]
Yeah, I changed the scaling quality from high to low... I’ll change it back.

**Comment by xupefei** [comment]
How about now? https://ci.appveyor.com/project/xupefei/quicklook/builds/32619446/artifacts

**Comment by iamshilov** [comment]
![burns_excellent](https://user-images.githubusercontent.com/64053730/81046559-5854b480-8ec1-11ea-9e36-2f619a4efb68.jpg)

works flawlessly for me, thanks ))
