### ISSUE TITLE
是否考虑支持在everyting中使用quicklook

### ISSUE THREAD

**Issue by fuyanzhi** [QL-Win/QuickLook#631]
这应该可以提升很大查找文件的效率

**Comment by rsyqvthv** [comment]
currently supported.

if you haven't seen any functional, please use service for Everything instead of Admin.
than restart computer if you still haven't seen any implement.

**Comment by Surfingserenity** [comment]
I can confirm that running Everything as a service solves the issue.
This makes the already awesome Everything app now beyond amazing!!!

**Comment by scoful** [comment]
@fuyanzhi everything重装，选择安装成服务，不要开始管理员模式，就可以预览了

**Comment by klxq520** [comment]
everything自带预览功能啊
