### ISSUE TITLE
Add a setting to open quick look in the Screen where Explorer is in multiple monitor setup

### ISSUE THREAD

**Issue by renecum** [QL-Win/QuickLook#633]
I've noticed that in a multiple monitor setup QuickLook is opened in the screen where the mouse is. I'm a keyboard shortcut fan so I leave the mouse in the last place I needed to use, and usually, I'm on a window in the other screen where the mouse pointer is, and when I press the spacebar in explorer, QuickLook opens in the other screen.

Could you change that?

Thanks.

**Comment by xupefei** [comment]
I did some changes to the code and need your help: could you run `QuickLook.exe` inside the attached ZIP file and answer the following questions?

1. When you press the spacebar while selecting a file *on the desktop*, does the popup appear in the middle of the desktop window?

2. Go to Display Settings and swap the main and secondary monitor (now desktop icons should be in the secondary monitor). Do Question 1 again. Does the popup appear in the middle of the secondary monitor?

3. Open a folder in File Explorer, select a file within and press the spacebar again. Does the popup appear in the monitor the same as the File Explorer window?

4. Move the File Explorer window across monitors and test multiple times. Is there anything wrong?

[test1.zip](https://github.com/QL-Win/QuickLook/files/4571633/test1.zip)

**Comment by renecum** [comment]
Hi.

A little context before.

I have two screens (left and right), left was main before doing the changes
you suggested.
I have Explorer in the right monitor and mouse cursor in the left one.


   1.

    When you press the spacebar while selecting a file *on the desktop*,
   does the popup appear in the middle of the desktop window?

*Yes, in the left one (where the mouse cursor is).*

   1.

   Go to Display Settings and swap the main and secondary monitor (now
   desktop icons should be in the secondary monitor). Do Question 1 again.
   Does the popup appear in the middle of the secondary monitor?

*Yes (the new secondary monitor is left where the mouse cursor is) and the
popup window shows in the center of the screen.*

   1.

   Open a folder in File Explorer, select a file within and press the
   spacebar again. Does the popup appear in the monitor the same as the File
   Explorer window?

*No, I have explorer in the right screen and after pressing space the popup
window shows in the left screen where the cursor is. *

   1.

   Move the File Explorer window across monitors and test multiple times.
   Is there anything wrong?

- Yes there are a few things wrong. The popup keeps following the mouse
cursor.
- The popup no longer shows the content of text files, and it only shows a
small thumbnail instead of the whole file for example with images.
- There is another weird behaviour. I'll try to describe it.
I have explorer with two files in the left monitor and the mouse in the
right one.
I press spacebar and the popup appears in the right monitore.
I press the down key to move to the second monitor the popup window shows
in the right border of the screen and in the center from top to bottom.

I hope this helps.

Regards!


*René Cum*

Cel. 35155174


*"Todo lo puedo en Cristo que me fortalece!" Fil.4:13 *

**Comment by xupefei** [comment]
I managed to setup a multi-monitor environment and fixed this issue. Try it now at: https://ci.appveyor.com/project/xupefei/quicklook/builds/32921270/artifacts
