### ISSUE TITLE
在安装桌面整理软件（腾讯桌面整理/Fences/360桌面整理）之后，无法通过空格预览文件。

### ISSUE THREAD

**Issue by doxepine** [QL-Win/QuickLook#634]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log` (`.msi` or `.zip` version) or `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log` (Windows Store version).

**Comment by scoful** [comment]
@doxepine 老问题了，这些桌面管理工具都不支持的

**Comment by Ice-Astro** [comment]
我也在被这个问题困扰着，只要桌面整理软件开着，就无法在桌面上预览文件。

I'm also troubled by this problem. As long as the "Desktop finishing software" is open, I can't preview file on the desktop.

**Comment by Geeyun-JY3** [comment]
> *Please search within existing issues before the submission. Has this issue already been reported?*

开 issue 之前能不能先搜索一下：#289，#721

**Comment by doxepine** [comment]
> _For all's convenience, please use English to fill this issue._
> 
> _Please search within existing issues before the submission. Has this issue already been reported?_
> 
> **Describe the bug**
> A clear and concise description of what the bug is.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Go to '...'
> 2. Click on '....'
> 3. Scroll down to '....'
> 4. See error
> 
> **Expected behavior**
> A clear and concise description of what you expected to happen.
> 
> **Desktop (please complete the following information):**
> 
> * OS Version: [e.g. Windows 10 1803]
> * QuickLook Version: [e.g. 0.3.3 from Windows Store]
> 
> **Screenshots and Exception Log**
> If applicable, add screenshots and logs to help explain your problem. The log file is located in `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log` (`.msi` or `.zip` version) or `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log` (Windows Store version).

**Comment by yangweijie** [comment]
360文件夹 这种资源管理器增强的软件不支持
