### ISSUE TITLE
How can i uninstall plugins?

### ISSUE THREAD

**Issue by komson** [QL-Win/QuickLook#635]
I installed a plugin (QuickLook.Plugin.OfficeViewer.qlplugin), and it would let QL dead when it runs on some docs. Then i want to uninstall the plugin, what should i do?

**Comment by rabelux** [comment]
This is explained in the [wiki](https://github.com/QL-Win/QuickLook/wiki/Available-Plugins#how-to-remove-a-plugin)

**Comment by komson** [comment]
Thank you very much. I found it.
