### ISSUE TITLE
为什么office 系列无法正常预览呢？

### ISSUE THREAD

**Issue by 1tonsilla** [QL-Win/QuickLook#637]
![why](https://user-images.githubusercontent.com/33661246/80053709-230aa700-8550-11ea-9ec1-9a061c3d266b.png)
别的txt之类的都可以，但是office系列不行
（我的office 版本是2016 专业增强版）

**Comment by diligamer** [comment]
you need a plugin

**Comment by 1tonsilla** [comment]
> you need a plugin

Previous versions, it seems, didn't require a plugin to open. I've taken care of the problem. Thank you！

**Comment by chenjian930528** [comment]
> > 你需要一个插件
> 
> 以前的版本似乎不需要插件即可打开。我已经解决了这个问题。谢谢！

你怎么解决的？告知一下，谢谢了

**Comment by chenjian930528** [comment]
> 你需要一个插件

我下载了插件也不行

**Comment by Senko-Dev** [comment]
huh>

**Comment by xupefei** [comment]
At least one of OfficeViewer v3 and OfficeViewer-Native v1 will work for you.

**Comment by chenjian930528** [comment]
I try V3



737697859@qq.com
 
发件人： Pengfei Xu
发送时间： 2020-07-16 01:40
收件人： QL-Win/QuickLook
抄送： chenjian930528; Comment
主题： Re: [QL-Win/QuickLook] 为什么office 系列无法正常预览呢？ (#637)
At least one of OfficeViewer v3 and OfficeViewer-Native v1 will work for you.

**Comment by 1tonsilla** [comment]
> > > 你需要一个插件
> > 
> > 
> > 以前的版本似乎不需要插件即可打开。我已经解决了这个问题。谢谢！
> 
> 你怎么解决的？告知一下，谢谢了

https://github.com/QL-Win/QuickLook/wiki/Available-Plugins             你试试在这里找看看，我就是装了插件好的

**Comment by chenjian930528** [comment]
可以了，谢谢HXD



737697859@qq.com
 
发件人： 1tonsilla
发送时间： 2020-07-23 20:49
收件人： QL-Win/QuickLook
抄送： chenjian930528; Comment
主题： Re: [QL-Win/QuickLook] 为什么office 系列无法正常预览呢？ (#637)
你需要一个插件
以前的版本似乎不需要插件即可打开。我已经解决了这个问题。谢谢！
你怎么解决的？告知一下，谢谢了
https://github.com/QL-Win/QuickLook/wiki/Available-Plugins 你试试在这里找看看，我就是装了插件好的

**Comment by feijie825** [comment]
https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer/releases
安装 V3 版本插件

**Comment by emako** [comment]
现在可以获取新版本插件了
The new version of the plugin is now available

https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer/releases
