### ISSUE TITLE
bug preview images or psd,ai with a big resolution

### ISSUE THREAD

**Issue by apierre55000** [QL-Win/QuickLook#640]
hello
since last versions i can't pre-visualize correctly the image file (png or jpeg or other extension) and psd, or ai file too
quicklook preview zoom the file to the center but i can't view the entire preview image of the document like before... 
it arrives only when the file has a big resolution (2000px x 2000px) for exemple
could you make anything to change it ? 

thanks !

**Comment by xupefei** [comment]
Try this: https://ci.appveyor.com/project/xupefei/quicklook/builds/32586205/artifacts
Does it solve your problem?

**Comment by apierre55000** [comment]
oh super it works !!! thanks a lot !

**Comment by xupefei** [comment]
Thanks for the confirmation!
