### ISSUE TITLE
Image disappear

### ISSUE THREAD

**Issue by DexGunner** [QL-Win/QuickLook#650]
**Describe the bug**

When trying to zoom in, some images disappear and the size becomes 0%

**Expected behavior**

Images should not disappear when zoomed in.

**Desktop:**
 - OS Version: Windows 10 1903
 - QuickLook Version: v3.6.7 GitHub (.msi)

**Screenshots and Exception Log**
![](https://i.imgur.com/EkGXmtC.png)
![](https://i.imgur.com/P21JcxS.png)

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/4636258/QuickLook.Exception.log)

**Comment by xupefei** [comment]
The latest Nightly build has this issue fixed. Have a try!

**Comment by DexGunner** [comment]
> The latest Nightly build has this issue fixed. Have a try!

How to download that build?

**Comment by xupefei** [comment]
It's here: https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts
