### ISSUE TITLE
Request: Always on top feature

### ISSUE THREAD

**Issue by frascow** [QL-Win/QuickLook#653]
Always on top feature will be a great addon. Having the chance to use **quick look** as a fast reference image browser while you still working in another program will be very usefull to any sort of artists.

**Comment by xupefei** [comment]
It's already there: the first icon in the title bar.

**Comment by frascow** [comment]
So sorry
Thanks a lot for the information
Gonzalo Díaz-Palacios.

+358406528217
Helsinki

**Comment by rabelux** [comment]
@frascow if your issue has been solved, would you mind closing it?
