### ISSUE TITLE
Can't copy when preview files

### ISSUE THREAD

**Issue by zhaoliang0302** [QL-Win/QuickLook#655]
Can't copy when preview files after upgraded to v3.6.8, this function is enabled in v3.6.7

**Comment by xupefei** [comment]
Now you have to right-click on selected texts and choose Copy.

**Comment by vivek-nodes** [comment]
Why?

**Comment by OpenWaygate** [comment]
> Now you have to right-click on selected texts and choose Copy.

The shortcut hints are misleading when right-click on selected texts, <kbd>ctrl</kbd>+<kbd>c</kbd> will copy the file in previewing, <kbd>ctrl</kbd>+<kbd>a</kbd> will select all files in current folder. I think this is a bug.

![image](https://user-images.githubusercontent.com/27287694/83038512-9f246d00-a06f-11ea-964e-18de03691265.png)

**Comment by ZUIcat** [comment]
> Now you have to right-click on selected texts and choose Copy.

Right-click to copy is too much trouble. In previous versions, I can quickly preview and copy text through QuickLook. The operation is too much trouble now.

**Comment by xupefei** [comment]
Yeah, 3.6.9 reverted the change so you can now CTRL+C again.
