### ISSUE TITLE
QuickLook.WoW64HookHelper.exe false positive ?

### ISSUE THREAD

**Issue by SRThibaultP** [QL-Win/QuickLook#656]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
Windows Defender detecting QuickLook.WoW64HookHelper.exe as a Wacatac.D!ml malware.

**To Reproduce**
Windows Defender automatically detected the software as a malware and I wasn't manage to reproduce with the zip version.

**Expected behavior**
This is probably a false positive I think.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - QuickLook Version: 3.6.7 from Windows Store

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/42326001/82496205-aa661e80-9aec-11ea-8385-b8df45d3ff99.png)

**Comment by xupefei** [comment]
Yes, it is a false positive.
This issue has been reported many times nevertheless nothing I can do to fix it.
