### ISSUE TITLE
installing a new version altered my %DESKTOP%

### ISSUE THREAD

**Issue by copenhaus** [QL-Win/QuickLook#660]
**Describe the bug**
After installing a new version (3.6.8 and 3.6.9), my modified c:\users\name\Desktop was changed from C:\users\name\<my own path> to c:\users\name\Desktop

**To Reproduce**
1. Download the latest install code (.msi)
2. Install and click through the wizard
3. Desktop/Background changed

**Expected behavior**
My path to DESKTOP should remained the same.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1909 Build 18363.836]
 - QuickLook Version: [3.6.8 and 3.6.9 MSI]

**Comment by xupefei** [comment]
I don't think Windows has a `%DESKTOP%` environment variable by default. Is it created by yourself?
Can you try reinstall 3.6.8 and see if the variable is modified again?

**Comment by copenhaus** [comment]
sorry, you are right, I meant c:\users\name\Desktop.  I've modified the original post.

I've tried both 3.6.7 and 3.6.9, both behaved the same.

All I have to do is:
- create the alternate DESKTOP path
- installed QuickLook MSI
- reboot
- uninstalled QuickLook
- reboot (sometimes it happened without reboot)


This started with 3.6.8.

**Comment by xupefei** [comment]
How you changed the desktop path? By editing the registry or [by following these steps](https://www.dummies.com/computers/operating-systems/windows-10/how-to-change-the-location-of-user-folders-in-windows-10/)?

**Comment by copenhaus** [comment]
No, not quite...by doing the following commands:

C:\>rd /s/q c:\Users\%username%\Desktop
C:\>mklink /j c:\Users\%username%\Desktop  C:\Users\%username%\<newpath>

**Comment by xupefei** [comment]
Your method is not recommended by Microsoft. I believe any other MSI-based installer will also reset your modification.

If there is a reason to not using one of two methods I mentioned before, you can install QL from ZIP or Windows Store.
