### ISSUE TITLE
GitHub release 3.6.9 msi triggers Windows SmartScreen

### ISSUE THREAD

**Issue by adam7** [QL-Win/QuickLook#663]
**Describe the bug**
Release 3.6.9 msi triggers Windows SmartScreen when trying to install

**To Reproduce**
1. Go to https://github.com/QL-Win/QuickLook/releases/tag/3.6.9
2. Download QuickLook-3.6.9.msi
3. Run downloaded QuickLook-3.6.9.msi
4. See SmartScreen Warning

**Expected behavior**
Installation should not trigger a SmartScreen Warning. 

**Desktop (please complete the following information):**
 - OS Version: Windows 10 19041.264
 - QuickLook Version: 3.6.9 downloaded from GitHub releases page

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/104364/83330962-ff472900-a292-11ea-937c-65a92913276f.png)

https://github.com/microsoft/winget-pkgs/pull/1241#issuecomment-636261587

**Comment by xupefei** [comment]
Strange. I have already submitted the same report for the 3.6.8 version, why this happening again?

I will do it once more, and this is the last time I do it. If this happens for the next release you will have to submit the file by yourself at https://www.microsoft.com/en-us/wdsi/filesubmission.

**Comment by xupefei** [comment]
I need to know the reported malware name in order to submit a claim. What is it? Previously it was `Trojan:Win32/Fuerboos.A!cl` as reported in https://github.com/QL-Win/QuickLook/issues/561.

**Comment by MilkFather** [comment]
Does not look like this program is being blocked by smartscreen anymore. If the response from Microsoft's security team is available please provide it to @adam7 so he can continue with his pr.

**Comment by adam7** [comment]
@xupefei I don't think this is a threat detection, it's because the installer isn't signed.

**Comment by xupefei** [comment]
> @xupefei I don't think this is a threat detection, it's because the installer isn't signed.

Unfortunately there is nothing I can do if this is the case. I don't have a code signing certificate to sign the installer. Is it possible for winget to use the ZIP package?

**Comment by MilkFather** [comment]
> > @xupefei I don't think this is a threat detection, it's because the installer isn't signed.
> 
> 
> 
> Unfortunately there is nothing I can do if this is the case. I don't have a code signing certificate to sign the installer. Is it possible for winget to use the ZIP package?

No, it is currently impossible. This feature is in discussion and is planned for next release though.

**Comment by adam7** [comment]
I don't really see how this can be resolved, SmartScreen requires a cert which costs $ and there's no way to justify that. I'll leave my PR open on the WinGet repo but this can be closed, in my opion it's not an issue with QuickLook it's a fundamental problem with WinGet.

**Comment by superusercode** [comment]
@xupefei Is it possible that you can make the MSIX/APPX releases you submit to the Microsoft Store available in releases? MusicBrainz Picard does this and it's the easiest way around SmartScreen

**Comment by KiruyaMomochi** [comment]
> I need to know the reported malware name in order to submit a claim. What is it? Previously it was `Trojan:Win32/Fuerboos.A!cl` as reported in #561.

Looks like Microsoft is detecting virus using [Artificial Intelligence](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3aWin32%2fFuerboos.C!cl), but the accuracy maybe not so good. Now he is reporting my C++ homework as a virus over and over again, so annoying...

**Comment by MilkFather** [comment]
> @xupefei Is it possible that you can make the MSIX/APPX releases you submit to the Microsoft Store available in Github releases? MusicBrainz Picard does this and it's the easiest way around SmartScreen

Microsoft Store release has limited functionality. The msi package offers full functionality so it may not be a good idea to use MSIX/APPX release to bypass SmartScreen. It does not **solve** the problem

**Comment by adam7** [comment]
In the next release of WinGet windows store apps will be enabled. For now Microsoft have validated that the error message was erroneous and my pull request was merged so I'm going to close this issue.
