### ISSUE TITLE
.eml and .msg files don't open

### ISSUE THREAD

**Issue by glocalglocal** [QL-Win/QuickLook#664]
.eml and .msg files don't open. The QuickLook window opens but it is blank. The 'Open with' button correctly identifies the default applications for these (Thunderbird and Outlook here on Windows 10 Pro 64 bit). 

Otherwise, QuickLook v3.6.9 and v3.6.8 work fine. In case it is relevant, the only other problem is that .gif files don't open either.

**Comment by xupefei** [comment]
Only when viewing EML & MSG or when viewing all types of files?

**Comment by glocalglocal** [comment]
I tested as many file types as I could. The only ones that didn't work were EML, MSG and GIF (GIF now fixed). I tried many files just in case. 

BTW, impressed that MHT is support. Only IE opens them these days here.

**Comment by ljgp** [comment]
I just installed QuickLook and for me also eml and msg files do not show, only a blank page appears. Is there any logging or tip on how to diagnose this issue ?

**Comment by rjmoggach** [comment]
I have `eml` files opening as ASCII only currently - needs some better mime-type handling to understand html vs text content vs attachments vs inline content

**Comment by emako** [comment]
It should be an outdated issue
