### ISSUE TITLE
HEIC images display with wrong colours

### ISSUE THREAD

**Issue by skmskmskmskm** [QL-Win/QuickLook#669]
**Describe the bug**
When previewing HEIC images produced by iOS, the images have the wrong, almost inverted colours.

**To Reproduce**
Preview the attached HEIC image file in Quicklook

[IMG_2322.zip](https://github.com/QL-Win/QuickLook/files/4728834/IMG_2322.zip)

**Expected behavior**
Expect to show with correct colours per the jpeg screenshot below.

**Desktop (please complete the following information):**
 - Windows 10 1909
 - QuickLook Version: 3.6.9 (UWP)

**Screenshots and Exception Log**

HEIC screenshot
<img width="1122" alt="heic" src="https://user-images.githubusercontent.com/52801888/83737675-3d559b80-a64b-11ea-91d3-0881b1cc7f7a.png">

JPEG screenshot
<img width="1122" alt="jpg" src="https://user-images.githubusercontent.com/52801888/83737703-47779a00-a64b-11ea-89a5-117cfe8f1e82.png">

**Comment by cameronetchart** [comment]
Having this issue as well; have the [HEIF/HEVC extension from the microsoft store](https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7?activetab=pivot:overviewtab) installed. Images look correct in the default Photos app, but not Quicklook.

**Comment by ybyOxidant** [comment]
I have the same problem as above~ Apps install at Windows 10 2004, QuickLook Version: 3.6.9 (UWP), with HEIF extension.

**Comment by xupefei** [comment]
Fixed!

**Comment by ybyOxidant** [comment]
> Fixed!
> Try it here: https://ci.appveyor.com/project/xupefei/quicklook/builds/33913242/artifacts

thank you~ looking forward to the next version

**Comment by cameronetchart** [comment]
> Fixed!
> Try it here: https://ci.appveyor.com/project/xupefei/quicklook/builds/33913242/artifacts

Thanks @xupefei. That version works for me; heic files from an iPhone look normal. Only downside is that performance isn't great; it takes 3-4 seconds for the preview to load on a <2mb heic photo, versus the regular ~0.5 seconds for a 4mb jpg. I'm getting 20-35% CPU usage (on a 4c4t Intel i5 6500) versus 10% for the jpg. Same lag even if I reopen the same file over and over in quicklook.

**Comment by xupefei** [comment]
> Thanks @xupefei. That version works for me; heic files from an iPhone look normal. Only downside is that performance isn't great; it takes 3-4 seconds for the preview to load on a <2mb heic photo, versus the regular ~0.5 seconds for a 4mb jpg. I'm getting 20-35% CPU usage (on a 4c4t Intel i5 6500) versus 10% for the jpg. Same lag even if I reopen the same file over and over in quicklook. Though I don't think this is a new lag from the update; the old version has the same.

The loading speed is delayed for three reasons:
1. Decoding HEIC images **is** much slower compared to JPG.
2. The thumbnail component used by QL, exiv2, does not extract thumbnails from HEIC images. Therefore, you saw the loading icon until the full image is loaded. In contrast, when previewing a JPG, a thumbnail is loaded at first and the full image is being loaded in the background.
3. The image decoder used by QL, Magick.NET, actually has a multi-threaded version (i.e., `Magick.NET-Q8-OpenMP-x64`), but only for 64bits OSs. QL still need to run on 32bit OSs so it still uses the single-threaded version.

**Comment by JaredDC** [comment]
> > Thanks @xupefei. That version works for me; heic files from an iPhone look normal. Only downside is that performance isn't great; it takes 3-4 seconds for the preview to load on a <2mb heic photo, versus the regular ~0.5 seconds for a 4mb jpg. I'm getting 20-35% CPU usage (on a 4c4t Intel i5 6500) versus 10% for the jpg. Same lag even if I reopen the same file over and over in quicklook. Though I don't think this is a new lag from the update; the old version has the same.
> 
> The loading speed is delayed for three reasons:
> 
> 1. Decoding HEIC images **is** much slower compared to JPG.
> 2. The thumbnail component used by QL, exiv2, does not extract thumbnails from HEIC images. Therefore, you saw the loading icon until the full image is loaded. In contrast, when previewing a JPG, a thumbnail is loaded at first and the full image is being loaded in the background.
> 3. The image decoder used by QL, Magick.NET, actually has a multi-threaded version (i.e., `Magick.NET-Q8-OpenMP-x64`), but only for 64bits OSs. QL still need to run on 32bit OSs so it still uses the single-threaded version.

It's time to abandon the 32bit OSs. Or add the 64bit branch.

**Comment by xupefei** [comment]
> Or add the 64bit branch

But who is going to maintain it?
