### ISSUE TITLE
反复打开十次excel后再打开excel文件报错

### ISSUE THREAD

**Issue by cjsvaxlp** [QL-Win/QuickLook#674]
反复打开十次excel后再打开excel文件报错
consider reporting this incident to quicklook author
例如
![Snipaste_2020-06-10_14-16-53](https://user-images.githubusercontent.com/33271782/84233405-dccfce00-ab24-11ea-8f75-75b0cf69041d.png)

**Comment by 1llilhz** [comment]
我也有这个问题，测试了一下
独立版的（不需要安装Office的）对旧的excel文件能够预览，新保存的excel文件会报错，但word不会有报错；
Native版插件对所有office格式都会报错
