### ISSUE TITLE
GIF Playback speed Issue

### ISSUE THREAD

**Issue by ghost** [QL-Win/QuickLook#675]
Having issues with .gif playback speed.
This is only present with .gif

Here is a video
https://drive.google.com/uc?id=1tK7GX2LT4r3xDhOCxlFBgGg3XxX-QSoT

I've tested with multiple gifs and this happens with all of them.

**Comment by xupefei** [comment]
QuickLook currently ignores the timeout setting of each frame, rather switching frames every 0.01s: https://github.com/QL-Win/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.ImageViewer/AnimatedImage/Providers/GifProvider.cs#L50
The reason why I use the current dumb GIF render is RAM usage. WpfAnimatedGif is a better choice in every dimension except RAM usage.

**Comment by emako** [comment]
Duplicate issue with https://github.com/QL-Win/QuickLook/issues/993 #767

And done in nightly build

https://github.com/QL-Win/QuickLook/releases
