### ISSUE TITLE
The search button that opens the search textbox is not active

### ISSUE THREAD

**Issue by gamboalx** [QL-Win/QuickLook#679]
The bug:
The text box where we are supposed to write down the name of the file we want to find, does not show up. I can see the magnifying glass icon but it does not have response when I pass the mouse pointer over it.

**To Reproduce**
1. Open the explorer
2. Click on 'the magnifying glass icon'
3. the  text box does not open, so I can't write the file name
4. this is the error

**Expected behavior**
I expect to have a Text Box to be filled with the name of the file to be searched

**Desktop (please complete the following information):**
 -Windows 10 1909
OS version 18363.900
 
-Archivos UWP Version 0.9.2.0 from Windows Store
![UWP ISSUE](https://user-images.githubusercontent.com/66921038/84675658-900c3e80-aefa-11ea-8546-307b725f97a8.png)

**Comment by xupefei** [comment]
I guess you have submitted your issue in a wrong repo :)
