### ISSUE TITLE
Win 8.1 preview doc/docx file failed

### ISSUE THREAD

**Issue by ridewindgo** [QL-Win/QuickLook#680]
**Describe the bug**
      doc/docx file  cannot be previewed correctly when i using space button，it only emit a window which contains it`s file information，not the expecting content.  All other files such as “.xlsx
” “.ppt” “.jpg/.png” “.zip/.rar” can be previewed correctly.
![无标题](https://user-images.githubusercontent.com/56723418/84849814-c1b31000-b088-11ea-897d-527bc1104b56.png)

**Desktop (please complete the following information):**
 - OS Version: Win8.1 X64
 - QuickLook Version: V3.6.9+OfficeViewer-Native v1
 - Office Version: office2013 X64

**Screenshots and Exception Log**

========2020/6/15 星期一 13:21:11========
System.TypeInitializationException: “QuickLook.App”的类型初始值设定项引发异常。 ---> System.Runtime.InteropServices.COMException: 消息筛选器取消了调用。 (异常来自 HRESULT:0x80010002 (RPC_E_CALL_CANCELED))
   在 System.Management.ThreadDispatch.Start()
   在 System.Management.ManagementScope.Initialize()
   在 System.Management.ManagementObjectSearcher.Initialize()
   在 System.Management.ManagementObjectSearcher.Get()
   在 QuickLook.NativeMethods.WMI.GetGPUNames()
   在 QuickLook.Helpers.SystemHelper.IsGPUInBlacklist()
   在 QuickLook.App..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 QuickLook.TrayIconManager..ctor()
   在 QuickLook.TrayIconManager.GetInstance()
   在 QuickLook.App.RunListener(StartupEventArgs e)
   在 QuickLook.App.Application_Startup(Object sender, StartupEventArgs e)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 QuickLook.App.Main()

========2020/6/15 星期一 21:26:03========
System.TypeInitializationException: “QuickLook.App”的类型初始值设定项引发异常。 ---> System.Runtime.InteropServices.COMException: 消息筛选器取消了调用。 (异常来自 HRESULT:0x80010002 (RPC_E_CALL_CANCELED))
   在 System.Management.ThreadDispatch.Start()
   在 System.Management.ManagementScope.Initialize()
   在 System.Management.ManagementObjectSearcher.Initialize()
   在 System.Management.ManagementObjectSearcher.Get()
   在 QuickLook.NativeMethods.WMI.GetGPUNames()
   在 QuickLook.Helpers.SystemHelper.IsGPUInBlacklist()
   在 QuickLook.App..cctor()
   --- 内部异常堆栈跟踪的结尾 ---
   在 QuickLook.TrayIconManager..ctor()
   在 QuickLook.TrayIconManager.GetInstance()
   在 QuickLook.App.RunListener(StartupEventArgs e)
   在 QuickLook.App.Application_Startup(Object sender, StartupEventArgs e)
   在 System.Windows.Application.OnStartup(StartupEventArgs e)
   在 System.Windows.Application.<.ctor>b__1_0(Object unused)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   在 System.Windows.Application.RunDispatcher(Object ignore)
   在 System.Windows.Application.RunInternal(Window window)
   在 QuickLook.App.Main()

========2020/6/17 星期三 10:06:31========
System.Runtime.InteropServices.COMException (0x80040154): 检索 COM 类工厂中 CLSID 为 {0C7FEF07-DCD9-4120-9647-D1CE32F289CD} 的组件失败，原因是出现以下错误: 80040154 没有注册类 (异常来自 HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))。
   在 System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   在 System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, Boolean nonPublic)
   在 System.Activator.CreateInstance(Type type)
   在 QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   在 QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass7_0.<BeginShow>b__1()

========2020/6/17 星期三 10:07:36========
System.Runtime.InteropServices.COMException (0x80040154): 检索 COM 类工厂中 CLSID 为 {0C7FEF07-DCD9-4120-9647-D1CE32F289CD} 的组件失败，原因是出现以下错误: 80040154 没有注册类 (异常来自 HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))。
   在 System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   在 System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, Boolean nonPublic)
   在 System.Activator.CreateInstance(Type type)
   在 QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   在 QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass7_0.<BeginShow>b__1()

========2020/6/17 星期三 10:08:23========
System.Runtime.InteropServices.COMException (0x80040154): 检索 COM 类工厂中 CLSID 为 {0C7FEF07-DCD9-4120-9647-D1CE32F289CD} 的组件失败，原因是出现以下错误: 80040154 没有注册类 (异常来自 HRESULT:0x80040154 (REGDB_E_CLASSNOTREG))。
   在 System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   在 System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, Boolean nonPublic)
   在 System.Activator.CreateInstance(Type type)
   在 QuickLook.Plugin.OfficeViewer.PreviewHandlerHost.Open(String path)
   在 QuickLook.Plugin.OfficeViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass7_0.<BeginShow>b__1()

**Comment by xupefei** [comment]
Try OfficeViewer v3 instead.

**Comment by ridewindgo** [comment]
> Try OfficeViewer v3 instead.

yes, this solution worked, thank you.
