### ISSUE TITLE
When the excel program is opened, the xls and xlsx files cannot be previewed

### ISSUE THREAD

**Issue by zuimeng086** [QL-Win/QuickLook#688]
当打开excel程序时，无法预览xls、xlsx文件，弹出提示。见下图链接
Google translate： When the excel program is opened, the xls and xlsx files cannot be previewed, and a prompt is displayed. See the link below

https://imgchr.com/i/NbHhNQ

**Comment by chenjian930528** [comment]
我也是

**Comment by rabelux** [comment]
Can't reproduce. I can even preview the same file that is currently opened in excel.
Please provide exception log.

**Comment by zuimeng086** [comment]
> Can't reproduce. I can even preview the same file that is currently opened in excel.
> Please provide exception log.

Reason: The personal macro workbook PERSONAL.XLSB automatically started by Excel

原因：Excel自动启动的个人宏工作簿PERSONAL.XLSB
