### ISSUE TITLE
Support math expressions for Markdown 

### ISSUE THREAD

**Issue by sunyinqi0508** [QL-Win/QuickLook#693]
It would be nice to have TeX math support for Markdown files. Since the original md plugin for quick look uses markdown-it to render markdown into html, maybe consider using [markdown-it-math](https://github.com/runarberg/markdown-it-math) on top of it.

**Comment by sunyinqi0508** [comment]
https://github.com/QL-Win/QuickLook/pull/694

Here is my implementation, unfortunately MathJax 3.0 doesn't seem to work for the HTML plugin. So I used 2.0 instead, which seem to be working just fine. Maybe consider updating the HTML render engine for the plugin.

**Comment by Justaphysicsnerd** [comment]
same as #639

**Comment by MrPancakes39** [comment]
@sunyinqi0508 Does MathJax 3.0 work on normal browsers such as chrome?? If so then it would definitively prove it's the HTML render plugin

Also I didn't know you can just import a node module library to browsers just fine :o

Will try your fix tomorrow :D

**Comment by MrPancakes39** [comment]
Chromium Engine renders MathJax 3.0 fine with [markdown-it-mathjax](https://github.com/classeur/markdown-it-mathjax) plugin. So maybe it's QuickLook's HTML render engine?

**Comment by sunyinqi0508** [comment]
> Chromium Engine renders MathJax 3.0 fine with [markdown-it-mathjax](https://github.com/classeur/markdown-it-mathjax) plugin. So maybe it's QuickLook's HTML render engine?

Yeah, I believe QuickLook uses the UWP's webview which is the old EdgeHtml. The new WebView2 uses Chromium Edge for html but I don't know if the author of QL plans to make the change.

**Comment by rabelux** [comment]
QuickLook switched to WebView2 on 10th Jan this year, see #539
