### ISSUE TITLE
Bug Report: Crash after editing a file

### ISSUE THREAD

**Issue by arcanelegender** [QL-Win/QuickLook#695]
**Description of the Bug:**
On Windows 10, this happened to me multiple times and I think I've finally pinpointed the culprit. The app crashes/closes on its own when you edit a file outside Files UWP. More specifically in my case, whenever I edit and save a PDF in Adobe Illustrator, Files UWP crashes. This seems to not have any side effect other than losing all your tabs that were open.

**To Reproduce:**
1. Drag a PDF from Files UWP and drop it into Illustrator (_might be irrelevant to the bug, and might as well use whatever you want to edit the file_)
2. Make changes and save.
3. Wait for a few seconds, and notice the spike in the power usage of `explorer.exe`.
4. Files UWP crashes.

**Expected Behaviour:**
No crash, of course.

**Laptop:**
 - OS Version: Windows 10 Home Single Language version 1909
 - Files UWP version: 0.11.0.0 from Windows Store

**Comment by rabelux** [comment]
![grafik](https://user-images.githubusercontent.com/16120882/87222251-9e6f3e00-c372-11ea-979f-539e559aeadf.png)

**Comment by xupefei** [comment]
There have been recently multiple bug reports like this. I managed to ask one reporter what directed him here and he replied me this image:

![image](https://user-images.githubusercontent.com/1687847/87233893-f1c1aa80-c3cb-11ea-8b4d-8d89f42ce383.png)

and told that he followed the most he noticeable link in the above page.

I think I should go ask Files UWP to make some changes...
