### ISSUE TITLE
Support Krita files (.kra)

### ISSUE THREAD

**Issue by junkajii** [QL-Win/QuickLook#696]
**Is your feature request related to a problem? Please describe.**
...

**Describe the solution you'd like**
Open .kra files

**Describe alternatives you've considered**
...

**Additional context**
...

**Comment by xupefei** [comment]
I found code C++ codes which generate thumbnails from Krita files: https://github.com/alvinhochun/KritaShellExtension.
We might be able to reuse these code by exposing some APIs. Any volunteer for creating a plugin?

**Comment by zhangkaihua88** [comment]
I created [QuickLook.Plugin.KritaVirwer-MergedImage](https://github.com/zhangkaihua88/QuickLook.Plugin.KritaVirwer-MergedImage), which preview kra file base on mergedimage.png in kra file. But the loading speed is slow, while the kra file is lager.

**Comment by rabelux** [comment]
Thanks @zhangkaihua88, closing this as completed.
