### ISSUE TITLE
HEIC images show inverted (?) colors

### ISSUE THREAD

**Issue by acseven** [QL-Win/QuickLook#699]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
HEIC (iOS) photos are shown with apparently inverted colors. Viewing on Photos shows photo correctly. This has been happening for quite a while (multiple quicklook versions) now, I just hadn't reported it. 

**To Reproduce**
(as stated)

**Expected behavior**
No color issue.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - QuickLook Version: 3.6.9 MSI

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/1176371/87530391-2eb9c580-c688-11ea-999d-7586ba0a5a04.png)

**Comment by rabelux** [comment]
duplicate of #669
should be fixed with latest nightly https://ci.appveyor.com/project/xupefei/quicklook/builds/33913242/artifacts
please search for existing issues next time

**Comment by acseven** [comment]
I did search, but only for open issues. That one is closed, hence not finding it. 
In any case, thanks
