### ISSUE TITLE
Add Markup support for PDFs

### ISSUE THREAD

**Issue by serendipia21** [QL-Win/QuickLook#705]
I'm currently working with pdf files on my iPad.
There I use the markup function to anotate. Then I upload them thru gDrive to my pc.
If I preview the uploaded files with QuickLook, the markup is not displayed. But if I open the file with any PDF reader, I can see and interact with the markup.
Would be nice to also see it in the preview.

Thanks!

**Comment by rabelux** [comment]
Duplicate of #421
