### ISSUE TITLE
WIKI: Link to ApkViewer is false

### ISSUE THREAD

**Issue by TheDarkTron** [QL-Win/QuickLook#706]
Hi there! Just a quick info:
The DL Link to the ApkViewer on the Wiki Plugins page is wrong.
Not working: https://github.com/canheo136/QuickLook.Plugin.ApkViewer/releases/download/v1/QuickLook.Plugin.ApkViewer.qlplugin

Working: https://github.com/canheo136/QuickLook.Plugin.ApkViewer/releases

**Comment by rabelux** [comment]
@Mornwind fixed it so this issue can be closed
