### ISSUE TITLE
Failed to preview media files in Windows 10 Pro N

### ISSUE THREAD

**Issue by dearrrfish** [QL-Win/QuickLook#707]
**Describe the bug**
Failed to preview media files with errors shown in screenshot, in OS of Windows 10 Pro N version with DirectX 12 and Windows Media Player installed.

**To Reproduce**
Space on the file to preview.

**Expected behavior**
Play media file.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro N (2004)
 - QuickLook Version: 3.6.9 from Windows Store

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/467746/88839947-95fb6d80-d190-11ea-99bd-3284adf30953.png)

**Comment by xupefei** [comment]
Windows N does not have the EVR filter used by QuickLook: https://pete.akeo.ie/2016/01/windows-10-n-edition-mtp-and-evr.html
You must install a Media Feature Pack to play media. The link is in the above blog article.

**Comment by dearrrfish** [comment]
@xupefei Thanks. Installed media feature pack and the issue was gone.
