### ISSUE TITLE
Transparency feature

### ISSUE THREAD

**Issue by salmivas** [QL-Win/QuickLook#708]
Good day!

It would be nice to have transparency feature especially for graphical formats. 
I frequently use QuickLook for the sake of comparing Image files and sometimes I need to picture perfect it. So, I think the ability to quickly place one picture above another to make PP is great for designers and front-end developers.

**Comment by xupefei** [comment]
Thanks for your suggestion but your suggestion goes beyond the scope of QuickLook, which is design to be a *fast* previewing tool. I suggest you to first use QuickLook to find images you want to compare, then open another tool to actually compare them.

**Comment by salmivas** [comment]
OK, I see. Thank you for quick response.
