### ISSUE TITLE
Slow heic images load

### ISSUE THREAD

**Issue by ashokleyland** [QL-Win/QuickLook#710]
**Describe the bug**
Loading an heic image (coming from an iPhone iOS 13, uploaded with onedrive) is very slow compared to a jpg image. For comparison, loading is really quick in MS Photos (with the latest  HEIF extension).

**To Reproduce**
quicklook any heic file

**Expected behavior**
Fast preview of the file

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - QuickLook Version: QuickLook-3.6.9-9-ga41a7bd

**Comment by rabelux** [comment]
The dev listed some reasons for this [here](https://github.com/QL-Win/QuickLook/issues/669#issuecomment-653906086).
As he doesn't really have time for this project at the moment better don't expect an overhaul soon

**Comment by xupefei** [comment]
It looks like HEIC/HEIF has been added to Exiv2 in this PR: https://github.com/Exiv2/exiv2/pull/978.
Don't know if it can extract thumbnails.

**Comment by emako** [comment]
Done
