### ISSUE TITLE
pdf rendering fails on single page pdf

### ISSUE THREAD

**Issue by ashokleyland** [QL-Win/QuickLook#711]
**Describe the bug**
Sometimes (very often, enough to open a new issue), pdf rendering is stuck to a blurry state. To solve the problem, you have to change the size of the preview and then the renders is making it good. Strangely, this happens only on _single page_ pdf. Any multi-pages pdf are doing good. Sometimes, if you scroll down to another pdf and go back, render is happening as expected, sometimes not and the file is stuck. You can notice that on a single page pdf, rendering is slower than on multi-pages, which is weird.

**To Reproduce**
1. preview "pdf single.pdf"
2. if bad render, try resize the window to make it happen
3. preview "pdf multi.pdf" > always good

**Expected behavior**
As fast and clean preview on single page pdf than on multi-pages ones.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - QuickLook Version: QuickLook-3.6.9-9-ga41a7bd (AppVeyor)

**Attached files**
See attached pdf files to test : 
[pdf single.pdf](https://github.com/QL-Win/QuickLook/files/5007545/pdf.single.pdf)
[pdf multi.pdf](https://github.com/QL-Win/QuickLook/files/5007546/pdf.multi.pdf)

and the png to see bad rendering : 
![pdf single bad render](https://user-images.githubusercontent.com/33458721/89045764-5b3e3480-d34c-11ea-97c7-decfc0588e4f.png)

**Comment by ashokleyland** [comment]
Almost !
Now rendering is doing ok almost everytime but not always. It's random but sometimes it stays blurry (only on single pages pdf), you move and back and forth to another file and it comes back...

**Comment by xupefei** [comment]
Might be related to the render delay. I'll look into it in the next weekend.

**Comment by emako** [comment]
Done
