### ISSUE TITLE
Suggestions on operation

### ISSUE THREAD

**Issue by zingplus** [QL-Win/QuickLook#714]
1. If I do not press Space again to cancel the loading, the preview image will run in the background due to switching windows and other reasons. The next time I execute the preview, I should first press Space to end the previous operation, and then press again to execute this operation. May the software automatically restore the initial state when the preview image is not in the front? 
2. I suggest that to follow the mouse movement to quickly preview multiple objects when long pressing Space without clicking mouse. Thanks.

**Comment by xupefei** [comment]
1. Do remember to close the preview window, or to avoid forgetting, make preview windows top-most.
2. That's not how Quick Look should behave. I can imagine it cause a lot of confusion.
