### ISSUE TITLE
Please allow the appearance style to be closer to Fluent Design's acrylic blur rather than Aero.

### ISSUE THREAD

**Issue by Shomnipotence** [QL-Win/QuickLook#716]
Without a doubt, I think it makes sense to be closer to acrylic, so that QuickLook will be in harmony with the appearance of other areas of Windows.

Another point is that the current blur effect is easily disturbed by the underlying image, making the text appear on a colorful surface, and the line of sight cannot be effectively focused.

There are several options for using acrylic effect. I am not sure how the current blur is achieved. On this basis, increasing the blur radius will effectively approach the acrylic effect.

Second, consider using XAML Island. In view of Microsoft's current solution, using acrylic through XAML in Win32 programs may slow down the running speed.

Third, wait for WinUI3, when hardware accelerated rendering can be used, the current Win32 general interface uses GDI rendering (transparency is not supported), GDIPlus supports transparency, but the efficiency is lower.

**Comment by xupefei** [comment]
The acrylic effect is available in desktop apps, but a serious render bug (shadows are becoming black) pushes me to disable it. If you are interested in how that bug looks like:
1. Go to https://github.com/QL-Win/QuickLook.Common/blob/master/Helpers/WindowHelper.cs#L128
2. Modify `accent.AccentState = AccentState.AccentEnableBlurbehind;` accroding to https://github.com/sourcechord/FluentWPF/blob/master/FluentWPF/Utility/AcrylicHelper.cs#L70
3. Compile your own version.
