### ISSUE TITLE
Portable version does not run when starting Windows 10

### ISSUE THREAD

**Issue by Dhyfer1** [QL-Win/QuickLook#717]
**Describe the bug**
Latest version of portable installer does not start when starting Windows 10

**Expected behavior**
I want that the portable version of Quicklook to start at Windows 10 startup, I don't know if it's possible. 

I have unlocked the .zip file before extracting its contents and I run the .exe file and QuickLook works without problem until I restart the PC. When the PC restarts, Quicklook does not launch at startup and does not appear in the Startup tab of the Task Manager.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro version 2004 
 - QuickLook Version: 3.6.9 portable installer

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in `%APPDATA%\pooi.moe\QuickLook\QuickLook.Exception.log` (`.msi` or `.zip` version) or `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\QuickLook.Exception.log` (Windows Store version).

**Comment by xupefei** [comment]
Have you tried to ✅ the "Run at startup" option in the tray icon menu?

**Comment by Dhyfer1** [comment]
> Have you tried to ✅ the "Run at startup" option in the tray icon menu?

Hi. 

After a re-installation of Windows 10, I re-downloaded the portable version and checked the "Run at Startup" option of the system tray icon. After restarting the PC, Quicklook now if it runs at startup. It also appears in startup programs of Task Manager. 

So my problem is already solved. Thank you very much for your help and your great program!

Regards.
