### ISSUE TITLE
Doesn't support text file encoded with utf-8

### ISSUE THREAD

**Issue by taooceros** [QL-Win/QuickLook#719]
**Describe the bug**
Text encoded with utf-8 will display weird in preview.

**Expected behavior**
The preview should be the same as what the text is.

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 2004]
 - QuickLook Version: 3.6.9 windows store

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/45326534/89726179-02585580-da4a-11ea-9c50-414ee2512cef.png)
![image](https://user-images.githubusercontent.com/45326534/89726185-1e5bf700-da4a-11ea-9104-f4a56e1085d8.png)

**Comment by xupefei** [comment]
How long is the file?
Can you share with me by email?

**Comment by glocalglocal** [comment]
Possibly related. Plain text file in Notepad:

![notepad](https://user-images.githubusercontent.com/16408198/94365646-1a4f6b80-00c2-11eb-8164-ef9e497427ca.png)

in QuickLook:
![ql](https://user-images.githubusercontent.com/16408198/94365652-22a7a680-00c2-11eb-8052-5d0c06dcdd59.png)

**Comment by taooceros** [comment]
> How long is the file?
> Can you share with me by email?

Sorry for no response for so long. The file is generated by exporting a database data with utf8 encoding. I will send it to your email.

**Comment by Cyberdroid1** [comment]
Is the behaviour fixed now?

**Comment by taooceros** [comment]
No

**Comment by emako** [comment]
It should be an outdated issue
