### ISSUE TITLE
EXR file preview support

### ISSUE THREAD

**Issue by dowding** [QL-Win/QuickLook#723]
Open EXR is an animation standard across the world. The MAC has it built in but Windows doesn't. 
It REALLY helps people move from Mac to PC if this was added as a supported format. It's open source.

**Comment by xupefei** [comment]
It's supported in ImageMagick (the image decoder QuickLook is using) so I can fix this issue easily.
https://github.com/QL-Win/QuickLook/commit/41b42d81e962cde4c6f72fc1b6687bff22b6bd66 now supports EXR.

**Comment by dowding** [comment]
oooh. Where can I download a full windows installer? (not a proper developer here....)

**Comment by xupefei** [comment]
Here: https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts

**Comment by dowding** [comment]
Amazing!

 


Leigh

 

Email: leigh@dowding.com 

Phone: 07808 048719

www.dowding.com  


 

Dowding Design Limited. Company number 11520973
Registered address: 47 Girons Close, Hitchin, Herts, SG4 9PG

 


 


The information transmitted by this email is intended only for the person or entity to which it is addressed. This email may contain proprietary, business-confidential and/or privileged material. If you are not the intended recipient of this message, be aware that any use, review, retransmission, distribution, reproduction or any action taken in reliance upon this message is strictly prohibited. If you received this in error, please contact the sender and delete the material from all computers.
