### ISSUE TITLE
About Markdown preview

### ISSUE THREAD

**Issue by Kpure1000** [QL-Win/QuickLook#728]
**MD File Preview Problem**

Markdown previewing **ALWAYS** makes QuickLook Except 'No response'.

**To Reproduce**
1. Find some path including markdown file likes README.md
2. Make sure that QuickLook is running
3. Highlight (select) on this MD file
4. Press space to preview using QuickLook
5. The preview window can be open normally, and the file also looks well.
6. Click on the window anywhere, and then the preview window might stop working
7. If u try to close or move the window, there will be a system dialog: 'QuickLook no response, close or wait for response'

**Expected behavior**

System dialog: 'QuickLook no response, close or wait for response'

**Desktop:**

 - OS Version: Windows 10 1909
 - QuickLook Version: 3.6.9 from release (.zip)

**Screenshots and Exception Log**

This exception is **NOT** recorded in Exception Log.

**Comment by Kpure1000** [comment]
Thanks for reply. 
There is NO problem in ver 3.6.7 (get from that link) in few hours.
Hope this bug can be fixed in new version soon.

**Comment by xupefei** [comment]
Can you try one more time with this one https://ci.appveyor.com/project/xupefei/quicklook/builds/32921839/artifacts?

Btw, are you in mainland China?

**Comment by Kpure1000** [comment]
emmm '*For all's convenience, please use English to fill this issue.*'
我在多重启几次试试这俩版本

**Comment by xupefei** [comment]
I am asking because `QuickLook-3.6.7-20-g0d8d405.msi` introduces two new javascript files: https://github.com/QL-Win/QuickLook/commit/0d8d405cc23ef577ac0f8438b5fd5bfd638bec51

Your freezing issue may be related to the Great Firewall if it blocks these two domains.

**Comment by Kpure1000** [comment]
I'll try these 3 versions (3.6.7-19, 3.6.7-20 and 3.6.9?) agian in GWF and also out of it.
**Q:**
1. Is the service of MathJax  blocked by GFW?? 
But it was working in other MD Editor like Typora when used MathJax in js, like the commit code did. Maybe the reference link is a little different.
2. Can I remove this js code in 3.6.9 (new) ver and rebuild it?
Although I may not know how to do that ...
So  I should get out of wall when I need preview MD, if it is does blocked by GFW?
3. Is there some difference between the same version from .zip and Windows Store?

Btw, the download from these two Appveyor sources is quite slow...

**Comment by xupefei** [comment]
For your questions:

1. I don't know. But even if it's not blocked, the slow downloading speed (of resources) may hang the window.
2. You can. Delete lines 134 and 135 then compile.
3. No differences in the Markdown previewer. Other differences can be found in https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions.

I'll try to clarify the three versions you mentioned:
* 3.6.7-19: last version that does not import those javascript.
* 3.6.7-20:  first version that does import those javascript.

If -20 works fine and -19 does not, then there are two possible reasons causing this problem:

1. MathJax resources (fonts/scripts/css) are blocked.
2. MathJax resources are not blocked, but it does not work on IE11.

The true reason can be discovered by using / not using proxies. But I'm not sure whether QuickLook will use the system proxy... VPN is a safe option.

**Comment by kkdd** [comment]
Hello,
I have just realized that when using QuickLook inside an authenticated proxy environment, markdown preview requires user authentication every time, i.e., it loses its memory.

**Comment by KamilDev** [comment]
I recently updated MarkdownViewer in PR https://github.com/QL-Win/QuickLook/pull/1490.

It no longer loads any resources from online, it's all local. Furthermore, it should now support caching, which may fix @kkdd issue of "losing its memory".

Please try the [latest pre-release version](https://github.com/QL-Win/QuickLook/releases/tag/latest) and let me know if your issues are fixed.

**Comment by kkdd** [comment]
Thank you for your work.
I'm however not able to confirm it, because I'm not inside an authenticated proxy environment for a recent few years.
