### ISSUE TITLE
Quicklook cannot launch in Windows 10 (both Microsoft Store Version and .msi Version)

### ISSUE THREAD

**Issue by ygu2004** [QL-Win/QuickLook#732]
Work normally, but from a time, the application cannot launch when startup and also manual launch from start menu. There is no icon in task bar, and no response when press space for review.

 - OS Version: Windows 10 1909
 - QuickLook Version: QuickLook-3.6.9.msi

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/5222803/QuickLook.Exception.log)

**Comment by xupefei** [comment]
Looks like the error is caused by this commit: https://github.com/QL-Win/QuickLook/commit/e303c52f9c6ba37370279fa851828412b0fb8717

Do you have any security software, especially HIPS, running on your PC?

**Comment by ygu2004** [comment]
Thank you for your reply.

Actually, my laptop is using AMD Ryzen 7 4800HS，without intel graphic, it is not caused by transparency issue.

But I think your second point is correct, I have security software with HIPS, after I disable the software, quicklook can be launched normally.
