### ISSUE TITLE
HEIC and HEVC Support

### ISSUE THREAD

**Issue by marcosesperon** [QL-Win/QuickLook#735]
Hi! Thanks so much for your work.

Please, consider support to view HEIC photos / HEVC videos, it would be great.

I installed CopyTrans HEIC https://www.copytrans.net/copytransheic/ who offers support to Photo App, but preview still no working.

Also, there are some Microsoft Store codecs:
https://www.microsoft.com/en-us/p/heif-image-extensions/9pmmsr1cgpwg?activetab=pivot:overviewtab
https://www.microsoft.com/en-us/p/hevc-video-extensions-from-device-manufacturer/9n4wgh0z6vhq?activetab=pivot:overviewtab

Thanks for your time!
Regards

**Comment by rabelux** [comment]
Regarding HEIC try this: https://github.com/QL-Win/QuickLook/issues?q=is%3Aissue+heic
HEIC-Support has been added in June/Juli but still hasn't left the nightly. Try the nightly if you need it.

**Comment by marcosesperon** [comment]
It works perfect!!! 
Thanks so much and sorry (my mistake not to check nightly features before) :)

**Comment by xupefei** [comment]
You remind me. I'll update the Store version this weekend.
