### ISSUE TITLE
Cannot zoom in / out .xls and .xlsx file by pressing Ctrl + Wheel up / down

### ISSUE THREAD

**Issue by pytkr** [QL-Win/QuickLook#736]
Hello, I love this software, and find a small bug while using it. 
Please try to select any **.xls** and **.xlsx** file,  press down **space**, in the quick look, press **Ctrl** key, then roll **Wheel up / down**, nothing happen, however, in **.doc** and **.docx** file, the window will zoom in / out.

**Comment by xupefei** [comment]
For the OfficeViewer: if anything does not work, then it doesn't work since I am not able to fix it.

The Office component is provided by Microsoft as a buggy black box. It is MS's duty to fix any issue.
