### ISSUE TITLE
office 文件预览不了

### ISSUE THREAD

**Issue by Reveanime** [QL-Win/QuickLook#737]
两天电脑配置如下：

电脑 A：
- Windows 10 2004 (x64)，版本号：19041.508
- office 2019 专业增强版本 (64位)

电脑 B：
- Windows 10 2004 (x64)，版本号：19041.508
- office 365 for enterpise (32位)

---------------------------

两台电脑都装了 [OfficeViewer-Native](https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native) 插件，Quicklook (3.6.9) 均安装在 C 盘，电脑 A 可以预览 office 文件，电脑 B 预览 office 文件会一直卡住转圈

----------------------------

唯一能想到的就是 office 版本不同，我也不知道是 bug 还是没适配 office 365，有时间希望您能修复一下

**Comment by xupefei** [comment]
Native有时不稳定。你可以换另一个插件。
