### ISSUE TITLE
Opening speed is very slow

### ISSUE THREAD

**Issue by hhchaobin** [QL-Win/QuickLook#739]
When the document is slightly larger, the opening speed is very slow, even though my computer is well configured.

**Comment by rabelux** [comment]
word? pdf? both?

**Comment by hhchaobin** [comment]
As long as the office document is slightly larger, for example, an excel document larger than 20MB.

**Comment by xupefei** [comment]
Office previewing is slow and even can crash QuickLook. I don't know any solution yet.
