### ISSUE TITLE
[feature request] more syntax highlighting

### ISSUE THREAD

**Issue by ligq** [QL-Win/QuickLook#74]
Hope the syntax highlighting could support more program languages, such as python, matlab

**Comment by xupefei** [comment]
It is related to the upstream AvalonEdit: https://github.com/icsharpcode/AvalonEdit
AFAK there is [a python highlighting scheme](https://github.com/icsharpcode/AvalonEdit/pull/114) in the PR but no one is going to merge it.

**Comment by neilsustc** [comment]
WinQuickLook supports syntax highlight after this [PR](https://github.com/shibayan/WinQuickLook/pull/4).
