### ISSUE TITLE
Release 3.6.10 is identified as Heur.AdvML.D virus by Symantec Endpoint Protection

### ISSUE THREAD

**Issue by 0xced** [QL-Win/QuickLook#741]
I had to downgrade to version 3.6.9 to continue to use QuickLook.

**Comment by xupefei** [comment]
I don't feel surprised. Please report this to Symantec as a false positive.

**Comment by 0xced** [comment]
I reported it on [SymSubmission](https://symsubmit.symantec.com) (_Incorrectly Detected by Symantec_ tab) following instructions on [How to submit suspicious files via the online submission form that have been quarantined by Symantec Endpoint Protection](https://knowledge.broadcom.com/external/article/178064).

**Comment by 0xced** [comment]
QuickLook 3.6.10 is no longer quarantined by Symantec Endpoint Protection with the latest virus definitions.
