### ISSUE TITLE
Dark theme for markdown file and tray menu 

### ISSUE THREAD

**Issue by Geeyun-JY3** [QL-Win/QuickLook#742]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
Nope

**Describe the solution you'd like**
Add dark theme for markdown file and notification area context menu (tray menu).

**Describe alternatives you've considered**
Nope

**Additional context**
![image](https://user-images.githubusercontent.com/49396421/93775151-a7269f00-fc54-11ea-9d79-73660e57cfa7.png)

**Comment by Michael18751** [comment]
It works for me?
![Uploading image.png…]()

**Comment by Geeyun-JY3** [comment]
@Michael18751 I say markdown file.

**Comment by emako** [comment]
After 06e796a markdown viewer support dark theme.
