### ISSUE TITLE
can add aac audio preview support?

### ISSUE THREAD

**Issue by Aragamiz** [QL-Win/QuickLook#743]
aac audio usually use in movie and effect.

**Comment by rabelux** [comment]
do you mean aac? that should be supported already

**Comment by Aragamiz** [comment]
> do you mean aac? that should be supported already

yeah , also support flac will more great

**Comment by rabelux** [comment]
Thats also supported...
Here is a list of supported audio-formats:
".3gp", ".aa", ".aac", ".aax", ".act", ".aif", ".aiff", ".amr", ".ape", ".au", ".awb", ".dct", ".dss",
".dvf", ".flac", ".gsm", ".iklax", ".ivs", ".m4a", ".m4b", ".m4p", ".m4r", ".mmf", ".mp3", ".mpc", ".msv",
".ogg", ".oga", ".mogg", ".opus", ".ra", ".rm", ".raw", ".tta", ".vox", ".wav", ".wma", ".wv", ".webm"'

I'm closing this
