### ISSUE TITLE
Not able to find Quicklook.config file

### ISSUE THREAD

**Issue by Cyberdroid1** [QL-Win/QuickLook#744]
**Describe the bug**
I wanted to remove the tray icon of QuickLook app. I went to the said file location (UWP one) but there was no pooi.moe folder. How do I hide the icon now?

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 20H2]
 - QuickLook Version: [3.6.10 from Microsoft Store]

**Comment by xupefei** [comment]
Can you try to run and quit QuickLook before looking for this folder?

**Comment by Cyberdroid1** [comment]
I have done this many times. I have also tried reinstalling. Nothing works, sadly.

**Comment by xupefei** [comment]
Try this:

1. Open a preview on any file.
2. Click the "keep on top" button in the titlebar.
3. Close the preview.
4. Quit QuickLook.
5. Run QuickLook again and open a preview.
6. Is the "on-top" status maintained?

**Comment by xupefei** [comment]
Btw, can you also check if `%APPDATA%\pooi.moe\QuickLook\` exists?

**Comment by Cyberdroid1** [comment]
> Btw, can you also check if `%APPDATA%\pooi.moe\QuickLook\` exists?

Yup, this exists.

![image](https://user-images.githubusercontent.com/51435948/94004463-5fba2300-fdba-11ea-93ee-d36e62f00094.png)

These files are there.

-----------------------------------------


> Try this:
> 
> 1. Open a preview on any file.
> 2. Click the "keep on top" button in the titlebar.
> 3. Close the preview.
> 4. Quit QuickLook.
> 5. Run QuickLook again and open a preview.
> 6. Is the "on-top" status maintained?

This works properly too. Status is maintained.

**Comment by xupefei** [comment]
Can you quit QuickLook and delete all files in `%APPDATA%\pooi.moe` then run QL again?

**Comment by Cyberdroid1** [comment]
Deleted successfully. Now what should I do?

**Comment by Cyberdroid1** [comment]
I hunted down in the previous location and have found the file. But the file is almost empty.

[QuickLook.txt](https://github.com/QL-Win/QuickLook/files/5273384/QuickLook.txt)
(converted .config to.txt by changing extension)

**Comment by xupefei** [comment]
Now quit and re-run QuickLook. You should find the `ShowTrayIcon` key in this config.

**Comment by Cyberdroid1** [comment]
Sorry to say, but I already checked and it is not there. I checked just now also.

**Comment by xupefei** [comment]
I'm confused. Let's make it clear: let
- A: `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\`
- B: `%APPDATA%\pooi.moe\QuickLook\`

Now, follow these steps:
1. Right-click on the tray icon and make sure you are running the Store version ("(UWP)" after the version number).
2. Quit QuickLook.
3. Navigate to both paths A and B. Delete any files you found in both paths.
4. Run QuickLook and repeat Steps 1 and 2.
5. Navigate to both paths A and B. Which of A or B contains some new files?

**Comment by Cyberdroid1** [comment]
Ok, I did all the steps. Posting results for some.

step3) I go to both locations. No files in B (pooi.moe folder does not exist) , some files in A. I delete both.
step5) I looked for files. No files in B (pooi.moe folder does not exist), one file in A (Quicklook.config)

**Comment by rabelux** [comment]
Win 7 user here and I would like to confirm that my text file looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <LastUpdateTicks>637360351174525275</LastUpdateTicks>
  <Topmost>True</Topmost>
</Settings>
```
But if I add `<ShowTrayIcon>True</ShowTrayIcon>` the setting works and the icon is hidden.
@xupefei  So I guess either fix the code or leave it as it is and adapt the explanation in the wiki

**Comment by Cyberdroid1** [comment]
@rabelux Thanks for the help. I need to insert this just before </Settings> tag, right?

**Comment by rabelux** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <LastUpdateTicks>637360351174525275</LastUpdateTicks>
  <Topmost>True</Topmost>
  <ShowTrayIcon>True</ShowTrayIcon>
</Settings>
```

**Comment by xupefei** [comment]
> So I guess either fix the code that there actually is this the expected line with true, or leave it as it is and adapt the explanation in the wiki

That's strange. The `ShowTrayIcon` should appear automatically when QuickLook has been ran and exited once. I'll check what is going wrong here.
 @Cyberdroid1 please let me know whether @rabelux's reply solved your problem.

**Comment by Cyberdroid1** [comment]
Yes, my problem is fixed now. The code part was missing.
