### ISSUE TITLE
QuickLook.WoW64HookHelper.exe is insecure

### ISSUE THREAD

**Issue by HaleShaw** [QL-Win/QuickLook#748]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
For the version of 3.6.10, the `QuickLook.WoW64HookHelper.exe` is insecure by the McAfee. It will be deleted by the McAfee.
It will not for the version of 3.6.9.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909
 - QuickLook Version: 3.6.10 from zip

**Comment by xupefei** [comment]
It's a false positive because the code has changed in 3.6.10: https://github.com/QL-Win/QuickLook/commits/master/QuickLook.Native/QuickLook.WoW64HookHelper.
