### ISSUE TITLE
Contribute Quicklook into Microsoft Powertoys

### ISSUE THREAD

**Issue by daslicht** [QL-Win/QuickLook#750]
Hi, 
it woudl be great if you could integrate Qicklook into Microsoft Powertoys:
https://github.com/microsoft/PowerToys
That we would only need to install / run one package on logon.

related:
https://github.com/microsoft/PowerToys/issues/5715

**Comment by xupefei** [comment]
Not in my plan. See https://github.com/QL-Win/QuickLook/issues/626.

**Comment by daslicht** [comment]
Ok that are less good news, woudl you allow that  they would include it ?

**Comment by xupefei** [comment]
Depend on the terms they proposed. Btw they haven't contacted me.
