### ISSUE TITLE
McAfee Detects Artemis!7510720F196C in 3.6.10 MSI

### ISSUE THREAD

**Issue by sharpjs** [QL-Win/QuickLook#751]
McAfee thinks it detects **Artemis!7510720F196C** in the file [QuickLook-3.6.10.msi](https://github.com/QL-Win/QuickLook/releases/download/3.6.10/QuickLook-3.6.10.msi) available from the [GitHub release page](https://github.com/QL-Win/QuickLook/releases/tag/3.6.10).

[See here on VirusTotal](https://www.virustotal.com/gui/file/b788df588af0e868e89b90d6359bf7a14cee7511e2a42bb687fcd0f96b2bd65e/detection)

Another false positive?

**Comment by xupefei** [comment]
Please report it to McAfee so that they can have some guy to inspect manually.
