### ISSUE TITLE
Markdown supports latex preview

### ISSUE THREAD

**Issue by codezijie** [QL-Win/QuickLook#752]
如题，希望markdown预览能够支持latex

Hopefully markdown preview supports latex

**Comment by Justaphysicsnerd** [comment]
same as #639

**Comment by rabelux** [comment]
Duplicate of #639

**Comment by emako** [comment]
This feature should have been implemented in the nightly build (I have not tested it)

https://github.com/QL-Win/QuickLook/releases

If there are any issues, continue to track them
