### ISSUE TITLE
Eps file failed to be previewed in Win7(64bit)

### ISSUE THREAD

**Issue by Sun-Pengcheng** [QL-Win/QuickLook#753]
**Describe the bug**
In Win7(64bit) opertating system, an eps file failed to be previewed after intalling QuickLook.Plugin.PostScriptViewer.
**To Reproduce**
1. Install the QuickLook.Plugin.PostScriptViewer.qlplugin
2. Restart Quicklook and try to preview an eps file, a promt appears: "conversion to PDF failed"

**Desktop (please complete the following information):**
 - OS Version: Windows 7 64bit
 - QuickLook Version:  3.6.10

**Screenshots and Exception Log**
The eps file has been compressed into a zip file and uploaded below.  
[Plot3_lasso_RFSRC_sur_venn.zip](https://github.com/QL-Win/QuickLook/files/5321871/Plot3_lasso_RFSRC_sur_venn.zip)

**Comment by xupefei** [comment]
What happened when you double-click the `gswin32c.exe` in `QuickLook.Plugins\QuickLook.Plugin.PostScriptViewer\gs9.52\`?

**Comment by xupefei** [comment]
Btw, your provided EPS fails also on macOS:
![image](https://user-images.githubusercontent.com/1687847/94995554-63f6f500-059f-11eb-9b04-9b7f63409c58.png)

**Comment by Sun-Pengcheng** [comment]
> What happened when you double-click the `gswin32c.exe` in `QuickLook.Plugins\QuickLook.Plugin.PostScriptViewer\gs9.52\`?

I have made a screen-shot after double-clicking the `gswin32c.exe`, it seemed to work ok.
I also downloaded another eps file named `花草叶子.eps`, and it could be previewed by Quicklook.
I tried to open the the two eps in photoshop and LibreOffice Draw. Photoshop opened the `花草叶子.eps` successfully, but failed to open the previous one. LibreOffice Draw opened the previous one successfully, but had some trouble while opening `花草叶子.eps`(only showed a blank drawing without contents). 
I don't know why, maybe the EPS files are of different subtypes? 

![Snipaste_2020-10-04_10-12-51](https://user-images.githubusercontent.com/62691819/95005386-5e92bc80-062a-11eb-9df6-b49f8ef816ef.png)
![Snipaste_2020-10-04_09-40-37](https://user-images.githubusercontent.com/62691819/95005390-63f00700-062a-11eb-9126-34c8e27587de.png)
![Snipaste_2020-10-04_10-13-36](https://user-images.githubusercontent.com/62691819/95005391-65b9ca80-062a-11eb-838d-c2809a00fe59.png)
![Snipaste_2020-10-04_09-57-53](https://user-images.githubusercontent.com/62691819/95005394-681c2480-062a-11eb-9499-ca812f188596.png)

**Comment by xupefei** [comment]
I can find [some discussions](https://community.adobe.com/t5/photoshop/why-does-photoshop-not-open-this-eps-file-while-illustrator-does/td-p/10084170?page=1) in Adobe Support regarding EPS files. Definitely EPS are not following a universal standard.

Closing this issue since it's not only QuickLook-related.
