### ISSUE TITLE
HW accelerated rendering? (Or/and take advantage of the raw HW performance)

### ISSUE THREAD

**Issue by Michael18751** [QL-Win/QuickLook#755]
Whenever I view a high-resolution gif or even video sometimes it runs at an extremely low framerate even though I am using an intel core i7 8th gen with around 13% cpu usage and barely any on my nvidia gpu at all . When I set the gpu to my intel gpu it uses much more ram but when I set it to my nvidia gpu the ram usage goes way down but I don't see any of my gpus or the cpu being stressed out. Is there a way you could add GPU acceleration or is it more of a windows or program limitation?

And Vram utilization if that's not already implemented.

The DLL files for the video plugin seem to be using LAV filters and other HW accelerated codecs(?) I use those plugins for potplayer and it plays much more smoothly.

**Comment by Nerdwiththehat** [comment]
Same issue, though I can't tell what's being stressed while running .gifs, given task shows both CPU & GPU load. Even when at small resolutions the framerates of .gifs are very choppy and low.

**Comment by Michael18751** [comment]
Its also laggy when playing video files and the UI is showing. Its much faster when its not visible (Mouse not over it)

**Comment by xupefei** [comment]
QuickLook does use HW acceleration when playing video, but it is disabled for Intel HD graphics card due to a driver bug.

**Comment by Michael18751** [comment]
> QuickLook does use HW acceleration when playing video, but it is disabled for Intel HD graphics card due to a driver bug.

How about nvidia? Also Even still, it should be close to maxing out the GPU then? HW acceleration would use gpu decoding here.
If HW acceleration is disabled then it should be using/doing a lot of 3D operations, which it is not on the nvidia gpu, nor the intel gpu and cpu
![image](https://user-images.githubusercontent.com/53535277/97632187-8d713800-1a08-11eb-98b5-7bc35a867faa.png)

**Comment by xupefei** [comment]
Intel HD and Intel UHD are different things. HW decoding should work with Intel UHD.
I don't have an Intel but I can say confirm it works with my Nvidia:

![Untitled](https://user-images.githubusercontent.com/1687847/97641927-53be2280-1a44-11eb-80c0-79789ebf9492.png)

**Comment by Michael18751** [comment]
Interesting. It does seem to work. It still does not explain the fact why it wont take advantage of the raw performance of the hardware if acceleration is not available.

**Comment by Michael18751** [comment]
Like high resolution gifs just play sooo slowly

**Comment by xupefei** [comment]
GIF is not video. Please open another issue.

**Comment by Michael18751** [comment]
> GIF is not video. Please open another issue.

HW acceleration appears to be working in videos (although experience slowdown when you interact with the UI). gifs are the issue here. Opening new issue
