### ISSUE TITLE
The position of the launch window is always on the lower side in the high resolution.

### ISSUE THREAD

**Issue by Airloss** [QL-Win/QuickLook#757]
**Describe the bug**
In the high resolution screen (4K) with the zoom 150%, the launch window's position is always lower

**To Reproduce**
1. Select a file
2. Press the Spacebar
3. See the view window is on a lower position.

**Expected behavior**
Hope the view window an appear on the center position or remeber the last position I adjust.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 19042.546
 - QuickLook Version: 3.6.10 from Windows Store

**Screenshots and Exception Log**
Screenshot:
![image](https://user-images.githubusercontent.com/39607704/95406343-2aced400-0955-11eb-952f-899469b2160b.png)

**Comment by xupefei** [comment]
Do you use multiple monitors?

**Comment by Airloss** [comment]
> Do you use multiple monitors?

Yes

**Comment by xupefei** [comment]
There's a known issue about window positioning when multiple monitors are used: https://github.com/QL-Win/QuickLook/issues/420 https://github.com/QL-Win/QuickLook/issues/452, I might able to look at it this weekend.

A possible workaround is to switch primary/secondary monitors.

**Comment by Airloss** [comment]
> There's a known issue about window positioning when multiple monitors are used: #420 #452, I might able to look at it this weekend.
> 
> A possible workaround is to switch primary/secondary monitors.

OK, Thank you😃

**Comment by xupefei** [comment]
Could you try https://ci.appveyor.com/project/xupefei/quicklook/builds/35688242/artifacts and confirm the fix?

**Comment by Airloss** [comment]
I try and it's wired that when I view a pdf, the windows top-bar is hidden as the follow picture, when I switch to another pdf the position has changed, but the code file is normal display.
![image](https://user-images.githubusercontent.com/39607704/95707482-9b972880-0c94-11eb-95b8-7e9390632e69.png)
![image](https://user-images.githubusercontent.com/39607704/95707503-ad78cb80-0c94-11eb-9aca-866777564de5.png)
![image](https://user-images.githubusercontent.com/39607704/95707551-cda88a80-0c94-11eb-8cba-425df2b4743e.png)
![image](https://user-images.githubusercontent.com/39607704/95707584-ddc06a00-0c94-11eb-9f4b-1b2c163c3aa6.png)

**Comment by Airloss** [comment]
> Could you try https://ci.appveyor.com/project/xupefei/quicklook/builds/35688242/artifacts and confirm the fix?

I try and it's wired that when I view a pdf, the windows top-bar is hidden as the follow picture, when I switch to another pdf the position has changed, but the code file is normal display.
![image](https://user-images.githubusercontent.com/39607704/95707482-9b972880-0c94-11eb-95b8-7e9390632e69.png)
![image](https://user-images.githubusercontent.com/39607704/95707503-ad78cb80-0c94-11eb-9aca-866777564de5.png)
![image](https://user-images.githubusercontent.com/39607704/95707551-cda88a80-0c94-11eb-8cba-425df2b4743e.png)
![image](https://user-images.githubusercontent.com/39607704/95707584-ddc06a00-0c94-11eb-9f4b-1b2c163c3aa6.png)

**Comment by TheSheepfolder** [comment]
> Could you try https://ci.appveyor.com/project/xupefei/quicklook/builds/35688242/artifacts and confirm the fix?

Yep, the "fixed" build shows the same behaviour as Airloss just replied about on my setup as well.
Primary display 2736x1824, 200% scaling
Secondary display 1600x1200, 100% scaling

On the larger primary display, the QuickLook window cuts off at the top of the screen when it's displaying something large like a PDF or image preview, but it always works flawlessly on the smaller secondary display.
I also tested switching the primary/secondary displays around (and signed out+in again just in case), and even when I have the smaller display set to primary, it works great like before, but on the larger display (secondary) it still cuts off the top of the screen.

**Comment by xupefei** [comment]
How about this one then: https://ci.appveyor.com/project/xupefei/quicklook/builds/35688332/artifacts

**Comment by Airloss** [comment]
> How about this one then: https://ci.appveyor.com/project/xupefei/quicklook/builds/35688332/artifacts

I have tested several types of files and they all display normally in my multiple monitors.
:-)
