### ISSUE TITLE
Issue previewing vertical RAW images 

### ISSUE THREAD

**Issue by AndrewSRiddle** [QL-Win/QuickLook#759]
**Describe the bug**
The quick preview works great for horizontal images, comes up immediately. But when the RAW image is vertical quick preview squishes the image and changes it's rotation for about 5-8 seconds and then previews it normal after that. Might not seem like a huge problem but when you're sorting and upwards of 4-5k RAW images that 5-8 seconds is a lot. 

**Expected behavior**
I expect an immediate clear preview like it already does for horizontal images. 

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 Pro]
 - QuickLook Version: [3.6.10.0]

**Screenshots and Exception Log**
![Quicklook vertical RAW preivew Issues](https://user-images.githubusercontent.com/72845639/95940065-1fd7d180-0da3-11eb-9d50-4b11388cdc30.JPG)

**Comment by xupefei** [comment]
I thought the thumbnail in ARW should be in the right orientation so didn't rotate it.

Could you share me a vertical ARW file? I'll look into this issue this weekend.

**Comment by AndrewSRiddle** [comment]
> I thought the thumbnail in ARW should be in the right orientation so didn't rotate it.
> 
> Could you share me a vertical ARW file? I'll look into this issue this weekend.

Please be more clear. I do not understand what you want.

**Comment by AndrewSRiddle** [comment]
Doesn't look like it'll let me attach RAW files. Here's a Dropbox link. It displays perfectly in Dropbox. 

https://www.dropbox.com/sh/pks5ixgchn02lxc/AABk19X0zm6zDF5TzQOGJ7Hja?dl=0

**Comment by xupefei** [comment]
Can you try this version https://ci.appveyor.com/project/xupefei/quicklook/builds/35806705/artifacts to see if your issue is fixed?

**Comment by AndrewSRiddle** [comment]
I'm confused by what i'm supposed to do with that.

**Comment by AndrewSRiddle** [comment]
IT WORKED! It was that first file. I uninstalled quicklook and downloaded that first file and it worked! Thank you! What was the issue?

**Comment by AndrewSRiddle** [comment]
You have no idea how thankful I am. You're amazing.

**Comment by xupefei** [comment]
You are welcome.

> What was the issue?

No issue now. I see it is resolved for you :)
