### ISSUE TITLE
.CR2 files incredibly dark for a while, .CR3 files not shown at all

### ISSUE THREAD

**Issue by mattnoir** [QL-Win/QuickLook#760]
QuickLook is not working for Canon RAWs as it should, they are either incredibly dark for several seconds (.cr2), or just show info and not the picture (.cr3). Checked with Nikon and those work as intended
I also have installed RAW image extension from windows store for .cr3 support

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - QuickLook Version: 3.6.10 from windows store

.cr2
![image](https://user-images.githubusercontent.com/21099343/96365189-1225a180-113f-11eb-8fb8-697c9cd20f4d.png)

.cr3
![image](https://user-images.githubusercontent.com/21099343/96365120-a2171b80-113e-11eb-9bb7-1496a0e96ab6.png)

**Comment by xupefei** [comment]
The dark image you saw in the first seconds is the thumbnail extracted from the CR2 file. QuickLook uses [Exiv2](https://github.com/QL-Win/exiv2) to extract thumbnails and does not perform postprocessing: the dark thumbnail is from the original CR2, and I'm not able to fix that.

The same applies to CR3. It is not supported by Exiv2: https://github.com/Exiv2/exiv2/issues/236.

**Comment by xupefei** [comment]
You can try out the CR3 previewing here: https://ci.appveyor.com/project/xupefei/quicklook/builds/35813695/artifacts
It will be slow nonetheless.

**Comment by mattnoir** [comment]
Thank you for clarifying this, however the thumbnail is not as dark (I would have problem with photos like that) at all and it was actually working well before (not sure when sadly), so I was just surprised that it now takes seconds to show proper picture. So unfortunately now I have to use xnview more, which is a few more clicks to close than just a spacebar.
Other than that, thank you for this amazing software
