### ISSUE TITLE
"Unblock" instead of "unlock"

### ISSUE THREAD

**Issue by BruceFraser1** [QL-Win/QuickLook#763]
Thanks for this great software.
Just one confusing item, though: with each release you caution "Should you decided to use the .zip portable package, remember to unlock it before extraction." I was confused--how do you lock or unlock ZIP files?
I think you mean "unblock it." At least, that's what it says in the website to which the helpful link sends one.

**Comment by xupefei** [comment]
Corrected. Thank you!
