### ISSUE TITLE
Quicklook is not working in ExplorerMax

### ISSUE THREAD

**Issue by HAOOFE** [QL-Win/QuickLook#764]
I am using a Tab feature explorer called ExplorerMax.
I found QuickLook is not funtioning in the explorer app.. Not sure if there would be a way to fix it from QuickLook. Or I should contact QuickLook?

**Comment by xupefei** [comment]
You should contact ExplorerMax and provide them with this link: https://github.com/QL-Win/QuickLook/wiki/Integration-and-Development#integrating-with-file-managers
