### ISSUE TITLE
Failed to preview a pdf file which is protected by password

### ISSUE THREAD

**Issue by rfhits** [QL-Win/QuickLook#765]
*pdf password required*

**can't preview a pdf which needs a password**

**To Reproduce**
1. create a pdf which needs the password
2. tap on the space key
3. see error

**Expected behavior**
I want this sofeware require the password, then I can preview this pdf file.

**Desktop (please complete the following information):**
 -Windows 10 1909
 - Sorry I dont know its version : (

**Comment by rabelux** [comment]
This has been on the roadmap before but never got implemented, see #155

**Comment by Cyberdroid1** [comment]
The preview window should tell that this file is inaccessible rather than crash.
