### ISSUE TITLE
闪退

### ISSUE THREAD

**Issue by H1bik1** [QL-Win/QuickLook#766]
不知道是不是我系统更新的问题，我在window 10专业版 2004版号的19041.572版本中，启动quiklook可以看到在后台运行了，但是当我空格浏览文件的时候无法显示并且闪退了

**Comment by xutq** [comment]
我也有同样的问题，win10 19042.1415版本。而且重启软件不管用，只有重启系统才可以，但是过了一会之后还会闪退。
