### ISSUE TITLE
Garbled characters appear when previewing utf-8 encoded files

### ISSUE THREAD

**Issue by haha-stomachache** [QL-Win/QuickLook#769]
When previewing the crawled data file, when the amount of data is small, the preview will display the text normally, and the preview will appear garbled if it exceeds 15 lines
Script default encoding :# -*- coding: UTF-8 -*-

OS version : win10 1909
QuickLook Version : 3.6.10

preview:
![(2GVX MX X71JCR39J{8EI6](https://user-images.githubusercontent.com/27619594/98252385-c4e46500-1f71-11eb-8ebf-7a9582d74a56.png)
open file :
![975UD{HCG0W5WV MBYKF98S](https://user-images.githubusercontent.com/27619594/98252796-3ae8cc00-1f72-11eb-8177-2dbd86f7adc0.png)

**Comment by emako** [comment]
Fixed in nightly build

https://github.com/QL-Win/QuickLook/releases
