### ISSUE TITLE
预览后无法删除

### ISSUE THREAD

**Issue by fan-cy** [QL-Win/QuickLook#77]
要删除刚预览过的文件的话，会提示文件已在quicklook中打开，无法删除。
可否关闭预览窗口后立即释放文件。或者可不可以使预览中也可以删除文件？

**Comment by xupefei** [comment]
我并没有发现这种现象。请提供更详细的信息。

**Comment by fan-cy** [comment]
也不是每次都这样，我还没有找到规律。
系统是win10_x64_Build16257, Quicklook版本是0.3.1 MSI安装的
![default](https://user-images.githubusercontent.com/30803671/29608828-e77c7178-8827-11e7-9636-0ecd09015d3b.PNG)

**Comment by chairchan** [comment]
有没有可能是开启预览后没有按空格关闭，点了其他窗口后预览窗口被挡住了？ @fan-cy

**Comment by emc2314** [comment]
应该会在下个版本修复 #92

**Comment by emako** [comment]
Done

**Comment by shelfofclub** [comment]
@emako 看到这个issue在24年12月还有更新，所以就在这里提了，不新开issue了。

quicklook预览一些种类文件后，仍占用文件，无法删除。
测试了几种文件，ttf和ttc字体文件，预览后无法删除。
其他的pdf和py可以正常删除。

另，删除插件的时候也有占用文件，无法删除的问题。使用[PdfViewer-Native](https://github.com/QL-Win/QuickLook.Plugin.PdfViewer-Native) v2后无法删除，重启电脑后可以删除。

**Comment by emako** [comment]
@shelfofclub    字体文件释放问题在preview版本里应该是解决了的，[preview版本URL](https://github.com/QL-Win/QuickLook/releases/tag/latest)。另，你需要关闭QL才能删除插件。

**Comment by shelfofclub** [comment]
> 字体文件释放问题在preview版本里应该是解决了的

7月22日发布的4.1.1版本仍不能释放。

在https://github.com/QL-Win/QuickLook/issues/1662 中看到插件FontViewer被并入主线。这个改动对字体文件释放会不会有影响？

**Comment by emako** [comment]
> > 字体文件释放问题在preview版本里应该是解决了的
> 
> 7月22日发布的4.1.1版本仍不能释放。
> 
> 在[#1662](https://github.com/QL-Win/QuickLook/issues/1662) 中看到插件FontViewer被并入主线。这个改动对字体文件释放会不会有影响？

@shelfofclub 卸载FontViewer插件才能保证使用的是内置的FontViewer

**Comment by shelfofclub** [comment]
@emako 我没有手动安装过FontViewer。当前插件文件夹内有如下文件：
```
    目录: C:\Users\xxx\AppData\Local\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickL
    ook


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----          2025/7/7     16:37                QuickLook.Plugin
d-----         2025/7/10      9:49                QuickLook.Plugin.FontViewer
d-----        2024/12/27     19:12                WebView2_Data
-a----         2025/7/21     23:18            123 QuickLook.config
-a----         2025/7/18     16:16          11242 QuickLook.Exception.log
-a----         2024/9/20     18:45             94 QuickLook.Plugin.ImageViewer.config
-a----          2024/6/2     20:55             53 QuickLook.Plugin.TextViewer.config
-a----         2025/7/21     12:16            134 QuickLook.Plugin.VideoViewer.config
```
FontViewer内是
```
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----         2025/7/11     10:34           4663 font2html.html
```
这个看着像是新的使用webview的版本？

**Comment by emako** [comment]
@shelfofclub 感谢反馈，确实还有一处未释放文件锁，已在preview版本修复
