### ISSUE TITLE
Shows videos off-screen/not centered/resized

### ISSUE THREAD

**Issue by reelism** [QL-Win/QuickLook#770]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
Videos do not appear centered, or resized, often overlapping screen edges

**To Reproduce**
1. Open file - spacebar
2. Larger videos show off screen
3. Drag to centre
3. Next video also off-screen, not remembering placement

**Expected behavior**
Video centred, resized as default

**Desktop (please complete the following information):**
 - OS Version: Windows LTSC
 - QuickLook Version: 3.6.10 portable

**Comment by rabelux** [comment]
If you're using multiple monitors this issue is related to #420, #452 & #757 and should be fixed in the nightly

**Comment by reelism** [comment]
Hi, not multiple monitor, but single monitor coming off laptop.

**Comment by rabelux** [comment]
> Is there a way to set to always center on displayed monitor?

That should actually be the default behaviour.
The nightly also fixed problems with high-dpi-displays and increased zoom, so I suggest you try the nightly and report back.

**Comment by reelism** [comment]
Right, I do have increased zoom, will try nightly.

**Comment by rabelux** [comment]
Closing this as nightly probably solved the issue
