### ISSUE TITLE
Show title of HTML files in preview

### ISSUE THREAD

**Issue by jlnprssnr** [QL-Win/QuickLook#773]
**Is your feature request related to a problem? Please describe.**
When previewing a HTML file, the title tag is not shown, only the body.

**Describe the solution you'd like**
The title could be shown in the menu bar of the preview window, next to the file name.

**Test case**
Create a HTML file test.html with this content:

```
<html>
<head>
<title>
A Simple HTML Document
</title>
</head>
<body>
<p>This is a very simple HTML document</p>
<p>It only has two paragraphs</p>
</body>
</html>
```

Then press space bar to preview it. No title is shown. Open it in a browser, the title is shown in the tab bar.

**Comment by emako** [comment]
There are no plans to support html title as window title
