### ISSUE TITLE
Add video speed control to video pluggin

### ISSUE THREAD

**Issue by chiragasawa** [QL-Win/QuickLook#780]
we can add a video speed controller to UI of video plugin

**Comment by xupefei** [comment]
Please consider using proper video editing software to tweak the speed.

**Comment by chiragasawa** [comment]
how can i implement this for personal requirements.

**Comment by xupefei** [comment]
You'll need to modify sth here: https://github.com/QL-Win/QuickLook/tree/master/QuickLook.Plugin/QuickLook.Plugin.VideoViewer. I do think DirectShow has this feature build-in so you have to surface it in your code.
