### ISSUE TITLE
Can't preview file on the desktop（无法在桌面预览文件）

### ISSUE THREAD

**Issue by Ice-Astro** [QL-Win/QuickLook#781]
在#634被提及过
It was mentioned in #634 

**Describe the bug**
**描述错误**
**As long as the "Desktop finishing software" is open, I can't preview file on the desktop.
只要“桌面整理软件”是打开的，我就不能在桌面上预览文件。**

**To Reproduce**
1. Install and use any "Desktop finishing software"。（安装任意一款桌面整理软件）
such as：【_360桌面助手_】、【_腾讯桌面整理_】、【_Fences_】
2. Try to preview the file with spacebar on the desktop（在桌面尝试使用空格预览文件）
3. The see the error：Cannot be previewed（发现无法预览）

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Enterprise 1809
 - QuickLook Version: V3.6.10

**Comment by LeiGuo0812** [comment]
Met the same bug
遇到了同样的问题

Moreover, QuickLook is unable to preview in desktop under either situation:
此外, QuickLook 在以下任意一种情况下都不能在桌面打开预览
1. Desktop finishing software is running （In my case, cooDesker）
1. 桌面整理软件运行（我的是cooDesker）
2. Lenovo computer manager is running
2. 联想电脑管家运行

QuickLook back to normal when the 2 software was closed up.
将两个软件都关掉后，QuickLook 恢复正常

**Comment by 2215987584** [comment]
> Met the same bug 遇到了同样的问题
> 
> Moreover, QuickLook is unable to preview in desktop under either situation: 此外, QuickLook 在以下任意一种情况下都不能在桌面打开预览
> 
> 1. Desktop finishing software is running （In my case, cooDesker）
>    桌面整理软件运行（我的是cooDesker）
> 2. Lenovo computer manager is running
>    联想电脑管家运行
> 
> QuickLook back to normal when the 2 software was closed up. 将两个软件都关掉后，QuickLook 恢复正常

最新发现 使用fences 在关闭联想电脑管家的加速球后 可以正常使用

**Comment by mxhx** [comment]
Lenovo computer manager tools: DesktopAssistant cause the view function fails.

**Comment by emako** [comment]
不支持第三方软件的兼容性问题
