### ISSUE TITLE
[FR] Add support for Matroska Audio (.mka)

### ISSUE THREAD

**Issue by Eridyne** [QL-Win/QuickLook#782]
**Describe the bug**
QuickLook displays the file details of, and does not play, Matroska container files with the .mka extension

**To Reproduce**
1. Activate QuickLook (space) on any .mka file

**Expected behavior**
QuickLook should play the contents of .mka files, as this is just a modified extension to indicate that a Matroska container holds audio.

**Desktop:**
 - OS Version: Windows 10 9042.662 (20H2)
 - QuickLook Version: 3.6.10 (UWP)

**Screenshots and Exception Log**
N/A

**Comment by rabelux** [comment]
should be solved with #788
