### ISSUE TITLE
Add Transparency Options to PNG previews

### ISSUE THREAD

**Issue by jackgraddon** [QL-Win/QuickLook#783]
**Transparent Effects when Viewing PNG's**
Instead of showing the typical tiled background when showing transparency, it would be a lot cooler if a semi-clear glass-like texture was put there in place (like on a real mac).

Some examples:
![Screen Shot 2020-11-28 at 9 19 34 AM](https://user-images.githubusercontent.com/61634132/100521859-31124d00-315b-11eb-9ce7-ed5a3c162e54.png)
![Screen Shot 2020-11-28 at 9 21 21 AM](https://user-images.githubusercontent.com/61634132/100521862-3374a700-315b-11eb-9d15-544649446da3.png)

On pc:
![image](https://user-images.githubusercontent.com/61634132/100521880-63bc4580-315b-11eb-8402-71dbc33bb0ee.png)

It would also be nice to add some padding of this same effect when viewing images with no transparency (like jpg, gif, and other pngs)

**Comment by xupefei** [comment]
What's the benefit?

**Comment by haythemgataa** [comment]
> What's the benefit?

It'll look way much better
