### ISSUE TITLE
3.6.10版本开了启动时自动运行，但自启不了，以前版本可以

### ISSUE THREAD

**Issue by 9747** [QL-Win/QuickLook#784]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by MC-dusk** [comment]
You didn't even fill the template?
