### ISSUE TITLE
QuickLook.exe - 损坏的映像

### ISSUE THREAD

**Issue by Gaoyifei1011** [QL-Win/QuickLook#785]
当我打开QuickLook或者在文件中运行QuickLook的时候，就会提示这个bug
When I opened the QuickLook or run in the file QuickLook, would prompt the bug
![image](https://user-images.githubusercontent.com/49179966/101231398-f6be2800-36e5-11eb-8bf2-36e46f1fdb90.png)

**Comment by xupefei** [comment]
Your GPU driver is faulty. Try upgrading it.
