### ISSUE TITLE
When can you bring 64 QuickLook

### ISSUE THREAD

**Issue by Gaoyifei1011** [QL-Win/QuickLook#786]
目前QuickLook是基于X86(32位)的，目前有很多Win32在Microsoft Store上架的应用都提供64位和32位的，想问一下QuickLook什么时候也可以提供一下64位的？
The QuickLook is based on X86 (32-bit), there are a lot of Win32 application in Microsoft Store shelves offer 64 - bit and 32-bit, want to ask QuickLook when can also provide a 64 - bit?

**Comment by Cyberdroid1** [comment]
Maintaining 32 bit allows the app to run on ARM based Windows.

Can be a reason.

**Comment by xupefei** [comment]
QuickLook is already a 64-bit application when running on X64 platform.
