### ISSUE TITLE
Add quick search in text based files

### ISSUE THREAD

**Issue by tpychev** [QL-Win/QuickLook#787]
It would be very convenient to do a search just by entering text. Without any search boxes or anything else.

**Comment by rabelux** [comment]
Just to let you know, don't think this will be implemented as it exceeds the scope of QuickLook

**Comment by mooflu** [comment]
It's quite easy to add. 2 lines of code See https://stackoverflow.com/a/26967514
![image](https://user-images.githubusercontent.com/693717/104082575-351a9b80-51ec-11eb-8811-9c3a67abef48.png)

**Comment by xupefei** [comment]
@mooflu Thank you for the link! I'll find a time slot tomorrow to add it to QL.
