### ISSUE TITLE
ppt preview is not working

### ISSUE THREAD

**Issue by Ryandonn** [QL-Win/QuickLook#789]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by xupefei** [comment]
Sorry I don't provide any support to the OfficeViewer plugin:
```
This plugin is kindly provided by XXX as a ready-to-use black box.
I am not able to add any new feature to or fix any bug from the black box.
If a feature is unsupported, then it means that - I am neither able and going to fix it.
Should any doubt arises, contact XXX.
```
