### ISSUE TITLE
Support for "open" and "save as" dialog boxes

### ISSUE THREAD

**Issue by oly444** [QL-Win/QuickLook#790]
Hi! First of all, thanks for the great software! :) It's almost perfect, I would just love to see additional support for windows dialog boxes: Often when I save a file, I'd like to check which file I'm gonna overwrite, but in these dialog boxes, QuickLook seems not to work/ can't give any previews by pressing the space key. So maybe that's a functionality you can implement? Thank you!

**Comment by xupefei** [comment]
Please read https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions

**Comment by oly444** [comment]
Oh awesome, thanks so much! I didn't know about the .msi installer because I found and installed QuickLook on the Microsoft store.

**Comment by eriksneff** [comment]
@xupefei - For the good of those who come after me and do exactly what I did (install the Microsoft Store version of this app without having any way of knowing there's a downside and a better option, and have to go hunting for answers about why spacebar doesn't work in open and save menus, only to find out the dev knew all along and but didn't share that info in a place a typical user could find it) - can you change this line in the microsoft store description from this:

Note: This app does NOT work on Windows 10 S devices.

to something like this:

Note:
 1) This app does NOT work on Windows 10 S devices.
 2) This version does NOT preview selected files in the Open- and Save-File Dialogs, only the [msi installer](https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts) does. Here's more about the [Differences in Distributions.](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions).

Thanks on behalf of everyone who follows...

**Comment by xupefei** [comment]
> This version does NOT preview selected files in the Open- and Save-File Dialogs

I have that in the original description, then MS tells that this sentence is not allowed.
