### ISSUE TITLE
Fixed startup window size

### ISSUE THREAD

**Issue by yanggggjie** [QL-Win/QuickLook#791]
Every time I turn on the preview software, it takes up most of my screen, and I need to manually zoom it out. Can you make it remember the window size I adjusted last time. Or add a set button to fix the size of the window. Every time I start it, it's the size I want. Thank you very much！

Operating environment:
System: windows10 20h2
Software version: 3.6.10 portable
Display resolution: 2880 x 1800
Zoom and layout: 225%

**Comment by xupefei** [comment]
I think you have hit a bug #420, #452, #757.
Could you try the nightly version and report back?

**Comment by grit-chengdu** [comment]
> I think you have hit a HiDPI bug: #420, #452, #757.
> Could you try the nightly version and report back?

我试了一下最新的 neighty version 不行呀， 我的意思是每次打开记不住上一次我调好的窗口大小 每次都会恢复默认窗口大小

**Comment by emako** [comment]
This problem may need to be upgraded to >=.NET Framework 4.7.2 to solve

**Comment by emako** [comment]
No response
