### ISSUE TITLE
不开启桌面整理软件，可以按空格预览，开启桌面整理，按快捷键无反应，不能预览，怎么处理

### ISSUE THREAD

**Issue by su316** [QL-Win/QuickLook#792]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Geeyun-JY3** [comment]
> *Please search within existing issues before the submission. Has this issue already been reported?*

开 issue 之前能不能先搜索一下：#289，#721
