### ISSUE TITLE
Toggling image in preview mode show thumbail aswell

### ISSUE THREAD

**Issue by schroef** [QL-Win/QuickLook#795]
When using space bar in conjunction with arrow keys to cycles through images in certain folder. Each time you switch an image it show both the full size and the hover image. This is very inconvenient for a smooth experience.

**To Reproduce**
1. Go to folder with multiple images
2. Highlight any image
3. Press space and use the arrows to cycle through images
4. On each tab you get both the full sized image and the thumbnail preview.

**Expected behavior**
When space is used the app should know not to show the smaller thumbnail image.

**Desktop (please complete the following information):**
 - Windows 10 20H2
 - QL 3.6.10
 
**Screenshots and Exception Log**
Cant be screen grabbed, on any press for screengrab thumbnail goes away. Im new to windows so dont have a proper screen recorder yet.

**Comment by xupefei** [comment]
I don't understand the problem. QuickLook shows full images only but where is the thumbnail comes from? Also, QuickLook does not use "tab". What is your use case?

**Comment by schroef** [comment]
Sorry for my late replay. I tried screengrabbing it with an application but the thumbnail would go away with keypresses. I forgot to use printscreen which does capture it.

Im not 100% this is causing it. I also use Sage Thumbs to see icons for a lot offile formats. I do believe i already had this experience before installing sage thumbs

![Thumbnail-shows-image-cycling](https://user-images.githubusercontent.com/6923008/107851122-eb6e3380-6ddd-11eb-9de4-d4ea4ddb208a.jpg)

**Comment by schroef** [comment]
Again sorry for the confusion. Ive found the app, it was QtToolBar doing it. Ive know disabled the feature and it no longer shows.
