### ISSUE TITLE
ALT+F4导致后台播放视频的BUG

### ISSUE THREAD

**Issue by yedsn** [QL-Win/QuickLook#796]
操作过程：
1. 点击 视频1，按空格键预览
2. 点击预览界面，按ALT+F4关闭
3. 点击 视频2，视频会在后台播放声音，但是没有界面

**Comment by xupefei** [comment]
Interesting find! I'll check.

**Comment by yedsn** [comment]
> Interesting find! I'll check.

Thanks, I found this bug because I like to use the mouse gesture tool to close the window, and mouse gestures usually use Alt+F4 or ctrl+W shortcuts to achieve the effect of closing the window😀. Thank you again for providing such a great tool!!!

**Comment by yedsn** [comment]
> Interesting find! I'll check.

Thanks, I found this bug because I like to use the mouse gesture tool to close the window, and mouse gestures usually use Alt+F4 or ctrl+W shortcuts to achieve the effect of closing the window😀

**Comment by xupefei** [comment]
I'm not able to reproduce this problem, but can you try this build: https://ci.appveyor.com/project/xupefei/quicklook/builds/37192088/artifacts?

**Comment by yedsn** [comment]
> reproduce

It works! I downloaded your version and it's fine. Maybe it's a problem with my previous version, which I downloaded from the Microsoft Store before.Thank you!
