### ISSUE TITLE
Pressing space key in explorer launches search, not preview pane

### ISSUE THREAD

**Issue by MaxVonMustermann** [QL-Win/QuickLook#798]
Whenever I try to open a preview by pressing the space bar using the QuickLook program, the explorer toggles the search instead of showing a preview. Would be great, if it was possible to alter the hotkey in order to launch the preview pane, so the issue can be prevented. 
Thanks in advance

**Comment by schroef** [comment]
Have you tried look in the OS keys and see if you can change that hotkey?

**Comment by xupefei** [comment]
Please read https://www.tenforums.com/tutorials/89368-change-when-typing-into-list-view-action-windows-10-file-explorer.html.
