### ISSUE TITLE
中国大佬做的软件，没有中文？说不过去吧

### ISSUE THREAD

**Issue by heibaigame** [QL-Win/QuickLook#800]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xupefei** [comment]
有：https://github.com/QL-Win/QuickLook/blob/master/QuickLook/Translations.config#L489
