### ISSUE TITLE
4k monitor support

### ISSUE THREAD

**Issue by kleenkanteen** [QL-Win/QuickLook#801]
I used this on a 1080p monitor, then switched to a 4k display. When I press spacebar it opens the picture in the bottom right instead of the center, like how it did on the 1080p display. It actually goes too far bottom right, a big part is cut outside of the screen. My screen is also at 175% scaling. Since 4k has a 4:1 pixel ratio it would be nice if there was a way to auto detect the resolution and scaling to view files.

**Comment by xupefei** [comment]
Have you tried the latest Nightly? It should have this issue fixed.

**Comment by kleenkanteen** [comment]
Just downloaded the latest build on nightly and yup, works perfectly now. I downloaded quicklook 2 days ago. Is the latest version on appveyor the same as on github and microsoft store?

**Comment by rabelux** [comment]
See https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions.
I hope that answers your question.
