### ISSUE TITLE
MAKE THE WINDOW LARGER for PDF files

### ISSUE THREAD

**Issue by SSeanX** [QL-Win/QuickLook#804]
The default size of the window is way too small while previewing PDF files!!! Plus it is inconvenient to enlarge the window as Quicklook regenerates the resized preview very slowly.
Please help resolve this, thanks!

**Comment by gaolipeng** [comment]
Yes, the preview window of PDF file is too small.

**Comment by SSeanX** [comment]
@xupefei Sorry but I found the window is still small in the latest version. Are there any difficulties to change the size, please? Plus it is inconvenient to enlarge the window as Quicklook regenerates the resized preview very slowly...

**Comment by xupefei** [comment]
It's now 90% of screen height. Can't be any larger I'm afraid.

**Comment by SSeanX** [comment]
@xupefei But it could be wider. Maybe you can try previewing a PDF you own... Thanks.

**Comment by xupefei** [comment]
Then one screen will not be able to show a full page. That contradicts with the purpose of "previewing" files :)

**Comment by SSeanX** [comment]
@xupefei Though you're telling the truth, the Preview is useless if the content is vague and invisible. Plus, as I pointed out earlier, Quicklook takes time to process (not short indeed) while enlarging the page and making it visible.
After all, I totally agree that Quicklook is used to Preview files - and it might be enough for lots of people to preview a portion of the page. So if you think it makes sense, please please please, at least add an option for the users to have a larger preview, or more freely, widen the window size as they wish. I would be grateful!
