### ISSUE TITLE
Installing plugins crashes the app

### ISSUE THREAD

**Issue by rafal06** [QL-Win/QuickLook#808]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

## **Describe the bug**
After installing a plugin and restarting the app, it shows in system tray for a second or two, and crashes.
Uninstalling the plugin solves the problem.

## **To Reproduce**
1. Download plugin from github
2. In file explorer select plugin file and press Spacebar
3. Click `Install`
4. After it completes, restart the app
5. Run QuickLook from start menu

## **Expected behavior**
Working QuickLook with plugin installed.

## **Desktop (please complete the following information):**
 - OS Version: Windows 10 in S mode, version 20H2, build 19042.685
 - QuickLook Version: 3.6.10 from Microsoft Store

## **Screenshots and Exception Log**

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/5792669/QuickLook.Exception.log)
Issue starts in line 535 in a log file.

**Comment by xupefei** [comment]
> Nie można załadować pliku lub zestawu 'file:///C:\Users\rafal\AppData\Roaming\pooi.moe\QuickLook\QuickLook.Plugin\QuickLook.Plugin.OfficeViewer\QuickLook.Plugin.OfficeViewer.dll' lub jednej z jego zależności. Twoja organizacja zablokowała tę aplikację za pomocą funkcji Device Guard. Skontaktuj się z osobą z działu pomocy technicznej, aby uzyskać więcej informacji. (Wyjątek od HRESULT: 0x800711C7)

Are you using a enterprise PC? If yes, please contact your IT department to fix the above issue. If this is your own PC, read this: https://www.tenforums.com/tutorials/68913-enable-disable-device-guard-windows-10-a.html

**Comment by rafal06** [comment]
It's my own PC. I read the instructions you sended me, but It's for Windows 10 Enterprise. I have Windows 10 Home in S mode. I checked, and I didn't found either `Hyper-V` in `Add/remove features` and `Group policy editor`

**Comment by xupefei** [comment]
Sorry, I don't know then. QuickLook does not support Windows 10 S so you have to figure out by yourself why this happens.
