### ISSUE TITLE
According to Windows Security, QuickLook has a Malware/Trojan inside 🙁

### ISSUE THREAD

**Issue by Ronald-G-Andrade** [QL-Win/QuickLook#809]
Hello dear people :) I encountered a problem with Windows Security (Windows Defender), it detects QuickLook as malware/trojan.

I installed the latest nightly build and the main exe file (QuickLook.exe) was deleted by the antivirus.

 - OS Version: Windows 10 20H2
 - QuickLook Version: 3.6.10-18 [Nightly Build]

**Comment by xupefei** [comment]
You can find multiple reports: https://github.com/QL-Win/QuickLook/issues?q=trojan about this issue. The only solution is adding QuickLook to the exclusion list.

**Comment by Ronald-G-Andrade** [comment]
Ok dear @xupefei thanks a lot for your reply 😀 Have a nice day :)
