### ISSUE TITLE
Support for docx files?

### ISSUE THREAD

**Issue by thebluedev** [QL-Win/QuickLook#812]
Is there an update with support for docx and other non-binary files coming?

it would be nifty to have support for them.

**Comment by Moenupa** [comment]
The docx preview is possible with an plugin, link: [https://github.com/QL-Win/QuickLook/wiki/Available-Plugins](https://github.com/QL-Win/QuickLook/wiki/Available-Plugins)

There are two versions of the office plugin.  Please be aware of the difference.

**Comment by thebluedev** [comment]
But is there an update scheduled to add add support?

**Comment by rabelux** [comment]
Plug-ins are the intended way to support various file types. Pls read the Readme and the wiki before creating unnecessary issues.
