### ISSUE TITLE
Provide full Explorer.exe context menu when right clicking on drives! and all its sub tabs

### ISSUE THREAD

**Issue by JohnnyXP64** [QL-Win/QuickLook#816]
![image](https://user-images.githubusercontent.com/5464394/104659800-001bb680-56ce-11eb-9636-6c653f3a9d65.png)
vs
![image](https://user-images.githubusercontent.com/5464394/104659817-0742c480-56ce-11eb-83a7-15dbe04e9fcb.png)

![image](https://user-images.githubusercontent.com/5464394/104659820-0c077880-56ce-11eb-8df6-426c480665fa.png)
vs
![image](https://user-images.githubusercontent.com/5464394/104659830-10cc2c80-56ce-11eb-9be8-e054e94a2c5c.png)

**Comment by rabelux** [comment]
wrong repo! pls stop spamming issues
