### ISSUE TITLE
Folder preview

### ISSUE THREAD

**Issue by kak8gm** [QL-Win/QuickLook#819]
![Folder preview](https://user-images.githubusercontent.com/71850180/104891177-40eb2800-5979-11eb-9849-72e793a93f29.PNG)
It would be really nice to be able to have previews for folders. 
A nice concept for that is already available on [reddit](https://www.reddit.com/r/Windows_Redesign/comments/ksdp49/inspired_a_bit_by_quick_look_on_macos_when_the/). 
I hope some day it will become a Quicklook feature.

**Comment by xupefei** [comment]
Please see https://github.com/QL-Win/QuickLook/issues/575.
@mooflu is working on a plugin.
