### ISSUE TITLE
Markdown 本地图片无法读取

### ISSUE THREAD

**Issue by klzsysy** [QL-Win/QuickLook#82]
只有URL能正常显示

![image](https://user-images.githubusercontent.com/3226923/30105760-2374ba00-932c-11e7-8f0f-4d2186e802d7.png)

![image](https://user-images.githubusercontent.com/3226923/30105860-63ed9d22-932c-11e7-86d6-28d3d59eb6e7.png)

**Comment by xupefei** [comment]
这是路径问题，不知道能不能修……

**Comment by xupefei** [comment]
此问题无法修复，除非扔掉 IE 内置一个 Webkit 引擎……

**Comment by kytrun** [comment]
问题依然存在，目前好像改用 webview 了？

**Comment by emako** [comment]
After 72d3c3187bc811189d7ba7c3c4ca235d01de1009 support to display local images.
#508
