### ISSUE TITLE
Remember the window size per filetype

### ISSUE THREAD

**Issue by profucius** [QL-Win/QuickLook#821]
I use a 4K monitor at resolution 3840x2160, but when opening QuickLook previews the window always defaults to 800x600, which on my screen is a small box. I resize the windows every time they open, but they do not remember their sizes.

I propose a feature enhancement to remember the window size (possibly location too) **per filetype.**

Use case: Previewing a .txt file will be the same window size every time you preview any .txt file. However when you preview an .rtf file, the window size will be remembered separately.

![image](https://user-images.githubusercontent.com/18254607/104965574-f5eb0800-59ac-11eb-958d-ba62555e3e2d.png)

**Comment by rabelux** [comment]
Pls try the latest nightly, the windowsize-bug should be fixed. See HiDPI bugs: #420, #452, #757.
I personally like that the preview-size always resets but I'll leave the answer to your feature request up to @xupefei

**Comment by profucius** [comment]
> Pls try the latest nightly, the windowsize-bug should be fixed. See HiDPI bugs: #420, #452, #757.
I downloaded the newest nightly build just today, using v3.6.10-24-g6b0f9df from Appveyor.

**Comment by rabelux** [comment]
Do you have a single or dual monitor setup?

**Comment by profucius** [comment]
Single 4K

**Comment by emako** [comment]
No plan to support
