### ISSUE TITLE
An error occurs when reading file names containing URL-encoded strings.

### ISSUE THREAD

**Issue by Pengtasia** [QL-Win/QuickLook#825]
*For all's convenience, please use English to fill this issue.*
I'll do my best.

*Please search within existing issues before the submission. Has this issue already been reported?*
Already done... maybe...?

**Describe the bug**
An error occurs when reading file names containing URL-encoded strings.

**To Reproduce**
1. Convert a string in a Non English using URL-Encoding. (Like Korean)
   ex) %EC%A0%9C%EB%AA%A9_%EC%97%86%EC%9D%8C-1.jpg
2. Rename file using That string.
3. Hit space key at File Explorer.
4. An error occurs!

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 (19042.746)
 - QuickLook Version: v3.6.10 (UWP)

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/5847177/QuickLook.Exception.log)

![Screenshot_20210121_144517_001](https://user-images.githubusercontent.com/77770102/105285857-8e28fd00-5bf8-11eb-8ca8-3a4f00edf070.png)

![%EC%A0%9C%EB%AA%A9_%EC%97%86%EC%9D%8C-1](https://user-images.githubusercontent.com/77770102/105285882-9a14bf00-5bf8-11eb-81b4-82cbb089aae0.png)

**Comment by xupefei** [comment]
It seems string->Uri conversion is doing something we don't want it to do.

I have recently made some change there and not sure if the problem still exists. Could you try the Nightly version https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts?

**Comment by Pengtasia** [comment]
Unfortunately same problem...
