### ISSUE TITLE
Webview2 Edge beta, dev, canary support

### ISSUE THREAD

**Issue by SplitGemini** [QL-Win/QuickLook#826]
Now use webview2 must install runtime, but any non-stable [Microsoft Edge (Chromium) Canary channel](https://www.microsoftedgeinsider.com/zh-cn/download) installed works too, please add support.  
[Getting started](https://docs.microsoft.com/en-us/microsoft-edge/webview2/gettingstarted/wpf)

**Comment by xupefei** [comment]
What's the current status? What happens if you have one of those non-stable runtimes installed?

I follow the guide here https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#offline-deployment to check if a Runtime is installed. It didn't mention non-stable runtimes are having different GUIDs so I assume it will work.

**Comment by SplitGemini** [comment]
> What's the current status? What happens if you have one of those non-stable runtimes installed?
> 
> I follow the guide here https://docs.microsoft.com/en-us/microsoft-edge/webview2/concepts/distribution#offline-deployment to check if a Runtime is installed. It didn't mention non-stable runtimes are having different GUIDs so I assume it will work.

There has 2 options to ensure webview2 useable. 
![image](https://user-images.githubusercontent.com/34861918/105474039-c7d13500-5cd8-11eb-9a94-2c11ceac5ed9.png)

The other one is [GetAvailableCoreWebView2BrowserVersionString](https://docs.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/webview2-idl?view=webview2-1.0.664.37#getavailablecorewebview2browserversionstring).

**Comment by SplitGemini** [comment]
> What's the current status? What happens if you have one of those non-stable runtimes installed?
> 

I have edge beta installed and not installed runtime, it works well.

**Comment by SplitGemini** [comment]
IsWebView2Available() add code below:
```C#
    try
    {
        if (!string.IsNullOrEmpty(CoreWebView2Environment.GetAvailableBrowserVersionString()))
             return true;
    }
    catch (Exception) { return false; }
```

**Comment by xupefei** [comment]
Fixed in https://github.com/QL-Win/QuickLook/commit/aeee21a85a26a2b39710821621151a34593d2337. Thanks all!

**Comment by K0media** [comment]
May I re-open this? Just passing by to alert that the current page that is being linked to download the installer for WebView2 for Edge is broken.

Please see the screencast below.

https://user-images.githubusercontent.com/22375465/113592958-34877a80-960c-11eb-87db-ccd75d451aeb.mp4

I can open a new issue if necessary, but I'd like a proper response for this.

Someone also mentioned about using some other framework to preview web files (html/htm/xhtml/etc) with other handles *such as Google Chrome*, but I'm not sure if you're going to work on that.

Thanks for the attention.
