### ISSUE TITLE
[feature request] .MXF support

### ISSUE THREAD

**Issue by CitizenXX** [QL-Win/QuickLook#83]
It would be awesome if in the future this could also support .mxf files.

**Comment by djcurley89** [comment]
I know this is an old request but still very much needed. MPC-BE and VLC can play them fine but being able to preview them with quicklook would help editors like myself a lot.

**Comment by Meekachu** [comment]
+1 for MXF support. Would dramatically help in bringing a quick workflow.

**Comment by emako** [comment]
Already impled.

MXF test files from: https://toolsfairy.com/video-test/sample-mxf-files#
