### ISSUE TITLE
quicklook3.6.6是否和Directory Opus 12有冲突，运行空格quicklook直接闪退

### ISSUE THREAD

**Issue by hanjunjun** [QL-Win/QuickLook#830]
![image](https://user-images.githubusercontent.com/16394348/106222289-2be48380-621a-11eb-9c19-c8b4e8233e39.png)
![image](https://user-images.githubusercontent.com/16394348/106222328-43bc0780-621a-11eb-95e3-4b3a7eb5110d.png)

**Comment by emako** [comment]
我不确定但目前应该是已解决问题，有问题继续回复
