### ISSUE TITLE
support for .wav files?

### ISSUE THREAD

**Issue by andydv462** [QL-Win/QuickLook#832]
attempting to quicklook a .wav file produces the following error:

![image](https://user-images.githubusercontent.com/65724433/106627999-f48a1580-653e-11eb-8c17-2ee2712031ea.png)

**Comment by rabelux** [comment]
WAV-Preview works for me. Feel free to reopen this issue if it still persists and provide a bit more information (Version of OS and QuickLook, Exception log, etc.)

**Comment by andydv462** [comment]
Thank you, the issue still persists. I cannot preview mp3 audio files either.

QuickLook 3.6.10 (UWP)
Windows 10 Pro 20H2 OS build 19042.844

I don't know how to create an exception log beyond the screenshot shared above.

**Comment by rabelux** [comment]
> Thank you, the issue still persists. I cannot preview mp3 audio files either.

That's weird. You don't have to create the log, it's located in:

 `%LOCALAPPDATA%\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Roaming\pooi.moe\QuickLook\`

**Comment by AraHaan** [comment]
Perhaps the files are encoded in a way that QuickLook does not know about, do the files play normally in programs like xmplay from https://www.un4seen.com/xmplay-stuff.php

or even play it with ffmpeg? if you can perhaps QuickLook can hook into things (like bass since it works on windows, linux and mac too)

There is even bass.net so it could be an easy option, if the thing throws ``WPFMediaKitException`` fall back to using ``bass.NET``.

**Comment by andydv462** [comment]
log below...i can look into your suggestions Ara but I am a video editor and have no issues playing audio files in various other software (my default media player is telestream Switch)

System.UnauthorizedAccessException: Access to the registry key 'HKEY_CURRENT_USER\Software\QLV\Audio' is denied.
   at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   at QuickLook.Plugin.VideoViewer.QLVRegistry.<>c.<Register>b__0_1(KeyValuePair`2 k2)
   at QuickLook.Common.ExtensionMethods.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at QuickLook.Plugin.VideoViewer.QLVRegistry.<>c.<Register>b__0_0(KeyValuePair`2 k)
   at QuickLook.Common.ExtensionMethods.EnumerableExtensions.ForEach[T](IEnumerable`1 enumeration, Action`1 action)
   at QuickLook.PluginManager.<>c.<InitLoadedPlugins>b__12_0(IViewer i)

**Comment by AraHaan** [comment]
I see looks like an registry error causes all the other issues to happen.

**Comment by xupefei** [comment]
If you are running a HIPS, please allow QL to access that registry node.

**Comment by andydv462** [comment]
I'm not running a HIPS (unless windows defender qualifies). I'm also not a computer programmer so if there are any tips for repairing the registry error that a big dumb idiot that just wants to quicklook audio files can handle, let me know :)

appreciate the input folks

**Comment by xupefei** [comment]
So there's something blocking QL from accessing `HKEY_CURRENT_USER\Software\QLV\Audio` key in the Registry. It can be due to antivirus software or insufficient user permission (rare).

**Comment by andydv462** [comment]
I was able to resolve by resetting the app in the windows 10 advanced options panel. A little odd that it worked because i tried uninstalling / re-installing the app a few times but I also ran some windows updates recently so who knows. Thanks! CLOSED.

**Comment by rabelux** [comment]
Glad you were able to solve it and thx for providing your solution 👍

**Comment by htw128** [comment]
I'm running into the same issue. Where can I find the log? 
Windows 11 21H2 22000.613
QuickLook is installed with .msi file, v3.7.1

**Comment by rabelux** [comment]
@htw128 https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location

**Comment by htw128** [comment]
> @htw128 https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location

![image](https://user-images.githubusercontent.com/24934673/164624855-6f2c3431-fcaf-44b9-93b4-5b7870503d5b.png)
I assume this directory doesn't contian any log file...

**Comment by AraHaan** [comment]
Wait QuickLook supports plugins?

**Comment by htw128** [comment]
> Wait QuickLook supports plugins?

Ummm... Yes? I suppose? You can find those plug-ins [here](https://github.com/QL-Win/QuickLook/wiki/Available-Plugins).
