### ISSUE TITLE
Failed to preview PNG image in latest nightly version

### ISSUE THREAD

**Issue by zyLiu6707** [QL-Win/QuickLook#833]
I installed the latest nightly version mentioned in [this comment](https://github.com/QL-Win/QuickLook/issues/827#issuecomment-770090088) in issue #827. These days I encountered new bugs in this version of QuickLook. In Microsoft Store version of QuickLook, there is no such bug. 

**Bug Description**
QuickLook cannot preview `.png` images and will pop-up an error message.
But after renaming `.png` image to `.jpg` image, this bug disappear. A

**To Reproduce**
**Note: Sometimes this bug will not happen on some other `.png` files. But try it for several different `.png` image, the chance of encountering this bug is relative high**
1. Prepare a `.png` image (for example, `test pic.png` in this example, attached below)
2. Then preview it by hitting `spacebar`
3. You will see the QuickLook failed and giving you an error message saying that *Failed to preview XXX.png Consider reporting this incident to [...]*, as the following screenshot shows

![image](https://user-images.githubusercontent.com/31042884/106641429-345bf780-6555-11eb-90ce-f1fe5769fff4.png)

**Desktop**
 - OS Version: Windows 10 1909 - 18363.1316
 - Hardware:
   + Laptop: ASUS ZenBook Pro Duo
   + Monitor 1: Main monitor, 3840 * 1100, scaled at 250%
   + Monitor 2: Secondary monitor, 3840 * 1100, scaled at 175%
   + Monitor 3: Plug-in via HDMI cable, 1920 * 1080, not scaled
 - QuickLook Version: [QuickLook-3.6.10-27-g826cda0](https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts)

**Attachment**

![test pic](https://user-images.githubusercontent.com/31042884/106641762-93ba0780-6555-11eb-83b7-cd7a24102cfd.png)

> Acknowledgment: 
> This `.png` image is used as the testing file in this issue, which is an artwork by Pixiv artist KNYT
> This artwork link: [夕](https://www.pixiv.net/artworks/64325630)

**Comment by xupefei** [comment]
Log please.

**Comment by zyLiu6707** [comment]
> Log please.

I didn't find the location of log file after vewing README or wiki. Where the log file located?

**Comment by zyLiu6707** [comment]
Update:
The file uploaded to GitHub Issue can be successfully previewed.. I uploaded my test file to the following link:
[One Drive Link](https://1drv.ms/u/s!AnrRvBB_I5LZj2tLMn2JQOc2OtPk?e=rJPUtk)

**Comment by xupefei** [comment]
It's in one of these two places:
- MSI version: %APPDATA%\pooi.moe\QuickLook\.
- Portable version: %APPDATA%\pooi.moe\QuickLook\ (up to v3.6.9) or UserData sub-folder in the QuickLook application folder.

**Comment by zyLiu6707** [comment]
Log:
```
========2021/2/2 13:46:06========
System.Reflection.TargetInvocationException: 调用的目标发生了异常。 ---> System.IO.FileNotFoundException: 未能找到文件“C:\Users\lzy67\Desktop\test%20pic.png”。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   在 System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   在 QuickLook.Plugin.ImageViewer.AnimatedImage.Providers.APngProvider.IsAnimatedPng(String path)
   在 QuickLook.Plugin.ImageViewer.AnimatedImage.Providers.APngProvider..ctor(String path, MetaProvider meta)
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   在 System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   在 System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   在 System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   在 System.Activator.CreateInstance(Type type, Object[] args)
   在 QuickLook.Plugin.ImageViewer.AnimatedImage.AnimatedImage.InitAnimationProvider(Uri path, MetaProvider meta)
   在 QuickLook.Plugin.ImageViewer.AnimatedImage.AnimatedImage.AnimationUriChanged(DependencyObject obj, DependencyPropertyChangedEventArgs ev)
   在 System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e)
   在 System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args)
   在 System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType)
   在 System.Windows.DependencyObject.InvalidateProperty(DependencyProperty dp, Boolean preserveCurrentValue)
   在 System.Windows.Data.BindingExpressionBase.Invalidate(Boolean isASubPropertyChange)
   在 System.Windows.Data.BindingExpression.TransferValue(Object newValue, Boolean isASubPropertyChange)
   在 MS.Internal.Data.PropertyPathWorker.UpdateSourceValueState(Int32 k, ICollectionView collectionView, Object newValue, Boolean isASubPropertyChange)
   在 MS.Internal.Data.ClrBindingWorker.OnSourcePropertyChanged(Object o, String propName)
   在 System.Windows.WeakEventManager.ListenerList`1.DeliverEvent(Object sender, EventArgs e, Type managerType)
   在 System.ComponentModel.PropertyChangedEventManager.OnPropertyChanged(Object sender, PropertyChangedEventArgs args)
   在 QuickLook.Plugin.ImageViewer.Plugin.View(String path, ContextObject context)
   在 QuickLook.ViewerWindow.<>c__DisplayClass6_0.<BeginShow>b__1()
```

**Comment by zyLiu6707** [comment]
I was suspecting that this is due to the white space in the filename. I noticed that the whitespace is encoded as `%20` in logfile.
I removed the whitespace in filename, and this `.png` can be successfully previewed.

**Comment by xupefei** [comment]
Yeah you are right.
Try this fix which will be ready in a few minutes: https://ci.appveyor.com/project/xupefei/quicklook/builds/37575165/artifacts.

**Comment by zyLiu6707** [comment]
The bug is gone! Great thanks to you XD !
