### ISSUE TITLE
Not possible to look into AV-1 encoded files

### ISSUE THREAD

**Issue by Saderius** [QL-Win/QuickLook#837]
**Describe the bug**
Attempt to open WebM AV-1 encoded files fails with error.

**To Reproduce**
1. Go to any folder containing WebM AV-1 encoded files.
2. Try to use Quick Look on the file.
3. See error

**Expected behavior**
Movie clip file opens normally, as any other.

**Desktop (please complete the following information):**
 - OS Version: Windows 10, 10.0.19042 Build 19042
 - QuickLook Version: 3.6.10-28-gf597137 (also tried on current stable)

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/41880851/106962713-d0e1ed80-673f-11eb-804c-95ca81c2aa0c.png)

**Comment by emako** [comment]
Old issue I think.
