### ISSUE TITLE
Office and PDF can interfere

### ISSUE THREAD

**Issue by 18189360594** [QL-Win/QuickLook#838]
After installing the Office plugin, there will be an error in PDF preview, and Office can not be previewed normally, only some temporary information

The screenshot below
![屏幕截图 2021-02-05 183939](https://user-images.githubusercontent.com/60801659/107023953-5027fd80-67e2-11eb-8e24-3b524e256f67.png)

**Comment by rabelux** [comment]
There is a template for reporting issues. Use it and provide a little more information or this issue will be closed.
