### ISSUE TITLE
在使用Everything时会自动复制文件路径

### ISSUE THREAD

**Issue by zYeoman** [QL-Win/QuickLook#84]
应该是实现时候方便用来预览？但是这样会覆盖掉之前剪贴板内的内容，有些时候会很麻烦。

看了一下，代码还在TODO :joy:

**Comment by xupefei** [comment]
现在的 Everything 只有这一种获取路径的办法。备份还原剪贴板也不是完美的，玩意你在还没还原的时候粘贴了怎么办。

**Comment by zYeoman** [comment]
可以有关掉它的选项么？因为作为Everything重度用户经常有复制一段内容要粘贴到别的地方的时候直接用Everything查找打开然后粘贴这样的流程，这样直接覆盖了剪贴板会很烦。

可以在按空格预览的一瞬间备份剪贴板然后获取路径然后还原的吧？貌似现在的实现是直要在Everything中移动了就会自动复制。。。

或者提供一个命令行调用的方式，我可以用Autohotkey之类的工具实现Everything甚至其他地方的空格预览

**Comment by xupefei** [comment]
只要不打开预览窗口或不在Everything里按空格键就不会自动复制。

> 提供一个命令行调用的方式
GitHub的Wiki页面里有说明。

cheers,
Paddy

**Comment by Cologler** [comment]
用 spy++ 可以看到 everything 的列表类名是 `SysListView32`。

![picpick-20171027-213402-001](https://user-images.githubusercontent.com/10906962/32106540-95b533a6-bb5e-11e7-9fe0-b1276a58b28d.png)

从 [stackoverflow](https://stackoverflow.com/questions/16877898) 上看起来有人已经试着从 `SysListView32` 获取 item 并成功了。

**Comment by xupefei** [comment]
我不确定这个方法是否可用，因为 Everything 的窗口是经过 UAC 提权的。
有空了我先试一试。

**Comment by xupefei** [comment]
我试了一下，结论是这个方法不行，因为 Path 列不一定会被显示出来。
@zYeoman 上面提到的 AHK 自己写脚本其实只能用剪切板，因为 Everything 的确没提供靠谱的获得当前文件的办法。

下下个版本里我会提供一个开关选项。

**Comment by Cologler** [comment]
我 mail 了 everything 作者，他这样答复我：

There is no specific API do this in Everything. I'll have to look into making one for Everything 1.5..
Everything does emulate a SysListView32 for the result list.
 
If you remotely allocate memory in the Everything process (VirtualAllocEx) you can use LVM_GETITEMTEXT to read the name and path to build the full path and filename of the focused item in Everything.
Use ReadProcessMemory to copy the listview text outside the Everything.exe process.

https://stackoverflow.com/questions/12679518/win32-getting-listview-control-content-from-another-application

**Comment by Cologler** [comment]
看起来 1.5 版本应该方便些了。

**Comment by xupefei** [comment]
VirtualAllocEx 的确是个办法。我试试看。

**Comment by Cologler** [comment]
@xupefei 不幸的是，Path 列一定要显示出来才能通过 VirtualAllocEx 获取……所以还是等 1.5 版本吧……

**Comment by sxul** [comment]
@Cologler  为啥不显示Path列QAQ

**Comment by foundkey** [comment]
可以配合使用剪切板管理软件，暂时规避剪切板呗覆盖的问题的。
我目前使用Ditto（http://ditto-cp.sourceforge.net/）。

**Comment by mmqmzk** [comment]
发现一个曲线方法, Everything的"浏览路径"可以自定义命令和快捷键, 打开Everything -> 工具 -> 选项 -> 常规 -> 上下文菜单 -> 浏览路径, 把命令改成$exec("path to QuickLook\QuickLook.exe" "%1"), 再在快捷键里面设置浏览路径的快捷键为空格以外的键, 就可以了. 这个方法不会覆盖剪贴板. 但是不能用空格, 以及会占用"浏览路径"命令.

**Comment by kaikaiiiiiii** [comment]
不光是按空格会复制路径，按回车也会复制路径。希望至少能把按回车时的复制路径去掉。执行前肯定不必再预览了。
