### ISSUE TITLE
Add the ability to preview marked content in PDFs within the preview pane

### ISSUE THREAD

**Issue by MaxVonMustermann** [QL-Win/QuickLook#844]
It would be really useful, if it was possible to see PDF makers in the preview pane.
I'm using Microsoft Edge Chromium in order to mark/underline texts in the PDF format for studying purposes. When I preview the given PDF with QuickLook, the colored markers don't show up, just the raw PDF text without any marks I made. 
Would it be possible to implement the support for marked lines to show up in the preview pane?

Hope my idea became clear. Thanks in advance.

**Comment by rabelux** [comment]
This has been fixed with 9c384be. Use the latest nightly as there hasn't been an official release yet.
