### ISSUE TITLE
Please support ffdshow to decode video files

### ISSUE THREAD

**Issue by dXrayb** [QL-Win/QuickLook#852]
Video preview now using CPU to decode, but sometimes it's not friendly to HD video, please add ffdshow support, GPU accelerating will lower CPU usage and improve video quality.

**Comment by xupefei** [comment]
> Video preview now using CPU to decode

This is not true. Video decoding is now handled by the GPU.

**Comment by dXrayb** [comment]
But CPU usage is higher than potplayer while video playing even open svp4.
