### ISSUE TITLE
Office file preview error

### ISSUE THREAD

**Issue by khaleeq11** [QL-Win/QuickLook#853]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
i install office plugin but i unable to preview office files when i press space bar on office files it just preview me file name date modified etc but not show me actual information in the file

**To Reproduce**

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by rabelux** [comment]
Which plugin did u install? There are two. My guess is u installed the wrong one.

**Comment by khaleeq11** [comment]
QuickLook.Plugin.OfficeViewer.qlplugin
QuickLook.Plugin.OfficeViewer.qlplugin
both plugin one in 5kb and other is almost 16mb

**Comment by rabelux** [comment]
You only need one. Did you press space on it and then install it?

**Comment by khaleeq11** [comment]
i already install it using space spacebar

**Comment by khaleeq11** [comment]
thanks for helping me i installed the experimental plugin
its wrong now i installed the correct one

**Comment by rabelux** [comment]
No problem. Would you mind closing this issue if it's solved?

**Comment by khaleeq11** [comment]
yes
