### ISSUE TITLE
Quicklook crashed when trying to preview an mp4

### ISSUE THREAD

**Issue by Cyberdroid1** [QL-Win/QuickLook#857]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
When I tried previewing an mp4 file, the QuickLook window opened, froze, and crashed.

**Expected behavior**
It should have previewed properly.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.844
 - QuickLook Version: 3.6.10 from Store

**Screenshots and Exception Log**

![image](https://user-images.githubusercontent.com/51435948/109416566-0b5c4480-79e5-11eb-9cee-4891734198ef.png)

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/6056703/QuickLook.Exception.log)

**Comment by rabelux** [comment]
Does this happen every time you preview any mp4, only when previewing that mp4 file or was it a one-time error?

**Comment by Cyberdroid1** [comment]
Hmmm, I tried again with the same file and others, and it didn't crash. 
So, it seems like a one-time error to me.

**Comment by rabelux** [comment]
I'll close this issue for now. If you manage to reproduce the error pls reopen this ticket and explain the steps that caused this error.

**Comment by Cyberdroid1** [comment]
Alright :D
Will do so.
