### ISSUE TITLE
How to preview file without typing space key, using cursor only?

### ISSUE THREAD

**Issue by pytkr** [QL-Win/QuickLook#858]
Hi! 
I want to preview file **without** clicking, pressing key, only by moving mouse cursor over the file or folder, which is better for faster preview. 
P.S., IMHO, if this can be realized, .zip or .rar file can be better previewed, because quick-look can only preview the folder structure in compressed file, not each file (except the image files), by press space key.

**Comment by xupefei** [comment]
I believe what you want is http://qttabbar.wdfiles.com/local--files/documents/preview.html.

**Comment by pytkr** [comment]
> I believe what you want is http://qttabbar.wdfiles.com/local--files/documents/preview.html.

Thanks for your reply, I tried with this feature and some java file includeed in zip file cannot be shown when not pressing spacebar, however. 

I acturally hope the quick-look powerful viewer can be effective with qttabbar.

**Comment by xupefei** [comment]
To do this QL has to monitor all your mouse activity in all running applications, which will consume more resource and makes QL (even) more like a spyware 😛

QTtabbar, on the other hand, only monitors the Explorer thus more light-weight for this task.
