### ISSUE TITLE
persist background setting

### ISSUE THREAD

**Issue by hoishing** [QL-Win/QuickLook#859]
Now we can toggle background light / dark mode by clicking the icon on the upper right corner. However, it does not persist. We have to click everytime if we are previewing a set of similar graphics. 

Can we persist the background setting? say by double click on the background mode icon?

many thanks :)

**Comment by xupefei** [comment]
This build https://ci.appveyor.com/project/xupefei/quicklook/builds/38103757/artifacts should fix your issue. Can you have a try?

**Comment by hoishing** [comment]
yes, the background can persist in version 3.6.11 preview 😊
