### ISSUE TITLE
Animations possible?

### ISSUE THREAD

**Issue by Scarwoman** [QL-Win/QuickLook#86]
Hey! What an amazing app have you made! I've been using Seer for a while but i'm impressed with the fluidity of your QuickLook!  Thanks for the hard work!
And maybe is it possible to add some animations? Do you think OS X's animation is possible or a fading animation?

Grtz,

Vincent

**Comment by codesharkasm** [comment]
That would be awesome!

**Comment by xupefei** [comment]
The development focus is now still on new features, so adding transition animations is something for the future. However you are welcome to help me with that!

**Comment by xupefei** [comment]
The recent nightly version has transition animations. The issue is solved,

**Comment by Scarwoman** [comment]
Great! Going to check it out! Thanks for the hard work!

**Comment by Scarwoman** [comment]
Thanks alot! it looks amazing! Transitions are almost complete in my opinion. A transition between the loading screen to the actual preview within the a app lacks an animation. Do you think a transition would be possible there so it will be 100% fluent?

**Comment by xupefei** [comment]
It can have a transition for the loading screen, but now it will not be 100% fluent, especially when switching previews. There are some UI-blocking operations in the code and it needs some time to rewrite them.

Anyway, I will add the animation soon, let's see how it performs.
