### ISSUE TITLE
Show wrong resolution, sets 1920x1080 to be smaller

### ISSUE THREAD

**Issue by schroef** [QL-Win/QuickLook#860]
**Describe the bug**
Noticed it beore but never actually investigated. But previewing images on my second monitor it shows wrong resolution. I dont have the monitor set to scaling, its actually 100% at 1920x1080. Yet when preview with quicklook i need to zoom to about 120%, which corresponds to my laptop monitor which does have zooming enabled. Yet i still think its wrong. If you zoom 1920x1080 it should be larger.

**To Reproduce**
1. Find image 0f 1920x1080
2. Press space
3. Notice how the image at 100% i smaller than actual display resolution

**Expected behavior**
Image should preview at reall 100% resolution.

**Desktop (please complete the following information):**
 - Windows 10 20H2
 - QuickLook 3.6.10

**Screenshots and Exception Log**
See attached
![wronf scale](https://user-images.githubusercontent.com/6923008/110064765-1c3dea80-7d44-11eb-8722-4a73e5083759.jpg)
![image specs](https://user-images.githubusercontent.com/6923008/110064768-1d6f1780-7d44-11eb-9d3e-e69bb2dfcbf4.jpg)
![actually resolution](https://user-images.githubusercontent.com/6923008/110064769-1d6f1780-7d44-11eb-884b-25a38a3225ac.jpg)

**Comment by xupefei** [comment]
Does the nightly version fix your issue?
