### ISSUE TITLE
Wrong Preview

### ISSUE THREAD

**Issue by Dominiquini** [QL-Win/QuickLook#863]
**Describe the bug**
When I select a file and press "SPACE", the next file are selected and their preview is showed.

**To Reproduce**
1. Open the Windows Explorer
2. Go to some folder with multiple files of the same type (video files)
3. Selected some file from the middle
4. Press "SPACEBAR"
5. The next file are previewed

**Expected behavior**
The selected file when I press "SPACEBAR" needs to keep the selection and their preview must be showed!

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10] Version 20H2 (OS Build 19042.844)
 - QuickLook Version: [e.g. 3.6.10 from GitHub releases page (Installer Version)]

**Screenshots and Exception Log**
.....

**Observations**
I have QTTabBar installed. This could be the problem?
- http://qttabbar.wikidot.com/

**Comment by rabelux** [comment]
What happens if you quit Quicklook and press space on the video file? Is the next file selected?
If yes then this has nothing to do with QuickLook and some other tool/plugin uses the spacebar to move selection to the next file

**Comment by Dominiquini** [comment]
I found the problem! It was with a option of QTTabBar. I changed the settings and now is working!

Thanks.

**Comment by Dominiquini** [comment]
Duplicate of #726
