### ISSUE TITLE
Right click context menu option to Preview files

### ISSUE THREAD

**Issue by arafat-ar13** [QL-Win/QuickLook#864]
Clicking a file and pressing Space to preview it is amazing. But I feel like integrating this feature in the Windows right-click menu is going to be a nice addition. While I am unable to provide any screenshot, I am talking about displaying a QuickLook icon and then "Preview" next to it whenever we right click on a file/folder to bring up the context menu. Clicking on "Preview" will be the same as pressing the Spacebar.

**Comment by Rasmagoric** [comment]
Or the middle mouse button, as there is no use for it on windows by default.

**Comment by Turk303** [comment]
"Send to Editor" from Sordum [dot] org will allow you to add a "send to" contextual menu for any file too any app. 
Simple to use, free and 1 request less of the 10,0000 already on the list :)

**Comment by rabelux** [comment]
Appreciate your input!! It's great to see people share possible solutions. 
I'll gladly close this request.
Only 999 to go 😉
