### ISSUE TITLE
Please add colour management feature for images

### ISSUE THREAD

**Issue by rockdengj** [QL-Win/QuickLook#865]
Read icc profiles from image files or monitors(Can give an option to choose), so it can render images correctly. Like the software _Honeyview_ does.

**Comment by xupefei** [comment]
QL now reads ICC from the image itself.

Use monitor ICCs will be a hard task. I think it's not me but Microsoft should be the one who works on it.

**Comment by rockdengj** [comment]
Windows will not convert colour space for software automatically(macOS does). It might be a hard task, but I still wonder how Photoshop and some image viewer(like Honeyview and JPEGview) do this. If it can read the monitor icc profile, I no longer need to export .png with icc profile embedded every time.

**Comment by rabelux** [comment]
Fixed. Details in #329
