### ISSUE TITLE
White text issue for code files (.xml, .kt, .gradle, etc.)

### ISSUE THREAD

**Issue by dnmcodes** [QL-Win/QuickLook#874]
![Screenshot (19)](https://user-images.githubusercontent.com/23311940/111471635-1c2fe880-874f-11eb-8084-f2e4f448effc.png)
Visual Code is used to preview code files.

**Comment by rabelux** [comment]
Why is noone using the template to report issues? May I ask whether you were following any link to create this issue?
I cannot reproduce your problem btw:
![2021-03-17 15_53_29-172 20 1 52 - Remotedesktopverbindung](https://user-images.githubusercontent.com/16120882/111488114-3e1e7080-8739-11eb-851b-81d3077eb050.png)

**Comment by dnmcodes** [comment]
Fixed the issue. Turns out a custom theme that I was using was the cause of the issue.
