### ISSUE TITLE
Ability to configure a hot key other than the space bar

### ISSUE THREAD

**Issue by johnatpackawhallop** [QL-Win/QuickLook#876]
I am needing to use QuickLook in a Windows 10 VM in Parallels on macOS, and QuickLook's use of the space bar conflicts with the macOS Quick Look feature. Funnily enough, they both work. In other words, when I select a file and hit the space bar, I get a Mac and a Windows preview! Anyway, it would be cool if QuickLook could be configured to use the key of your choosing in order to avoid situations like this. Thanks!

**Comment by rabelux** [comment]
Explained in #272
