### ISSUE TITLE
fix-修复智能识别文本编码

### ISSUE THREAD

**Issue by AdoShan** [QL-Win/QuickLook#878]
*Please search within existing issues before the submission. Has this issue already been reported?*
Not seen
**Describe the bug**
The recognition of UTF-8 encoded text into other encoding formats causes garbled characters to be displayed.

**Expected behavior**
It should be intelligently identified and load the file correctly.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 20H2(19042.867)
 - QuickLook Version: 3.6.11(UWP)

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/44154107/111857933-f59cc800-896f-11eb-8b3e-88822a1ad50a.png)

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/6174820/QuickLook.Exception.log)

**Comment by KrasnayaPloshchad** [comment]
[DNS Jumper](https://www.sordum.org/7952/dns-jumper-v2-2/) has a configuration file DnsJumper.ini encoded in UTF-16, but QuickLook does not view anything from this file.

**Comment by rabelux** [comment]
Related to #954
