### ISSUE TITLE
Support for previwing every file in a zip file.

### ISSUE THREAD

**Issue by AraHaan** [QL-Win/QuickLook#879]
**Is your feature request related to a problem? Please describe.**
I would love it if QuickLook when clicked on a zip file to preview the contents of everything inside of the zip file (if images displays the actual images inside, if text prints the text readonly, if neither image nor text show up readonly hex view of the contents).

**Why not open the file first?**
Well for starters I only would want to open the file only if I actually want to extract contents from it. Also many times I would forget what the files contents, extract, then find the file did not have anything that I wanted and so then I got to delete what I extracted then.

**Describe the solution you'd like**
The only solution for this would be to implement a way to preview what is in the zip file like the way I described.

**Describe alternatives you've considered**
Not sure yet. Also not sure why Windows does not have any software already that could preview them (without directly opening the file first).

**Additional context**

**Comment by emako** [comment]
obsoleted issue
