### ISSUE TITLE
Office Viewer Native does not support preview Visio documents，but Window Explorer does.

### ISSUE THREAD

**Issue by 1013801464** [QL-Win/QuickLook#882]
Please add visio preview function.

**Comment by rabelux** [comment]
I can see that the file-extensions for visio files are present, they're just commented out https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native/blob/13c7f5f0c204463d5cd209e573bb2ccf0e12fd6d/Plugin.cs#L32.
@xupefei I couldn't find any issue or commit that mentions problems with visio, was there a reason to remove support or did you just never get to test it?

**Comment by rabelux** [comment]
@xupefei friendly reminder ;)

**Comment by xupefei** [comment]
Thanks :)

> was there a reason to remove support or did you just never get to test it?

Yes, because the preview is not trimmed to fit the preview window for some reason. What I got is a white image with a tiny graph in the top-left corner. Don't know if the issue has now been fixed.

**Comment by emako** [comment]
Done

See here https://github.com/QL-Win/QuickLook.Plugin.OfficeViewer-Native/releases
