### ISSUE TITLE
hidden tray does not take effect

### ISSUE THREAD

**Issue by haocvg** [QL-Win/QuickLook#883]
When I add the hidden tray configuration in the configuration, it does not take effect
![image](https://user-images.githubusercontent.com/44605406/112109406-7f58c980-8bec-11eb-9a31-30b67ea15eb7.png)

**Comment by xupefei** [comment]
You configured it wrong. `ShowTrayIcon = True` means you want to see the tray icon. Modify it to `False` will hide it.
