### ISSUE TITLE
Unable to use in Clover 

### ISSUE THREAD

**Issue by jxyddtc** [QL-Win/QuickLook#885]
I use Clover as my explorer, but QuickLook isn't work in Clover.

**Comment by rabelux** [comment]
Are you using win 7? Then pls see #213

**Comment by jxyddtc** [comment]
> Are you using win 7? Then pls see #213

No, Win 10

**Comment by rabelux** [comment]
@gottaegbert seemed to have an issue in #681 but apparently found a fix, maybe he can help

**Comment by gottaegbert** [comment]
nan I haven't solved that .I kind of quit clover .

**Comment by xupefei** [comment]
You should ask Clover to fix this issue.

**Comment by rabelux** [comment]
Thx @gottaegbert for replying! I'll close this issue and mark it as rejected.
