### ISSUE TITLE
[Feature Request] Contacts vcard/*.vcf preview?

### ISSUE THREAD

**Issue by Darthagnon** [QL-Win/QuickLook#893]
**Is your feature request related to a problem? Please describe.**
I would love to be able to preview contact vcards in *.vcf and *.contact format with QuickLook. 

**Describe the solution you'd like**
Windows Vista (and by legacy support, Win7/8/8.1/10) has a Contacts folder in the user root. This folder is meant to contain contact information in the ```Joe Bloggs.contact``` format, which, by inspection, seems to be some sort of XML file. It's not widely used, though. A more common standard is...

vCards. They can be exported from Android/iOS devices and email clients (I use eM Client), typically in ```Joe Bloggs.vcf``` format, with contact metadata and base64 contact photos included.

Ideally, I would like to be able to preview contacts in a QuickLook window, with a consistent GUI for vcards and Windows ```*.contact``` files; QuickLook is already able to preview images and SVGs, so rendering base64 to an image hopefully wouldn't be a big jump. QuickLook already has code-recognition, and link highlighting (e.g. Markdown files; not sure if clickable links work, though) - so metadata and contact email addresses/telephone numbers/websites/social profiles could be tabulated something like iOS/iCloud contact previews, and links clickable by URL/URI standards (e.g. ```http(s)://```, ```mailto:```, ```tel:```, ```skype:```, ```fax:```, etc.)

**Comment by Darthagnon** [comment]
Might be better done as a plugin, but Windows doesn't have any good command-line vcard/.contact management programs to base it off, as far as I know.

Doesn't even have any good contact management software, full stop. MacOS has "Contacts", Linux has [KDE Kontact](https://kontact.kde.org/index.html). Windows has the ```%UserProfile%\Contacts``` folder which only supports the proprietary ```*.contact``` XML format, and is kinda rubbish. eM Client is the only other software with Contact Management features that I've found for Windows that isn't some sort of enterprise PIM or from 2003.

**Comment by emako** [comment]
There are no official plans to support such files.

But maybe in the future.
