### ISSUE TITLE
[Feature Request] - Change file name from preview window of QuickLook

### ISSUE THREAD

**Issue by zvtrung** [QL-Win/QuickLook#894]
All QuickLook's features are good now! I think it will be better if we can change file name for the file being quick-viewed. For ex, we can click on its filename, then a edit-box appear for user type in the new name of the file.

Happy quicklooking!

**Comment by rabelux** [comment]
What's the benefit of it? Just use the file explorer which is already open. Press F2 if you need a shortcut for renaming (only works if explorer has focus). You don't even need to close the preview.
