### ISSUE TITLE
[Feature Request] Incorrect file format detection for image files

### ISSUE THREAD

**Issue by nakonero** [QL-Win/QuickLook#896]
**Is your feature request related to a problem? Please describe.**
It would be extremely helpful to add incorrect file format detection to image files.

**Describe the solution you'd like**
If a .JPG file is incorrectly named as a .PNG, for example, 'this_is_a_jpg.png', QuickLook will detect it and offer to correct the file's filename.

An example flow would be, the user opens a file as described above, then QuickLook prompts the user with 'This file is a PNG file with an incorrect extension.  Rename?'.

**Describe alternatives you've considered**
Image viewers like IrfanView have this functionality built in, but I have struggled to find another software that does this.

**Comment by emako** [comment]
No plan to support
