### ISSUE TITLE
Files do not open from command line

### ISSUE THREAD

**Issue by jompiter** [QL-Win/QuickLook#897]
**Describe the bug**
Trying to open a file in the command line using `path\to\QuickLook.exe path\to\file` only shows the following window:

![imagen](https://user-images.githubusercontent.com/73229276/114529048-dd0b8f00-9c49-11eb-8aed-786f01f7acfd.png)

**Expected behavior**
The file opens in QuickLook

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2
 - QuickLook Version: 3.6.11 MSI Installer version

**Comment by rabelux** [comment]
That happens if you provide an invalid path as argument or no argument while quicklook is already running.
Responsible function is https://github.com/QL-Win/QuickLook/blob/6a0c116bd425db7870e2eb2f2fe97382e434cdf1/QuickLook/App.xaml.cs#L143-L160

*APP_SECOND_TEXT* is what you see

**Comment by jompiter** [comment]
Solved, it was due to the terminal not being able to see the specific folder, thanks!
