### ISSUE TITLE
Audio faded

### ISSUE THREAD

**Issue by Scarwoman** [QL-Win/QuickLook#90]
When peeking on music I have to adjust the volume slider to its maximum every time because the volume level of QuickLook doesn't correspond to the rest of the PC.
Is it possible to have to volume slider standard set at maximum?

Grtz

**Comment by xupefei** [comment]
For now you may use the mouse wheel to adjust volume.
I will add a "remember last volume" feature soon.

**Comment by neycodes** [comment]
That would be an awesome feature! Thanks!
