### ISSUE TITLE
[Feature Request] Add support for JPEG2000 format

### ISSUE THREAD

**Issue by Hinlavic** [QL-Win/QuickLook#901]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Add support for JPEG2000(.jp2) format, since JP2 is popular with high lossless compression of image. It has much higher compression rate (x10 ~ x20) than the old TIFF format and many institute use JP2 for archive, such as Library Of Congress(USA).

**Describe alternatives you've considered**

**Additional context**
By the way, I also suggest a global view for convenience of jumping in large file , such as large image and long codes.  Maybe it can be included as an optional feature.

**Comment by rabelux** [comment]
Should be solved once #818 gets approved
