### ISSUE TITLE
A little suggestion

### ISSUE THREAD

**Issue by Li-Lian1069** [QL-Win/QuickLook#906]
You can add the "Don't show me in System Tray" to the Tray menu
Most of the time, I just need him to work quietly, and I don't need to know its state
However, if it appears in my tray, it will take up my tray space
In particular, I'm an obsessive-compulsive person

你可以把 "不显示托盘图标放入托盘菜单中"
很多时候, 我只需要他安静的工作就行了, 不需要知道它的状态
但是, 如果它在我的托盘出现, 会占用我的托盘空间
尤其是, 我是一个有强迫症的人

**Comment by rabelux** [comment]
That's already possible - see https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations
