### ISSUE TITLE
Please add .rtf support

### ISSUE THREAD

**Issue by technobulb** [QL-Win/QuickLook#909]
Just want to know if there is any reason that .rtf (windows word pad/rich text format) isn't supported. It seems to be a quite popular and probably pretty simple to translate... Right now a bunch of incoherent gibberish comes up if you try to preview a .rtf

**Comment by jelleeey** [comment]
I second this!

**Comment by rabelux** [comment]
solved with #933 and available in the nightly

**Comment by technobulb** [comment]
Wow! Amazing job. Thanks, it makes such a difference for me!
