### ISSUE TITLE
quicklook能在桌面整理工具上生效吗

### ISSUE THREAD

**Issue by yxok200** [QL-Win/QuickLook#910]
最近把quicklook推荐给了一些朋友使用，朋友们都觉得quicklook很方便，可以提高工作效率，但是有2个朋友平时处理大量文件，桌面上百个文件，必须开着桌面整理工具才能看得过来，朋友使用的桌面管理工具是QQ提供的，目前情况是quicklook在桌面管理工具上是无法使用的，不知道以后能否支持

**Comment by xupefei** [comment]
QQ自己画了一个桌面，QL无法支持。
请考虑使用更先进的Fences。
