### ISSUE TITLE
Please add Krita (.kra) image format

### ISSUE THREAD

**Issue by flotasser** [QL-Win/QuickLook#912]
Hello and first off: thank you so much for Quicklook, been using it a few days and love it!
I'd like to suggest to include the image format of the free and open source digital painting software Krita. www.krita.org
As far as I know the .kra files are just a renamed zip with a merged PNG of the image.

Thank you for considering. :)

**Comment by emako** [comment]
test.kra here

[test.zip](https://github.com/user-attachments/files/18168161/test.zip)

**Comment by emako** [comment]
#696
