### ISSUE TITLE
"Quick" mode to open big text files.

### ISSUE THREAD

**Issue by Cai-98** [QL-Win/QuickLook#913]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when opening **big** `csv` or `json` files and QuickLook crashing.

**Describe the solution you'd like**
An *option/switch* that to view file using text viewer(that used when view `txt` files) for I've recognized text viewer can view really big files with quick speed.

**Comment by emako** [comment]
Currently, large files will be cropped and displayed with the first 5MB
