### ISSUE TITLE
[Feature Request] Be able to hide the page previews in PDF files

### ISSUE THREAD

**Issue by moxwel** [QL-Win/QuickLook#919]
**Is your feature request related to a problem? Please describe.**
When I open PDF files, the page thumbnails are always visible in the left side. Sometimes that menu is interfering with the document.
![0](https://user-images.githubusercontent.com/49621788/119188557-cfb3a280-ba48-11eb-9208-78c55ade3357.png)

**Describe the solution you'd like**
I wish that there's a button to hide the pages menu, and be able to view the document at full window.
![111](https://user-images.githubusercontent.com/49621788/119188565-d17d6600-ba48-11eb-9eae-de7e3f374da7.png)

**Describe alternatives you've considered**
I use other PDF readers, but I'd like to use QuickLook as PDF reader because it is so much faster to open.

**Comment by xupefei** [comment]
QL is designed to be a preview app, not a PDF reader. Have you tried a lightning-fast PDF reader [Sumatra PDF](https://www.sumatrapdfreader.org/free-pdf-reader)?

**Comment by moxwel** [comment]
Yeah, I've tried Sumatra PDF, but I don't like it very much...
