### ISSUE TITLE
Fix Issues about the Markdown Plugin

### ISSUE THREAD

**Issue by hyrious** [QL-Win/QuickLook#920]
**Is your feature request related to a problem? Please describe.**
[All issues related to Markdown](https://github.com/QL-Win/QuickLook/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+Markdown).
I'm not able to debug QuickLook in my visual studio. So I'll put some suggestions here.

**Describe the solution you'd like**
- [ ] The default charset is not UTF8. It may be fixed by changing
https://github.com/QL-Win/QuickLook/blob/df66c425e30adbc349c8ba3d681edc780b41a65d/QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer/Plugin.cs#L72
   ```diff
   - var encoding = CharsetDetector.DetectFromBytes(bytes).Detected?.Encoding ?? Encoding.Default;
   + var encoding = CharsetDetector.DetectFromBytes(bytes).Detected?.Encoding ?? Encoding.UTF8;
   ```
- [ ] (#752, #728, #693, #362)
   Switch to [KaTeX](https://katex.org/) for better performance.
- [ ] (#742) Dark theme.
   You can use [my fork of github-markdown-css](https://github.com/hyrious/github-markdown-css).
   Also, #836 will be resolved by this css file.
- [ ] (#508, #82) Not able to read local image file.
   The best solution I can imagine is starting a local http server in the markdown file's folder, which is possible with `<Capability Name="privateNetworkClientServer" />`.
   A quick implementation in Node.js (with hot reload support) can be find [here](https://github.com/hyrious/marked-cli).

**Comment by bathtown** [comment]
I cannot find `Plugin.cs` in `QuickLook/QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer`, only `QuickLook.Plugin.MarkdownViewer.dll` & `UtfUnknown.dll`

**Comment by hyrious** [comment]
> I cannot find `Plugin.cs` in `QuickLook/QuickLook.Plugin/QuickLook.Plugin.MarkdownViewer`, only `QuickLook.Plugin.MarkdownViewer.dll` & `UtfUnknown.dll`

...Source code...

**Comment by Alaknar** [comment]
I'd LOVE for Markdown files to be displayed in dark mode.

![image](https://user-images.githubusercontent.com/26569304/141121025-52258912-fd06-4290-89cd-91b076a4c602.png)

**Comment by emako** [comment]
After 06e796a markdown viewer support dark theme.
