### ISSUE TITLE
Can‘t preview mp4 or mp3 files

### ISSUE THREAD

**Issue by happybaby8882** [QL-Win/QuickLook#921]
**Describe the bug**
.mp4 and .mp3 files are not previewed, When click 'space bar' an error window pops up.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 1803]
Edition    Windows 10 Pro N
Version	21H1
Installed on	‎2021/‎4/‎8
OS build	19043.985
Experience	Windows Feature Experience Pack 120.2212.2020.0

 - QuickLook Version: [e.g. 0.3.3 from Windows Store]
V3.6.11 from git, .msi

**Screenshots and Exception Log**
![Snipaste_2021-05-26_17-30-20](https://user-images.githubusercontent.com/70244073/119638377-2bb36800-be49-11eb-8cf5-ca10c6e7d18d.png)
![Snipaste_2021-05-26_17-31-32](https://user-images.githubusercontent.com/70244073/119638381-2d7d2b80-be49-11eb-9b77-7f7014b8cf9a.png)

**Comment by rabelux** [comment]
see #707

**Comment by happybaby8882** [comment]
> see #707

Thank you. I thought Quicklook was independent from windows media earlier.

**Comment by happybaby8882** [comment]
> see #707

Thank you. I thought Quicklook was independent from windows media earlier.

**Comment by lf2593** [comment]
> > see #707
> 
> Thank you. I thought Quicklook was independent from windows media earlier.

Hey you, I follow your steps "Settings > Apps > Apps and Features > Optional Features > Add a Feature " but I didn't find Media Feature Pack in the list! Can you help me?
![image](https://user-images.githubusercontent.com/34355658/122529185-c6215880-d04f-11eb-9dc6-7018040ad81a.png)

**Comment by happybaby8882** [comment]
> > > see #707
> > 
> > 
> > Thank you. I thought Quicklook was independent from windows media earlier.
> 
> Hey you, I follow your steps "Settings > Apps > Apps and Features > Optional Features > Add a Feature " but I didn't find Media Feature Pack in the list! Can you help me?
> ![image](https://user-images.githubusercontent.com/34355658/122529185-c6215880-d04f-11eb-9dc6-7018040ad81a.png)

You have already installed "windows media player", I think you should look for other issues.
