### ISSUE TITLE
Please add another pdf preview option

### ISSUE THREAD

**Issue by jiewangjs** [QL-Win/QuickLook#925]
recently, I found another plugin called WinQuicklook, its pdf preview is very smooth, which is really what this app lacks.

**Comment by SpiritSeal** [comment]
Might be coming soon with the switch to CefSharp (https://github.com/QL-Win/QuickLook/issues/551).

**Comment by netsonicyxf** [comment]
The current PDF viewer has no vertical scroll，any chance to add it?

**Comment by xupefei** [comment]
Switching to CefSharp is not gonna happen after we merged 7cf0d0affb363f084e16af8afa52220e85a3f19d.
But of course you are welcome to make a CefSharp plugin to replace WebView2.
