### ISSUE TITLE
Preview only by hovering?

### ISSUE THREAD

**Issue by DeiniBrett** [QL-Win/QuickLook#926]
I have been through a bunch of suggestions and I have not seen this one, but I might be wrong, I might have just missed it.

Can't the hovering be used to pick which file you want to preview? I have only done two years of programming, so I am pretty bad, but instead of clicking, cant the hovering trigger be used to decide which file should be previewed? I imagine many people would prefer the arrow keys, but maybe there could be an option to choose from the original mode, or the hover mode.

Again, if this was suggested before I apologise,

**Comment by xupefei** [comment]
You can try http://qttabbar.wdfiles.com/local--files/documents/preview.html.

**Comment by snowman** [comment]
How to *disable* preview by hovering? (want to preview only by explicit press `SPACE`)

Today, after away from keyboard, it triggers play of video unexpectedly.
(I know this 20 minutes later, that's, the video has played 20 minutes)

It happens with mobile phone un-plugin, then `Explorer` window pops up,
and coincidentally mouse pointing on video file, and then it got played.

The first few seconds of video is silent, so I didn't notice that it's playing.
so after leaving room, it plays video with some sound, which is *embarrass*

**Comment by rabelux** [comment]
@snowman wrong tool, QuickLook can only preview with space bar

**Comment by snowman** [comment]
LOL, it pops up little window when hovering.

![Clip_20230910_003335](https://github.com/QL-Win/QuickLook/assets/16096559/b4d471a6-d466-42ba-8963-aa9996c4a378)

I thought it was QuickLook, but after your prompt, I catch it, that's window named `QTTabBar Preview Window`
