### ISSUE TITLE
bug when use “everything” tool

### ISSUE THREAD

**Issue by uvery9** [QL-Win/QuickLook#927]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
When I use "quicklook" with "everything" in PC dual-screen mode, I often lose focus in the result list.
Press the space on the search result to display the result. But when I move the cursor using arrow keys, there is often no response.
我在双屏模式使用”quicklook“搭配“everything”使用的时候，在结果列表，经常失去聚焦。
按搜索结果上的空格，显示结果。但移动光标，经常没有任何反应。

**To Reproduce**
1. Use PC dual-mode screen
2. Install everything V1.4.1.1005 (x64)  in https://www.voidtools.com/zh-cn/
3. Type some keywords
4. Move the mouse to the search result, click and make it turn blue.
5. Press "Space" button.
6. It works.
7. When I press arrow keys on the keyboard.
8. Quick Look often no response.
9. Try to use sing-monitor, the issue comes again. 

**Expected behavior**
Just act like the single-screen mode.

**Desktop (please complete the following information):**
 - Windows 10 20H2 home-ZH_cn
 - QuickLook Version: v3.6.11(from github)

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).
[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/6617138/QuickLook.Exception.log)

https://user-images.githubusercontent.com/42594123/121206209-de081800-c8aa-11eb-95bd-c273b9f9ebe4.mp4

**Comment by xupefei** [comment]
Are these images very large (in size or dimensions)?

**Comment by JaredDC** [comment]
No, almost all image files are less than 1MB, download from bing.com. The resolution is 1920*1080.
<img width="593" alt="Snipaste_2021-06-08_23-14-53" src="https://user-images.githubusercontent.com/42594123/121211820-5f61a980-c8af-11eb-99da-a3cd0f489f09.png">

**Comment by xupefei** [comment]
Then it's strange. The polling interval is 500ms but your video shows a refreshing time much longer than that.
I'll see if I can find some time this weekend to looking at this issue.

**Comment by JaredDC** [comment]
> Are these images very large (in size or dimensions)?

Not just pictures, but also other files.

https://user-images.githubusercontent.com/42594123/121214754-021b2780-c8b2-11eb-88d9-e799f450c86a.mp4

**Comment by JaredDC** [comment]
The characteristics of this file list are below example:
1.txt          C:\a\1.txt
1.txt          C:\b\c\1.txt
2.txt          D:\d\e\f\2.txt
Is it possible that the QuickLook cannot obtain the full path of the entire file, so it cannot be displayed normally?
I can get this full path of file by right clicking.
![image](https://user-images.githubusercontent.com/42594123/121217425-6ccd6280-c8b4-11eb-859a-defac35a1807.png)
