### ISSUE TITLE
Opening QuickLook inside Total Commander

### ISSUE THREAD

**Issue by C0N73MN** [QL-Win/QuickLook#928]
I am not able to open quicklook inside total commander when pressing separator key. I've managed to remove total commanders default shortcut of the separator but after doing so the quicklook is not loading. Any help with that? thank you

**Comment by rabelux** [comment]
Have a look at the [wiki](https://github.com/QL-Win/QuickLook/wiki/File-Managers:-Total-Commander)

**Comment by C0N73MN** [comment]
yes I found it right before i post this. (stupid me). thank you
