### ISSUE TITLE
Can not open video and audio file 无法打开视频音频文件

### ISSUE THREAD

**Issue by lf2593** [QL-Win/QuickLook#930]
系统版本：Windows 10 家庭版   20H2    19042.985
QL版本：3.6.11UWP/msi
![222222](https://user-images.githubusercontent.com/34355658/121451321-f6be1e00-c9cf-11eb-8f11-69bfd0cba6ff.png)
![1111](https://user-images.githubusercontent.com/34355658/121451326-f7ef4b00-c9cf-11eb-99c3-dad6d94427df.png)

**Comment by lf2593** [comment]
第一张图是打开视频出现的问题，第二张图是打开音频出现的问题

**Comment by lf2593** [comment]
nobody here?

**Comment by rabelux** [comment]
Sry I don't speak asian languages, only the dev and he's busy atm.
Are you using Windows N?

**Comment by lf2593** [comment]
thanks for your reply, what is Window N?
My system version is Windows 10 home 20H2 19042.985 and Quicklook version is 3.6.11UWP/msi

**Comment by rabelux** [comment]
Your issue looks similiar to Windows-N-problems, so please check if you have the Media Features Pack installed. See #921 for reference.

**Comment by rabelux** [comment]
Is your problem solved? If yes please report back and close this issue.

**Comment by lf2593** [comment]
Actually not. I tried the approach you referred to me, but the difference between us is my OS version is Windows 10 home, not Windows N.

**Comment by lf2593** [comment]
I do not find Media Feature Pack by following these steps " Settings > Apps > Apps and Features > Optional Features > Add a Feature and find the Media Feature Pack in the list of available Optional Features"

![image](https://user-images.githubusercontent.com/34355658/122529057-9e31f500-d04f-11eb-8d34-2b78828383b0.png)

**Comment by rabelux** [comment]
Maybe because it's already installed?

**Comment by lf2593** [comment]
That's probable because I have confirmed issue #921 will only appear on Windows N or KN version.

**Comment by lf2593** [comment]
So, according to my system version, can you do me a favor? I'll appreciate

**Comment by lf2593** [comment]
This is my system info
![image](https://user-images.githubusercontent.com/34355658/122531943-932c9400-d052-11eb-80c1-c6e7fa3a30e3.png)

**Comment by rabelux** [comment]
Sry I'm out of ideas

**Comment by lf2593** [comment]
pity

**Comment by xupefei** [comment]
What is the model of your graphic card?

**Comment by lf2593** [comment]
> What is the model of your graphic card?
Thanks for your reply. 
Intel(R) HD Graphics 630 and NVIDIA GeForce GTX 1050

**Comment by xupefei** [comment]
I've no idea. HD630 is new enough to handle EVR when supported by the OS. I now suspect your OS lacks a few components.
If it is possible, could you try upgrading the OS to the normal or Pro version (ie without "Home")?

**Comment by lf2593** [comment]
Ok, I‘ll follow your advice several days later.
