### ISSUE TITLE
*.mid midi piano-roll viewer

### ISSUE THREAD

**Issue by oxygen-dioxide** [QL-Win/QuickLook#931]
This issue is different from #436

I hope to view midi file with quicklook in a piano-roll ui (like in DAWs and vocaloid).
![image](https://user-images.githubusercontent.com/54425948/121615223-f3d83180-ca92-11eb-928a-0341adf4beab.png)

**Comment by jetrotal** [comment]
+ 1 to this one, 
I also wish to listen to midi stuff on quick view, does it support javascript, there are plenty of JS libraries for that.

**Comment by emako** [comment]
Note that https://github.com/melanchall/drywetmidi can play midi with device named Microsoft GS Wavetable Synth

**Comment by emako** [comment]
Done in nightly build

https://github.com/QL-Win/QuickLook/releases
