### ISSUE TITLE
the application is running, but won't work at all

### ISSUE THREAD

**Issue by importchan** [QL-Win/QuickLook#934]

**Comment by rabelux** [comment]
Closed for not filling out the template.

**Comment by importchan** [comment]
> Closed for not filling out the template.



> Closed for not filling out the template.

sorry im new to this website, i dont know which template you are talking about

**Comment by rabelux** [comment]
When you created this issue there was already some text written and that is the template. You created this issue containing the template. Then you edited your issue and deleted said template. Fill out the template, provide a little bit more information than "doesn't work" and maybe we can help you.
