### ISSUE TITLE
QuickLook window is too bright

### ISSUE THREAD

**Issue by rvpto** [QL-Win/QuickLook#940]
**Describe the bug**
QuickLook preview windows look too bright to be useful. I tried changing Windows' color/transparency effects settings and uninstalling and installing different versions of QuickLook, with no success.

**To Reproduce**
1. Have QuickLook running.
2. Preview any file or item with spacebar.
3. See error.

**Expected behavior**
A nice, readable window should appear.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 virtual machine, on VMWare Player 16.1.2 (Windows 10 host)
 - QuickLook Version: 3.6.9 msi, 3.6.10 msi, 3.6.11 msi and zip, and nightly 3.6.11-13-g1e5de83 msi.

**Screenshots and Exception Log**
![bug quicklook](https://user-images.githubusercontent.com/43444778/122692117-bbaabe80-d209-11eb-8c74-8da445a03b1a.png)

**Comment by xupefei** [comment]
Blame the inferior VMware GPU driver. I don't have a solution :(

**Comment by rvpto** [comment]
That's what I thought... :( It works fine on Hyper-V though. Thanks for the quick reply!
