### ISSUE TITLE
Language is not being applied correctly

### ISSUE THREAD

**Issue by d-l-n** [QL-Win/QuickLook#941]
My OS language is set on Spanish (es) but app keeps showing all texts in English and there isn't any manual way to change it (at least i didn't find it and repo doesn't says anything about it)

**Comment by xupefei** [comment]
It reads and matches your UI language.
Is your Start Menu in Spanish?

**Comment by d-l-n** [comment]
Yes, I have everything in Spanish
![imagen](https://user-images.githubusercontent.com/56566724/122940270-b43efe80-d34a-11eb-8c64-790c1e0de98d.png)
![imagen](https://user-images.githubusercontent.com/56566724/122940295-b99c4900-d34a-11eb-94b9-b4b2875f0f1a.png)
![imagen](https://user-images.githubusercontent.com/56566724/122940324-c02ac080-d34a-11eb-9752-aabeb66d8f3a.png)

**Comment by xupefei** [comment]
I think there's a bug in finding a translation: https://github.com/QL-Win/QuickLook.Common/blob/master/Helpers/TranslationHelper.cs#L56
`locale.Parent.Name` should be changed to `locale.TwoLetterISOLanguageName`.

Do you have developing exp to test this fix? If not I'll find some time tod test it.

**Comment by d-l-n** [comment]
I'm starting at coding but tell me what to do & I'll try

**Comment by xupefei** [comment]
Nevermind, I got some time to debug.
Could you download this DLL and overwrite the same file in the installation folder (you'll need MSI or ZIP version)?
When running QL it will pop up multiple message boxes. What are their contents?

[QuickLook.Common.zip](https://github.com/QL-Win/QuickLook/files/6704329/QuickLook.Common.zip)

**Comment by d-l-n** [comment]
i have msi version but i dont see any QuickLook.Common.dll file in app dir

**Comment by xupefei** [comment]
It's located aside QuickLook.exe.

**Comment by d-l-n** [comment]
i replaced it but now QuickLook doesn't starts. I tried rebooting OS but nothing

**Comment by xupefei** [comment]
Got it. I'll give you are full test package tomorrow.

**Comment by xupefei** [comment]
Try this one: 
[QuickLookUITest.zip](https://github.com/QL-Win/QuickLook/files/6711870/QuickLookUITest.zip)

**Comment by d-l-n** [comment]
![imagen](https://user-images.githubusercontent.com/56566724/123328239-bb643900-d511-11eb-8d11-2b0a1c4f3cec.png)
![imagen](https://user-images.githubusercontent.com/56566724/123328244-be5f2980-d511-11eb-8bc5-664386006e55.png)
![imagen](https://user-images.githubusercontent.com/56566724/123328250-c0c18380-d511-11eb-9191-4ee13d8abece.png)

**Comment by xupefei** [comment]
If you right click on the tray icon, what language is the menu in?

**Comment by d-l-n** [comment]
Yes!!

**Comment by xupefei** [comment]
So it's correct now, whereas in the release version you see English, correct?

**Comment by d-l-n** [comment]
yes it's showing text correctly

**Comment by xupefei** [comment]
I don't get it. What is your issue then?

**Comment by d-l-n** [comment]
The QL languague keeps in English. With the files you sent me the app shows texts in OS lang (es) but only when I right click on tray icon (https://github.com/QL-Win/QuickLook/issues/941#issuecomment-867971988) and QL doesnt work anymore, just shows the message boxes.

**Comment by d-l-n** [comment]
the issue is that QL is not recognizing the language and there's no manual way to select it neither

**Comment by xupefei** [comment]
Do you mean: with QuickLookUITest.zip you see the context menu in Spanish, but with the official release the same context menu in English?

**Comment by d-l-n** [comment]
Exactly

**Comment by rabelux** [comment]
Ok so your issue is fixed if you use the latest zip file, right?
If not then please provide screenshots as I'm also getting confused.

**Comment by d-l-n** [comment]
Look

![imagen](https://user-images.githubusercontent.com/56566724/123454409-e6549880-d5b6-11eb-939f-72fa4bc31a64.png)

And when I try to use QL to see files preview it shows this boxes (https://github.com/QL-Win/QuickLook/issues/941#issuecomment-867931781) so idk if the strings of file previews are showing translated

**Comment by xupefei** [comment]
https://ci.appveyor.com/project/xupefei/quicklook/builds/39767002/artifacts should fix your issue. Please try and report back!

**Comment by d-l-n** [comment]
Yes!! Thanks!
![imagen](https://user-images.githubusercontent.com/56566724/123711370-c0452780-d846-11eb-8b57-f8d34ce6302f.png)

The only thing, compressed files previews shows strings in English but I think it's related to ArchiveViewer plugin
![imagen](https://user-images.githubusercontent.com/56566724/123711705-48c3c800-d847-11eb-8f3d-773cdfca1ea8.png)
![imagen](https://user-images.githubusercontent.com/56566724/123711709-4a8d8b80-d847-11eb-875d-cfd2a561d846.png)
