### ISSUE TITLE
Quicklook stopped working

### ISSUE THREAD

**Issue by timlitos** [QL-Win/QuickLook#942]
Hello,
First off, I love this app. I can't believe it isn't built in. I've been using it for at least a year. Recently it has stopped working. I try to open in and nothing happens. Then I try to run as admin and I get an error, see attached image. I tried uninstalling and reinstalling and that doesn't seem to help. Any thoughts? Thanks in advance!

<img width="414" alt="error" src="https://user-images.githubusercontent.com/74060996/122979683-d85c0900-d365-11eb-810c-e5ff9bd9e19d.png">

**Comment by rabelux** [comment]
Try resetting your app:
Settings -> Apps and Features -> Quicklook -> Reset

**Comment by xupefei** [comment]
It seems you installed QL from the Store. In this case you can't run it directly from the installation dir.
