### ISSUE TITLE
[Feature Request] Preview only as long as spacebar is held down.

### ISSUE THREAD

**Issue by ankit1w** [QL-Win/QuickLook#947]
**The problem :**
Personally, I display the file's contents only for a few seconds before determining if this is the file I was looking for, so that I can open it in some other program intended for that specific file type. Pressing the spacebar twice makes the job a bit more tedious.

**Possible solution :**
It would be a useful optional feature to display the preview only when the spacebar is held down, and automatically close it when it is released.

**Comment by xupefei** [comment]
Yeah I know the macOS Quick Look also has such behavior. Specifically, when holding the spacebar for 0.5s then release.

This feature requires some changes in https://github.com/QL-Win/QuickLook/blob/master/QuickLook/KeystrokeDispatcher.cs.

**Comment by xupefei** [comment]
This build should work https://ci.appveyor.com/project/xupefei/quicklook/builds/39921588/artifacts, but note that I haven't tested it too much.

**Comment by ankit1w** [comment]
Okay this works perfectly and I'll be using this build for now. Also this one combines the hold-down and press modes which I found very useful. Thanks.

**Comment by xupefei** [comment]
Yes, I'm close it.
If you found any issue in this build please let me know.
