### ISSUE TITLE
File icon for PDF

### ISSUE THREAD

**Issue by nitin2953** [QL-Win/QuickLook#949]
**Problem**
I have setted QuickLook to open PDF by Default,
Which is showing QuickLook icon for PDF files everywhere

**Solution**
A separate icon for PDF files  ( ? with small quickLook icon at bottom right ? )

 
**Additional context**
MS Edge PDF file icon was looking good. So, similar like that

**Comment by rabelux** [comment]
This is not the scope of QuickLook. It is not intended to be the default file handler.
QuickLook has limited functionality so a proper pdf viewer is strongly recommended.
