### ISSUE TITLE
[Feature Request] Preview in a corner window when Mouse stops over a file.

### ISSUE THREAD

**Issue by gindark** [QL-Win/QuickLook#951]
Option to allow previews when mouse stops aover a file or folder, and auto close preview when mouse moves out.
Let preview show afther time: XXX ms. Let set size of preview window and fix it with ot without borders in any of 4 corners. Add Info from File/Folder bellow Preview Window.

![preview](https://user-images.githubusercontent.com/86907579/124377368-df5f1180-dcab-11eb-9a6f-08fd5914e72f.jpg)

**Comment by rabelux** [comment]
Related to #858

**Comment by xupefei** [comment]
Yeah, please check out https://github.com/QL-Win/QuickLook/issues/858#issuecomment-788870261.
For QL it's unrealistic to monitor all your mouse activity in all running applications.
