### ISSUE TITLE
!!! New update, QuickLook is spying on my mailbox and outlook account

### ISSUE THREAD

**Issue by marcustone** [QL-Win/QuickLook#953]
**Describe the bug**

Please note that the outlook OST file in Quicklook cache folder is not a mirror nor injection! It seems to be theft in regular period, not sure when the next theft is taking place, further details please see the screenshots to compare

**To Reproduce**
To install Quicklook in Windows

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 1803]
 - QuickLook Version: [0.3.3 from Windows Store]

**Screenshots and Exception Log**
![Snipaste_2021-07-06_12-22-17](https://user-images.githubusercontent.com/17929904/124542713-7c5dae00-de56-11eb-85a4-21a9c8651246.png)
![Snipaste_2021-07-06_12-22-19](https://user-images.githubusercontent.com/17929904/124542720-7d8edb00-de56-11eb-9126-aeada6d935a9.png)

**Comment by marcustone** [comment]
Anyone there who suspects this please try to access your directory to check whether your outlook OST files are monitored by Paddyxu's Quicklook if you have local outlook account
C:\Users[xxx]\AppData\Local\Packages\21090PaddyXu.QuickLook_egxr34yet59cg\LocalCache\Local\Microsoft\Outlook

**Comment by marcustone** [comment]
Paddyxu, please explain, and are you from China?
Is this an expected behavior? What kind of logic is this, and why is QuickLook spying on user's private email communication regularly??

**Comment by xupefei** [comment]
I have explained in https://github.com/QL-Win/QuickLook/issues/937:
> The path you provided is managed by UWP Sandbox, and files are copied by the sandbox. If you haven't ever tried to preview files from Outlook then it might be due to the [WoW64HookHelper](https://github.com/QL-Win/QuickLook/tree/master/QuickLook.Native/QuickLook.WoW64HookHelper) which injects itself into Outlook, which makes Windows thinks Outlook data should be sandboxed.
> 
> I believe this issue will go away if you use [ZIP or MSI versions](https://github.com/QL-Win/QuickLook/releases), which are not sandboxed.

Please note that race discrimination is now alowed in Github. Also I want to remind you that you are responsible for your words. Next time I will to Github.

**Comment by rabelux** [comment]
Hi marcus, sorry to bust your conspiracy theories, but this tool is open source. This means that (if you would have a technical understanding) you can track everything this tool does. If I had the right to block you I would have done that as you keep repeating the same nonsene in new tickets. The dev gave you a qualified answer and even a solution (use zip or msi version) but apperently your mind is trapped in a timelapse with no way to evolve.
BTW: I'm not from China and in no way related to xupefei - I don't even know him.

**Comment by marcustone** [comment]
xupefei, China is a country not a race, and there's no words implicating race discrimination. 
And Sandbox does NOT work like this to replicate ost file regularly, please don't find excuses.

Hi rabelux, it's not until I clean up the disk that I found such illegal replication, Sandbox does not work this way.
And if such behavior persists, xupefei shall remove the app from Microsoft store first until there's a total fix for that so called 'sandboxed' replication.
This is the fact, please show your fact.
 
![image](https://user-images.githubusercontent.com/17929904/124602535-8950c080-de9b-11eb-82dd-4f05c7f1bdcc.png)
![image](https://user-images.githubusercontent.com/17929904/124602553-8e157480-de9b-11eb-8503-f6a9920478d2.png)


I want to uninstall Quicklook, but when I click uninstall in Start Menu, it won't launch installation, but open Programs and Features, from there I don't find Quicklook in list thus have no way to uninstall it.

![image](https://user-images.githubusercontent.com/17929904/124602277-42fb6180-de9b-11eb-9a51-c9af8a4c148f.png)

**Comment by marcustone** [comment]
Please let user know the best way to uninstall Quicklook successfully and completely, thanks

**Comment by xupefei** [comment]
> Please let user know the best way to uninstall Quicklook successfully and completely, thanks

Sure: https://www.addictivetips.com/windows-tips/uninstall-a-uwp-app-in-windows-10/
