### ISSUE TITLE
[Bug] Strange characters in .txt preview

### ISSUE THREAD

**Issue by moxwel** [QL-Win/QuickLook#954]
**Describe the bug**
When previewing a .txt file with special characters (like `á é í ó ú ñ ¿` etc), those characters sometimes renders badly, and sometimes renders fine.

**To Reproduce**
1. Create a new .txt file with UTF-8 encoding.
2. Write `árbol` as example. The character `á` renders badly.
![1](https://user-images.githubusercontent.com/49621788/125179558-350c5000-e1bd-11eb-8bb9-853c8296f9cf.png)

3. Write `¿Hola?` as example. The character `¿` renders badly.
![2](https://user-images.githubusercontent.com/49621788/125179566-540ae200-e1bd-11eb-9003-3eaf3353f400.png)

4. Write `café` as example. Now all characters renders fine.
![3](https://user-images.githubusercontent.com/49621788/125179574-6c7afc80-e1bd-11eb-8dd1-c19f8a5137e1.png)

**Expected behavior**
All the characters should render fine from the beginning,

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.1081
 - QuickLook Version: 3.6.11 (MSI version from GitHub)

**Comment by xupefei** [comment]
The first two files are too short so the CharDet guessed a wrong encoding. The third file is long enough for CharDet to see it's UTF8.

No solution on my mind, I think you can try save these files as UTF8 with BOM.

**Comment by moxwel** [comment]
Well... this bug even happens with more large files, like this:
![image](https://user-images.githubusercontent.com/49621788/125328338-356a2f80-e312-11eb-8771-034a3ea4d2aa.png)

Saving the file as UTF-8 with BOM fixes the issue tho, but nevertheless, it's kinda annoying.
There is really no solution? 🤔

**Comment by rabelux** [comment]
Related to #920.
I have to say I also get wrong character detections quite regularly.

@xupefei What do you think about using utf8 as default, as suggested by @hyrious?
At least for my use case that would always be the right guess.

**Comment by emako** [comment]
I think overly short text may require exhaustive traversal of most encodings before a decision can be made.

For instance, if both the current PC language and other languages are detected, the current PC language should be given priority.

**Comment by emako** [comment]
Fixed in nightly build

https://github.com/QL-Win/QuickLook/releases
