### ISSUE TITLE
RE: QuickLook crashes after Windows 10 20H2 upgrade #948

### ISSUE THREAD

**Issue by eric3272** [QL-Win/QuickLook#956]
Hello, the same issue of #948 is happening again with another Windows 10 update, I can't seem to be able to reopen that issue so I'm here to open a new one. I included a crash dump file in the new comment under #948. Sorry for opening a new issue. 

QuickLook crashes after Windows 10 20H2 upgrade #948

**Comment by xupefei** [comment]
Cloused
