### ISSUE TITLE
Mouse scroll wheel needs to change next and previous file

### ISSUE THREAD

**Issue by gitsamhub** [QL-Win/QuickLook#959]
It would be really convenient if I can use only **mouse wheel scroll to navigate next and previous file**. And with [control+ scroll] it can zoom in and out images. 

I tried to change hotkey with my five button mouse but It doesn't work.

If possible can any one suggest any alternative to change that hotkey?

Thank you.

**Comment by xupefei** [comment]
No. Navigating between files w/o from Explorer is not what a Quick Look looks like.
You could write some AHK scripts for Explorer to map wheels to arrow keys, then QL will work when you scrolling in the Explorer.
