### ISSUE TITLE
QuickLook Only Valid in Desktop

### ISSUE THREAD

**Issue by dkl78167816** [QL-Win/QuickLook#960]
**Describe the bug**

QuickLook preview takes effect in desktop, including view documents in folders of desktop. 
But if I open folder with file manager, even the same files as above, the space preview will be invalid

**Desktop**
 - OS Version: Windows 10 21H1 19043.1083 in AMD platform.
 - QuickLook Version: v 3.6.11, installed with msi file.

**Comment by rabelux** [comment]
Are you using the default file manager?

**Comment by dkl78167816** [comment]
> Are you using the default file manager?

Yes. And it will be fine after reboot in first few hours, I'll try to reproduce stably.
