### ISSUE TITLE
Nothing displayed when open from command line

### ISSUE THREAD

**Issue by kkdd** [QL-Win/QuickLook#961]
**Describe the bug**
Trying to open a file in the command line using ```path\to\QuickLook.exe path\to\file``` doesn't display anything.

***Note***
When not-existing ```path\to\file``` is specified, it is confirmed to display a warning window saying:
* ```QuickLook enables quick previewing of certain type of files by pressing the spacebar while it is highlighted.```

**Expected behavior**
The file content is displayed in Quicklook in the same way as by pressing the space key in Windows File Explorer and Open and Save File Dialog.

**Desktop**
 - OS Version: Windows 10 20H2
 - QuickLook Version: 3.6.11 MSI Installer version

**Comment by emako** [comment]
It should be an outdated issue
