### ISSUE TITLE
windows11环境下，拖动图片会存在卡顿的情况

### ISSUE THREAD

**Issue by calonye** [QL-Win/QuickLook#963]
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**
1. 敲击空格显示任意一张图片格式的文件，在显示出来的界面中，点击鼠标左键对其进行拖动，界面呈现出一种延迟移动的动画，移动过程中异常卡顿。

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: Windows 11 企业版 21H2 22000.100
 - QuickLook Version: [V3.6.11]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by xupefei** [comment]
Windows 11 is not officially released and not ready for daily use. See https://github.com/QL-Win/QuickLook/issues/955
