### ISSUE TITLE
Can we have QL compatibility with Everything (by voidtools) v1.5 alpha already?

### ISSUE THREAD

**Issue by K0media** [QL-Win/QuickLook#964]
**Is your feature request related to a problem? Please describe.**
I've attempted to use QL on Everything v1.5 alpha, but it just doesn't work on the latest version.

**Describe the solution you'd like**
It would be great if it worked right away without workarounds, natively.

**Describe alternatives you've considered**
So far, QL default installer would be great, but with another update, if needed.

I haven't tested other things, since I update QL via Choco, but the updates didn't seem to work with that yet.

EDIT: I've also tried to run Everything as admin (as advised on #533), and installed it as a service, but it didn't work either.
Also tried restarting the machine after changing some settings and options, still no luck.

**Additional context**
Right now it is happening that I open up Everything, look up for an item and press space and nothing happens.
Not sure exactly why, but I believe it's due to a path misleading compatibility.

I'd be glad if you could fix that.

PS: I'm using Everything v1.5 alpha because of the dark mode and other additional features that are being tested.

Thanks for the help.

**Comment by xupefei** [comment]
In #533 I said to **not** run the Everything GUI as the administrator. Have you tried that?

**Comment by rabelux** [comment]
Closed due to missing feedback
