### ISSUE TITLE
Error when trying to play any video

### ISSUE THREAD

**Issue by hilmyapriliano** [QL-Win/QuickLook#974]
**Describe the bug**
I was trying to play a video file when this happened. To be precise, an .m4a file. Images works fine though!
![image](https://user-images.githubusercontent.com/88835660/129197259-e19b21f2-18f2-4ed5-a476-74b525c21b68.png)
I've tried to install K-Lite video codecs as well. Not sure if its the issue but it doesnt do anything to it lol. Any help would be appreciated :)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro N ver. 21H1 (with Media features installed)
 - QuickLook Version: 3.6.11.msi

**Comment by rabelux** [comment]
Did you just install K-Lite codec or also the media feature pack?
see https://github.com/QL-Win/QuickLook/issues/921#issuecomment-848651211

**Comment by hilmyapriliano** [comment]
> 
> 
> Did you just install K-Lite codec or also the media feature pack?
> see [#921 (comment)](https://github.com/QL-Win/QuickLook/issues/921#issuecomment-848651211)

Reinstalling the media pack worked for me, i think it was conflicting with one of my debloat scripts haha. Thanks!

**Comment by hilmyapriliano** [comment]
So the problem occurs only when playing on my D:\ drive. Not sure if the filesystem is the culprit as i have my external drive also formatted to exFAT and has no issues. Playing files on VLC and Photos works fine. Really strange.
