### ISSUE TITLE
希望在预览中添加对触控板手势支持的功能 please add touchpad gestures while previewing photos, files, etc.

### ISSUE THREAD

**Issue by ilikeyu** [QL-Win/QuickLook#975]
现在 win10 笔记本触控板功能已经比较完善，如在浏览器中，可以通过 **双指捏合** 放大/缩小内容，**双指平移滑动**实现内容的移动，所以希望在查看图片，预览pdf/office文件 时候也可以实现。虽然微软官方自己做的就很垃圾，请问可以做到吗？

Most laptop has a precision touchpad, and when using web browser, we could use two fingers to  scroll and pinch to zoom, and I hope to use these two gestures while previewing photos or files.

**Comment by xupefei** [comment]
The image viewer already supports that: https://github.com/QL-Win/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.ImageViewer/ImagePanel.xaml.cs#L313
What's the issue you have?
