### ISSUE TITLE
CSV preview doesn't support comma separated files

### ISSUE THREAD

**Issue by D-ominik** [QL-Win/QuickLook#979]
**Describe the bug**
The preview of csv files, which use a comma (,) as separator, is not split into columns. Files separated with a semicolon (;) work as intended.

![image](https://user-images.githubusercontent.com/3935749/131113137-6a5fa3c8-f80f-4439-a067-f5a86adedb2b.png)

**To Reproduce**
Create sample CSV:
```
Field 1,Field 2
Lorem ipsum,234.45
Dolor aurum,324.23
``` 

**Expected behavior**
The preview should be split in columns, as with semicolon separated files.

![image](https://user-images.githubusercontent.com/3935749/131113224-08789f4e-0338-4673-9cf9-b9599e1c4772.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 19043.1165
 - QuickLook Version: 3.6.11

**Last but not least: thanks for this great tool**

**Comment by D-ominik** [comment]
No. Just tried no spaces in header line, no spaces in whole file and each field enclosed in quotes. The result remains the same.

**Comment by Jarartur** [comment]
I just checked it on my PC and it looks like it's connected to regional settings in Windows.
If I change semicolon as a separator to a comma then it discards semicolon as a separator and uses comma.
