### ISSUE TITLE
希望预览文件时可以编辑

### ISSUE THREAD

**Issue by HKMV** [QL-Win/QuickLook#985]
希望在预览文件时可以直接编辑。
思路如下:
1.默认预览为只读模式。
2.在预览窗口的右上角添加一个启用编辑的按钮。
3.启用编辑后，在窗口的右上角出现放弃修改以及保存修改的按钮。
4.同时支持快捷键保存文件。

希望师傅可以采纳一下，万分感谢。

**Comment by xupefei** [comment]
请使用文本编辑器，本软件的名字是Quick**Look**。

**Comment by HKMV** [comment]
好吧，非常感谢您的回复。
