### ISSUE TITLE
(sorry newbie question) How do I open settings for quicklook?

### ISSUE THREAD

**Issue by nutnutwin** [QL-Win/QuickLook#986]
Hi, I used quicklook 1year ago, and I remember entering setting from the floating window
some button, or right click I remember...

wonder if setting is still available? (like changing fonts/transparency? 

I right clicked on quicklook icon in the tray, but found nothing. 

Sorry for this really newbie question. 
---
Also wonder if there are anyway I can make a donation to this project? if it is needed. 

Thank you

**Comment by xupefei** [comment]
You're not using QuickLook one year ago, because QuickLook never had a setting interface :)
Few options are configurable, see https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations.

**Comment by nutnutwin** [comment]
> You're not using QuickLook one year ago, because QuickLook never had a setting interface :)
> 
> Few options are configurable, see https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations.

Thank you. 
Will look into that.
