### ISSUE TITLE
QuickLook stopped working after Windows 10 Update today

### ISSUE THREAD

**Issue by Ravie13** [QL-Win/QuickLook#987]
**Describe the bug**
I installed QuickLook on my Windows 10 PC laptop and it was working great. Then I restarted my computer after updates were downloaded and upon restart QuickLook no longer works. If I select a file in a folder and press the spacebar - nothing happens. I tried uninstalling and reinstalling from the Microsoft Store. No luck. When I click on Launch from the Microsoft Store I get a message that says QuickLook is already running.

(UPDATE - As I was writing this report, I downloaded the MSI version from Git and installed and now it is working again. This may be a clue - the problem may have already been fixed in the MSI version?)

**To Reproduce**
1. Go to a file you want to preview
2. Click on the filename
3. Press spacebar
4. Nothing happens

**Expected behavior**
I hit spacebar while a file is selected and a window pops up previewing the file.

**Desktop (please complete the following information):**

Edition	Windows 10 Home
Version	21H1
Installed on	‎7/‎22/‎2020
OS build	19043.1165
Experience	Windows Feature Experience Pack 120.2212.3530.0

 - QuickLook Version: The current version in the Microsoft Store.

**Screenshots and Exception Log**

![image](https://user-images.githubusercontent.com/16327198/132930338-4b43ca49-c2fd-4052-81c6-19ba20de4af6.png)

**Comment by rabelux** [comment]
I've seen two occurances of Windows breaking QuickLook. Reinstalling didn't do the job but a repair somehow worked. As the msi and the store version are identical as far as I know there is nothing QuickLook can do about it. Just another weird behaviour on Microsoft's side I'd say.
