### ISSUE TITLE
Tablacus Explorer Support

### ISSUE THREAD

**Issue by HyperCriSiS** [QL-Win/QuickLook#988]
Hi,

would it be possible to add support for the Tablacus explorer?
[https://github.com/tablacus/TablacusExplorer
](url)

Regards,
Hyper

**Comment by rabelux** [comment]
How about using the [shortcut-plugin] (https://tablacus.github.io/wiki/addons/key.html) and execute QuickLook with it? Have a look at the wiki to see how to do it.

**Comment by rabelux** [comment]
Closed due to missing feedback
