### ISSUE TITLE
靓仔 这个gif显示效果有点卡 有点慢 能换换吗 谢谢ヾ(๑╹◡╹)ﾉ"

### ISSUE THREAD

**Issue by xxm101010** [QL-Win/QuickLook#993]
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by emako** [comment]
Done in nightly build

https://github.com/QL-Win/QuickLook/releases
