### ISSUE TITLE
Incompatible plugin in Windows 11

### ISSUE THREAD

**Issue by Zbynius** [QL-Win/QuickLook#995]
Font plugin don't work in Windows 11 (64 bit Home) in QuickLook QuickLook-3.7.
Crashing on TTF and OTF font files.

Please add function "uninstall plugin" or "deactivate plugin".

**Comment by rabelux** [comment]
> Please add function "uninstall plugin" or "deactivate plugin".

There is an old PR for this (#415) and it has been discussed in #406

**Comment by xupefei** [comment]
There's a Wiki page for that: https://github.com/QL-Win/QuickLook/wiki/Available-Plugins#how-to-remove-a-plugin
