### ISSUE TITLE
Feature Requested: PEViewer, and more than it

### ISSUE THREAD

**Issue by seven-mile** [QL-Win/QuickLook#997]
Viewing PE file is something professional developers often need. It would be nicer for QuickLook to provide such a feature to view them quickly. Of course, as it's not a very common usage, we can provide this feature as an addtional plugin.

I've been using the [PEViewer of ProcessHacker](https://github.com/processhacker/processhacker/tree/master/tools/peview) project for several years:

![peviewer_general](https://p.sda1.dev/2/83d301e7a1caa366c53a8b8f5a6d8d7d/QQ截图20210921222527.jpg)

![peviewer_exports](https://p.sda1.dev/2/333e56198dde009b7483c54ec6b36e78/QQ截图20210921222552.jpg)

As you can see, it provides quite complicated and rich information of the PE file.

Originally, I want to develop a plugin directly. But after inspecting the IViewer interface, I realised that the viewer plugin should construct above the default view window, which means I need to rewrite a PE file viewer. Though there are some libraries can achieve this goal...

**One possible convenient and extendable solution**
From a boarder view point, we can assume to add a new view model: when triggered, we create and monitor a sub-process. Then when the process is closed, we call `Cleanup` to end viewing state. When user pressed space again, manually close this sub-process. This method not only solves this problem, but also enables us to integrate other light-weighted viewing tools to Windows Shell more conveniently.

Hmm, should we take account of privilege? I don't know details about that.

Please inform me about your consideration on this proposal, if you aren't planning to adapt this new view model, I'll just write a self-supporting PE viewer instead. Thanks for reading   ; )

**Comment by emako** [comment]
A simple PE Viewer has been implemented. (Nightly build in https://github.com/QL-Win/QuickLook/releases)

We are not considering loading such complex information into the PE Viewer, which will not be necessary for the vast majority of people.

I suggest you can use the Open With button to jump to other external previewers.

![image](https://github.com/user-attachments/assets/89ea4c49-6f24-4117-b3d0-d6afd35f489c)
