### ISSUE TITLE
windows 10 1809 Display Error

### ISSUE THREAD

**Issue by ajadds** [QL-Win/QuickLook#998]
windows 10 1809 Display Error

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1809
 - QuickLook Version: 3.7.0 from Windows portable 

![1](https://user-images.githubusercontent.com/50348289/134322721-cd8e91db-d5ea-4eb6-a61a-9535585884b8.png)

**Comment by rabelux** [comment]
I don't see any problem and no error log. If you have a display bug there is known bug for some Intel graphics.
