### ISSUE TITLE
Video files of the Sony A7SIII are not playable

### ISSUE THREAD

**Issue by jcwnoff** [QL-Win/QuickLook#999]
**Describe the bug**
Video files of the Sony A7SIII are not playable anymore. In former versions of QuickLook it worked flawlessly. Now, when you hit the spacebar a window appears and closes.

**To Reproduce**

**Expected behavior**
That the file is playable with Quick Look

**Desktop (please complete the following information):**
 - OS Version: Edition	Windows 10 Pro
Version	21H1
Installiert am	‎14.‎06.‎2020
Betriebssystembuild	19043.1237
Leistung	Windows Feature Experience Pack 120.2212.3530.0

 - QuickLook Version: v 3.7.0 UWP

**Comment by rabelux** [comment]
1. Does it only affect these files or all files of any type? 
2. Is there a error log?
3. If it affects all files - does this also occur with the zip or msi version?
